Repository mozilla/bedrock, pull requests merged in 2018-04, with the labels that each got.

#5547 [fix bug 1449758] Landing page for Facebook Container
  bedrock/firefox/templates/firefox/facebookcontainer/index.html
  bedrock/firefox/urls.py
  bedrock/settings/static_media.py
  media/css/firefox/facebook-container.scss
  media/img/firefox/facebook-container/video-poster.png
  media/js/firefox/facebook-container-video.js
Labels: L10N - Not Required

#5533 [fix bug 1448875] Skip /zh-CN/ home page hreflang
  bedrock/base/templates/includes/canonical-url.html
Labels: Bug :bug:

#5534 [fix bug 1401728] Omit LANG from canonical URL on /credits/faq/
  bedrock/mozorg/templates/mozorg/credits-faq.html
  media/css/mozorg/credits-faq.less
Labels: Bug :bug:

#5585 [fix bug 1436737] Remove blog thumbnail links from global nav side drawer
  bedrock/base/templates/includes/global-nav.html
  media/css/base/global-nav.less
  media/css/pebbles/components/_global-nav.scss
  media/img/nav/promos/better-browser-high-res.png
  media/img/nav/promos/better-browser.png
  media/img/nav/promos/css-grid-demo-high-res.png
  media/img/nav/promos/css-grid-demo.png
  media/img/nav/promos/fb-share-tips-high-res.png
  media/img/nav/promos/fb-share-tips.png
  media/img/nav/promos/safer-logins-high-res.png
  media/img/nav/promos/safer-logins.png
  media/img/nav/promos/smooth-scrolling-high-res.png
  media/img/nav/promos/smooth-scrolling.png
  media/img/nav/promos/web-assembly-high-res.png
  media/img/nav/promos/web-assembly.png
Labels: Performance :zap:

#5592 Fix Bug 1455460: Removed two links to facebook from footer per request from Janis G.
  bedrock/base/templates/includes/site-footer.html
Labels: P3

#5606 [fix bug 1457539] utm_source Empty for FxA iframe
  bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
Labels: Bug :bug:
