Repository mozilla/bedrock, pull requests merged in 2018-12, with the labels that each got.

#6503 [#6339] New Firefox Accounts page
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/accounts-2018.html
  bedrock/firefox/templates/firefox/accounts-features.html
  bedrock/firefox/templates/firefox/features/index.html
  bedrock/firefox/templates/firefox/features/send-tabs.html
  bedrock/firefox/templates/firefox/features/sync.html
  bedrock/firefox/templates/firefox/feedback/happy.html
  bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
  bedrock/firefox/templates/firefox/firstrun/index.html
  bedrock/firefox/templates/firefox/includes/top-menu.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx60.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx61.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx62.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx63.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fxa.html
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  bedrock/privacy/templates/privacy/faq.html
  media/css/firefox/accounts-2018.scss
  media/css/firefox/accounts-features.scss
  media/css/firefox/features/sync.scss
  media/css/protocol/components/_fxa-form.scss
  media/img/firefox/accounts/blob-img.png
  media/img/firefox/accounts/fx-qr.png
  media/img/firefox/accounts/fxa-hero-img-high-res.png
  media/img/firefox/accounts/fxa-hero-img.png
  media/img/firefox/accounts/fxa-lockbox-high-res.png
  media/img/firefox/accounts/fxa-lockbox.png
  media/img/firefox/accounts/fxa-notes-high-res.png
  media/img/firefox/accounts/fxa-notes.png
  media/img/firefox/accounts/fxa-pocket-high-res.png
  media/img/firefox/accounts/fxa-pocket.png
  media/img/firefox/accounts/fxa-send-high-res.png
  media/img/firefox/accounts/fxa-send.png
  media/img/firefox/accounts/fxa-sync-high-res.png
  media/img/firefox/accounts/fxa-sync.png
  media/img/firefox/accounts/fxa-thanks-blob-high-res.png
  media/img/firefox/accounts/fxa-thanks-blob.png
  media/img/firefox/accounts/lockbox-qr.png
  media/img/firefox/accounts/notes-qr.png
  media/img/firefox/accounts/pocket-qr.png
  media/js/firefox/accounts-2018.js
  media/static-bundles.json
  tests/functional/firefox/test_accounts_features.py
  tests/functional/newsletter/test_newsletter_embed.py
  tests/pages/firefox/accounts.py
  tests/pages/firefox/accounts_features.py
  tests/redirects/map_globalconf.py
Labels: Do Not Merge :warning:, L10N - Localization Started, Needs Review, P1, Review: L

#6538 [fix #6337] Add FxA benefits CTAs to home page
  bedrock/mozorg/templates/mozorg/home/home-en.html
  media/css/mozorg/home/home-2018.scss
  media/img/home/2018/banner-fffy-high-res.png
  media/img/home/2018/banner-fffy.png
  media/img/home/2018/banner-ffyr-high-res.png
  media/img/home/2018/banner-ffyr.png
  media/img/home/2018/banner-fxa-high-res.png
  media/img/home/2018/banner-fxa.png
  media/js/mozorg/home/home.js
  tests/functional/test_home.py
  tests/pages/home.py
Labels: Fx Existing User aDAU, Fx Master Brand, In Sprint, P1, Review: M

#6557 Update tests for new accounts page
  tests/functional/firefox/test_accounts.py
  tests/pages/firefox/accounts.py
Labels: Bug :bug:

#6558 [fix #6556] Keep basic store badges hidden when modal opens
  bedrock/firefox/templates/firefox/accounts-2018.html
  media/css/firefox/accounts-2018.scss
Labels: Bug :bug:

#6515 Remove jQuery dependency from search-params.js
  media/js/base/search-params.js
Labels: P3, Review: S

#6555 WPN 64 Conditional formatting
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx64-base.html
  media/css/firefox/whatsnew/whatsnew-64.scss
  media/css/protocol/components/_state-fxa.scss
  media/static-bundles.json
Labels: Needs Review, Review: XS

#6493 Remove old /foundation page templates (#6467)
  bedrock/foundation/templates/foundation/about.html
  bedrock/foundation/templates/foundation/advocacy.html
  bedrock/foundation/templates/foundation/annualreport/2012/faq.html
  bedrock/foundation/templates/foundation/annualreport/2013/faq.html
  bedrock/foundation/templates/foundation/annualreport/2014/faq.html
  bedrock/foundation/templates/foundation/annualreport/2015/faq.html
  bedrock/foundation/templates/foundation/annualreport/2015/index.html
  bedrock/foundation/templates/foundation/base-resp.html
  bedrock/foundation/templates/foundation/documents/index.html
  bedrock/foundation/templates/foundation/index.html
  bedrock/foundation/templates/foundation/issues.html
  bedrock/foundation/templates/foundation/leadership-network.html
  bedrock/foundation/urls.py
  bedrock/mozorg/templates/mozorg/about-en.html
  bedrock/mozorg/templates/mozorg/about.html
  bedrock/mozorg/templates/mozorg/about/governance/organizations.html
  bedrock/mozorg/templates/mozorg/about/leadership.html
Labels: P3, Papercuts 💸, Review: S

#6576 Remove reggiewatts and wait-face firefox/new variants.
  bedrock/firefox/templates/firefox/new/reggie-watts/base.html
  bedrock/firefox/templates/firefox/new/reggie-watts/scene1.html
  bedrock/firefox/templates/firefox/new/reggie-watts/scene2.html
  bedrock/firefox/templates/firefox/new/wait-face/base.html
  bedrock/firefox/templates/firefox/new/wait-face/scene1.html
  bedrock/firefox/templates/firefox/new/wait-face/scene2.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/css/firefox/new/reggie-watts.scss
  media/css/firefox/new/wait-face.scss
  media/img/firefox/new/reggie-watts/orange-wave.png
  media/img/firefox/new/reggie-watts/oval.png
  media/img/firefox/new/reggie-watts/reggie-watts.jpg
  media/img/firefox/new/wait-face/arrow.png
  media/img/firefox/new/wait-face/oval.png
  media/img/firefox/new/wait-face/purple-wave.png
  media/img/firefox/new/wait-face/wait-face.jpg
  media/static-bundles.json
Labels: Review: S

#6614 [fix #6609] Enclose string for l10n on CPG reporting page
  bedrock/mozorg/templates/mozorg/about/governance/policies/reporting.html
Labels: L10N

#6600 Show button in default state (#6387)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx64-base.html
Labels: Needs Review, P3, Review: XS

#6622 Fix broken download test
  tests/functional/test_download_l10n.py
Labels: P1, Review: XS

#6625 Revert to jQuery DOM ready handler in core-datalayer-init.js (Fixes #6624)
  media/js/base/core-datalayer-init.js
Labels: P1, Review: S

#6632 [fix #6544] Add Pocket sponsorship link to contact landing
  bedrock/mozorg/templates/mozorg/contact/contact-landing.html
Labels: In Sprint, Pocket, Review: XS

#6631 [fix #6606] Update Mitchell’s bio
  bedrock/mozorg/templates/mozorg/about/leadership.html
Labels: Review: XS

#6572 Move WN64 templates to sub folder
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64-base.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.de.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.en-CA.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.en-GB.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.es-ES.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.fr.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.pl.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.pt-BR.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.ru.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.zh-TW.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx64.es-MX.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx64.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
Labels: Needs Review, P3, Review: XS

#6637 Text change to French WN64
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.fr.html
Labels: Bug :bug:, P2, Review: XS

#6638 Separate fr and de locales in pre-download experiment (Fixes #6634)
  bedrock/firefox/templates/firefox/home.html
Labels: P2, Review: XS

#6641 [fix #6580] Updating fundraising banner copy
  bedrock/mozorg/templates/mozorg/home/includes/fundraiser-eoy2018.html
  media/css/mozorg/home/fundraiser2018.scss
Labels: Needs Review, Review: XS

#6599 Transparency Report: jan-june 2018 update ( #6479)
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2018.html
  bedrock/mozorg/urls.py
Labels: Needs Review, Review: S

#6644 Add concert video to Firefox Concerts page
  bedrock/firefox/templates/firefox/concerts.html
  media/img/firefox/concerts/concert-phosphorescent.jpg
  media/img/firefox/concerts/video-poster-phosphorescent.jpg
Labels: Review: XS

#6649 [fix #6647] Update home page card
  bedrock/mozorg/templates/mozorg/home/home-en.html
  media/img/home/2018/cards/dec/holidays-high-res.png
  media/img/home/2018/cards/dec/holidays.png
  media/img/home/2018/cards/dec/shopping-high-res.jpg
  media/img/home/2018/cards/dec/shopping.jpg
Labels: Review: XS

#6654 Fix Bug 1504292 - Remove SVN section from Mozilla Commit Access Policy
  bedrock/mozorg/templates/mozorg/about/governance/policies/commit/access-policy.html
Labels: L10N - Not Required

#6658 [fix #6584] Add French translation of FFFY page
  bedrock/firefox/templates/firefox/fights-for-you.fr.html
  bedrock/firefox/urls.py
Labels: In Sprint, Review: XS

#6655 (Fixes #6604) Add Firefox SEO page for Windows
  bedrock/firefox/templates/firefox/new/base.html
  bedrock/firefox/templates/firefox/new/scene1.html
  bedrock/firefox/templates/firefox/new/scene1_windows.html
  bedrock/firefox/urls.py
  media/css/firefox/new/common.scss
  media/img/firefox/new/icon-blocker.svg
  media/img/firefox/new/icon-opensource.svg
  media/img/firefox/new/icon-seamless.svg
Labels: Do Not Merge :warning:

#6660 [fix #6580] Home fundraising banner copy update
  bedrock/mozorg/templates/mozorg/home/includes/fundraiser-eoy2018.html
  media/css/mozorg/home/fundraiser2018.scss
Labels: Review: XS

#6661 [fix #6592] Fix home sticky banner dismiss button
  media/js/mozorg/home/home.js
Labels: Bug :bug:, Review: XS
