Repository mozilla/bedrock, pull requests merged in 2018-11, with the labels that each got.

#6362 Update Reps Council on Leadership Page accoding to latest Council Ele…
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/edoardo-viola-high-res.jpg
  media/img/mozorg/about/leadership/edoardo-viola.jpg
  media/img/mozorg/about/leadership/mayur-patil-high-res.jpg
  media/img/mozorg/about/leadership/mayur-patil.jpg
  media/img/mozorg/about/leadership/monica-bonilla-high-res.jpg
  media/img/mozorg/about/leadership/monica-bonilla.jpg
  media/img/mozorg/about/leadership/prathamesh-chavan-high-res.jpg
  media/img/mozorg/about/leadership/prathamesh-chavan.jpg
  media/img/mozorg/about/leadership/ruben-martin-high-res.jpg
  media/img/mozorg/about/leadership/ruben-martin.jpg
  media/img/mozorg/about/leadership/yofie-setiawan-high-res.jpg
  media/img/mozorg/about/leadership/yofie-setiawan.jpg
Labels: P2, Review: S

#6396 Change campaign parameters on fx-fxa experiment form
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/new/fx/scene1.html
Labels: P1, Review: S

#6446 [fix #6171] Add “What is a web browser” page
  bedrock/mozorg/templates/mozorg/what-is-a-browser.html
  bedrock/mozorg/urls.py
  media/css/mozorg/what-is-a-browser.scss
  media/img/mozorg/technology/illo-browser.png
  media/static-bundles.json
Labels: L10N - Not Required

#6451 Remove interstitial link to Pocket in the main navigation (Fixes #6450)
  bedrock/base/templates/includes/protocol/navigation/menu/firefox.html
Labels: P1, Review: XS

#6441 Add Protocol navigation to release notes pages (Fixes #6403)
  bedrock/firefox/templates/firefox/releases/index.html
  bedrock/firefox/templates/firefox/releases/release-notes.html
Labels: P3, Review: XS

#6139 Features page header a/b test
  bedrock/firefox/templates/firefox/features/index.html
  bedrock/firefox/urls.py
  media/js/firefox/experiment_features_header.js
  media/static-bundles.json
  tests/functional/firefox/features/test_landing.py
Labels: Moz.org, P2, Review: S, Size: XS

#6449 Add Mozilla Labs newsletter form to /technology (Fixes #6400)
  bedrock/mozorg/templates/mozorg/technology.html
Labels: P3, Review: XS

#6442 Adjust Edge comparison SEM page experiment (Fixes #6371)
  bedrock/firefox/templates/firefox/new/compare/scene1-edge-1.html
  bedrock/firefox/templates/firefox/new/compare/scene1-edge-2.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/js/firefox/new/compare-edge-experiment.js
Labels: P3, Review: S

#6397 Add language selection page (Fixes #5827)
  bedrock/mozorg/templates/mozorg/locales.html
  bedrock/mozorg/urls.py
  bedrock/settings/base.py
  media/css/mozorg/locales.scss
  media/img/mozorg/locales/world-map-high-res.png
  media/img/mozorg/locales/world-map.png
  media/static-bundles.json
Labels: P2, Review: S

#6460 [fix bug 1506463] Fix typo in Firefox subtitle in navigation
  bedrock/base/templates/includes/protocol/navigation/menu/firefox.html
Labels: L10N - Not Required, P2, Review: XS

#6463 Update bedrock/firefox/templates/firefox/new/base.html
  bedrock/firefox/templates/firefox/new/base.html
Labels: P3, Review: XS

#6459 Update bedrock to @mozilla-protocol/core v3.1.0 (Fixes #6453)
  .eslintrc.js
  bedrock/base/templates/includes/protocol/lang-switcher.html
  bedrock/base/templates/includes/protocol/navigation/index.html
  bedrock/firefox/templates/firefox/election/index.html
  bedrock/firefox/templates/firefox/firstrun/firstrun-election.html
  bedrock/firefox/templates/firefox/includes/download-button.html
  bedrock/firefox/templates/firefox/new/compare/base-1.html
  bedrock/firefox/templates/firefox/new/compare/base-2.html
  bedrock/firefox/templates/firefox/pocket.html
  bedrock/firefox/templates/firefox/recommended.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx62.html
  bedrock/mozorg/templates/mozorg/about-en.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  media/css/base/global-nav.less
  media/css/firefox/developer/developer.scss
  media/css/firefox/developer/includes/features-gallery.scss
  media/css/firefox/developer/includes/newsletter.scss
  media/css/firefox/developer/includes/performance.scss
  media/css/firefox/developer/whatsnew.scss
  media/css/firefox/election.scss
  media/css/firefox/enterprise.scss
  media/css/firefox/features/adblocker.scss
  media/css/firefox/mobile.scss
  media/css/firefox/new/compare.scss
  media/css/firefox/new/scene2.scss
  media/css/firefox/pocket.scss
  media/css/firefox/recommended.scss
  media/css/firefox/whatsnew/send-to-device.scss
  media/css/firefox/whatsnew/send-yourself.scss
  media/css/firefox/whatsnew/whatsnew-62.scss
  media/css/firefox/whatsnew/whatsnew-63.scss
  media/css/hubs/_masthead.scss
  media/css/hubs/_sub-nav.scss
  media/css/mozorg/about-en.scss
  media/css/mozorg/home/home-2018.scss
  media/css/mozorg/lean-data.scss
  media/css/mozorg/what-is-a-browser.scss
  media/css/pebbles/components/_buttons.scss
  media/css/pebbles/components/_global-nav.scss
  media/css/pebbles/components/_protocol-nav.scss
  media/css/privacy/privacy-protocol.scss
  media/css/protocol/components/_download-button.scss
  media/css/protocol/components/_global-nav.scss
  media/css/protocol/components/_masthead.scss
  media/css/protocol/components/_navigation.scss
  media/css/protocol/includes/_navigation-hide-download-button.scss
  media/css/protocol/oldIE.scss
  media/css/protocol/protocol.scss
  media/css/quantum/_newsletter.scss
  media/css/sandstone/buttons.less
  media/css/sandstone/protocol-nav.scss
  media/js/base/protocol/init-lang-switcher.js
  media/js/base/protocol/init-navigation.js
  media/js/firefox/new/scene2-email.js
  media/js/mozorg/home/home.js
  media/js/privacy/privacy-firefox.js
  package.json
  yarn.lock
Labels: P2, Review: L

#6477 [fix #6473] Hide Fx download button in nav on Dev Edition product page
  media/css/firefox/developer/developer.scss
Labels: Bug :bug:

#6502 [bug 1444000] Decommission Portland campaign pages
  bedrock/firefox/templates/firefox/new/portland/base.html
  bedrock/firefox/templates/firefox/new/portland/includes/efficient.html
  bedrock/firefox/templates/firefox/new/portland/includes/safe.html
  bedrock/firefox/templates/firefox/new/portland/includes/socially-responsible.html
  bedrock/firefox/templates/firefox/new/portland/scene1-fast.html
  bedrock/firefox/templates/firefox/new/portland/scene1-safe.html
  bedrock/firefox/templates/firefox/new/portland/scene1.html
  bedrock/firefox/templates/firefox/new/portland/scene2-fast.html
  bedrock/firefox/templates/firefox/new/portland/scene2-safe.html
  bedrock/firefox/templates/firefox/new/portland/scene2.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  bedrock/settings/base.py
  media/css/firefox/new/portland.scss
  media/fonts/42d7564d-dbd2-4098-b346-18b43c615bb2.woff
  media/fonts/7089f9c8-406a-4162-b5c7-3cffa5d6d3d8.woff2
  media/img/firefox/new/portland/bg-portland-fast-tile.png
  media/img/firefox/new/portland/bg-portland-fast.png
  media/img/firefox/new/portland/bg-portland-safe.png
  media/img/firefox/new/portland/bg-portland-wave.svg
  media/img/firefox/new/portland/bg-portland.png
  media/img/firefox/new/portland/checkbox.png
  media/js/firefox/new/portland-scene1.js
  media/static-bundles.json
Labels: P3, Papercuts 💸, Review: XS

#6505 Update currency presets for 2018 Fundraising banner
  bedrock/settings/base.py
Labels: P1, Review: XS

#6501 [#6465] Add 2018 Fundraising banner to home page
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/templates/mozorg/home/includes/fundraiser-eoy2018.html
  bedrock/mozorg/views.py
  media/css/mozorg/home/fundraiser2018.scss
  media/img/home/fundraiser2018/background-hearts-high-res.png
  media/img/home/fundraiser2018/background-hearts.png
  media/js/mozorg/home/fundraiser-eoy2018.js
  media/static-bundles.json
Labels: P1, Review: S

#6497 Remove legacy navigation (Fixes #6377)
  bedrock/base/templates/base-pebbles-basic.html
  bedrock/base/templates/base-pebbles.html
  bedrock/base/templates/base-protocol.html
  bedrock/base/templates/base-resp.html
  bedrock/base/templates/includes/global-nav.html
  bedrock/base/templates/includes/navigation-switch.html
  bedrock/base/templates/includes/protocol/navigation/index.html
  bedrock/firefox/templates/firefox/base-pebbles.html
  bedrock/firefox/templates/firefox/base-protocol.html
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/firefox/templates/firefox/releases/index.html
  bedrock/firefox/templates/firefox/releases/release-notes.html
  bedrock/foundation/templates/foundation/annualreport/2011.html
  bedrock/mozorg/templates/mozorg/about/manifesto.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/report-base.html
  bedrock/mozorg/templates/mozorg/contact/contact-base.html
  bedrock/mozorg/templates/mozorg/developer/index.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/templates/mozorg/internet-health/decentralization.html
  bedrock/mozorg/templates/mozorg/internet-health/digital-inclusion.html
  bedrock/mozorg/templates/mozorg/internet-health/index.html
  bedrock/mozorg/templates/mozorg/internet-health/open-innovation.html
  bedrock/mozorg/templates/mozorg/internet-health/privacy-security.html
  bedrock/mozorg/templates/mozorg/internet-health/web-literacy.html
  bedrock/mozorg/templates/mozorg/moss/base.html
  bedrock/mozorg/templates/mozorg/technology.html
  media/css/base/global-nav.less
  media/css/pebbles/components/_global-nav.scss
  media/css/pebbles/global-nav.scss
  media/css/protocol/components/_global-nav.scss
  media/css/protocol/protocol-global-nav.scss
  media/img/nav/drawer-close.svg
  media/img/nav/menu-closed.svg
  media/img/nav/menu-open.svg
  media/img/nav/subnav-collapse.svg
  media/img/nav/subnav-expand.svg
  media/js/base/mozilla-global-nav.js
  media/js/base/protocol/init-navigation.js
  media/static-bundles.json
Labels: P2, Review: M

#6506 Fights For You Campaign page
  bedrock/base/templates/macros-protocol.html
  bedrock/firefox/templates/firefox/fights-for-you.de.html
  bedrock/firefox/templates/firefox/fights-for-you.html
  bedrock/firefox/urls.py
  media/css/firefox/fights-for-you.scss
  media/css/libs/system-font.scss
  media/img/firefox/fights-for-you/callout-left.png
  media/img/firefox/fights-for-you/callout-right.png
  media/img/firefox/fights-for-you/chevron.svg
  media/img/firefox/fights-for-you/footer-md-bottom.png
  media/img/firefox/fights-for-you/footer-md-dot.png
  media/img/firefox/fights-for-you/footer-md-top.png
  media/img/firefox/fights-for-you/footer-sm-left.png
  media/img/firefox/fights-for-you/footer-sm-right.png
  media/img/firefox/fights-for-you/hero-high-res.png
  media/img/firefox/fights-for-you/hero.png
  media/img/firefox/fights-for-you/icon-focus.svg
  media/img/firefox/fights-for-you/icon-monitor.svg
  media/img/firefox/fights-for-you/icon-privacy.svg
  media/img/firefox/fights-for-you/noodle.svg
  media/img/firefox/fights-for-you/pic-focus.jpg
  media/img/firefox/fights-for-you/pic-monitor.jpg
  media/img/firefox/fights-for-you/pic-privacy.jpg
  media/js/firefox/fights-for-you.js
  media/static-bundles.json
Labels: P1, Review: M

#6482 Add link to /locales/ page from the main footer (Fixes #6455)
  bedrock/base/templates/includes/lang_switcher.html
  bedrock/base/templates/includes/protocol/lang-switcher.html
  media/css/pebbles/components/_footer.scss
  media/css/sandstone/sandstone-resp.less
Labels: P2, Review: XS

#6516 [#6465] Mobile CSS fixes for fundraising banner
  media/css/mozorg/home/fundraiser2018.scss
Labels: Bug :bug:

#6528 [fix bug 1506402] Update Participation Guidelines, add reporting
  bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html
  bedrock/mozorg/templates/mozorg/about/governance/policies/reporting.html
  bedrock/mozorg/urls.py
  media/css/mozorg/participation-reporting.scss
  media/static-bundles.json
Labels: L10N, P1, Review: S

#6529 Add en and de videos to FFFY campaign page
  bedrock/firefox/templates/firefox/fights-for-you.de.html
  bedrock/firefox/templates/firefox/fights-for-you.html
  media/css/firefox/fights-for-you.scss
  media/js/firefox/fights-for-you.js
  media/static-bundles.json
Labels: P1, Review: S

#6496 Run firefox pre-download experiment for de and fr locales (Fixes #6456)
  bedrock/firefox/templates/firefox/home-b.de.html
  bedrock/firefox/templates/firefox/home-b.fr.html
  bedrock/firefox/templates/firefox/home-c.de.html
  bedrock/firefox/templates/firefox/home-c.fr.html
  bedrock/firefox/templates/firefox/home.html
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  bedrock/privacy/templates/privacy/email.de.html
  bedrock/privacy/templates/privacy/email.fr.html
  bedrock/privacy/urls.py
  media/js/firefox/home/experiment-pre-download-locales.js
  media/static-bundles.json
Labels: L10N - Not Required, P1, Review: S

#6470 Add SEM landing pages for Internet Explorer comparison (Fixes #6466)
  bedrock/firefox/templates/firefox/new/compare/scene1-ie-1.html
  bedrock/firefox/templates/firefox/new/compare/scene1-ie-2.html
  bedrock/firefox/templates/firefox/new/compare/scene1-ie-3.html
  bedrock/firefox/templates/firefox/new/compare/scene1-ie-4.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/img/logos/ie/logo-ie-high-res.png
  media/img/logos/ie/logo-ie.png
  media/js/firefox/new/compare-ie-experiment.js
  media/static-bundles.json
Labels: P2, Review: S

#6541 Minor text updates to SOM 2017 page (#6478)
  bedrock/foundation/templates/foundation/annualreport/2017/index.html
Labels: P3, Review: XS

#6542 Fix IE SEM comparison page cohort sizes (#6466)
  bedrock/firefox/templates/firefox/new/compare/scene1-ie-2.html
  media/js/firefox/new/compare-ie-experiment.js
Labels: P2, Review: XS

#6540 Fix /about/ page URL regex (Fixes #6539)
  bedrock/mozorg/urls.py
Labels: P2, Review: XS

#6546 [#6444] Add Firefox Concert Series landing page
  bedrock/firefox/templates/firefox/concerts.html
  bedrock/firefox/urls.py
  bedrock/newsletter/templates/newsletter/includes/form-protocol.html
  media/css/firefox/concerts.scss
  media/img/firefox/concerts/concert.jpg
  media/img/firefox/concerts/confetti-left.svg
  media/img/firefox/concerts/confetti-right.svg
  media/img/firefox/concerts/icon-alarm.svg
  media/img/firefox/concerts/icon-ended.svg
  media/img/firefox/concerts/icon-live.svg
  media/img/firefox/concerts/illo-fxaccount-high-res.png
  media/img/firefox/concerts/illo-fxaccount.png
  media/img/firefox/concerts/phosphorescent.jpg
  media/js/firefox/concerts-init.js
  media/js/firefox/concerts.js
  media/static-bundles.json
Labels: Do Not Merge :warning:, Fx New User aDAU, In Sprint

#6545 What's New Page for version 64 (Fixes #6492)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx64.html
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-64.scss
  media/img/firefox/whatsnew_64/fxa-lockbox-high-res.png
  media/img/firefox/whatsnew_64/fxa-lockbox.png
  media/img/firefox/whatsnew_64/fxa-notes-high-res.png
  media/img/firefox/whatsnew_64/fxa-notes.png
  media/img/firefox/whatsnew_64/fxa-pocket-high-res.png
  media/img/firefox/whatsnew_64/fxa-pocket.png
  media/img/firefox/whatsnew_64/fxa-send-high-res.png
  media/img/firefox/whatsnew_64/fxa-send.png
  media/img/firefox/whatsnew_64/fxa-sync-high-res.png
  media/img/firefox/whatsnew_64/fxa-sync.png
  media/img/firefox/whatsnew_64/hero-high-res.png
  media/img/firefox/whatsnew_64/hero-rtl-high-res.png
  media/img/firefox/whatsnew_64/hero-rtl.png
  media/img/firefox/whatsnew_64/hero.png
  media/img/firefox/whatsnew_64/lockbox-qr.png
  media/img/firefox/whatsnew_64/notes-qr.png
  media/img/firefox/whatsnew_64/pocket-qr.png
  media/js/firefox/whatsnew/whatsnew-64.js
  media/static-bundles.json
Labels: L10N, P1, Review: S
