Repository mozilla/bedrock, pull requests merged in 2018-05, with the labels that each got.

#5616 Fix legal docs code snippet for updating git submodules
  docs/install.rst
Labels: Bug :bug:

#5615 [fix bug 1343823] Redirect old /firstrun URLs to /firefox/new/
  bedrock/base/templates/base.html
  bedrock/firefox/templates/firefox/australis/base.html
  bedrock/firefox/templates/firefox/australis/firstrun.html
  bedrock/firefox/templates/firefox/australis/fx38_0_5/firstrun.html
  bedrock/firefox/templates/firefox/base.html
  bedrock/firefox/templates/firefox/firstrun/base.html
  bedrock/firefox/templates/firefox/includes/sync-animation.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  bedrock/settings/static_media.py
  docs/l10n.rst
  media/css/firefox/australis/australis-page-common.less
  media/css/firefox/australis/australis-page-stacked.less
  media/css/firefox/australis/fx38_0_5/firstrun.less
  media/css/firefox/sync-animation.less
  media/css/sandstone/sandstone.less
  media/img/firefox/australis/fx38.0.5/firefox-logo-bg-high-res.png
  media/img/firefox/australis/fx38.0.5/firefox-logo-bg.png
  media/img/firefox/australis/fx38.0.5/firefox-logo-high-res.png
  media/img/firefox/australis/fx38.0.5/firefox-logo.png
  media/img/firefox/australis/fx38.0.5/sync-high-res.png
  media/img/firefox/australis/fx38.0.5/sync.png
  media/img/firefox/sync/composite.png
  media/img/firefox/sync/sync-icon-sprite-high-res.png
  media/img/firefox/sync/sync-icon-sprite.png
  media/js/firefox/australis/common.js
  media/js/firefox/australis/fx38_0_5/firstrun.js
  media/js/firefox/australis/no-tour.js
Labels: L10N, Papercuts :moneybag:

#5610 Fix Bug 1455199: Update /id/whatsnew/ Rocket promo
  bedrock/firefox/templates/firefox/whatsnew/index.id.html
  media/css/firefox/whatsnew/whatsnew-rocket.scss
  media/img/firefox/whatsnew/rocket/bg-lines.svg
  media/img/firefox/whatsnew/rocket/bg-rocket-left-high-res.png
  media/img/firefox/whatsnew/rocket/bg-rocket-left.png
  media/img/firefox/whatsnew/rocket/bg-rocket-right-high-res.png
  media/img/firefox/whatsnew/rocket/bg-rocket-right.png
  media/img/firefox/whatsnew/rocket/code-high-res.gif
  media/img/firefox/whatsnew/rocket/code.gif
  media/img/firefox/whatsnew/rocket/qrcode-rocket.png
  media/img/firefox/whatsnew/rocket/screenshot-high-res.png
  media/img/firefox/whatsnew/rocket/screenshot.png
Labels: Firefox Retention Team, L10N - Not Required

#5662 [bug 1458111] Leadership, delete Fridman, clean up switch
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/alex-fridman-high-res.jpg
  media/img/mozorg/about/leadership/alex-fridman.jpg
Labels: Papercuts :moneybag:

#5665 Fix bug 1457975: Promote Enterprise beta
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/enterprise/signup-thanks.html
  bedrock/firefox/templates/firefox/enterprise/signup.html
  bedrock/firefox/templates/firefox/organizations/organizations.html
  bedrock/firefox/urls.py
  media/css/firefox/enterprise.scss
  media/css/firefox/organizations.less
  media/img/firefox/enterprise/laptop-high-res.png
  media/img/firefox/enterprise/laptop.png
  media/img/firefox/organizations/title-high-res.png
  media/img/firefox/organizations/title.png
Labels: L10N - Not Required

#5695 [fix bug 1458036] Copy updates to /firefox/enterprise/ page
  bedrock/firefox/templates/firefox/enterprise/index.html
  media/css/firefox/enterprise.scss
  tests/functional/firefox/test_enterprise.py
  tests/pages/firefox/enterprise.py
Labels: L10N - Not Required

#5692 Bug 1456355: Sticky download cta
  bedrock/mozorg/templates/mozorg/home/home-a.html
  bedrock/settings/static_media.py
  media/css/mozorg/home/home-2018.scss
  media/css/pebbles/components/_card.scss
  media/img/home/2018/browser-high-res.png
  media/img/home/2018/browser.png
  media/js/mozorg/home/home.js
Labels: L10N - Not Required

#5736 Berlin page video experiment (Fixes #5637)
  bedrock/firefox/templates/firefox/new/berlin/base.html
  bedrock/firefox/templates/firefox/new/berlin/scene1-b.html
  bedrock/firefox/templates/firefox/new/berlin/scene1.html
  bedrock/firefox/templates/firefox/new/berlin/scene2-b.html
  bedrock/firefox/templates/firefox/new/berlin/scene2-herz.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  bedrock/settings/static_media.py
  media/css/firefox/new/berlin-b.scss
  media/css/firefox/new/berlin.scss
  media/img/firefox/new/berlin/hearts-large.png
  media/img/firefox/new/berlin/video-placeholder.jpg
  media/js/firefox/new/berlin-experiment.js
Labels: Do Not Merge :warning:, WIP :construction:

#5760 Add base template for Protocol design system (Fixes #5752)
  bedrock/base/templates/base-protocol.html
  media/css/protocol/components/_download-button.scss
  media/css/protocol/components/_footer.scss
  media/css/protocol/components/_global-nav.scss
  media/css/protocol/components/_masthead.scss
  media/css/protocol/oldIE.scss
  media/css/protocol/protocol.scss
Labels: Do Not Merge :warning:

#5768 Newsletter logo is too large on low-res screens (Fixes #5761)
  media/css/newsletter/fxnewsletter-subscribe.less
Labels: Bug :bug:
