Repository mozilla/bedrock, pull requests merged in 2018-02, with the labels that each got.

#5437 [fix bug 1405822] Set Firefox Accounts email-first form as default on /firstrun
  bedrock/firefox/templates/firefox/firstrun/email-first-experiment/index-a.html
  bedrock/firefox/templates/firefox/firstrun/email-first-experiment/index-b.html
  bedrock/firefox/templates/firefox/firstrun/firstrun_quantum.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  bedrock/settings/static_media.py
  docs/firefox-accounts.rst
  media/css/firefox/firstrun/firstrun_quantum.less
  media/js/firefox/firstrun/experiment-firstrun-email-first.js
Labels: Firefox, L10N - Strings Extracted

#5438 [fix bug 1407278] Update 'click here' link text on /firefox/new/?scene=2
  bedrock/firefox/templates/firefox/new/scene2.html
Labels: L10N - Strings Extracted

#5447 [fix bug 1433298] Add link to /firefox/switch/ from /firefox
  bedrock/firefox/templates/firefox/home.html
  media/css/firefox/home.scss
  media/img/firefox/home/data-truck-rtl.svg
  media/img/firefox/home/data-truck.svg
  media/img/firefox/home/switch-to-firefox-high-res.png
  media/img/firefox/home/switch-to-firefox.png
Labels: Firefox, L10N

#5452 [fix bug 1432493] Update branding on Firefox Nightly /whatsnew page
  bedrock/firefox/templates/firefox/nightly_whatsnew.html
  bedrock/firefox/templates/firefox/whatsnew/includes/header.html
  bedrock/settings/static_media.py
  media/css/firefox/nightly_whatsnew.less
  media/css/firefox/whatsnew/whatsnew-nightly.scss
Labels: L10N

#5445 Remove unused, old Firefox logos
  media/img/firefox/firefox-100.jpg
  media/img/firefox/template/header-logo-inverse-high-res.png
  media/img/firefox/template/header-logo-inverse.png
  media/img/firefox/template/logo-high-res.png
  media/img/firefox/template/logo.png
Labels: Papercuts, Quantum Cleanup

#5448 [fix bug 1437797] Remove old /56.0/whatsnew/ template
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-56.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  bedrock/settings/static_media.py
  media/css/firefox/whatsnew/whatsnew-56.scss
  media/img/firefox/whatsnew_56/fox-tail-header.png
  media/img/firefox/whatsnew_56/green-check.svg
  media/img/firefox/whatsnew_56/icon-library.svg
  media/img/firefox/whatsnew_56/icon-new-tab.svg
  media/img/firefox/whatsnew_56/icon-search.svg
  media/img/firefox/whatsnew_56/laptop-high-res.png
  media/img/firefox/whatsnew_56/laptop.png
  media/img/firefox/whatsnew_56/new-tab-high-res.png
  media/img/firefox/whatsnew_56/new-tab.png
  media/img/firefox/whatsnew_56/wave.svg
Labels: L10N, Papercuts

#5453 [fix bug 1438373] Correct pullquote on Decentralization page
  bedrock/mozorg/templates/mozorg/internet-health/decentralization.html
Labels: L10N

#5424 Fix Bug 1427250 - Out of date link in the Firefox ESR page
  bedrock/firefox/templates/firefox/organizations/organizations.html
Labels: No l10n required

#5454 [fix bug 1419244] Remove old one-off mobile download pages
  bedrock/etc/templates/etc/firefox/retention/thank-you-a.html
  bedrock/etc/templates/etc/firefox/retention/thank-you-b.html
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/includes/horizon.html
  bedrock/firefox/templates/firefox/mobile-download-desktop.html
  bedrock/firefox/templates/firefox/mobile-download.html
  bedrock/firefox/urls.py
  bedrock/settings/static_media.py
  media/css/firefox/horizon/background.less
  media/css/firefox/horizon/lib.less
  media/css/firefox/mobile-download-desktop.less
  media/css/firefox/mobile-download.less
  media/css/firefox/whatsnew-tw-hk-49.less
  media/img/firefox/horizon/foreground-high-res.png
  media/img/firefox/horizon/foreground.png
  media/img/firefox/horizon/fox.svg
  media/img/firefox/horizon/mountains-no-path.svg
  media/img/firefox/horizon/mountains.svg
  media/img/firefox/horizon/pathway-stones.svg
  media/img/firefox/horizon/sun.svg
  media/img/firefox/horizon/trees-left.svg
  media/img/firefox/horizon/trees-right.svg
  media/img/firefox/mobile/scene2-mobile-promo-device-lineup.png
  media/img/firefox/template/bg-noise.png
  media/img/send-to-device/device-icon-green-high-res.png
  media/img/send-to-device/device-icon-green.png
  media/js/firefox/mobile-download-desktop.js
  tests/redirects/map_globalconf.py
Labels: Papercuts

#5456 [fix bug 1438464] Decommission Lightbeam pages
  bedrock/foundation/templates/foundation/annualreport/2011.html
  bedrock/lightbeam/__init__.py
  bedrock/lightbeam/models.py
  bedrock/lightbeam/redirects.py
  bedrock/lightbeam/templates/lightbeam/about.html
  bedrock/lightbeam/templates/lightbeam/lightbeam.html
  bedrock/lightbeam/urls.py
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/about/manifesto.html
  bedrock/settings/base.py
  bedrock/settings/static_media.py
  bedrock/teach/templates/teach/smarton/tracking.html
  bedrock/urls.py
  media/css/lightbeam/lightbeam.less
  media/img/lightbeam/Lightbeam-AMOScreenshot1_anon.jpg
  media/img/lightbeam/Lightbeam-UpdatedGraphImageLandscape2.png
  media/img/lightbeam/Lightbeam-list-view.jpg
  media/img/lightbeam/Lightbeam-meet-firefox.png
  media/img/lightbeam/Lightbeam_Illustration1.png
  media/img/lightbeam/Lightbeam_Illustration2.png
  media/img/lightbeam/Lightbeam_Illustration4.png
  media/img/lightbeam/Lightbeam_Illustration5.png
  media/img/lightbeam/Lightbeam_Illustration6.png
  media/img/lightbeam/Lightbeam_Illustration7.png
  media/img/lightbeam/Lightbeam_partners_ecuad.png
  media/img/lightbeam/Lightbeam_partners_fordfoundation.png
  media/img/lightbeam/favicon.png
  media/img/lightbeam/ford-foundation.png
  media/img/lightbeam/lightbeam_logo-wordmark_500x156.png
  tests/redirects/map_globalconf.py
Labels: L10N, Papercuts

#5468 [fix bug 1439718] Convert /firstrun from Sandstone to Pebbles
  bedrock/firefox/templates/firefox/firstrun/base-pebbles.html
  bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  bedrock/settings/static_media.py
  media/css/base/mozilla-fxa-iframe.scss
  media/css/firefox/firstrun/firstrun-quantum.scss
Labels: Papercuts

#5473 [fix bug 1436973] Decommission legacy /firefox/unsupported/ URLs
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/unsupported/EOL.html
  bedrock/firefox/templates/firefox/unsupported/base.html
  bedrock/firefox/templates/firefox/unsupported/details.html
  bedrock/firefox/templates/firefox/unsupported/mac.html
  bedrock/firefox/templates/firefox/unsupported/warning.html
  bedrock/firefox/templates/firefox/unsupported/win2k.html
  bedrock/firefox/templates/firefox/unsupported/winxp.html
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  bedrock/settings/static_media.py
  media/css/firefox/unsupported.less
  media/img/firefox/unsupported/background.jpg
  tests/redirects/map_globalconf.py
Labels: Papercuts :money_with_wings:

#5474 [fix bug 1440404] Remove custom URL scheme for app store links to Firefox on iOS
  media/js/base/mozilla-utils.js
  tests/unit/spec/base/mozilla-utils.js
Labels: Bug :bug:

#5432 Fix Bug 1430027 - On the download page, for Linux, highlight the 64-bit version (to limit the number of 32 downloads)
  bedrock/base/templates/product-all-macros.html
  bedrock/firefox/firefox_details.py
  bedrock/firefox/views.py
  media/css/firefox/all.less
Labels: Firefox, L10N - Ready
