Repository mozilla/bedrock, pull requests merged in 2018-10, with the labels that each got.

#6244 [fix #5938] New Lean Data pages
  bedrock/foundation/templates/foundation/annualreport/2015/index.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/build-security.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/engage-users.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/index.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/stay-lean.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2016.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/templates/mozorg/internet-health/privacy-security.html
  bedrock/mozorg/urls.py
  media/css/mozorg/about-lean-data.less
  media/css/mozorg/lean-data.scss
  media/img/mozorg/about/lean-data/build-security-hero-high-res.png
  media/img/mozorg/about/lean-data/build-security-hero.png
  media/img/mozorg/about/lean-data/engage-users-hero-high-res.png
  media/img/mozorg/about/lean-data/engage-users-hero.png
  media/img/mozorg/about/lean-data/engage-users-icon.svg
  media/img/mozorg/about/lean-data/github-icon-high-res.png
  media/img/mozorg/about/lean-data/github-icon.png
  media/img/mozorg/about/lean-data/hero-data.svg
  media/img/mozorg/about/lean-data/lean-data-hero-high-res.png
  media/img/mozorg/about/lean-data/lean-data-hero.png
  media/img/mozorg/about/lean-data/lean-data-icon.svg
  media/img/mozorg/about/lean-data/security-icon.svg
  media/img/mozorg/about/lean-data/stay-lean-hero-high-res.png
  media/img/mozorg/about/lean-data/stay-lean-hero.png
  media/static-bundles.json
Labels: L10N - Not Required

#6235 [fix #5764] Update MOSS pages
  bedrock/mozorg/templates/mozorg/moss/index-092018.html
  bedrock/mozorg/urls.py
  bedrock/mozorg/views.py
  media/css/mozorg/moss/common.scss
  media/img/mozorg/moss/securedrop-high-res.png
  media/img/mozorg/moss/securedrop.png
Labels: L10N

#6240 Update SEM browser comparison tables (Fixes #6202)
  bedrock/firefox/templates/firefox/new/compare/scene1-chrome-2.html
  bedrock/firefox/templates/firefox/new/compare/scene1-edge-2.html
  bedrock/firefox/templates/firefox/new/compare/scene1-safari-2.html
  media/css/firefox/new/compare.scss
Labels: Needs Review

#6241 Remove background image from /firefox/switch/ (Fixes #6192)
  media/css/firefox/switch.scss
  media/img/firefox/switch/arrow.png
  media/img/firefox/switch/face.png
  media/img/firefox/switch/icon-e.svg
  media/img/firefox/switch/icon-fb.svg
  media/img/firefox/switch/icon-t.svg
  media/img/firefox/switch/oval.png
  media/img/firefox/switch/wave.png
Labels: Needs Review

#6242 [fix bug 1494310] Rename shadow-outside to shape-outside on /firefox/developer/
  bedrock/firefox/templates/firefox/developer/includes/highlights.html
Labels: L10N, Needs Review

#6169 Capitalize 'Restart Tour' in variation 0 of Tracking Protection tour (#6082)
  bedrock/firefox/templates/firefox/tracking-protection-tour/variation-0.html
Labels: L10N - Not Required, Needs Review

#6219 Move FxA state CSS to a common shared file (Fixes #6211)
  media/css/base/mozilla-fxa-state.scss
  media/css/firefox/accounts-features.scss
  media/css/firefox/accounts.scss
  media/css/firefox/features/sync.scss
  media/css/firefox/new/scene1-fx.scss
  media/css/firefox/profile-per-install.scss
  media/css/pebbles/components/_fxa.scss
  media/static-bundles.json
Labels: Needs Review, Papercuts

#6232 Update @mozilla-protocol/core to v2.4.2
  media/css/firefox/new/compare.scss
  media/css/firefox/new/scene2.scss
  media/css/firefox/pocket.scss
  media/css/firefox/whatsnew/whatsnew-62.scss
  media/css/mozorg/about-en.scss
  media/css/mozorg/home/home-2018.scss
  media/css/mozorg/lean-data.scss
  media/css/privacy/privacy-email.scss
  media/css/protocol/components/_download-button.scss
  media/css/protocol/components/_footer.scss
  media/css/protocol/components/_global-nav.scss
  media/css/protocol/components/_masthead.scss
  media/css/protocol/oldIE.scss
  media/css/protocol/protocol.scss
  package.json
  yarn.lock
Labels: Needs Review

#6195 Add /whatsnew page for Firefox 63 (Fixes #6161)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx63.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-63.scss
  media/img/firefox/whatsnew_63/avatar.svg
  media/img/firefox/whatsnew_63/wnp63-content-blocking-high-res.png
  media/img/firefox/whatsnew_63/wnp63-content-blocking-rtl-high-res.png
  media/img/firefox/whatsnew_63/wnp63-content-blocking-rtl.png
  media/img/firefox/whatsnew_63/wnp63-content-blocking.png
  media/img/firefox/whatsnew_63/wnp63-hero-high-res.png
  media/img/firefox/whatsnew_63/wnp63-hero.png
  media/img/firefox/whatsnew_63/wnp63-secure-sync-devices-high-res.png
  media/img/firefox/whatsnew_63/wnp63-secure-sync-devices.png
  media/img/firefox/whatsnew_63/wnp63-tracking-controls-high-res.png
  media/img/firefox/whatsnew_63/wnp63-tracking-controls.png
  media/js/firefox/whatsnew/whatsnew-63.js
  media/static-bundles.json
Labels: L10N - Strings Extracted

#6273 [fix bug 1495671] Content Blocking Tour breaks on step 3 with only cookie restrictions enabled.
  bedrock/firefox/templates/firefox/tracking-protection-tour/index.html
Labels: Bug :bug:, Needs Review

#6286 [fix bug 1498290] Expose locale versions of Content Blocking Tour
  bedrock/firefox/templates/firefox/tracking-protection-tour/variation-1.html
  bedrock/firefox/templates/firefox/tracking-protection-tour/variation-2.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
Labels: L10N - Strings Extracted, Needs Review

#6313 Fix Bug 1500250 - Broken layout on https://www.mozilla.org/fr/firefox/developer/
  bedrock/firefox/templates/firefox/developer/includes/highlights.html
  media/css/firefox/developer/developer.scss
  media/css/firefox/developer/includes/highlights.scss
Labels: Bug :bug:

#6324 Add clarifying legal copy to /foundation
  bedrock/foundation/templates/foundation/index.html
Labels: L10N

#6224 Remove pre-download experiment code (#5944)
  bedrock/firefox/templates/firefox/home-a.html
  bedrock/firefox/templates/firefox/home-b.html
  bedrock/firefox/templates/firefox/home-c.html
  bedrock/firefox/templates/firefox/home.html
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  media/css/firefox/home-pre-download.scss
  media/js/firefox/home/experiment-pre-download.js
  media/js/firefox/home/pre-download-a-ga.js
  media/js/firefox/home/pre-download-newsletter.js
  media/static-bundles.json
  tests/functional/firefox/test_home.py
Labels: Needs Review

#6220 Update bedrock to use new Protocol navigation (Fixes #6174)
  bedrock/base/templates/base-pebbles-basic.html
  bedrock/base/templates/base-pebbles.html
  bedrock/base/templates/base-protocol.html
  bedrock/base/templates/base-resp.html
  bedrock/base/templates/includes/navigation-switch.html
  bedrock/base/templates/includes/protocol/navigation/index.html
  bedrock/base/templates/includes/protocol/navigation/menu/about.html
  bedrock/base/templates/includes/protocol/navigation/menu/developers.html
  bedrock/base/templates/includes/protocol/navigation/menu/firefox.html
  bedrock/base/templates/includes/protocol/navigation/menu/projects.html
  bedrock/firefox/templates/firefox/base-pebbles.html
  bedrock/firefox/templates/firefox/base-protocol.html
  bedrock/mozorg/templates/mozorg/about/manifesto.html
  bedrock/mozorg/templates/mozorg/contact/contact-base.html
  bedrock/mozorg/templates/mozorg/developer/index.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/templates/mozorg/internet-health/decentralization.html
  bedrock/mozorg/templates/mozorg/internet-health/digital-inclusion.html
  bedrock/mozorg/templates/mozorg/internet-health/open-innovation.html
  bedrock/mozorg/templates/mozorg/internet-health/privacy-security.html
  bedrock/mozorg/templates/mozorg/moss/base.html
  bedrock/mozorg/templates/mozorg/technology.html
  media/css/base/page-not-found.scss
  media/css/firefox/profile-per-install.scss
  media/css/hubs/_nav-download-button-remove.scss
  media/css/legal/legal.less
  media/css/mozorg/home/home-2018.scss
  media/css/newsletter/newsletter.less
  media/css/pebbles/components/_protocol-nav.scss
  media/css/pebbles/global-nav.scss
  media/css/pebbles/global.scss
  media/css/pebbles/protocol-nav.scss
  media/css/privacy/privacy.less
  media/css/protocol/components/_footer.scss
  media/css/protocol/components/_navigation.scss
  media/css/protocol/protocol-global-nav.scss
  media/css/protocol/protocol.scss
  media/css/sandstone/protocol-nav.scss
  media/img/nav/cards/add-ons.png
  media/img/nav/cards/developer-edition.png
  media/img/nav/cards/firefox-reality.png
  media/img/nav/cards/mozilla-festival.jpg
  media/js/base/protocol/init-navigation.js
  media/static-bundles.json
  package.json
  yarn.lock
Labels: L10N - Not Required

#6151 Create reusable macros for Protocol components (#6107)
  bedrock/base/templates/macros-protocol.html
  bedrock/firefox/templates/firefox/features/adblocker.html
  bedrock/firefox/templates/firefox/new/compare/base-1.html
  bedrock/firefox/templates/firefox/new/compare/base-2.html
  bedrock/firefox/templates/firefox/new/compare/scene1-chrome-1.html
  bedrock/firefox/templates/firefox/new/compare/scene1-edge-1.html
  bedrock/firefox/templates/firefox/new/compare/scene1-opera-1.html
  bedrock/firefox/templates/firefox/new/compare/scene1-safari-1.html
  bedrock/firefox/templates/firefox/new/compare/scene1-safari-2.html
  bedrock/firefox/templates/firefox/pocket.html
  bedrock/firefox/templates/firefox/recommended.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx62.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx63.html
  bedrock/mozorg/templates/mozorg/about-en.html
  bedrock/mozorg/templates/mozorg/home/home-en-election.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/tests/test_views.py
  bedrock/mozorg/views.py
  media/css/firefox/features/adblocker.scss
  media/css/firefox/whatsnew/whatsnew-63.scss
  media/js/firefox/whatsnew/whatsnew-63.js
Labels: Needs Review, Papercuts

#6382 Add main navigation to /firefox/channel/, /firefox/accounts/ and /firefox/enterprise/ (Fixes #6381)
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  media/css/firefox/accounts.scss
  media/css/firefox/enterprise.scss
Labels: L10N - Not Required

#6314 update testflight logo
  bedrock/firefox/templates/firefox/testflight.html
  media/css/firefox/testflight.less
  media/img/firefox/ios/testflight/devices-high-res.png
  media/img/firefox/ios/testflight/devices-mobile-high-res.png
  media/img/firefox/ios/testflight/devices-mobile.png
  media/img/firefox/ios/testflight/devices.png
Labels: P2, Review: XS
