Repository mozilla/bedrock, pull requests merged in 2018-07, with the labels that each got.

#5850 Data Privacy content updates
  bedrock/privacy/redirects.py
  bedrock/privacy/templates/privacy/archive/firefox-cliqz-2018-06.de.html
  bedrock/privacy/templates/privacy/archive/firefox-cliqz-2018-06.html
  bedrock/privacy/templates/privacy/archive/firefox-marketplace-2015-01.html
  bedrock/privacy/templates/privacy/archive/index.html
  bedrock/privacy/templates/privacy/index.html
  bedrock/privacy/templates/privacy/notices/firefox-cliqz-quantum.html
  bedrock/privacy/templates/privacy/notices/firefox-cliqz.html
  bedrock/privacy/urls.py
  bedrock/privacy/views.py
  media/css/privacy/privacy.less
  tests/redirects/map_globalconf.py
Labels: L10N - Strings Extracted

#5863 [#5745] Add principles link to privacy sidebar
  bedrock/privacy/templates/privacy/index.html
  media/css/privacy/privacy.less
Labels: L10N

#5871 Remove invalid chars from UTM params on /firefox/accounts/features/ CTAs (Fixes #5870)
  bedrock/base/templates/macros.html
Labels: Bug :bug:

#5916 Update release notes page titles
  bedrock/firefox/templates/firefox/releases/release-notes.html
Labels: SEO 🔎

#5917 [Fix #5862] Update Firefox Accounts benefits page
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/accounts-features.html
  bedrock/firefox/templates/firefox/features/send-tabs.html
  bedrock/firefox/templates/firefox/features/sync.html
  media/css/firefox/accounts-features.scss
  media/img/firefox/accounts/features/passwords-high-res.png
  media/img/firefox/accounts/features/passwords.png
  media/js/firefox/accounts-features-experiment.js
Labels: L10N - Not Required
