Repository mozilla/bedrock, pull requests merged in 2019-08, with the labels that each got.

#7446 Decommission old /whatsnew and /firstrun pages for Dev Edition (Fixes #7437)
  bedrock/firefox/templates/firefox/dev-firstrun.html
  bedrock/firefox/templates/firefox/dev-whatsnew.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/dev-firstrun.less
  media/img/firefox/dev-firstrun/devtools-blue-high-res.png
  media/img/firefox/dev-firstrun/devtools-blue.png
  media/img/firefox/dev-firstrun/devtools-white-high-res.png
  media/img/firefox/dev-firstrun/devtools-white.png
  media/img/firefox/dev-firstrun/sync-blue-high-res.png
  media/img/firefox/dev-firstrun/sync-blue.png
  media/img/firefox/dev-firstrun/sync-white-high-res.png
  media/img/firefox/dev-firstrun/sync-white.png
  media/img/firefox/developer/feature-responsive.jpg
  media/img/firefox/developer/feature-valence.jpg
  media/img/firefox/developer/title-inverse-high-res.png
  media/img/firefox/developer/title-inverse.png
  media/js/firefox/dev-firstrun.js
  media/js/firefox/dev-whatsnew.js
  media/static-bundles.json
Labels: P3, Review: XS

#7471 Port MPL pages to Protocol (Fixes #6464)
  bedrock/mozorg/templates/mozorg/base.html
  bedrock/mozorg/templates/mozorg/mpl/1.1/faq.html
  bedrock/mozorg/templates/mozorg/mpl/2.0/combining-mpl-and-gpl.html
  bedrock/mozorg/templates/mozorg/mpl/2.0/faq.html
  bedrock/mozorg/templates/mozorg/mpl/2.0/permissive-code-into-mpl.html
  bedrock/mozorg/templates/mozorg/mpl/2.0/revision-faq.html
  bedrock/mozorg/templates/mozorg/mpl/headers/index.html
  bedrock/mozorg/templates/mozorg/mpl/historical.html
  bedrock/mozorg/templates/mozorg/mpl/index.html
  bedrock/mozorg/templates/mozorg/mpl/license-policy.html
  media/css/mozorg/mpl-1-1-annotated.scss
  media/css/mozorg/mpl-1-1.scss
  media/css/mozorg/mpl-2-0.scss
  media/css/mozorg/mpl-differences.scss
  media/css/mozorg/mpl.less
  media/static-bundles.json
Labels: P3, Review: S

#7453 Decommission the /about/history/ slideshow (Fixes #7435)
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/about-base-resp.html
  bedrock/mozorg/templates/mozorg/about-base.html
  bedrock/mozorg/templates/mozorg/about/history-details.html
  bedrock/mozorg/templates/mozorg/about/history.html
  bedrock/mozorg/urls.py
  media/css/mozorg/about-base.less
  media/css/mozorg/history-slides.less
  media/img/mozorg/history/fact01-pads.png
  media/img/mozorg/history/fact02-pads.png
  media/img/mozorg/history/fact03-pads.png
  media/img/mozorg/history/fact04-pads.png
  media/img/mozorg/history/fact05-pads.png
  media/img/mozorg/history/fact06-pads.png
  media/img/mozorg/history/fact07-pads.png
  media/img/mozorg/history/fact08-pads.png
  media/img/mozorg/history/fact09-pads.png
  media/img/mozorg/history/fact10-pads.png
  media/img/mozorg/history/fact11-pads.png
  media/img/mozorg/history/fact12-pads.png
  media/img/mozorg/history/fact13-pads.png
  media/img/mozorg/history/fact14-pads.png
  media/img/mozorg/history/fact15-pads.png
  media/img/mozorg/history/fxlogo.png
  media/img/mozorg/history/numbers.png
  media/img/mozorg/history/path-darkblue.png
  media/img/mozorg/history/path-green.png
  media/img/mozorg/history/path-lightblue.png
  media/img/mozorg/history/path-orange.png
  media/img/mozorg/history/path-red.png
  media/img/mozorg/history/slide-arrows.png
  media/js/libs/jquery.sequence.js
  media/js/mozorg/history-slides.js
  media/static-bundles.json
  tests/functional/test_history.py
  tests/pages/history.py
  tests/redirects/map_globalconf.py
Labels: P3, Review: XS

#7510 Fix privacy notice template name
  bedrock/privacy/views.py
Labels: Bug :bug:

#7502 Update universal CSS for legacy IE browsers (Fixes #7390)
  bedrock/base/templates/includes/protocol/navigation/index.html
  bedrock/base/templates/includes/sub-nav.html
  bedrock/firefox/templates/firefox/accounts-2019.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/includes/macros.html
  media/css/pebbles/base/oldIE.scss
  media/css/protocol/components/_navigation-ie.scss
  media/css/protocol/oldIE.scss
  media/css/sandstone/old-ie.scss
  media/img/nav/logo-black.png
  media/img/nav/menu.png
  media/js/ie8/base-page-init-ie8.js
  media/js/ie8/mozilla-utils-ie8.js
  media/static-bundles.json
Labels: P2, Review: S

#7514 Port Firefox legal page to Protocol (Fixes #7513)
  bedrock/legal/templates/legal/firefox.html
Labels: P1, Review: XS

#7529 Fix transparency report base template
  bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/report-base.html
Labels: Bug :bug:

#7540 Remove pathlib2
  bedrock/contentcards/models.py
  bedrock/contentcards/tests/test_models.py
  bedrock/mozorg/tests/test_commands.py
  bedrock/pocketfeed/tests/test_models.py
  bedrock/releasenotes/tests/test_base.py
  bedrock/releasenotes/tests/test_models.py
  bedrock/settings/base.py
  bedrock/utils/git.py
  bedrock/wordpress/tests/test_models.py
  bin/cron.py
  lib/l10n_utils/tests/test_dotlang.py
  lib/l10n_utils/tests/test_template.py
  requirements/base.txt
Labels: Papercuts 💸

#7493 Update firstrun page [Fixes: #7354]
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
  bedrock/firefox/templates/firefox/firstrun/firstrun.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/firstrun/firstrun-quantum.scss
  media/css/firefox/firstrun/firstrun.scss
  media/css/firefox/whatsnew/whatsnew-63.scss
  media/css/firefox/whatsnew/whatsnew-65.scss
  media/css/firefox/whatsnew/whatsnew-66.scss
  media/img/firefox/firstrun/deviceSwoosh.gif
  media/static-bundles.json
Labels: Do Not Merge :warning:, P2, Review: S

#7518 Port grants pages to Protocol (Fixes #7511)
  bedrock/grants/templates/grants/base.html
  bedrock/grants/templates/grants/index.html
  bedrock/grants/templates/grants/info.html
  bedrock/grants/templates/grants/reports/gnome-haeger-report.html
  bedrock/grants/templates/grants/reports/ushahidi-chile-report.html
  media/css/grants/grants.less
  media/css/grants/grants.scss
  media/static-bundles.json
Labels: P3, Review: XS

#7517 Defer loading YouTube API on homepage (Fixes #7423)
  media/js/mozorg/home/home.js
  media/js/mozorg/home/youtube.js
  media/static-bundles.json
Labels: P2, Review: S

#7550 Decommission /firefox/feedback/ page (Fixes #7436)
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/feedback/happy.html
  bedrock/firefox/templates/firefox/feedback/unhappy.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  media/css/firefox/feedback.less
  media/img/firefox/feedback/cta-icons-high-res.png
  media/img/firefox/feedback/cta-icons.png
  media/static-bundles.json
  tests/redirects/map_globalconf.py
Labels: P3, Review: XS

#7516 Add deep linking to /firefox/all/ (Fixes #7208)
  media/js/firefox/all/all-downloads-unified.js
  tests/unit/spec/firefox/all/all-downloads-unified.js
Labels: P2, Review: S

#7562 Implement Generic CTA datalayer attributes (Fixes #7541)
  bedrock/base/templates/includes/protocol/navigation/index.html
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/accounts-2019.html
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/concerts.html
  bedrock/firefox/templates/firefox/new/scene1.html
  bedrock/newsletter/templates/newsletter/includes/form-protocol.html
  bedrock/newsletter/templates/newsletter/includes/form.html
  docs/analytics.rst
  docs/firefox-accounts.rst
Labels: P3, Review: S

#7549 Standardize UTM parameters on mozilla.org for FxA referrals (Fixes #7417)
  bedrock/base/templates/includes/protocol/navigation/index.html
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/accounts-2019.html
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/developer/whatsnew-fx68-trailhead.html
  bedrock/firefox/templates/firefox/developer/whatsnew-fx68.html
  bedrock/firefox/templates/firefox/firstrun/firstrun.html
  bedrock/firefox/templates/firefox/new/scene1.html
  bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68-trailhead.html
  bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64-base.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx63.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx65.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-b.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-c.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-d.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-e.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-trailhead.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68.html
  docs/firefox-accounts.rst
Labels: P2, Review: M

#7563 Update /contribute survey (Fixes #7553)
  bedrock/mozorg/templates/mozorg/contribute/contribute-base.html
  bedrock/mozorg/templates/mozorg/contribute/index.html
  media/css/mozorg/contribute/contribute-base.less
  media/js/mozorg/contribute/contribute-survey.js
  media/static-bundles.json
Labels: P3, Review: XS

#7573 Update Nightly /firstrun page to use Protocol (FIxes #7451)
  bedrock/base/templates/macros-protocol.html
  bedrock/firefox/templates/firefox/nightly_firstrun.html
  media/css/firefox/nightly-firstrun.scss
  media/css/firefox/nightly_firstrun.less
  media/css/firefox/whatsnew/whatsnew-nightly.scss
  media/img/firefox/firstrun/background-nightly.jpg
  media/img/firefox/firstrun/grain.png
  media/img/firefox/firstrun/logo-nightly-high-res.png
  media/img/firefox/firstrun/logo-nightly.png
  media/img/firefox/firstrun/nightly-badge.png
  media/img/firefox/nightly/favicon-192.png
  media/img/firefox/nightly/favicon.png
  media/img/firefox/nightly/page-image.png
  media/img/logos/firefox/nightly-logo-high-res.png
  media/img/logos/firefox/nightly-logo.png
  media/static-bundles.json
  tests/pages/firefox/nightly.py
Labels: P2, Review: XS

#7601 Fix JS error on /firefox/firstrun/ page (Fixes #7581)
  media/js/firefox/firstrun/firstrun_quantum.js
  media/static-bundles.json
Labels: P3, Review: XS

#7599 [fix #7465] Add whatsnew page for Firefox 69
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-b.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-c.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx69.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  docs/firefox-accounts.rst
  media/css/firefox/whatsnew/whatsnew-69.scss
  media/img/firefox/glyphs/experiments.svg
  media/img/firefox/glyphs/heart.svg
  media/img/firefox/glyphs/inbox.svg
  media/img/firefox/glyphs/layers.svg
  media/img/firefox/glyphs/lockwise.svg
  media/img/firefox/glyphs/pocket.svg
  media/img/firefox/glyphs/send.svg
  media/img/firefox/glyphs/tracking-protection.svg
  media/img/icons/pocket.svg
  media/img/icons/tracking-protection.svg
  media/js/firefox/whatsnew/whatsnew-69.js
  media/static-bundles.json
Labels: Review: M

#7610 Update to Protocol 8.0.0
  media/css/firefox/enterprise-sla.scss
  media/css/privacy/privacy-protocol.scss
  media/css/protocol/basic-article.scss
  media/css/security/security.scss
  media/fonts/Metropolis-Bold.woff
  media/fonts/Metropolis-Bold.woff2
  media/fonts/Metropolis-Medium.woff
  media/fonts/Metropolis-Medium.woff2
  package.json
  yarn.lock
Labels: P2, Review: XS

#7621 Fix bug 1576673: Disable GA on Fx Privacy Notice
  bedrock/privacy/templates/privacy/notices/firefox-quantum.html
  bedrock/privacy/templates/privacy/notices/websites.html
Labels: Needs Review, P2

#7602 Remove legacy l10n-example page (Fixes #7519)
  bedrock/l10n_example/__init__.py
  bedrock/l10n_example/models.py
  bedrock/l10n_example/templates/l10n_example/example.html
  bedrock/l10n_example/urls.py
  bedrock/settings/base.py
  bedrock/urls.py
Labels: P3, Review: XS

#7633 Update Firefox Beta and Developer logos (Fixes #7568)
  bedrock/firefox/templates/firefox/all.html
  bedrock/foundation/templates/foundation/trademarks/list.html
  media/css/firefox/channel.less
  media/css/firefox/developer/includes/intro.scss
  media/css/firefox/nightly-firstrun.scss
  media/css/firefox/system-requirements.scss
  media/css/firefox/whatsnew/whatsnew-nightly.scss
  media/img/firefox/developer/browser-high-res.png
  media/img/firefox/developer/browser-nightly-high-res.png
  media/img/firefox/developer/browser-nightly.png
  media/img/firefox/developer/browser.png
  media/img/firefox/developer/favicon-196.png
  media/img/firefox/developer/favicon.png
  media/img/firefox/developer/logo-wordmark-high-res.png
  media/img/firefox/developer/logo-wordmark-stacked-high-res.png
  media/img/firefox/developer/logo-wordmark-stacked.png
  media/img/firefox/developer/logo-wordmark.png
  media/img/firefox/developer/page-image.png
  media/img/firefox/template/header-logo-nightly-high-res.png
  media/img/firefox/template/header-logo-nightly.png
  media/img/logos/firefox/beta-high-res.png
  media/img/logos/firefox/beta-logo-high-res.png
  media/img/logos/firefox/beta-logo.png
  media/img/logos/firefox/beta.png
  media/img/logos/firefox/developer-high-res.png
  media/img/logos/firefox/developer-wordmark-dark-high-res.png
  media/img/logos/firefox/developer-wordmark-dark.png
  media/img/logos/firefox/developer-wordmark-high-res.png
  media/img/logos/firefox/developer-wordmark.png
  media/img/logos/firefox/developer.png
  media/img/logos/firefox/logo-dev-edition-quantum-wordmark-wide-high-res.png
  media/img/logos/firefox/logo-dev-edition-quantum-wordmark-wide.png
  media/img/logos/firefox/logo-developer-quantum-high-res.png
  media/img/logos/firefox/logo-developer-quantum.png
  media/img/logos/firefox/nightly-high-res.png
  media/img/logos/firefox/nightly-wordmark-dark-high-res.png
  media/img/logos/firefox/nightly-wordmark-dark.png
  media/img/logos/firefox/nightly-wordmark-high-res.png
  media/img/logos/firefox/nightly-wordmark.png
  media/img/logos/firefox/nightly.png
  media/img/trademarks/logo-developer-quantum.png
  media/img/trademarks/nightly-logo.png
Labels: P2, Review: S
