Repository mozilla/bedrock, pull requests merged in 2019-07, with the labels that each got.

#7304 Add MSI installers to /all page (Fixes #7209)
  bedrock/base/templates/product-all-unified-macros.html
  bedrock/firefox/firefox_details.py
  bedrock/firefox/templates/firefox/all-unified.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/tests/test_helpers.py
  bedrock/firefox/views.py
  media/css/firefox/all/all-unified.scss
  media/css/pebbles/components/_buttons-download.scss
  media/css/protocol/components/_download-button.scss
  media/css/sandstone/buttons.less
  media/img/firefox/all/icon-question-high-res.png
  media/img/firefox/all/icon-question.png
  media/js/firefox/all/all-downloads-unified-init.js
Labels: P1, Review: S

#7362 Convert /enterprise to Protocol (#7352)
  bedrock/firefox/templates/firefox/enterprise/index.html
  media/css/firefox/enterprise.scss
  media/img/firefox/enterprise/circle.png
  media/img/firefox/enterprise/curve.png
  media/img/firefox/enterprise/ent-noodles-wide.svg
  media/img/firefox/enterprise/ent-noodles.svg
  media/img/firefox/enterprise/fx-browser-img.svg
  media/img/firefox/enterprise/laptop-high-res.png
  media/img/firefox/enterprise/laptop.png
  media/img/firefox/enterprise/wave.png
  media/img/logos/firefox/logo-quantum-full-wordmark-high-res.png
  media/img/logos/firefox/logo-quantum-full-wordmark-white-high-res.png
  media/img/logos/firefox/logo-quantum-full-wordmark-white.png
  media/img/logos/firefox/logo-quantum-full-wordmark.png
Labels: P1, Review: XS

#7346 Run hero rendering experiment for mobile users (#7118)
  media/js/mozorg/perf-exp/control.js
  media/js/mozorg/perf-exp/experiment.js
  media/js/mozorg/perf-exp/variation.js
Labels: P3, Review: XS

#7334 Add 'Why Firefox' SEO page. (Fixes #6815)
  bedrock/firefox/templates/firefox/best-browser.html
  bedrock/firefox/urls.py
  media/css/firefox/bestbrowser.scss
  media/img/firefox/best-browser/hero-pattern.png
  media/static-bundles.json
Labels: Review: XS

#7364 Update structured data on home-en
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/templates/mozorg/home/includes/structured-data.html
Labels: P3, Review: XS

#7355 Update jQuery to v3.4.2 (Fixes #7351)
  media/js/firefox/tracking-protection-tour.js
  media/js/libs/jquery-3.2.1.min.js
  media/js/libs/jquery-3.4.1.min.js
  media/static-bundles.json
  tests/unit/karma.conf.js
Labels: P1, Review: S

#7376 Remove Nick Nguyen from leadership page. (Fixes #7374)
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/nick-nguyen-high-res.jpg
  media/img/mozorg/about/leadership/nick-nguyen.jpg
Labels: P1

#7363 Remove legacy /firefox/accounts/ template (Fixes #6837)
  bedrock/firefox/templates/firefox/accounts-2018.html
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/css/firefox/accounts-2018.scss
  media/css/firefox/accounts.scss
  media/img/firefox/accounts/green-check-high-res.png
  media/img/firefox/accounts/green-check.png
  media/img/firefox/accounts/sync-devices-high-res.png
  media/img/firefox/accounts/sync-devices.png
  media/img/firefox/accounts/tail.png
  media/js/firefox/accounts.js
  media/static-bundles.json
Labels: P3, Review: XS

#7361 Fixing issue #7331
  bedrock/base/templates/includes/protocol/navigation/index.html
  bedrock/firefox/templates/firefox/accounts-2019.html
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/installer-help.html
  media/css/firefox/new/trailhead/download.scss
Labels: P3, Review: XS

#7369 Enable /whatsnew page for Firefox 68 (Fixes #7367)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-trailhead.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
Labels: P1, Review: XS

#7384 String changes for enterprise page [Fixes #7375]
  bedrock/firefox/templates/firefox/enterprise/index.html
  tests/pages/firefox/enterprise.py
Labels: P2, Review: XS

#7385 removed unused assets and associated tests [fixes #7066]
  media/css/base/platform-footer-links.less
  media/css/base/svg-animation-check.less
  media/css/libs/jquery.pageslide.css
  media/css/libs/tipsy.css
  media/js/base/mozilla-firefox-default.js
  media/js/base/mozilla-highlight-target.js
  media/js/base/mozilla-image-helper.js
  media/js/base/mozilla-svg-image-fallback.js
  media/js/base/svg-animation-check.js
  media/js/firefox/new-ios-redirect-helper.js
  media/js/firefox/new-ios-redirect.js
  media/js/firefox/platforms.js
  media/js/firefox/private-browsing.js
  media/js/libs/fxa-relier-client.min.js
  media/js/libs/jquery.sequence.2.1.0.min.js
  media/js/libs/mozcountdown.js
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-firefox-default.js
  tests/unit/spec/base/mozilla-highlight-target.js
  tests/unit/spec/base/mozilla-image-helper.js
  tests/unit/spec/base/mozilla-svg-image-fallback.js
  tests/unit/spec/firefox/new-ios-redirect-helper.js
Labels: P3, Review: XS

#7359 Convert Enterprise form pages to Protocol (#7352)
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/enterprise/signup-thanks.html
  bedrock/firefox/templates/firefox/enterprise/signup.html
  media/css/firefox/enterprise.scss
Labels: Needs Review, P1, Review: XS

#7396 Removed Attributes causing duplication of events [Fixes #7392]
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/mobile.html
  bedrock/mozorg/templates/mozorg/about-2019.html
  bedrock/mozorg/templates/mozorg/home/includes/macros.html
Labels: P2, Review: XS

#7418 Selecting ESR on /all should let me download an MSI installer (Fixes #7410)
  bedrock/base/templates/product-all-unified-macros.html
  bedrock/firefox/templates/firefox/all-unified.html
  media/css/firefox/all/all-unified.scss
  media/js/firefox/all/all-downloads-unified.js
  tests/unit/spec/firefox/all/all-downloads-unified.js
Labels: Bug :bug:, P1, Review: XS

#7416 Update firefox/features/adblocker copy for l10n
  bedrock/firefox/templates/firefox/features/adblocker.html
Labels: P1, Review: XS

#7397 Standardize fxa_email_form UTM values. (Fixes #7387)
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/accounts-2019.html
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/developer/whatsnew-fx68-trailhead.html
  bedrock/firefox/templates/firefox/developer/whatsnew-fx68.html
  bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
  bedrock/firefox/templates/firefox/new/scene1.html
  bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68-trailhead.html
  bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64-base.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx63.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx65.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-trailhead.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68.html
Labels: P1

#7339 Upgrade Jasmine and Karma dependencies (Fixes #6867)
  .circleci/config.yml
  .eslintrc.js
  media/js/base/stub-attribution-macos.js
  media/js/firefox/tracking-protection-tour.js
  package.json
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-client.js
  tests/unit/spec/base/mozilla-notification-banner.js
  tests/unit/spec/base/mozilla-pager.js
  tests/unit/spec/base/mozilla-traffic-cop-funnelcake-geo.js
  tests/unit/spec/base/search-params.js
  tests/unit/spec/base/send-to-device.js
  tests/unit/spec/firefox/all/all-downloads-unified.js
  tests/unit/spec/firefox/new/yandex/scene1.js
  tests/unit/spec/firefox/tracking-protection-tour.js
  yarn.lock
Labels: P3, Review: S

#7415 [fix #7413] Remove TriageBot from Nightly WNP
  bedrock/firefox/templates/firefox/nightly_whatsnew.html
Labels: Review: XS

#7399 [fix #7297] Remove June fundraising banner
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/includes/fundraiser.html
  media/css/mozorg/home/fundraiser.scss
  media/js/mozorg/home/fundraiser.js
  media/static-bundles.json
Labels: Papercuts 💸, Review: XS

#7432 Re-enable smoothscroll unit test (#6867)
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-smoothscroll.js
Labels: P3, Review: XS

#7428 Adresses CSP violation [Fixes #6684]
  bedrock/mozorg/templates/mozorg/about/forums/forums.html
  media/img/logos/google/logo_google.svg
Labels: P2, Review: XS

#7402 Update stylelint (Fixes #6869)
  .stylelintrc
  gulpfile.js
  media/css/sandstone/buttons.less
  media/css/sandstone/lib.less
  media/css/sandstone/mixins/at2x.less
  package.json
  yarn.lock
Labels: P3, Review: XS

#7427 /firefox pre-download newsletter cleanup (Fixes #7254)
  bedrock/firefox/templates/firefox/home/index.de.html
  bedrock/firefox/templates/firefox/home/index.fr.html
  bedrock/firefox/templates/firefox/home/index.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/css/firefox/home/pre-download-newsletter.scss
  media/js/firefox/home/pre-download-newsletter.js
  media/static-bundles.json
Labels: P3, Review: XS

#7445 Decommission ITU page (Fixes #7434)
  bedrock/mozorg/templates/mozorg/itu.html
  bedrock/mozorg/urls.py
  media/css/mozorg/itu.less
  media/static-bundles.json
Labels: P3, Review: XS

#7243 Add script to optimize images #6480
  bin/img.sh
  docs/coding.rst
  package.json
  yarn.lock
Labels: P3, Review: XS

#7395 Compare master and stage hash during deployment
  bin/tag-release.sh
Labels: P3, Review: XS

#7447 Remove old /about/ page template (Fixes #7442)
  bedrock/mozorg/templates/mozorg/about-2019.html
  bedrock/mozorg/templates/mozorg/about.html
  bedrock/mozorg/templates/mozorg/perf-exp/control.html
  bedrock/mozorg/templates/mozorg/perf-exp/variation.html
  bedrock/mozorg/tests/test_views.py
  bedrock/mozorg/urls.py
  bedrock/mozorg/views.py
  media/css/mozorg/about.less
  media/css/mozorg/about.scss
  media/css/mozorg/perf-exp/index.scss
  media/js/mozorg/about.js
  media/js/mozorg/perf-exp/control.js
  media/js/mozorg/perf-exp/experiment.js
  media/js/mozorg/perf-exp/variation.js
  media/static-bundles.json
Labels: P3, Review: XS

#7383 Add Join Firefox modal to /firefox/new/ (Fixes #7232)
  bedrock/firefox/templates/firefox/new/trailhead/download.html
  media/css/firefox/new/trailhead/download.scss
  media/js/firefox/new/trailhead/join-modal.js
  media/static-bundles.json
  tests/functional/firefox/new/test_download.py
  tests/pages/firefox/new/download.py
Labels: P1, Review: S

#7433 Updating contribute-base.less to fix italic addresses on /contribute/events/.
  media/css/mozorg/contribute/contribute-base.less
Labels: P3, Review: XS

#7459 Remove /firefox brand experiment
  bedrock/firefox/templates/firefox/home/index-b.html
  bedrock/firefox/templates/firefox/home/index.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/css/firefox/home/protocol.scss
  media/css/hubs/_sub-nav-download-button-remove-protocol.scss
  media/css/hubs/_sub-nav-protocol.scss
  media/img/firefox/home/desktop-account.svg
  media/img/firefox/home/desktop-change-high-res.png
  media/img/firefox/home/desktop-change.png
  media/img/firefox/home/desktop-smooth.svg
  media/img/firefox/home/hero-small-high-res.jpg
  media/img/firefox/home/hero-small.jpg
  media/img/firefox/home/icon-extensions.svg
  media/img/firefox/home/icon-faster.svg
  media/img/firefox/home/icon-private.svg
  media/img/firefox/home/icon-theme.svg
  media/img/firefox/home/icon-toolbar.svg
  media/img/firefox/home/icon-tracking.svg
  media/js/firefox/home/experiment-brand.js
  media/js/firefox/home/experiment-variation-brand.js
  media/static-bundles.json
Labels: P3, Review: S

#7381 Update gulp-less and clean-css (Fixes #6870)
  gulpfile.js
  package.json
  yarn.lock
Labels: P3, Review: XS

#7405 Update eslint and gulp-eslint (Fixes #7404)
  gulpfile.js
  media/js/base/fxa-utm-referral.js
  media/js/base/mozilla-client.js
  media/js/base/mozilla-notification-banner.js
  media/js/base/search-params.js
  media/js/base/stub-attribution-custom.js
  media/js/base/stub-attribution-macos.js
  media/js/firefox/new/variation-scene1.js
  media/js/libs/mozilla-traffic-cop.js
  package.json
  tests/unit/spec/base/core-datalayer-page-id.js
  tests/unit/spec/base/core-datalayer.js
  tests/unit/spec/base/dnt-helper.js
  tests/unit/spec/base/fxa-utm-referral.js
  tests/unit/spec/base/mozilla-accordion.js
  tests/unit/spec/base/mozilla-client.js
  tests/unit/spec/base/mozilla-fxa.js
  tests/unit/spec/base/mozilla-lazy-load.js
  tests/unit/spec/base/mozilla-notification-banner.js
  tests/unit/spec/base/mozilla-pager.js
  tests/unit/spec/base/mozilla-pixel.js
  tests/unit/spec/base/mozilla-smoothscroll.js
  tests/unit/spec/base/mozilla-traffic-cop-funnelcake-geo.js
  tests/unit/spec/base/mozilla-utils.js
  tests/unit/spec/base/search-params.js
  tests/unit/spec/base/send-to-device.js
  tests/unit/spec/base/site.js
  tests/unit/spec/base/stub-attribution-custom.js
  tests/unit/spec/base/stub-attribution-macos.js
  tests/unit/spec/base/stub-attribution.js
  tests/unit/spec/firefox/all/all-downloads-unified.js
  tests/unit/spec/firefox/new/yandex/scene1.js
  tests/unit/spec/firefox/tracking-protection-tour.js
  tests/unit/spec/ie8/mozilla-utils-ie8.js
  yarn.lock
Labels: P3, Review: XS

#7472 Revise form fields based on latest marketing and Salesforce output
  bedrock/firefox/templates/firefox/enterprise/signup.html
Labels: Review: XS

#7494 Fix firefox/accounts form for Firefox on iOS (Fixes #7483)
  media/js/base/mozilla-fxa-form.js
Labels: P1, Review: XS

#7470 Port unsupported-systems page to Protocol (Fixes #7454)
  bedrock/firefox/templates/firefox/unsupported-systems.html
  media/css/firefox/unsupported-systems.less
  media/css/firefox/unsupported-systems.scss
  media/static-bundles.json
Labels: P3, Review: XS

#7464 Port /mission/ page to Protocol (Fixes #7450)
  bedrock/mozorg/templates/mozorg/mission.html
  media/css/base/mozilla-video-poster.less
  media/css/mozorg/mission.less
  media/css/mozorg/mission.scss
  media/css/protocol/basic-article.scss
  media/img/sandstone/video/play-shadow.png
  media/img/sandstone/video/play.png
  media/img/sandstone/video/shadow.png
  media/js/base/mozilla-video-poster.js
  media/js/mozorg/about-video.js
  media/static-bundles.json
  tests/functional/newsletter/test_newsletter_embed.py
  tests/functional/test_mission.py
  tests/pages/mission.py
Labels: P3, Review: XS

#7462 Update privacy section to use Protocol base templates (#7358)
  bedrock/mozorg/templates/mozorg/about-base.html
  bedrock/mozorg/templates/mozorg/about/policy/patents/license.html
  bedrock/mozorg/templates/mozorg/manifesto-base.html
  bedrock/privacy/templates/privacy/archive/base-resp.html
  bedrock/privacy/templates/privacy/archive/firefox-2006-10.html
  bedrock/privacy/templates/privacy/archive/firefox-2008-06.html
  bedrock/privacy/templates/privacy/archive/firefox-2009-01.html
  bedrock/privacy/templates/privacy/archive/firefox-2009-09.html
  bedrock/privacy/templates/privacy/archive/firefox-2010-01.html
  bedrock/privacy/templates/privacy/archive/firefox-2010-12.html
  bedrock/privacy/templates/privacy/archive/firefox-2011-06.html
  bedrock/privacy/templates/privacy/archive/firefox-2012-06.html
  bedrock/privacy/templates/privacy/archive/firefox-2012-09.html
  bedrock/privacy/templates/privacy/archive/firefox-2012-12.html
  bedrock/privacy/templates/privacy/archive/firefox-2013-05.html
  bedrock/privacy/templates/privacy/archive/firefox-cliqz-2018-06.de.html
  bedrock/privacy/templates/privacy/archive/firefox-cliqz-2018-06.html
  bedrock/privacy/templates/privacy/archive/firefox-marketplace-2015-01.html
  bedrock/privacy/templates/privacy/archive/firefox-third-party.html
  bedrock/privacy/templates/privacy/archive/hello-2014-11.html
  bedrock/privacy/templates/privacy/archive/hello-2016-03.html
  bedrock/privacy/templates/privacy/archive/index.html
  bedrock/privacy/templates/privacy/archive/persona-2017-07.html
  bedrock/privacy/templates/privacy/archive/thunderbird-2010-06.html
  bedrock/privacy/templates/privacy/archive/websites-2013-08.html
  bedrock/privacy/templates/privacy/base-protocol.html
  bedrock/privacy/templates/privacy/faq.html
  bedrock/privacy/templates/privacy/index.html
  bedrock/privacy/templates/privacy/notices/base-notice-headings.html
  bedrock/privacy/templates/privacy/notices/base-notice-paragraphs.html
  bedrock/privacy/templates/privacy/notices/base-notice.html
  bedrock/privacy/templates/privacy/notices/facebook.html
  bedrock/privacy/templates/privacy/notices/firefox-fire-tv.html
  bedrock/privacy/templates/privacy/notices/firefox-focus.html
  bedrock/privacy/templates/privacy/notices/firefox-hello.html
  bedrock/privacy/templates/privacy/notices/firefox-lite.html
  bedrock/privacy/templates/privacy/notices/firefox-monitor.html
  bedrock/privacy/templates/privacy/notices/firefox-os.html
  bedrock/privacy/templates/privacy/notices/firefox-quantum.html
  bedrock/privacy/templates/privacy/notices/firefox-reality.html
  bedrock/privacy/templates/privacy/notices/firefox-screenshotgo.html
  bedrock/privacy/templates/privacy/notices/firefox.html
  bedrock/privacy/templates/privacy/notices/thunderbird.html
  bedrock/privacy/templates/privacy/notices/websites.html
  bedrock/privacy/templates/privacy/principles.html
  media/css/pebbles/components/_side.scss
  media/css/privacy/fb-privacy.less
  media/css/privacy/privacy-protocol.scss
  media/css/protocol/basic-article.scss
  media/img/privacy/logo-sprite.png
  media/js/base/mozilla-article.js
  media/js/privacy/privacy-firefox.js
  media/js/privacy/privacy-protocol.js
  media/static-bundles.json
Labels: P2, Review: S
