Repository mozilla/bedrock, pull requests merged in 2019-10, with the labels that each got.

#7813 [no bug] Leadership - add Jascha to steering, update header images, reorder
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/css/mozorg/leadership.scss
  media/img/mozorg/about/leadership/header/snap-community-high-res.jpg
  media/img/mozorg/about/leadership/header/snap-community.jpg
  media/img/mozorg/about/leadership/header/snap-group-high-res.jpg
  media/img/mozorg/about/leadership/header/snap-group.jpg
  media/img/mozorg/about/leadership/header/snap-nweiner-high-res.jpg
  media/img/mozorg/about/leadership/header/snap-nweiner.jpg
Labels: Needs Review, P2, Review: XS

#7817 Leadership - fix reference to missing image
  media/css/mozorg/leadership.scss
Labels: Bug :bug:

#7848 [#7656] Use backgrounds for accounts page logos
  bedrock/firefox/templates/firefox/accounts-2019.html
  media/css/firefox/accounts-2019.scss
Labels: Bug :bug:, P1, Review: XS

#6838 Change Thimble to Glitch
  bedrock/mozorg/templates/mozorg/internet-health/decentralization.html
Labels: P3, Papercuts 💸, Review: XS

#7680 Create Lockwise page [ Fixes #7570 ]
  bedrock/base/templates/macros-protocol.html
  bedrock/firefox/templates/firefox/lockwise/lockwise.html
  bedrock/firefox/urls.py
  media/css/firefox/lockwise/lockwise.scss
  media/img/firefox/lockwise/arrows.svg
  media/img/firefox/lockwise/de.png
  media/img/firefox/lockwise/en.png
  media/img/firefox/lockwise/es.png
  media/img/firefox/lockwise/favicon.ico
  media/img/firefox/lockwise/fingerprinters.svg
  media/img/firefox/lockwise/fr.png
  media/img/firefox/lockwise/it.png
  media/img/firefox/lockwise/mask.svg
  media/js/firefox/lockwise/lockwise.js
  media/static-bundles.json
Labels: Needs Review, P1, Review: S

#7870 Dev Edition: add “made for devs” section
  bedrock/firefox/templates/firefox/developer/firstrun.html
  bedrock/firefox/templates/firefox/developer/includes/alt-newsletter.html
  bedrock/firefox/templates/firefox/developer/includes/for-developers.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/developer/whatsnew.html
  media/css/firefox/developer/includes/intro.scss
  media/css/firefox/developer/includes/newsletter.scss
Labels: Needs Review, P2, Review: XS

#7829 Add whatsnew page for Firefox 70 (#7677)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-70.scss
  media/img/firefox/whatsnew_70/whatsnew_background.svg
  media/js/firefox/whatsnew/whatsnew-70.js
  media/static-bundles.json
Labels: P1, Review: M

#7884 Update join link (Fix #7883)
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/join.html
Labels: Needs Review, P1, Review: XS

#7886 Fix unclosed </div> on firefox/enterprise (Fixes #7819)
  bedrock/firefox/templates/firefox/enterprise/index.html
Labels: P3, Review: XS

#7882 Lockwise link updates [Fixes #7628]
  bedrock/base/templates/includes/protocol/footer/firefox-new.html
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/products.html
  bedrock/firefox/templates/firefox/accounts-2019.html
  bedrock/firefox/templates/firefox/features/safebrowser.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-b.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68.html
  bedrock/mozorg/templates/mozorg/home/includes/structured-data.json
Labels: Needs Review, P1, Review: S

#7889 Add browser and product favicons (#7656)
  media/img/favicons/firefox/apple-touch-icon.png
  media/img/favicons/firefox/browser/apple-touch-icon.png
  media/img/favicons/firefox/browser/beta/apple-touch-icon.png
  media/img/favicons/firefox/browser/beta/favicon-16x16.png
  media/img/favicons/firefox/browser/beta/favicon-196x196.png
  media/img/favicons/firefox/browser/beta/favicon-32x32.png
  media/img/favicons/firefox/browser/beta/favicon.ico
  media/img/favicons/firefox/browser/developer/apple-touch-icon.png
  media/img/favicons/firefox/browser/developer/favicon-16x16.png
  media/img/favicons/firefox/browser/developer/favicon-196x196.png
  media/img/favicons/firefox/browser/developer/favicon-32x32.png
  media/img/favicons/firefox/browser/developer/favicon.ico
  media/img/favicons/firefox/browser/favicon-16x16.png
  media/img/favicons/firefox/browser/favicon-196x196.png
  media/img/favicons/firefox/browser/favicon-32x32.png
  media/img/favicons/firefox/browser/favicon.ico
  media/img/favicons/firefox/browser/nightly/apple-touch-icon.png
  media/img/favicons/firefox/browser/nightly/favicon-16x16.png
  media/img/favicons/firefox/browser/nightly/favicon-196x196.png
  media/img/favicons/firefox/browser/nightly/favicon-32x32.png
  media/img/favicons/firefox/browser/nightly/favicon.ico
  media/img/favicons/firefox/browser/quantum/apple-touch-icon.png
  media/img/favicons/firefox/browser/quantum/favicon-16x16.png
  media/img/favicons/firefox/browser/quantum/favicon-196x196.png
  media/img/favicons/firefox/browser/quantum/favicon-32x32.png
  media/img/favicons/firefox/browser/quantum/favicon.ico
  media/img/favicons/firefox/favicon-16x16.png
  media/img/favicons/firefox/favicon-196x196.png
  media/img/favicons/firefox/favicon-32x32.png
  media/img/favicons/firefox/favicon.ico
  media/img/favicons/firefox/lockwise/apple-touch-icon.png
  media/img/favicons/firefox/lockwise/favicon-16x16.png
  media/img/favicons/firefox/lockwise/favicon-196x196.png
  media/img/favicons/firefox/lockwise/favicon-32x32.png
  media/img/favicons/firefox/lockwise/favicon.ico
  media/img/favicons/firefox/monitor/apple-touch-icon.png
  media/img/favicons/firefox/monitor/favicon-16x16.png
  media/img/favicons/firefox/monitor/favicon-196x196.png
  media/img/favicons/firefox/monitor/favicon-32x32.png
  media/img/favicons/firefox/monitor/favicon.ico
  media/img/favicons/firefox/send/apple-touch-icon.png
  media/img/favicons/firefox/send/favicon-16x16.png
  media/img/favicons/firefox/send/favicon-196x196.png
  media/img/favicons/firefox/send/favicon-32x32.png
  media/img/favicons/firefox/send/favicon.ico
  media/img/favicons/mozilla/apple-touch-icon.png
  media/img/favicons/mozilla/favicon-16x16.png
  media/img/favicons/mozilla/favicon-196x196.png
  media/img/favicons/mozilla/favicon-32x32.png
  media/img/favicons/mozilla/favicon.ico
  media/img/favicons/pocket/apple-touch-icon.png
  media/img/favicons/pocket/favicon-16x16.png
  media/img/favicons/pocket/favicon-196x196.png
  media/img/favicons/pocket/favicon-32x32.png
  media/img/favicons/pocket/favicon.ico
Labels: Needs Review, P1, Review: XS

#7909 [bugfix] Activate DE and FR locales for whatsnew 70
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
Labels: Bug :bug:, P1, Review: XS

#7916 Get Mozilla favicons from favicons folder (#7915)
  bedrock/base/templates/base-pebbles.html
  bedrock/base/templates/base-resp.html
  bedrock/mozorg/templates/mozorg/contribute/contribute-embed.html
  media/css/firefox/features/index.scss
  media/css/firefox/whatsnew/header.scss
  media/img/favicon.ico
  media/img/favicon/apple-touch-icon-180x180.png
  media/img/favicon/favicon-196x196.png
  media/img/favicons/mozilla/favicon.png
  root_files/favicon.ico
  root_files/favicon.png
Labels: P3, Review: XS

#7914 [bugfix] whatsnew page for Firefox 70 papercuts. (Fixes #7910, bug 1579940)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70.html
  media/js/firefox/whatsnew/whatsnew-70.js
Labels: Bug :bug:, Needs Review, P1, Review: XS

#7918 Get master and browser favicons from favicons folder
  bedrock/exp/templates/exp/base/base-firefox.html
  bedrock/firefox/templates/firefox/accounts-2019.html
  bedrock/firefox/templates/firefox/base/base-pebbles.html
  bedrock/firefox/templates/firefox/base/base-protocol.html
  bedrock/firefox/templates/firefox/base/base-resp.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/home/index-quantum.html
  media/img/firefox/favicon-196.png
  media/img/firefox/favicon.ico
  media/img/firefox/ios-icon-180.png
Labels: Needs Review, P1, Review: XS

#7922 Use pocket favicon on firefox/pocket (#7915)
  bedrock/firefox/templates/firefox/pocket.html
Labels: Needs Review, P3, Review: XS

#7921 Get Lockwise favicons from favicons folder (#7915)
  bedrock/firefox/templates/firefox/lockwise/lockwise.html
  media/img/firefox/lockwise/favicon.ico
Labels: Needs Review, P2, Review: XS

#7733 Pass through UTM parameters for Firefox Monitor referrals (#7585)
  bedrock/base/templates/macros.html
  media/js/base/fxa-utm-referral-init.js
  media/js/base/fxa-utm-referral.js
  media/static-bundles.json
  tests/unit/spec/base/fxa-utm-referral.js
Labels: Needs Review, P2, Review: XS

#7940 iOS and Android store links trigger download events #7919
  bedrock/firefox/templates/firefox/home/index-master.html
Labels: Needs Review, P1, Review: XS

#7936 Activate mozilla footer and firefox nav and footer for all (#7913)
  bedrock/base/templates/includes/protocol/footer/firefox-new.html
  bedrock/base/templates/includes/protocol/footer/firefox.html
  bedrock/base/templates/includes/protocol/footer/mozilla-new.html
  bedrock/base/templates/includes/protocol/footer/mozilla-old.html
  bedrock/base/templates/includes/protocol/footer/mozilla.html
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/nav-switch.html
  bedrock/firefox/templates/firefox/accounts-2019.html
  bedrock/firefox/templates/firefox/all-unified.html
  bedrock/firefox/templates/firefox/base/base-pebbles.html
  bedrock/firefox/templates/firefox/base/base-protocol.html
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/election/index-de.html
  bedrock/firefox/templates/firefox/election/index-fr.html
  bedrock/firefox/templates/firefox/election/index.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/installer-help.html
  bedrock/firefox/templates/firefox/mobile.html
  bedrock/firefox/templates/firefox/new/trailhead/thanks.html
  bedrock/firefox/templates/firefox/releases/index.html
  bedrock/firefox/templates/firefox/releases/notes.html
  bedrock/settings/base.py
  lib/l10n_utils/tests/test_template.py
Labels: Needs Review, P1, Review: XS

#7942 [fix #7911] Add survey to lifecycle page 1
  bedrock/firefox/templates/firefox/welcome/page1.html
  media/css/firefox/welcome.scss
Labels: Needs Review, Review: XS

#7804 Preserve Quantum logos on Release Notes (#7803)
  bedrock/firefox/templates/firefox/releases/notes.html
  media/css/firefox/releasenotes.scss
  media/img/firefox/releasenotes/beta-quantum-high-res.png
  media/img/firefox/releasenotes/beta-quantum.png
  media/img/firefox/releasenotes/developer-quantum-high-res.png
  media/img/firefox/releasenotes/developer-quantum.png
  media/img/firefox/releasenotes/nightly-quantum-high-res.png
  media/img/firefox/releasenotes/nightly-quantum.png
  media/img/firefox/releasenotes/release-quantum-high-res.png
  media/img/firefox/releasenotes/release-quantum.png
Labels: Needs Review, P2, Review: XS

#7924 Content that links to firefox browser now links to firefox.new (#7923)
  bedrock/firefox/templates/firefox/accounts-2019.html
  bedrock/firefox/templates/firefox/all-unified.html
  bedrock/firefox/templates/firefox/base/base-resp.html
  bedrock/firefox/templates/firefox/includes/hub/sub-nav.html
  bedrock/firefox/templates/firefox/includes/release-menu.html
  bedrock/firefox/templates/firefox/includes/top-menu.html
  bedrock/firefox/templates/firefox/installer-help.html
  bedrock/firefox/templates/firefox/releases/index.html
  bedrock/firefox/templates/firefox/unsupported-systems.html
  bedrock/mozorg/templates/mozorg/about.html
  bedrock/mozorg/templates/mozorg/about/governance/organizations.html
  bedrock/mozorg/templates/mozorg/contribute/index.html
  bedrock/privacy/templates/privacy/archive/firefox-2009-09.html
  bedrock/security/templates/security/bug-bounty/faq.html
Labels: Needs Review, P1, Review: XS

#7948 Download Firefox button is not shown on Lockwise page in IE11 (Fixes #7947)
  media/js/firefox/lockwise/lockwise.js
Labels: Needs Review, P1, Review: XS

#7925 Update "Firefox Desktop" menu link to link to firefox/new #7917
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/firefox.html
  tests/pages/base.py
Labels: P1, Review: XS

#7768 Add Firefox Privacy Hub pages (Fixes #7766, #7709)
  bedrock/base/templates/includes/protocol/footer/firefox.html
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/about.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/privacy/base.html
  bedrock/firefox/templates/firefox/privacy/includes/subnav.html
  bedrock/firefox/templates/firefox/privacy/index.html
  bedrock/firefox/templates/firefox/privacy/products.html
  bedrock/firefox/urls.py
  media/css/firefox/enterprise/landing.scss
  media/css/firefox/privacy/common.scss
  media/css/firefox/privacy/products.scss
  media/css/firefox/privacy/promise.scss
  media/css/protocol/components/_fxa-form.scss
  media/css/protocol/components/_sub-navigation.scss
  media/img/firefox/privacy/icon-privacy.svg
  media/img/firefox/privacy/products/icon-control.svg
  media/img/firefox/privacy/products/icon-invisible.svg
  media/img/firefox/privacy/products/icon-protection.svg
  media/img/firefox/privacy/products/lockwise.svg
  media/img/firefox/privacy/products/monitor.svg
  media/img/firefox/privacy/products/pocket-high-res.png
  media/img/firefox/privacy/products/pocket.png
  media/img/firefox/privacy/products/report.svg
  media/img/firefox/privacy/products/send.svg
  media/img/firefox/privacy/promise/icon-mountain.svg
  media/img/firefox/privacy/promise/icon-privacy.svg
  media/img/firefox/privacy/promise/less-high-res.jpg
  media/img/firefox/privacy/promise/less.jpg
  media/img/firefox/privacy/promise/privacy-hero-high-res.png
  media/img/firefox/privacy/promise/privacy-hero.png
  media/img/firefox/privacy/promise/safe-high-res.jpg
  media/img/firefox/privacy/promise/safe.jpg
  media/img/firefox/privacy/promise/secrets-high-res.jpg
  media/img/firefox/privacy/promise/secrets.jpg
  media/js/base/mozilla-fxa-sign-in-link.js
  media/js/firefox/accounts-2019.js
  media/js/firefox/privacy/products.js
  media/static-bundles.json
  tests/functional/firefox/privacy/__init__.py
  tests/functional/firefox/privacy/test_products.py
  tests/pages/firefox/privacy/__init__.py
  tests/pages/firefox/privacy/products.py
Labels: P1, Review: S

#7905 Add /firefox/accounts/ page to CRO sandbox (Fixes #7507)
  bedrock/exp/templates/exp/base/base-firefox.html
  bedrock/exp/templates/exp/firefox/accounts-2019.html
  bedrock/exp/templates/exp/firefox/new/base.html
  bedrock/exp/urls.py
  media/css/exp/firefox/accounts-2019.scss
  media/js/exp/firefox/accounts-2019.js
  media/static-bundles.json
Labels: P2, Review: XS

#7953 add updated logos [Fixes #7951]
  media/img/firefox/mobile/intro-firefox-high-res.png
  media/img/firefox/mobile/intro-firefox.png
Labels: Do Not Merge :warning:, P1, Review: XS

#7968 Update 'Personal Data Promise' link on /firefox/accounts/ page (Fixes #7967)
  bedrock/exp/templates/exp/firefox/accounts-2019.html
  bedrock/firefox/templates/firefox/accounts-2019.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
Labels: P2, Review: XS

#7963 Add Firefox for FireTV to Firefox nav
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/browsers.html
Labels: Needs Review, P3, Review: XS

#7965 Firefox privacy hub headings should use Metropolis font
  bedrock/firefox/templates/firefox/privacy/index.html
  bedrock/firefox/templates/firefox/privacy/products.html
Labels: Bug :bug:, Needs Review, P3, Review: XS

#7976 [fix #7975] Update trackers blocked
  bedrock/firefox/templates/firefox/privacy/products.html
Labels: Review: XS

#7979 MOSS pages cleanup (Fixes #7970)
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/moss/base.html
  bedrock/mozorg/templates/mozorg/moss/foundational-technology.html
  bedrock/mozorg/templates/mozorg/moss/index-092018.html
  bedrock/mozorg/templates/mozorg/moss/index.html
  bedrock/mozorg/templates/mozorg/moss/mission-partners-india.html
  bedrock/mozorg/templates/mozorg/moss/mission-partners.html
  bedrock/mozorg/templates/mozorg/moss/secure-open-source.html
  bedrock/mozorg/urls.py
  bedrock/mozorg/views.py
  tests/redirects/map_globalconf.py
Labels: P3, Review: XS

#7973 Additional ctas on welcome/1 and /2 (Fixes #7961)
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/welcome/base.html
  bedrock/firefox/templates/firefox/welcome/page1.html
  bedrock/firefox/templates/firefox/welcome/page2.html
  docs/analytics.rst
  media/css/firefox/welcome.scss
  media/js/base/mozilla-monitor-button.js
  media/js/firefox/welcome-page1-init.js
  media/js/firefox/welcome-page2.js
  media/static-bundles.json
  tests/functional/firefox/test_welcome_page1.py
  tests/functional/firefox/test_welcome_page2.py
  tests/pages/firefox/accounts.py
  tests/pages/firefox/welcome/page1.py
  tests/pages/firefox/welcome/page2.py
Labels: P1

#7998 Remove button_id argument from monitor button macro.
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx69.html
Labels: Bug :bug:, Review: XS

#7988 [fix #7856] Add Firefox page to CRO sandbox
  bedrock/exp/templates/exp/firefox/index.de.html
  bedrock/exp/templates/exp/firefox/index.html
  bedrock/exp/urls.py
  media/css/exp/firefox/index-ie9.scss
  media/css/exp/firefox/index.scss
  media/js/exp/firefox/index.js
  media/static-bundles.json
Labels: Review: S

#7873 Add ADR: Use Convert and Cloudflare Workers for multi-variant testing
  docs/architecture/decisions/0003-use-cloudflare-workers-and-convert-for-multi-variant-testing.md
Labels: Needs Review, P3, Review: XS

#7834 Add lifecycle page 1 to CRO Sandbox (Fixes #7802)
  bedrock/exp/templates/exp/firefox/welcome/base.html
  bedrock/exp/templates/exp/firefox/welcome/page1.html
  bedrock/exp/urls.py
  bedrock/firefox/views.py
  media/css/exp/firefox/welcome.scss
  media/js/exp/firefox/welcome-page1-init.js
  media/static-bundles.json
  tests/functional/test_experiment_pages.py
Labels: P2, Review: XS

#7992 WNP updates for Indonesia (Fixes #7991, #6732)
  bedrock/firefox/templates/firefox/whatsnew/index-lite.id.html
  bedrock/settings/base.py
  media/css/firefox/whatsnew/whatsnew-lite.scss
Labels: Needs Review, P2, Review: XS

#7946 Add functional tests for firefox/lockwise page (Fixes #7899)
  tests/functional/firefox/test_lockwise.py
  tests/functional/test_about.py
  tests/pages/firefox/lockwise.py
Labels: Needs Review, P2, Review: XS

#7990 Get developer logos from protocol-assets (#7790 & #7980)
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/developers.html
  bedrock/firefox/templates/firefox/all.html
  bedrock/firefox/templates/firefox/developer/firstrun.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/developer/whatsnew.html
  bedrock/foundation/templates/foundation/trademarks/list.html
  media/css/firefox/channel.less
  media/img/firefox/developer/page-image.png
  media/img/logos/firefox/developer-high-res.png
  media/img/logos/firefox/developer-wordmark-dark-high-res.png
  media/img/logos/firefox/developer-wordmark-dark.png
  media/img/logos/firefox/developer-wordmark-high-res.png
  media/img/logos/firefox/developer-wordmark.png
  media/img/logos/firefox/developer.png
  media/img/logos/firefox/logo-dev-edition-quantum-wordmark-high-res.png
  media/img/logos/firefox/logo-dev-edition-quantum-wordmark.png
  media/img/mozorg/developer/hub/resource-devtools.jpg
  media/img/nav/cards/developer-edition-high-res.jpg
  media/img/nav/cards/developer-edition.jpg
  media/img/nav/cards/developer-edition.png
  media/img/social/firefox-devedition-logo-1200x627.png
Labels: P2, Review: XS

#8009 [no bug] Update board membership
  bedrock/foundation/templates/foundation/moco.html
  bedrock/mozorg/templates/mozorg/about/leadership.html
Labels: Needs Review, P1, Review: XS

#8010 [bugfix] flowParams in fxa fetch request appending `undefined` to button hrefs.
  media/js/base/mozilla-monitor-button.js
  media/js/firefox/welcome-page2.js
Labels: Bug :bug:, Review: XS

#8012 Fix background position on Firefox Lite /whatsnew page (#7991)
  media/css/firefox/whatsnew/whatsnew-lite.scss
Labels: P3, Review: XS

#8013 Add /whatsnew 70 page to CRO app (Fixes #7855)
  bedrock/exp/templates/exp/firefox/whatsnew/whatsnew-fx70.html
  bedrock/exp/urls.py
  bedrock/exp/views.py
  media/css/exp/firefox/whatsnew/whatsnew-70.scss
  media/js/exp/firefox/whatsnew/whatsnew-70.js
  media/static-bundles.json
  tests/functional/test_experiment_pages.py
Labels: P2, Review: XS

#7908 Update A/B testing docs for Convert (Fixes #7906)
  docs/abtest.rst
Labels: Needs Review, P3, Review: XS

#8018 Adjust Firefox Lite product image positioning (#7991)
  media/css/firefox/whatsnew/whatsnew-lite.scss
Labels: Needs Review, P2, Review: XS

#8016 [fix #7839] Add download links to leadership page
  bedrock/mozorg/templates/mozorg/about/leadership.html
Labels: Needs Review, P2, Review: XS

#8047 Fixed Responsive styles bug on product list
  media/css/firefox/home/master.scss
Labels: Needs Review, P2, Review: XS

#7937 Port Transparency Report pages to Protocol (Fixes #7530)
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-dec-2015.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2016.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2017.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2018.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2019.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2016.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2017.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2018.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/report-base.html
  media/css/mozorg/about-transparency.scss
  media/js/mozorg/about-transparency.js
  media/static-bundles.json
Labels: P3, Papercuts 💸, Review: S

#8048 Get Firefox master brand logos from protocol-assets (#7790)
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/join.html
  media/css/mozorg/home/home-2018.scss
  media/css/protocol/components/_navigation.scss
  media/img/logos/firefox/logo-master-wordmark-dark.svg
  media/img/logos/firefox/logo-master-wordmark-light.svg
  media/img/logos/firefox/logo-master.svg
  media/img/logos/firefox/master-md-high-res.png
  media/img/logos/firefox/master-md.png
  media/img/logos/firefox/master-sm-high-res.png
  media/img/logos/firefox/master-sm.png
Labels: Needs Review, P3, Review: XS

#7989 Get beta logos from protocol-assets (#7790)
  media/css/firefox/channel.less
  media/css/firefox/system-requirements.scss
  media/img/logos/firefox/beta-high-res.png
  media/img/logos/firefox/beta.png
Labels: Needs Review, P3, Review: XS

#8054 Update whatsnew 70 headlines for FR/DE/EN (Fixes #8038)
  bedrock/exp/templates/exp/firefox/whatsnew/whatsnew-fx70.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
Labels: P1, Review: XS

#8050 Firefox home image and string updates (#8049)
  bedrock/exp/templates/exp/firefox/index.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/privacy/products.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  media/img/firefox/home/master/browsers-high-res.jpg
  media/img/firefox/home/master/browsers.jpg
  media/img/firefox/home/master/pocket.svg
Labels: P1, Review: XS

#8061 [fix #8060] Update welcome 1 page title
  bedrock/firefox/templates/firefox/welcome/page1.html
  media/css/firefox/welcome.scss
Labels: Needs Review, P1, Review: XS

#7929 Port privacy archive pages to Protocol (Fixes #7515)
  bedrock/privacy/templates/privacy/archive/base-resp.html
  bedrock/privacy/templates/privacy/archive/firefox-2006-10.html
  bedrock/privacy/templates/privacy/archive/firefox-2008-06.html
  bedrock/privacy/templates/privacy/archive/firefox-2009-01.html
  bedrock/privacy/templates/privacy/archive/firefox-2009-09.html
  bedrock/privacy/templates/privacy/archive/firefox-2010-01.html
  bedrock/privacy/templates/privacy/archive/firefox-2010-12.html
  bedrock/privacy/templates/privacy/archive/firefox-2011-06.html
  bedrock/privacy/templates/privacy/archive/firefox-2012-06.html
  bedrock/privacy/templates/privacy/archive/firefox-2012-09.html
  bedrock/privacy/templates/privacy/archive/firefox-2012-12.html
  bedrock/privacy/templates/privacy/archive/firefox-2013-05.html
  bedrock/privacy/templates/privacy/archive/firefox-cliqz-2018-06.de.html
  bedrock/privacy/templates/privacy/archive/firefox-cliqz-2018-06.html
  bedrock/privacy/templates/privacy/archive/firefox-marketplace-2015-01.html
  bedrock/privacy/templates/privacy/archive/firefox-third-party.html
  bedrock/privacy/templates/privacy/archive/hello-2014-11.html
  bedrock/privacy/templates/privacy/archive/hello-2016-03.html
  bedrock/privacy/templates/privacy/archive/index.html
  bedrock/privacy/templates/privacy/archive/persona-2017-07.html
  bedrock/privacy/templates/privacy/archive/thunderbird-2010-06.html
  bedrock/privacy/templates/privacy/archive/websites-2013-08.html
  media/css/privacy/privacy-protocol.scss
  media/css/privacy/privacy.less
  media/js/privacy/privacy.js
  media/static-bundles.json
Labels: P3, Review: S

#8053 Assign fallback whatsnew page content to non-FRENDE locales for Firefox 70 (Fixes #8039)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/static-bundles.json
Labels: P1, Review: S
