Repository mozilla/bedrock, pull requests merged in 2019-05, with the labels that each got.

#7123 What's New 67 page
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-67.scss
  media/img/firefox/whatsnew_67/lockbox.svg
  media/img/firefox/whatsnew_67/logo-high-res.png
  media/img/firefox/whatsnew_67/logo.png
  media/img/firefox/whatsnew_67/monitor.svg
  media/img/firefox/whatsnew_67/pocket.svg
  media/img/firefox/whatsnew_67/send.svg
  media/img/firefox/whatsnew_67/update.svg
  media/js/firefox/whatsnew/whatsnew-67.js
  media/static-bundles.json
Labels: P1

#7113 Standardizing fxa utm parameters and values (#7061)
  bedrock/base/templates/includes/protocol/navigation/index.html
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/accounts-2018.html
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/developer/whatsnew-fx68.html
  bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
  bedrock/firefox/templates/firefox/new/scene1.html
  bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64-base.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx63.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx65.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
Labels: Blocked, Do Not Merge :warning:, P1

#7125 Add data-card-tag attribute to card macro (Fixes #7090)
  bedrock/base/templates/macros-protocol.html
Labels: P3, Review: XS

#7137 Add subheading to elections page
  bedrock/firefox/templates/firefox/election/index-de.html
  bedrock/firefox/templates/firefox/election/index.html
  media/css/firefox/election.scss
  media/img/logos/firefox/release-lockup-high-res.png
  media/img/logos/firefox/release-lockup.png
Labels: P2, Review: XS

#7151 Fix typo
  bedrock/firefox/templates/firefox/election/index-de.html
Labels: P1, Review: XS

#7072 Update browser comparison pages for auto-play blocking in Firefox (Fixes #6536)
  bedrock/firefox/templates/firefox/campaign/compare/scene1-edge.html
  bedrock/firefox/templates/firefox/campaign/compare/scene1-safari.html
Labels: P3, Review: XS

#7145 Add French version of EU Elections page
  bedrock/firefox/templates/firefox/election/index-fr.html
  bedrock/firefox/views.py
Labels: P1, Review: XS

#7165 [fix bug 1549841] Update Dave Camp’s title and bio
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/alan-davidson-high-res.jpg
  media/img/mozorg/about/leadership/alan-davidson.jpg
  media/img/mozorg/about/leadership/amy-keating-high-res.jpg
  media/img/mozorg/about/leadership/amy-keating.jpg
  media/img/mozorg/about/leadership/lindsey-shepard-high-res.jpg
  media/img/mozorg/about/leadership/lindsey-shepard.jpg
  media/img/mozorg/about/leadership/michael-deangelo-high-res.jpg
  media/img/mozorg/about/leadership/michael-deangelo.jpg
Labels: Review: XS

#7168 Experiment: redesign /new and /thanks pages (Fixes #7139, #7129, #7140)
  bedrock/base/templates/macros-protocol.html
  bedrock/firefox/templates/firefox/campaign/index.html
  bedrock/firefox/templates/firefox/new/scene1.html
  bedrock/firefox/templates/firefox/new/trailhead/base.html
  bedrock/firefox/templates/firefox/new/trailhead/download-a.html
  bedrock/firefox/templates/firefox/new/trailhead/download-b.html
  bedrock/firefox/templates/firefox/new/trailhead/thanks.html
  bedrock/firefox/templates/firefox/recommended.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/css/firefox/new/trailhead/download.scss
  media/css/firefox/new/trailhead/thanks.scss
  media/img/firefox/new/trailhead/browser-window.svg
  media/img/firefox/new/trailhead/hero-bg-rtl.svg
  media/img/firefox/new/trailhead/hero-bg.svg
  media/img/firefox/new/trailhead/icon-community.svg
  media/img/firefox/new/trailhead/icon-devices.svg
  media/img/firefox/new/trailhead/icon-join.svg
  media/img/firefox/new/trailhead/icon-lockwise.svg
  media/img/firefox/new/trailhead/icon-private.svg
  media/img/firefox/new/trailhead/icon-products.svg
  media/img/firefox/new/trailhead/icon-safety.svg
  media/img/firefox/new/trailhead/thanks-bg-high-res.png
  media/img/firefox/new/trailhead/thanks-bg-rtl-high-res.png
  media/img/firefox/new/trailhead/thanks-bg-rtl.png
  media/img/firefox/new/trailhead/thanks-bg.png
  media/img/logos/firefox/release-lockup-white-high-res.png
  media/img/logos/firefox/release-lockup-white.png
  media/js/firefox/new/trailhead/download.js
  media/js/firefox/new/trailhead/experiment.js
  media/js/firefox/new/trailhead/variation.js
  media/js/firefox/new/variation-scene1.js
  media/static-bundles.json
  tests/functional/firefox/new/test_download.py
Labels: Needs Review, P1, Review: M

#7186 Fix typo in /firefox/new/ trailhead page
  bedrock/firefox/templates/firefox/new/trailhead/download-b.html
  bedrock/firefox/templates/firefox/new/trailhead/thanks.html
Labels: P3, Review: XS

#7124 Experiment: page hero rendering performance (Fixes #7118)
  bedrock/mozorg/templates/mozorg/about-2019.html
  bedrock/mozorg/templates/mozorg/perf-exp/control.html
  bedrock/mozorg/templates/mozorg/perf-exp/variation.html
  bedrock/mozorg/tests/test_views.py
  bedrock/mozorg/views.py
  media/css/mozorg/perf-exp/index.scss
  media/js/mozorg/perf-exp/control.js
  media/js/mozorg/perf-exp/experiment.js
  media/js/mozorg/perf-exp/variation.js
  media/static-bundles.json
  tests/functional/test_about.py
Labels: P3, Review: S

#7215 Add Stan Leong to leadership page #7212
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/stan-leong-high-res.jpg
  media/img/mozorg/about/leadership/stan-leong.jpg
Labels: P1

#7206 WNP 67.0.5 (#7128)
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-67.0.5.scss
  media/img/firefox/whatsnew_67/WNP-PDP-icon.svg
  media/img/firefox/whatsnew_67/WNP-knowledge-icon.svg
  media/img/firefox/whatsnew_67/experiments.svg
  media/img/firefox/whatsnew_67/heart_glyph.svg
  media/img/firefox/whatsnew_67/inbox.svg
  media/img/firefox/whatsnew_67/lockbox_glyph.png
  media/img/firefox/whatsnew_67/lockbox_glyph.svg
  media/img/firefox/whatsnew_67/monitor_icon.svg
  media/img/firefox/whatsnew_67/noodles.png
  media/img/firefox/whatsnew_67/protects_glyph.svg
  media/img/firefox/whatsnew_67/send_glyph.png
  media/img/firefox/whatsnew_67/send_glyph.svg
  media/js/base/mozilla-monitor-button.js
  media/static-bundles.json
Labels: P1, Trailhead

#7247 Localized /firefox/67.0.1/whatsnew/ URLs redirect to /en-US/ (Fixes #7246)
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
Labels: P1, Review: XS

#7187 Roll out /firefox/new/ trailhead design (#7143)
  bedrock/firefox/templates/firefox/new/scene1.html
  bedrock/firefox/templates/firefox/new/trailhead/download-a.html
  bedrock/firefox/templates/firefox/new/trailhead/download.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/js/firefox/new/trailhead/experiment.js
  media/js/firefox/new/trailhead/variation.js
  media/static-bundles.json
  tests/functional/firefox/new/test_download.py
  tests/functional/firefox/new/test_download_yandex.py
  tests/pages/firefox/new/download.py
  tests/pages/regions/modal.py
Labels: L10N, L10N - Localization Started, L10N - Strings Extracted, P1, Review: S

#7203 Update branding on /firefox round 2 testing (#6865)
  bedrock/firefox/templates/firefox/home/index-b.html
  bedrock/firefox/templates/firefox/home/index.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/css/firefox/home/pre-download-newsletter-protocol.scss
  media/css/firefox/home/protocol.scss
  media/css/hubs/_sub-nav-download-button-remove-protocol.scss
  media/css/hubs/_sub-nav-protocol.scss
  media/img/firefox/home/bright.png
  media/img/firefox/home/desktop-account.svg
  media/img/firefox/home/desktop-smooth.svg
  media/img/firefox/home/hero-high-res.jpg
  media/img/firefox/home/hero-small-high-res.jpg
  media/img/firefox/home/hero-small.jpg
  media/img/firefox/home/hero.jpg
  media/img/firefox/home/icon-extensions.svg
  media/img/firefox/home/icon-faster.svg
  media/img/firefox/home/icon-private.svg
  media/img/firefox/home/icon-sprite.svg
  media/img/firefox/home/icon-theme.svg
  media/img/firefox/home/icon-toolbar.svg
  media/img/firefox/home/icon-tracking.svg
  media/img/firefox/home/var-e-bg.svg
  media/img/firefox/home/var-e-product.svg
  media/img/firefox/home/wave.svg
  media/js/firefox/home/experiment-brand.js
  media/js/firefox/home/experiment-variation-brand.js
  media/js/firefox/home/pre-download-newsletter-protocol.js
  media/static-bundles.json
Labels: P3, Review: XS

#7197 [fix #7132] New Firefox accounts page
  bedrock/base/templates/macros.html
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/accounts-2019.html
  bedrock/firefox/views.py
  media/css/firefox/accounts-2019.scss
  media/css/firefox/fights-for-you.scss
  media/css/protocol/base/fonts/sharpsans.scss
  media/img/firefox/accounts/trailhead/accounts-hero-logged-in.svg
  media/img/firefox/accounts/trailhead/accounts-hero-logged-out.svg
  media/img/firefox/accounts/trailhead/icon-experiments.svg
  media/img/firefox/accounts/trailhead/icon-inbox.svg
  media/img/firefox/accounts/trailhead/value-knowledge-high-res.jpg
  media/img/firefox/accounts/trailhead/value-knowledge.jpg
  media/img/firefox/accounts/trailhead/value-respect-high-res.jpg
  media/img/firefox/accounts/trailhead/value-respect.jpg
  media/img/logos/firefox/logo-lockwise.svg
  media/img/logos/firefox/logo-master-wordmark-dark.svg
  media/img/logos/firefox/logo-master-wordmark-light.svg
  media/img/logos/firefox/logo-monitor.svg
  media/img/logos/firefox/logo-send.svg
  media/js/base/mozilla-fxa-form.js
  media/js/firefox/accounts-2019.js
  media/static-bundles.json
  tests/functional/firefox/test_accounts.py
  tests/pages/firefox/accounts.py
Labels: L10N, Review: S

#7251 Show trailhead /whatsnew page for Beta and Dev Edition (Fixes #7248, #7249)
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/developer/whatsnew-fx68-trailhead.html
  bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68-trailhead.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
Labels: P1, Review: XS

#7264 Update Firefox Reality Logo (#7216)
  media/img/logos/firefox/logo-reality.png
Labels: P3, Review: XS

#7262 Trailhead WNP: add up to date banner JS, design tweaks. (Fixes #7256, #7244)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html
  media/css/firefox/whatsnew/whatsnew-67.0.5.scss
  media/js/firefox/whatsnew/up-to-date.js
  media/static-bundles.json
Labels: Review: XS
