Repository mozilla/bedrock, pull requests merged in 2019-06, with the labels that each got.

#7271 Fetch FxA metrics for non-FF browsers on /accounts (Fixes #7269)
  media/js/base/mozilla-fxa-form.js
Labels: P1, Review: XS

#7255 Buttons and links to FxA trigger FxA-Sync event action only (#7252)
  bedrock/base/templates/includes/protocol/navigation/index.html
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/accounts-2018.html
  bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68.html
Labels: Needs Review, P2, Review: XS

#7276 Link to German blog post from /de/firefox/accounts/ page (Fixes #7275)
  bedrock/firefox/templates/firefox/accounts-2019.html
Labels: P2, Review: XS

#7257 Use standardized adjust links across the site (Fixes #7214)
  bedrock/base/templates/macros.html
  bedrock/firefox/firefox_details.py
  bedrock/firefox/templates/firefox/accounts-2018.html
  bedrock/firefox/templates/firefox/facebookcontainer/index.html
  bedrock/firefox/templates/firefox/fights-for-you.de.html
  bedrock/firefox/templates/firefox/fights-for-you.fr.html
  bedrock/firefox/templates/firefox/mobile.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64-base.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html
  bedrock/firefox/tests/test_helpers.py
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/settings/appstores.py
  bedrock/settings/base.py
Labels: P3, Review: S

#7230 Redesigned /firefox/all/ page (Fixes #7076)
  bedrock/base/templates/product-all-unified-macros.html
  bedrock/firefox/templates/firefox/all-unified.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  media/css/firefox/all/all-unified-old-ie.scss
  media/css/firefox/all/all-unified.scss
  media/css/firefox/all/all.less
  media/img/firefox/all/icon-question-high-res.png
  media/img/firefox/all/icon-question.png
  media/js/firefox/all/all-downloads-unified-init.js
  media/js/firefox/all/all-downloads-unified.js
  media/js/firefox/all/all-downloads.js
  media/static-bundles.json
  tests/functional/firefox/test_all.py
  tests/functional/firefox/test_all_legacy_pages.py
  tests/functional/newsletter/test_newsletter_embed.py
  tests/functional/test_download_l10n.py
  tests/pages/firefox/all.py
  tests/unit/karma.conf.js
  tests/unit/spec/firefox/all/all-downloads-unified.js
Labels: P2, Review: L

#7279 Rename "Firefox Lockbox" to "Firefox Lockwise" (Fixes #7242)
  bedrock/firefox/templates/firefox/accounts-2018.html
  bedrock/firefox/templates/firefox/new/scene1.en-GB.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64-base.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.de.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.es-ES.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.fr.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.pl.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.pt-BR.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.ru.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64.zh-TW.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html
  bedrock/foundation/templates/foundation/annualreport/2017/index.html
  media/css/firefox/accounts-2018.scss
  media/css/firefox/whatsnew/whatsnew-64.scss
  media/css/firefox/whatsnew/whatsnew-66.scss
  media/css/firefox/whatsnew/whatsnew-67.scss
  media/img/firefox/accounts/fxa-lockwise-high-res.png
  media/img/firefox/accounts/fxa-lockwise.png
  media/img/firefox/accounts/lockwise-qr.png
  media/img/firefox/whatsnew_64/fxa-lockwise-high-res.png
  media/img/firefox/whatsnew_64/fxa-lockwise.png
  media/img/firefox/whatsnew_64/lockwise-qr.png
  media/img/firefox/whatsnew_67/lockwise.svg
  media/img/firefox/whatsnew_67/lockwise_glyph.png
  media/img/firefox/whatsnew_67/lockwise_glyph.svg
  media/js/firefox/accounts-2018.js
Labels: P3, Review: M

#7298 Remove zh-TW specific whatsnew template. (Fixes #7211)
  bedrock/firefox/templates/firefox/whatsnew/index.zh-TW.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-zh-tw.scss
  media/img/firefox/whatsnew/zh-tw/fox.png
  media/img/firefox/whatsnew/zh-tw/qrcode.png
  media/img/firefox/whatsnew/zh-tw/wave.png
  media/static-bundles.json
  tests/functional/firefox/test_whatsnew.py
  tests/pages/firefox/whatsnew.py
Labels: P3, Review: XS

#7278 [#7132] Trailhead accounts page: clean up switch
  bedrock/firefox/views.py
  tests/functional/firefox/test_accounts.py
Labels: Papercuts 💸

#7307 Replace Firefox Quantum w. Firefox Desktop Browser in global nav (#7303)
  bedrock/base/templates/includes/protocol/navigation/menu/firefox.html
Labels: Review: XS

#7313 Update newsletter ID on /contribute (Fixes #7305)
  bedrock/mozorg/templates/mozorg/contribute/contribute-base.html
Labels: P3, Review: XS

#7310 Change card layout on DE homepage (#7308)
  bedrock/base/templates/macros-protocol.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
Labels: P1

#7318 Add signed-in state on /firefox/accounts/ (Fixes #6907)
  bedrock/firefox/templates/firefox/accounts-2019.html
  media/css/firefox/accounts-2019.scss
  media/js/base/mozilla-monitor-button.js
  media/static-bundles.json
Labels: P3, Review: S

#7326 Remove unused lang_switcher file (Fix #7101)
  bedrock/base/templates/includes/lang_switcher.html
Labels: P3, Review: XS

#7322 Remove fxa_create_account_button macro (#7294)
  bedrock/base/templates/macros.html
Labels: P3, Review: XS

#7311 Add French homepage template (#7282)
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/tests/test_views.py
  bedrock/mozorg/views.py
  tests/functional/test_home.py
Labels: P1

#7333 Link A/B Testing to experiments section of Stub Attribution (#7332)
  docs/abtest.rst
  docs/stub-attribution.rst
Labels: P3, Review: XS

#7336 Convert System Requirements to Protocol (#7335)
  bedrock/firefox/templates/firefox/releases/system_requirements.html
  media/css/firefox/system-requirements.scss
  media/static-bundles.json
Labels: P3, Review: XS

#7329 Improve functional tests for /firefox/accounts/ page
  media/js/base/mozilla-fxa.js
  tests/functional/firefox/test_accounts.py
  tests/pages/firefox/accounts.py
  tests/pages/regions/join_firefox_form.py
Labels: P3, Review: XS

#7350 Upgrade protocol to 7.0.1
  media/css/firefox/features/adblocker.scss
  media/css/mozorg/what-is-a-browser.scss
  package.json
  yarn.lock
Labels: Review: XS
