Repository mozilla/bedrock, pull requests merged in 2019-11, with the labels that each got.

#8072 Fix numbered list syntax
  docs/coding.rst
Labels: Documentation, Review: XS, Size: XS

#8067 [fix #8064] Update legacy WNP copy and design
  bedrock/firefox/templates/firefox/whatsnew/index.html
  media/css/firefox/whatsnew/whatsnew.scss
  media/img/firefox/whatsnew/whatsnew_background.svg
  media/static-bundles.json
Labels: P1, Review: S

#8073 Update Selenium to 3.141.0 (Fixes #7419)
  docker/bin/run_integration_tests.sh
  jenkins/global.yml
  requirements/dev.txt
Labels: P2, Review: XS

#8076 Fix typos on German and French whatsnew 70 headlines. (Fixes #8075)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
Labels: P1, Review: XS

#8077 Update DE protection report CTA on whatsnew 70 (Fixes #8075)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
Labels: Bug :bug:, P1, Review: XS

#8080 Fix typo on /fr/firefox/70.0/whatsnew/ (Fix bug 1594001)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
Labels: Needs Review, P2, Review: XS

#8083 Update to Protocol 10.0.0
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/index.html
  bedrock/exp/templates/exp/firefox/whatsnew/whatsnew-fx70.html
  bedrock/firefox/templates/firefox/firstrun/firstrun.html
  bedrock/firefox/templates/firefox/installer-help.html
  bedrock/firefox/templates/firefox/privacy/products.html
  bedrock/firefox/templates/firefox/unsupported-systems.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
  media/css/exp/firefox/index.scss
  media/css/exp/firefox/whatsnew/whatsnew-70.scss
  media/css/firefox/developer/developer.scss
  media/css/firefox/firstrun/firstrun.scss
  media/css/firefox/home/master.scss
  media/css/firefox/installer-help.scss
  media/css/firefox/privacy/products.scss
  media/css/firefox/whatsnew/whatsnew-70.scss
  media/css/mozorg/about.scss
  media/css/protocol/components/_navigation.scss
  package.json
  yarn.lock
Labels: Needs Review, P2, Review: XS

#7865 Add site wide feature detect snippet (Fixes #7391)
  bedrock/base/templates/includes/sub-nav.html
  bedrock/exp/templates/exp/firefox/accounts-2019.html
  bedrock/firefox/templates/firefox/accounts-2019.html
  bedrock/firefox/templates/firefox/privacy/products.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/includes/fundraiser.html
  bedrock/mozorg/templates/mozorg/home/includes/macros.html
  docs/browser-support.rst
  media/css/firefox/all/all-unified.scss
  media/css/firefox/privacy/products.scss
  media/css/pebbles/base/oldIE.scss
  media/css/protocol/oldIE.scss
  media/css/sandstone/old-ie.scss
  media/js/base/mozilla-run.js
  media/js/base/site.js
  media/js/firefox/all/all-downloads-unified-init.js
  media/js/firefox/all/all-downloads-unified.js
  media/static-bundles.json
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-run.js
Labels: P3, Review: M

#8086 Fix image-replaced heading Safari bug (Fixes #8084)
  media/css/exp/firefox/index.scss
  media/css/firefox/home/master.scss
  media/css/firefox/privacy/products.scss
Labels: P2, Review: XS

#8102 Update URLs of the on-demand demo servers
  docs/contribute.rst
Labels: Documentation, Needs Review, Review: XS, Size: XS

#8098 Update Protocol to 10.0.1
  package.json
  yarn.lock
Labels: Needs Review, P1, Review: XS

#8057 Stop double counting event on the firefox/lockwise page (Fixes #7941)
  bedrock/exp/templates/exp/firefox/lockwise.de.html
  bedrock/exp/templates/exp/firefox/lockwise.html
  bedrock/firefox/templates/firefox/lockwise/lockwise.html
Labels: Needs Review, P2, Review: XS

#8093 Show default /whatsnew page for 70.0 > 70.0.2 update (Fixes #8091)
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
Labels: Needs Review, P1, Review: XS

#8110 [#8033] Fix experiment fetch params
  media/js/base/mozilla-monitor-button.js
Labels: Bug :bug:, Needs Review, P1, Review: XS

#8088 Add unit tests for mozilla-monitor-button.js (Fixes #7981)
  media/js/base/mozilla-monitor-button.js
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-monitor-button.js
Labels: Needs Review, P2, Review: XS

#8113 [fix #8099] Update Roxi Wen’s headshot
  media/img/mozorg/about/leadership/roxi-wen-high-res.jpg
  media/img/mozorg/about/leadership/roxi-wen.jpg
Labels: Needs Review, Review: XS

#8105 Make download link on /firefox locale neutral (Fixes #7982)
  bedrock/exp/templates/exp/firefox/index.de.html
  bedrock/exp/templates/exp/firefox/index.html
  bedrock/firefox/templates/firefox/home/index-master.html
Labels: Bug :bug:, Needs Review, P3, Review: XS

#8119 Change default whats new page banner
  media/css/firefox/whatsnew/whatsnew.scss
Labels: Bug :bug:, P3, Review: XS

#8125 Make newsletter subscription changes less confusing (Fixes #8112)
  bedrock/newsletter/templates/newsletter/existing.html
  media/css/newsletter/newsletter.less
Labels: P2, Review: XS

#8130 [#8108] Use white logo on legacy whatsnew
  bedrock/firefox/templates/firefox/whatsnew/index.html
Labels: Review: XS

#8136 [fix #8135] Fx privacy hub, add space to body class
  bedrock/firefox/templates/firefox/privacy/index.html
Labels: Needs Review, Review: XS

#7957 /mobile page redesign [Fixes #7859]
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/mobile-2019.html
  bedrock/firefox/templates/firefox/mobile.html
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  media/css/firefox/developer/developer.scss
  media/css/firefox/home/quantum.scss
  media/css/firefox/mobile-protocol.scss
  media/css/firefox/switch.scss
  media/css/protocol/components/send-to-device.scss
  media/css/protocol/hubs/_sub-nav-download-button-remove.scss
  media/css/protocol/hubs/_sub-nav.scss
  media/img/firefox/mobile/arrow-down.svg
  media/img/firefox/mobile/arrow-up.svg
  media/img/firefox/mobile/img-browser-mobile.svg
  media/img/firefox/mobile/img-mobile-noodles.svg
  media/img/firefox/mobile/protocol/account.svg
  media/img/firefox/mobile/protocol/extend-eye.svg
  media/img/firefox/mobile/protocol/extend-key.svg
  media/img/firefox/mobile/protocol/extend-star.svg
  media/img/firefox/mobile/protocol/focus-bg-lg.png
  media/img/firefox/mobile/protocol/focus-bg-md.png
  media/img/firefox/mobile/protocol/focus-bg.png
  media/img/firefox/mobile/protocol/hero-high-res-rtl.jpg
  media/img/firefox/mobile/protocol/hero-high-res.jpg
  media/img/firefox/mobile/protocol/hero-rtl.jpg
  media/img/firefox/mobile/protocol/hero-small-high-res-rtl.jpg
  media/img/firefox/mobile/protocol/hero-small-high-res.jpg
  media/img/firefox/mobile/protocol/hero-small-rtl.jpg
  media/img/firefox/mobile/protocol/hero-small.jpg
  media/img/firefox/mobile/protocol/hero.jpg
  media/img/firefox/mobile/protocol/icon-block.svg
  media/img/firefox/mobile/protocol/icon-erase.svg
  media/img/firefox/mobile/protocol/icon-send-device.svg
  media/img/firefox/mobile/protocol/qr-firefox-mozillaonline.png
  media/img/firefox/mobile/protocol/qr-firefox.png
  media/img/firefox/mobile/protocol/qr-focus.png
  media/img/firefox/mobile/protocol/screen-frame.svg
  media/img/firefox/mobile/protocol/screen-private.svg
  media/img/firefox/mobile/protocol/screen-tracking.svg
  media/img/firefox/mobile/protocol/theme-pink.svg
  media/img/firefox/mobile/protocol/theme-violet.svg
  media/img/firefox/mobile/protocol/theme-yellow.svg
  media/js/firefox/mobile/mobile-protocol.js
  media/static-bundles.json
  tests/functional/firefox/test_mobile.py
  tests/pages/firefox/mobile.py
Labels: Needs Review, P1, Review: M

#8063 Add integration tests for new /firefox (#7898)
  bedrock/firefox/templates/firefox/home/index-master.html
  tests/functional/firefox/test_home.py
  tests/pages/firefox/home.py
  tests/pages/regions/menu_list.py
Labels: Needs Review, P2, Review: S

#8115 Refactor mozilla-monitor-button.js to be reusable for other services (Fixes #7985)
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/welcome/page2.html
  bedrock/firefox/templates/firefox/whatsnew/exp/whatsnew-fx70-5.html
  bedrock/firefox/templates/firefox/whatsnew/exp/whatsnew-fx70-6.html
  bedrock/firefox/templates/firefox/whatsnew/exp/whatsnew-fx70-7.html
  docs/firefox-accounts.rst
  media/js/base/mozilla-fxa-product-button-init.js
  media/js/base/mozilla-fxa-product-button.js
  media/js/exp/firefox/accounts-2019.js
  media/js/exp/firefox/welcome-page1-init.js
  media/js/firefox/accounts-2019.js
  media/js/firefox/welcome-page1-init.js
  media/js/firefox/welcome-page2-init.js
  media/js/firefox/welcome-page2.js
  media/js/firefox/whatsnew/account-conditional-ctas.js
  media/js/firefox/whatsnew/whatsnew-69.js
  media/static-bundles.json
  tests/pages/firefox/accounts.py
  tests/pages/firefox/welcome/page1.py
  tests/pages/firefox/welcome/page2.py
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-fxa-product-button.js
Labels: P2, Review: S

#8138 Minor UI fixes on /firefox/mobile/ (Fixes #8137)
  bedrock/firefox/templates/firefox/mobile-2019.html
  media/css/firefox/mobile-protocol.scss
Labels: Needs Review, P2, Review: XS

#8106 Add localized images to /firefox and /firefox/privacy/products/ (Fixes #8074)
  bedrock/base/templates/macros-protocol.html
  bedrock/exp/templates/exp/firefox/index.de.html
  bedrock/exp/templates/exp/firefox/index.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/privacy/products.html
  media/css/firefox/privacy/products.scss
  media/img/l10n/de/firefox/home/browser-high-res.jpg
  media/img/l10n/de/firefox/home/browser.jpg
  media/img/l10n/de/firefox/privacy/products/report.svg
  media/img/l10n/en-US/firefox/home/browser-high-res.jpg
  media/img/l10n/en-US/firefox/home/browser.jpg
  media/img/l10n/en-US/firefox/privacy/products/report.svg
  media/img/l10n/fr/firefox/home/browser-high-res.jpg
  media/img/l10n/fr/firefox/home/browser.jpg
  media/img/l10n/fr/firefox/privacy/products/report.svg
Labels: P3, Review: S

#8107 Fix FxA auth links for non-Firefox browsers in nav and footer (Fixes #8044)
  bedrock/base/templates/includes/protocol/footer/firefox.html
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/join.html
  media/js/base/mozilla-fxa-sign-in-link.js
  media/static-bundles.json
Labels: Bug :bug:, P2, Review: XS

#8145 Trademark fixes
  bedrock/foundation/templates/foundation/trademarks/distribution-policy.html
  bedrock/foundation/templates/foundation/trademarks/policy.html
  media/css/protocol/basic-article.scss
Labels: Needs Review, P2, Review: XS

#8156 [fix #8152] Add welcome page 3 for Sync
  bedrock/exp/templates/exp/firefox/welcome/base.html
  bedrock/exp/templates/exp/firefox/welcome/page1.html
  bedrock/firefox/templates/firefox/welcome/base.html
  bedrock/firefox/templates/firefox/welcome/page1.html
  bedrock/firefox/templates/firefox/welcome/page2.html
  bedrock/firefox/templates/firefox/welcome/page3.html
  bedrock/firefox/urls.py
  media/css/exp/firefox/welcome.scss
  media/css/firefox/welcome.scss
  media/js/exp/firefox/welcome-page1-init.js
  media/js/firefox/welcome-page1-init.js
  media/js/firefox/welcome-page2-init.js
  media/static-bundles.json
  tests/functional/firefox/test_welcome_page3.py
  tests/pages/firefox/welcome/page3.py
Labels: P1, Review: S

#8162 Decommission old /firefox/all/ pages (Fixes #8096)
  bedrock/base/templates/product-all-macros.html
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/all.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/new/scene1.html
  bedrock/firefox/templates/firefox/new/trailhead/download.html
  bedrock/firefox/templates/firefox/new/yandex/scene1.html
  bedrock/firefox/templates/firefox/nightly_firstrun.html
  bedrock/firefox/templates/firefox/nightly_whatsnew.html
  bedrock/firefox/templatetags/helpers.py
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/tests/test_helpers.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  docs/javascript-libs.rst
  docs/mozilla-pager.rst
  media/css/base/mozilla-share-cta.less
  media/css/firefox/all/all.less
  media/js/base/mozilla-pager.js
  media/static-bundles.json
  tests/functional/firefox/test_all_legacy_pages.py
  tests/redirects/map_globalconf.py
  tests/redirects/test_urls.py
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-pager.js
Labels: P2, Review: M

#8154 Put Pocket FxA button on /firefox/pocket page (Fixes #8059)
  bedrock/firefox/templates/firefox/pocket.html
  bedrock/firefox/templates/firefox/welcome/page2.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  docs/firefox-accounts.rst
  media/css/firefox/pocket.scss
  media/static-bundles.json
  tests/pages/firefox/pocket.py
Labels: Needs Review, P2, Review: S

#8165 /firefox/accounts/ page renders at multiple URLs (Fixes #8164)
  bedrock/firefox/urls.py
Labels: P3, Review: XS

#8166 Remove stray assets from old /firefox/all/ page (#8096)
  media/img/firefox/all/download-icons-android-high-res.png
  media/img/firefox/all/download-icons-android.png
  media/img/firefox/all/download-icons-desktop.png
  media/js/firefox/all/all-downloads.js
Labels: Needs Review, P3, Review: XS

#8066 Add functional tests for /whatsnew pages (Fixes #8000)
  tests/functional/firefox/whatsnew/test_whatsnew.py
  tests/functional/firefox/whatsnew/test_whatsnew_67.py
  tests/functional/firefox/whatsnew/test_whatsnew_67_0_5.py
  tests/functional/firefox/whatsnew/test_whatsnew_68.py
  tests/functional/firefox/whatsnew/test_whatsnew_69.py
  tests/functional/firefox/whatsnew/test_whatsnew_70.py
  tests/functional/firefox/whatsnew/test_whatsnew_developer_70.py
  tests/functional/firefox/whatsnew/test_whatsnew_india.py
  tests/functional/firefox/whatsnew/test_whatsnew_nightly_70.py
  tests/functional/newsletter/test_newsletter_embed.py
  tests/pages/firefox/whatsnew/whatsnew.py
  tests/pages/firefox/whatsnew/whatsnew_67.py
  tests/pages/firefox/whatsnew/whatsnew_67_0_5.py
  tests/pages/firefox/whatsnew/whatsnew_68.py
  tests/pages/firefox/whatsnew/whatsnew_69.py
  tests/pages/firefox/whatsnew/whatsnew_70.py
  tests/pages/firefox/whatsnew/whatsnew_developer_70.py
  tests/pages/firefox/whatsnew/whatsnew_india.py
  tests/pages/firefox/whatsnew/whatsnew_nightly_70.py
Labels: P2, Review: S

#8171 Add welcome page 4 for mobile. (Fixes #8127)
  bedrock/firefox/templates/firefox/welcome/page4.html
  bedrock/firefox/urls.py
  media/css/firefox/welcome.scss
  media/img/firefox/welcome/mobile-hero.png
  media/img/firefox/welcome/welcome-qr-firefox.png
  media/img/icons/arrows.svg
  media/img/icons/eraser.svg
  media/img/icons/gradient-shield.svg
  media/js/firefox/welcome4.js
  media/static-bundles.json
  tests/functional/firefox/test_welcome_page4.py
  tests/pages/firefox/welcome/page4.py
Labels: P1, Review: S

#8199 [fix #7887] Show WNP70 content to 72beta
  bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx72-de.html
  bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx72-en.html
  bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx72-fr.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  tests/functional/firefox/whatsnew/test_whatsnew_beta_72.py
  tests/pages/firefox/whatsnew/whatsnew_beta_72.py
Labels: Needs Review, P1, Review: S

#8204 Add State of Mozilla 2018 Annual Report (Fixes #8177)
  bedrock/foundation/templates/foundation/annualreport/2018/index.html
  bedrock/foundation/urls.py
  media/css/foundation/annual-report.scss
  media/img/foundation/annualreport/2018/som-2018-large-high-res.jpg
  media/img/foundation/annualreport/2018/som-2018-large.jpg
  media/img/foundation/annualreport/2018/som-2018-small-high-res.jpg
  media/img/foundation/annualreport/2018/som-2018-small.jpg
Labels: P1

#8207 [fix #8189] Clean up WNP70 experiment
  bedrock/firefox/templates/firefox/whatsnew/exp/whatsnew-fx70-0.html
  bedrock/firefox/templates/firefox/whatsnew/exp/whatsnew-fx70-1.html
  bedrock/firefox/templates/firefox/whatsnew/exp/whatsnew-fx70-2.html
  bedrock/firefox/templates/firefox/whatsnew/exp/whatsnew-fx70-3.html
  bedrock/firefox/templates/firefox/whatsnew/exp/whatsnew-fx70-4.html
  bedrock/firefox/templates/firefox/whatsnew/exp/whatsnew-fx70-5.html
  bedrock/firefox/templates/firefox/whatsnew/exp/whatsnew-fx70-6.html
  bedrock/firefox/templates/firefox/whatsnew/exp/whatsnew-fx70-7.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-70-experiment.scss
  media/js/firefox/whatsnew/experiment-whatsnew-70.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_70.py
Labels: Needs Review, P3, Papercuts 💸, Review: XS

#8175 Add link to download in another language on /thanks (Fixes #8116)
  bedrock/firefox/templates/firefox/new/trailhead/thanks.html
  media/css/firefox/new/trailhead/thanks.scss
Labels: P2, Review: XS

#8159 Add /whatsnew page for Firefox 71 (Fixes #8026)
  bedrock/exp/templates/exp/firefox/whatsnew/whatsnew-fx70.html
  bedrock/exp/templates/exp/firefox/whatsnew/whatsnew-fx71.html
  bedrock/exp/views.py
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx71.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/exp/firefox/whatsnew/whatsnew-71.scss
  media/css/firefox/whatsnew/whatsnew-71.scss
  media/js/exp/firefox/whatsnew/whatsnew-70.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_71.py
  tests/functional/test_experiment_pages.py
  tests/pages/firefox/whatsnew/whatsnew_71.py
Labels: P1, Review: S

#8122 Pass utm params from upstream referrals on fxa_email_form (Fixes #8001)
  media/js/base/mozilla-fxa-form.js
  media/js/base/mozilla-fxa-product-button.js
Labels: P1, Review: S

#8225 Fix typos in SOM 2018 (Fixes #8224)
  bedrock/foundation/templates/foundation/annualreport/2018/index.html
Labels: Review: XS

#8187 Port Legal pages to Protocol (Fixes #7441)
  bedrock/legal/templates/legal/base-resp.html
  bedrock/legal/templates/legal/docs-base.html
  bedrock/legal/templates/legal/eula.html
  bedrock/legal/templates/legal/eula/firefox-2-eula.html
  bedrock/legal/templates/legal/eula/firefox-3-eula.html
  bedrock/legal/templates/legal/eula/thunderbird-1.5-eula.html
  bedrock/legal/templates/legal/eula/thunderbird-2-eula.html
  bedrock/legal/templates/legal/firefox.html
  bedrock/legal/templates/legal/fraud-report.html
  bedrock/legal/templates/legal/impressum.html
  bedrock/legal/templates/legal/index.html
  bedrock/legal/templates/legal/terms/services.html
  bedrock/legal/templates/legal/terms/vpn.html
  media/css/legal/eula.less
  media/css/legal/fraud-report.less
  media/css/legal/legal.less
  media/css/legal/legal.scss
  media/img/privacy/logo-sprite.png
  media/static-bundles.json
Labels: P3, Papercuts 💸, Review: S
