Repository mozilla/bedrock, pull requests merged in 2019-09, with the labels that each got.

#7458 Protocol based styles for the send to device widget
  bedrock/base/templates/macros.html
  media/css/protocol/base/send-to-device.scss
Labels: P3, Review: XS

#7611 Redesign /firefox/enterprise page (Fixes #7491)
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/all-unified.html
  bedrock/firefox/templates/firefox/all.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/enterprise/signup-thanks.html
  bedrock/firefox/templates/firefox/enterprise/signup.html
  bedrock/firefox/templates/firefox/organizations/organizations.html
  bedrock/firefox/templates/firefox/releases/notes.html
  bedrock/firefox/urls.py
  bedrock/security/templates/security/product-advisories.html
  media/css/firefox/enterprise.scss
  media/css/firefox/enterprise/landing.scss
  media/css/firefox/enterprise/signup.scss
  media/css/firefox/enterprise/sla.scss
  media/css/firefox/organizations.less
  media/css/protocol/components/_navigation.scss
  media/img/firefox/enterprise/enterprise-support.svg
  media/img/firefox/enterprise/icon-data-privacy.svg
  media/img/firefox/enterprise/icon-deploy.svg
  media/img/firefox/enterprise/icon-documentation.svg
  media/img/firefox/enterprise/icon-faq.svg
  media/img/firefox/enterprise/icon-mac.svg
  media/img/firefox/enterprise/icon-notes.svg
  media/img/firefox/enterprise/icon-release.svg
  media/img/firefox/enterprise/icon-win32.svg
  media/img/firefox/enterprise/icon-win64.svg
  media/img/firefox/organizations/release-overview-high-res.png
  media/img/firefox/organizations/release-overview.png
  media/img/firefox/organizations/title-high-res.png
  media/img/firefox/organizations/title.png
  media/js/firefox/enterprise/landing.js
  media/js/firefox/enterprise/sla.js
  media/static-bundles.json
  tests/functional/firefox/test_enterprise.py
  tests/pages/firefox/enterprise.py
  tests/pages/firefox/enterprise/__init__.py
  tests/pages/firefox/enterprise/landing.py
  tests/pages/firefox/enterprise/signup.py
  tests/redirects/map_globalconf.py
  tests/redirects/test_urls.py
Labels: P1, Review: M

#7642 Update resolution of dev edition wordmark.
  bedrock/firefox/templates/firefox/developer/firstrun.html
  media/css/firefox/developer/includes/intro.scss
  media/img/logos/firefox/developer-wordmark-dark-high-res.png
  media/img/logos/firefox/developer-wordmark-dark.png
  media/img/logos/firefox/developer-wordmark-high-res.png
  media/img/logos/firefox/developer-wordmark.png
Labels: Review: XS

#7644 Update string on /switch (#7608)
  bedrock/firefox/templates/firefox/switch.html
Labels: P1, Review: XS

#7638 If passing through UTMs to FxA, do not fall back to our default values (Fixes #7321)
  docs/firefox-accounts.rst
  media/js/base/fxa-utm-referral.js
  tests/unit/spec/base/fxa-utm-referral.js
Labels: P2, Review: XS

#7646 Fix websites privacy notice expanders and page title (Fixes #7645)
  bedrock/privacy/templates/privacy/notices/base-notice-paragraphs.html
  bedrock/privacy/templates/privacy/notices/websites.html
Labels: P2, Review: XS

#7631 Fix docs formatting errors
  docs/browser-support.rst
  docs/coding.rst
  docs/firefox-accounts.rst
Labels: P3, Review: XS

#7636 Deprecate send-yourself widget (Fixes #7632)
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/whatsnew/index-lite.id.html
  docs/send-to-device.rst
  media/css/base/send-to-device-micro.less
  media/css/base/send-to-device.less
  media/css/firefox/mobile.scss
  media/css/firefox/whatsnew/send-to-device.scss
  media/css/firefox/whatsnew/send-yourself.scss
  media/css/firefox/whatsnew/whatsnew-lite.scss
  media/css/protocol/components/send-to-device.scss
  media/img/send-to-device/logo-high-res.png
  media/img/send-to-device/logo.png
  media/js/base/send-to-device.js
  media/js/base/send-yourself.js
  media/js/firefox/whatsnew/whatsnew-id.js
  media/static-bundles.json
  tests/functional/firefox/test_whatsnew.py
  tests/pages/firefox/whatsnew.py
  tests/pages/regions/send_to_device.py
  tests/pages/regions/send_yourself.py
  tests/unit/spec/base/send-to-device.js
Labels: P3, Review: S

#7635 Update front-end dependencies (Fixes #7503)
  .circleci/config.yml
  package.json
  yarn.lock
Labels: P3, Review: XS

#7663 Move base files into own folder. [Fixes #7662]
  bedrock/firefox/templates/firefox/accounts-2019.html
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/all-unified.html
  bedrock/firefox/templates/firefox/all.html
  bedrock/firefox/templates/firefox/base/base-pebbles.html
  bedrock/firefox/templates/firefox/base/base-protocol.html
  bedrock/firefox/templates/firefox/base/base-resp.html
  bedrock/firefox/templates/firefox/best-browser.html
  bedrock/firefox/templates/firefox/campaign/berlin/base-variation.html
  bedrock/firefox/templates/firefox/campaign/berlin/base.html
  bedrock/firefox/templates/firefox/campaign/better-browser/base.html
  bedrock/firefox/templates/firefox/campaign/compare/base.html
  bedrock/firefox/templates/firefox/campaign/index-trailhead.html
  bedrock/firefox/templates/firefox/campaign/index.html
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/firefox/templates/firefox/concerts.html
  bedrock/firefox/templates/firefox/content-blocking-tour/index.html
  bedrock/firefox/templates/firefox/dedicated-profiles.html
  bedrock/firefox/templates/firefox/developer/firstrun.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/developer/whatsnew.html
  bedrock/firefox/templates/firefox/election/index-de.html
  bedrock/firefox/templates/firefox/election/index-fr.html
  bedrock/firefox/templates/firefox/election/index.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/facebookcontainer/index.html
  bedrock/firefox/templates/firefox/features/base.html
  bedrock/firefox/templates/firefox/features/safebrowser.html
  bedrock/firefox/templates/firefox/fights-for-you.de.html
  bedrock/firefox/templates/firefox/fights-for-you.fr.html
  bedrock/firefox/templates/firefox/fights-for-you.html
  bedrock/firefox/templates/firefox/firstrun/firstrun.html
  bedrock/firefox/templates/firefox/home/index.html
  bedrock/firefox/templates/firefox/installer-help.html
  bedrock/firefox/templates/firefox/mobile.html
  bedrock/firefox/templates/firefox/new/base.html
  bedrock/firefox/templates/firefox/new/scene2.html
  bedrock/firefox/templates/firefox/new/trailhead/base.html
  bedrock/firefox/templates/firefox/new/yandex/base.html
  bedrock/firefox/templates/firefox/nightly_firstrun.html
  bedrock/firefox/templates/firefox/nightly_whatsnew.html
  bedrock/firefox/templates/firefox/recommended.html
  bedrock/firefox/templates/firefox/releases/index.html
  bedrock/firefox/templates/firefox/releases/notes.html
  bedrock/firefox/templates/firefox/releases/system_requirements.html
  bedrock/firefox/templates/firefox/switch.html
  bedrock/firefox/templates/firefox/testflight.html
  bedrock/firefox/templates/firefox/tracking-protection-tour/index.html
  bedrock/firefox/templates/firefox/unsupported-systems.html
  bedrock/firefox/templates/firefox/whatsnew/base-pebbles.html
  bedrock/firefox/templates/firefox/whatsnew/base.html
  bedrock/firefox/templates/firefox/whatsnew/fx64/whatsnew-fx64-base.html
  bedrock/firefox/templates/firefox/whatsnew/index-lite.id.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx63.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx65.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx69.html
  bedrock/firefox/templates/firefox/windows-64-bit.html
Labels: Needs Review, P3, Review: XS

#7669 [fix #7667] Update Enterprise SLA help link
  bedrock/firefox/templates/firefox/enterprise/sla.html
Labels: Needs Review, P1, Review: XS

#7681 Change 'Emeritus' board members to 'Former' on /leadership page
  bedrock/mozorg/templates/mozorg/about/leadership.html
Labels: Needs Review, P1, Review: XS

#7685 Copy update for enterprise [Fixes #7683]
  bedrock/firefox/templates/firefox/enterprise/index.html
Labels: Needs Review, P1, Review: XS

#7659 Remove microdata from product pages (#7658)
  bedrock/firefox/templates/firefox/home/index.html
  bedrock/firefox/templates/firefox/includes/schemaorg-app.html
  bedrock/firefox/templates/firefox/new/scene1.html
  bedrock/firefox/templates/firefox/new/yandex/scene1.html
Labels: P2, Review: XS

#7691 Remove card description truncation Fix #7690
  bedrock/base/templates/macros-protocol.html
Labels: P3, Review: XS

#7660 Add structured_data template block (#7653)
  bedrock/base/templates/base-pebbles.html
  bedrock/base/templates/base-resp.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/includes/structured-data.html
  bedrock/mozorg/templates/mozorg/home/includes/structured-data.json
Labels: P2, Review: XS

#7712 Move nav menu in to mozilla namespace (#7711)
  bedrock/base/templates/base-pebbles.html
  bedrock/base/templates/base-resp.html
  bedrock/base/templates/includes/protocol/navigation/index.html
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/about.html
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/developers.html
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/firefox.html
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/index.html
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/projects.html
  bedrock/base/templates/includes/protocol/navigation/nav-cta.html
  bedrock/firefox/templates/firefox/accounts-2019.html
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/all-unified.html
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/election/index-de.html
  bedrock/firefox/templates/firefox/election/index-fr.html
  bedrock/firefox/templates/firefox/election/index.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/installer-help.html
  bedrock/firefox/templates/firefox/mobile.html
  bedrock/firefox/templates/firefox/releases/index.html
  bedrock/firefox/templates/firefox/releases/notes.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/templates/mozorg/moss/base.html
Labels: Needs Review, P1, Review: XS

#7695 String change to support family of products marketing (#7684)
  bedrock/firefox/templates/firefox/accounts-2019.html
Labels: Needs Review, P1, Review: XS

#7634 Trademark copy changes [fixed #7622]
  bedrock/foundation/templates/foundation/trademarks/distribution-policy.html
  bedrock/foundation/templates/foundation/trademarks/policy.html
Labels: Needs Review, P2, Review: S

#7728 [fix #7348] Leadership page updates
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/css/mozorg/leadership.scss
  media/img/mozorg/about/leadership/alan-davidson-high-res.jpg
  media/img/mozorg/about/leadership/alan-davidson.jpg
  media/img/mozorg/about/leadership/amy-keating-high-res.jpg
  media/img/mozorg/about/leadership/amy-keating.jpg
  media/img/mozorg/about/leadership/chris-beard-high-res.jpg
  media/img/mozorg/about/leadership/chris-beard.jpg
  media/img/mozorg/about/leadership/chris-lin-high-res.jpg
  media/img/mozorg/about/leadership/chris-lin.jpg
  media/img/mozorg/about/leadership/dave-camp-high-res.jpg
  media/img/mozorg/about/leadership/dave-camp.jpg
  media/img/mozorg/about/leadership/david-bryant-high-res.jpg
  media/img/mozorg/about/leadership/david-bryant.jpg
  media/img/mozorg/about/leadership/header/snap-lshepard-high-res.jpg
  media/img/mozorg/about/leadership/header/snap-lshepard.jpg
  media/img/mozorg/about/leadership/header/snap-mmayo-high-res.jpg
  media/img/mozorg/about/leadership/header/snap-mmayo.jpg
  media/img/mozorg/about/leadership/header/snap-nnguyen-high-res.jpg
  media/img/mozorg/about/leadership/header/snap-nnguyen.jpg
  media/img/mozorg/about/leadership/header/snap-rwen-high-res.jpg
  media/img/mozorg/about/leadership/header/snap-rwen.jpg
  media/img/mozorg/about/leadership/jascha-kaykas-wolff-high-res.jpg
  media/img/mozorg/about/leadership/jascha-kaykas-wolff.jpg
  media/img/mozorg/about/leadership/joe-hildebrand-high-res.jpg
  media/img/mozorg/about/leadership/joe-hildebrand.jpg
  media/img/mozorg/about/leadership/katharina-borchert-high-res.jpg
  media/img/mozorg/about/leadership/katharina-borchert.jpg
  media/img/mozorg/about/leadership/lindsey-shepard-high-res.jpg
  media/img/mozorg/about/leadership/lindsey-shepard.jpg
  media/img/mozorg/about/leadership/marissa-wood-high-res.jpg
  media/img/mozorg/about/leadership/marissa-wood.jpg
  media/img/mozorg/about/leadership/mary-ellen-muckerman-high-res.jpg
  media/img/mozorg/about/leadership/mary-ellen-muckerman.jpg
  media/img/mozorg/about/leadership/michael-deangelo-high-res.jpg
  media/img/mozorg/about/leadership/michael-deangelo.jpg
  media/img/mozorg/about/leadership/roxi-wen-high-res.jpg
  media/img/mozorg/about/leadership/roxi-wen.jpg
  media/img/mozorg/about/leadership/sean-white-high-res.jpg
  media/img/mozorg/about/leadership/sean-white.jpg
  media/img/mozorg/about/leadership/shani-higgins-high-res.jpg
  media/img/mozorg/about/leadership/shani-higgins.jpg
Labels: Needs Review, Review: XS

#7740 Remove shapeoftheweb app (Fixes #7520)
  bedrock/settings/base.py
  bedrock/shapeoftheweb/__init__.py
  bedrock/shapeoftheweb/models.py
  bedrock/shapeoftheweb/templates/shapeoftheweb/country-data.json
  bedrock/shapeoftheweb/templates/shapeoftheweb/infographics.json
  bedrock/shapeoftheweb/templates/shapeoftheweb/main.json
  bedrock/shapeoftheweb/urls.py
  bedrock/shapeoftheweb/views.py
  bedrock/urls.py
Labels: P3, Review: XS

#7735 Update the banners at the top and bottom of the homepage (#7684)
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/templates/mozorg/home/includes/macros.html
  media/css/mozorg/home/home-2018.scss
  media/img/home/2018/banner-fffy-high-res.png
  media/img/home/2018/banner-fffy.png
  media/img/home/2018/bg-primary.svg
  media/img/home/2018/bg-secondary.svg
  media/img/home/2018/browser-high-res.png
  media/img/home/2018/browser.png
  media/img/home/2018/home-high-res.jpg
  media/img/home/2018/home.jpg
  media/img/home/2018/noodle.svg
  media/img/home/2018/shield.svg
  media/img/home/2018/wave-primary.svg
  media/img/home/2018/wave-secondary.svg
  media/img/logos/firefox/browser-wordmark-horizontal-high-res.png
  media/img/logos/firefox/browser-wordmark-horizontal.png
  media/img/logos/firefox/master-md-high-res.png
  media/img/logos/firefox/master-md.png
  media/img/logos/firefox/master-sm-high-res.png
  media/img/logos/firefox/master-sm.png
Labels: Needs Review, P1, Review: S

#7715 Update the Impressum page (Fixes #7630)
  bedrock/legal/templates/legal/impressum.html
Labels: P2, Review: XS

#7613 Drop 1st class support for IE9 (Fixes #7559)
  bedrock/base/templates/base-article.html
  bedrock/base/templates/base-pebbles.html
  bedrock/base/templates/base-protocol.html
  bedrock/base/templates/base-resp.html
  bedrock/firefox/templates/firefox/election/index.html
  bedrock/firefox/templates/firefox/fights-for-you.de.html
  bedrock/firefox/templates/firefox/fights-for-you.fr.html
  bedrock/firefox/templates/firefox/fights-for-you.html
  bedrock/firefox/templates/firefox/home/index-quantum.html
  bedrock/mozorg/templates/mozorg/contribute/contribute-embed.html
  bedrock/mozorg/templates/mozorg/home/includes/fundraiser.html
  docs/browser-support.rst
  docs/stub-attribution.rst
  gulpfile.js
  media/css/firefox/home/ie9.scss
  media/css/firefox/home/includes/_header.scss
  media/css/firefox/home/quantum.scss
  media/js/firefox/new/scene2.js
  media/js/ie/base-page-init-ie.js
  media/js/ie/mozilla-utils-ie.js
  media/js/libs/matchMedia.addListener.js
  media/js/libs/matchMedia.js
  media/static-bundles.json
  tests/functional/firefox/features/test_landing.py
  tests/functional/firefox/test_developer.py
  tests/unit/karma.conf.js
  tests/unit/spec/ie/mozilla-utils-ie.js
  tests/unit/spec/ie8/mozilla-utils-ie8.js
Labels: P2, Review: S

#7730 Make /whatsnew urls use the new Geo redirector view class (Fixes #7637)
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  tests/pages/firefox/whatsnew.py
Labels: P2, Review: XS

#7739 Port /firefox/installer-help/ to use Protocol (Fixes #6882)
  bedrock/firefox/templates/firefox/installer-help.html
  media/css/firefox/installer-help.less
  media/css/firefox/installer-help.scss
  media/js/firefox/installer-help.js
  media/static-bundles.json
Labels: P3, Papercuts 💸, Review: XS

#7702 Add convert.com experimentation sandbox (Fixes #7508)
  bedrock/base/templates/base-pebbles.html
  bedrock/base/templates/base-resp.html
  bedrock/exp/__init__.py
  bedrock/exp/models.py
  bedrock/exp/templates/exp/base/base-firefox.html
  bedrock/exp/templates/exp/base/base.html
  bedrock/exp/templates/exp/firefox/new/base.html
  bedrock/exp/templates/exp/firefox/new/download.de.html
  bedrock/exp/templates/exp/firefox/new/download.html
  bedrock/exp/templates/exp/opt-out.html
  bedrock/exp/urls.py
  bedrock/exp/views.py
  bedrock/settings/base.py
  bedrock/urls.py
  media/css/exp/firefox/new/download.scss
  media/css/exp/opt-out.scss
  media/img/exp/firefox/new/hero-bg-rtl.svg
  media/img/exp/firefox/new/hero-bg.svg
  media/img/exp/firefox/new/icon-join.svg
  media/img/exp/firefox/new/icon-lockwise.svg
  media/img/exp/firefox/new/icon-private.svg
  media/js/exp/convert.js
  media/static-bundles.json
Labels: P1, Review: S

#7754 Make sure jQuery is included if convert switch is set to off (#7508)
  bedrock/exp/templates/exp/base/base.html
Labels: Bug :bug:, P2, Review: XS

#7737 [fix #7594] Add Firefox lifecycle/welcome page
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/welcome/base.html
  bedrock/firefox/templates/firefox/welcome/page1.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx69.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  docs/firefox-accounts.rst
  media/css/firefox/welcome.scss
  media/img/firefox/glyphs/pocket.svg
  media/img/icons/experiments.svg
  media/img/icons/heart.svg
  media/img/icons/inbox.svg
  media/img/icons/layers.svg
  media/img/icons/lockwise.svg
  media/img/icons/private-browsing.svg
  media/img/icons/send.svg
  media/img/icons/warning.svg
  media/img/logos/monitor/monitor-wordmark.svg
  media/static-bundles.json
  tests/functional/firefox/test_welcome_page1.py
  tests/pages/firefox/welcome/page1.py
Labels: P1, Review: M

#7672 Detect UITour failure / non-response on what's new page (Fixes #7671)
  media/js/firefox/whatsnew/whatsnew-69.js
Labels: Needs Review, P2, Review: XS

#7760 [no bug] Leadership page - update Leong’s headshot, remove Mayo
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/mark-mayo-high-res.jpg
  media/img/mozorg/about/leadership/mark-mayo.jpg
  media/img/mozorg/about/leadership/stan-leong-high-res.jpg
  media/img/mozorg/about/leadership/stan-leong.jpg
Labels: Needs Review, P1, Review: XS

#7757 Update UITour library for showProtectionReport (Fixes #7753)
  docs/uitour.rst
  media/js/base/uitour-lib.js
Labels: Needs Review, P1, Review: XS

#7756 Updated redirects.py
  bedrock/legal/redirects.py
Labels: Bug :bug:, P3, Review: XS

#7761 Redirect to send tab sumo article
  bedrock/firefox/redirects.py
Labels: Bug :bug:, Needs Review, Review: XS

#7759 Privacy preferences button is missing on /privacy/firefox/ (Fixes #7758)
  media/js/privacy/privacy-firefox.js
Labels: Bug :bug:, P1, Review: XS

#7791 Identify iPadOS as iOS and not macOS (Fixes #7299)
  media/js/base/site.js
  tests/unit/spec/base/site.js
Labels: Bug :bug:, P1

#7795 [fix #7794] Leadership: add Koidin, remove Higgins
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/matt-koidin-high-res.jpg
  media/img/mozorg/about/leadership/matt-koidin.jpg
  media/img/mozorg/about/leadership/shani-higgins-high-res.jpg
  media/img/mozorg/about/leadership/shani-higgins.jpg
Labels: Needs Review, P1, Review: XS

#7789 Update to Protocol 9.0.0 (#7788)
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/developers.html
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/firefox.html
  bedrock/firefox/templates/firefox/features/safebrowser.html
  bedrock/firefox/templates/firefox/firstrun/firstrun.html
  bedrock/firefox/templates/firefox/windows-64-bit.html
  media/css/firefox/new/scene1_gb_de.scss
  media/css/firefox/whatsnew/whatsnew-66.scss
  media/css/firefox/whatsnew/whatsnew-67.scss
  media/css/mozorg/home/fundraiser.scss
  media/css/mozorg/home/home-2018.scss
  media/css/protocol/protocol.scss
  media/img/logos/firefox/quantum/logo-2xl-high-res.png
  media/img/logos/firefox/quantum/logo-2xl.png
  media/img/logos/firefox/quantum/logo-and-word-hor-stack-white.svg
  media/img/logos/firefox/quantum/logo-and-word-hor-stack.svg
  media/img/logos/firefox/quantum/logo-and-word-hor-white.svg
  media/img/logos/firefox/quantum/logo-and-word-hor.svg
  media/img/logos/firefox/quantum/logo-and-word-ver-stack-white.svg
  media/img/logos/firefox/quantum/logo-and-word-ver-stack.svg
  media/img/logos/firefox/quantum/logo-and-word-ver-white.svg
  media/img/logos/firefox/quantum/logo-and-word-ver.svg
  media/img/logos/firefox/quantum/logo-flat-white.svg
  media/img/logos/firefox/quantum/logo-flat.svg
  media/img/logos/firefox/quantum/logo-lg-high-res.png
  media/img/logos/firefox/quantum/logo-lg.png
  media/img/logos/firefox/quantum/logo-md-high-res.png
  media/img/logos/firefox/quantum/logo-md.png
  media/img/logos/firefox/quantum/logo-sm-high-res.png
  media/img/logos/firefox/quantum/logo-sm.png
  media/img/logos/firefox/quantum/logo-word-hor-lg-high-res.png
  media/img/logos/firefox/quantum/logo-word-hor-lg.png
  media/img/logos/firefox/quantum/logo-word-hor-md-high-res.png
  media/img/logos/firefox/quantum/logo-word-hor-md.png
  media/img/logos/firefox/quantum/logo-word-hor-sm-high-res.png
  media/img/logos/firefox/quantum/logo-word-hor-sm.png
  media/img/logos/firefox/quantum/logo-word-hor-white-lg-high-res.png
  media/img/logos/firefox/quantum/logo-word-hor-white-lg.png
  media/img/logos/firefox/quantum/logo-word-hor-white-md-high-res.png
  media/img/logos/firefox/quantum/logo-word-hor-white-md.png
  media/img/logos/firefox/quantum/logo-word-hor-white-sm-high-res.png
  media/img/logos/firefox/quantum/logo-word-hor-white-sm.png
  package.json
  yarn.lock
Labels: P1, Review: S

#7801 [fix #7799] redirect welcome/1 to welcome/1/ (with trailing slash)
  bedrock/firefox/urls.py
Labels: Bug :bug:, Review: XS

#7777 Update browser-history.html
  bedrock/mozorg/templates/mozorg/browser-history.html
Labels: Bug :bug:, Review: XS

#7800 Port CSRF page to Protocol
  bedrock/mozorg/templates/mozorg/csrf-failure.html
  media/css/csrf-failure.less
  media/css/csrf-failure.scss
  media/static-bundles.json
Labels: P3, Review: XS

#7807 [#7794] Add Steering Committee notes to leadership page
  bedrock/mozorg/templates/mozorg/about/leadership.html
Labels: Review: XS

#7808 [#7794] Add Nate Weiner to leadership page
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/nate-weiner-high-res.jpg
  media/img/mozorg/about/leadership/nate-weiner.jpg
Labels: Needs Review, P1, Review: XS

#7784 Update fxa_link_fragment to use signin not login (#7783)
  bedrock/firefox/templates/firefox/developer/whatsnew-fx68.html
  bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
Labels: P3, Review: XS
