Repository mozilla/bedrock, pull requests merged in 2019-04, with the labels that each got.

#6983 Add fffy redirect (fixes #6979)
  bedrock/firefox/redirects.py
  tests/redirects/map_globalconf.py
Labels: Needs Review, P3, Review: XS

#7011 Add subhead to hero section on Mozilla.org for DE homepage (Fixes #6980)
  bedrock/mozorg/templates/mozorg/home/home-de.html
Labels: P2, Review: XS

#7008 Remove /firefox/new/ headline and dmt experiment code (#6995, #6996)
  bedrock/firefox/templates/firefox/new/privacy-dmt/scene1-a.html
  bedrock/firefox/templates/firefox/new/privacy-dmt/scene1-b.html
  bedrock/firefox/templates/firefox/new/privacy-dmt/scene1-c.html
  bedrock/firefox/templates/firefox/new/privacy-dmt/scene1-d.html
  bedrock/firefox/templates/firefox/new/privacy-dmt/scene1-e.html
  bedrock/firefox/templates/firefox/new/privacy-dmt/scene1-f.html
  bedrock/firefox/templates/firefox/new/privacy-dmt/scene2.html
  bedrock/firefox/templates/firefox/new/scene1.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/css/firefox/new/scene1-privacy-dmt.scss
  media/js/firefox/new/experiment-privacy-dmt.js
  media/js/firefox/new/headline/experiment-de.js
  media/js/firefox/new/headline/experiment-en.js
  media/static-bundles.json
Labels: P1, Review: XS

#6927 Features A/B test on firefox/new (Fixes #6830)
  bedrock/firefox/templates/firefox/new/features/index.de-a.html
  bedrock/firefox/templates/firefox/new/features/index.de-b.html
  bedrock/firefox/templates/firefox/new/features/index.de-c.html
  bedrock/firefox/templates/firefox/new/features/index.en-GB-a.html
  bedrock/firefox/templates/firefox/new/features/index.en-GB-b.html
  bedrock/firefox/templates/firefox/new/features/index.en-GB-c.html
  bedrock/firefox/templates/firefox/new/scene1.de.html
  bedrock/firefox/templates/firefox/new/scene1.en-GB.html
  bedrock/firefox/templates/firefox/new/scene1.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/css/firefox/new/scene1-features-experiment.scss
  media/img/firefox/new/features/de/control-center-high-res.png
  media/img/firefox/new/features/de/control-center.png
  media/img/firefox/new/features/de/faster-high-res.png
  media/img/firefox/new/features/de/faster.png
  media/img/firefox/new/features/de/password-manager-high-res.png
  media/img/firefox/new/features/de/password-manager.png
  media/img/firefox/new/features/de/private-high-res.png
  media/img/firefox/new/features/de/private.png
  media/img/firefox/new/features/de/switch-high-res.png
  media/img/firefox/new/features/de/switch.png
  media/img/firefox/new/features/de/sync-high-res.png
  media/img/firefox/new/features/de/sync.png
  media/img/firefox/new/features/de/tracking-high-res.png
  media/img/firefox/new/features/de/tracking.png
  media/img/firefox/new/features/en/control-center-high-res.png
  media/img/firefox/new/features/en/control-center.png
  media/img/firefox/new/features/en/faster-high-res.png
  media/img/firefox/new/features/en/faster.png
  media/img/firefox/new/features/en/password-manager-high-res.png
  media/img/firefox/new/features/en/password-manager.png
  media/img/firefox/new/features/en/private-high-res.png
  media/img/firefox/new/features/en/private.png
  media/img/firefox/new/features/en/switch-high-res.png
  media/img/firefox/new/features/en/switch.png
  media/img/firefox/new/features/en/sync-high-res.png
  media/img/firefox/new/features/en/sync.png
  media/img/firefox/new/features/en/tracking-high-res.png
  media/img/firefox/new/features/en/tracking.png
  media/js/firefox/new/experiment-features-variation.js
  media/js/firefox/new/experiment-features.js
  media/js/firefox/new/scene1_fxa_modal.js
  media/static-bundles.json
Labels: Needs Review, P1, Review: M

#7027 Fix JS error on /firefox/new/ whern using Firefox (Fixes #7026)
  media/js/firefox/new/scene1_fxa_modal.js
Labels: Bug :bug:, P1, Review: XS

#7025 Deindex /download/thanks/ (Fixes #7024)
  bedrock/firefox/templates/firefox/new/scene2.html
  bedrock/firefox/tests/test_views.py
Labels: Bug :bug:, P1, Review: XS

#6986 Update Release Notes to Protocol (#6823)
  bedrock/firefox/templates/firefox/releases/aurora-notes.html
  bedrock/firefox/templates/firefox/releases/beta-notes.html
  bedrock/firefox/templates/firefox/releases/dev-browser-notes.html
  bedrock/firefox/templates/firefox/releases/index.html
  bedrock/firefox/templates/firefox/releases/nightly-notes.html
  bedrock/firefox/templates/firefox/releases/notes.html
  bedrock/firefox/templates/firefox/releases/system_requirements.html
  media/css/firefox/releasenotes-firefox.less
  media/css/firefox/releasenotes.less
  media/css/firefox/releasenotes.scss
  media/css/firefox/releases-index.less
  media/css/firefox/releases-index.scss
  media/img/firefox/releasenotes/aurora-high-res.png
  media/img/firefox/releasenotes/aurora.png
  media/img/firefox/releasenotes/aurora_bg_800.png
  media/img/firefox/releasenotes/aurora_small.png
  media/img/firefox/releasenotes/beta-old-high-res.png
  media/img/firefox/releasenotes/beta-old.png
  media/img/firefox/releasenotes/developer-old-high-res.png
  media/img/firefox/releasenotes/developer-old.png
  media/img/firefox/releasenotes/firefox-old-high-res.png
  media/img/firefox/releasenotes/firefox-old.png
  media/img/firefox/releasenotes/nightly-old-high-res.png
  media/img/firefox/releasenotes/nightly-old.png
  media/js/firefox/releasenotes.js
  media/static-bundles.json
Labels: Needs Review, P1, Review: M

#7049 Bug 1542992 - Get distribution link with the correct attribute name
  media/js/base/mozilla-utils.js
Labels: Bug :bug:, P1, Review: XS

#7041 Fix download sticky issues on homepage #6989
  media/css/mozorg/home/home-2018.scss
  media/js/mozorg/home/home.js
Labels: P3, Review: XS

#7020 DUE 04/12: Remove Denelle Dixon from leadership page (Fixes #7019)
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/denelle-dixon-high-res.jpg
  media/img/mozorg/about/leadership/denelle-dixon.jpg
Labels: P1, Review: XS

#7065 Link to code of conduct from readme and contributing docs
  .github/CONTRIBUTING.md
  README.md
Labels: P3, Review: XS

#7029 Quantify daily unique users of Win10 S mode attempting to download Firefox (Fixes #6984)
  media/js/base/core-datalayer-init.js
  media/js/base/core-datalayer.js
  tests/unit/spec/base/core-datalayer.js
Labels: P1, Review: XS

#7077 Tighten up spacing on release notes
  bedrock/firefox/templates/firefox/releases/notes.html
  media/css/firefox/releasenotes.scss
Labels: P3

#7079 Remove estimates table from sprint task template
  .github/ISSUE_TEMPLATE/sprint_task.md
Labels: P3, Review: XS

#7005 Pre-download newsletter experiments on /new (Fixes #6950)
  bedrock/firefox/templates/firefox/new/newsletter/scene1-a.html
  bedrock/firefox/templates/firefox/new/newsletter/scene1-b.html
  bedrock/firefox/templates/firefox/new/newsletter/scene1-c.html
  bedrock/firefox/templates/firefox/new/newsletter/scene1-d.html
  bedrock/firefox/templates/firefox/new/newsletter/scene1-e.html
  bedrock/firefox/templates/firefox/new/newsletter/scene2-a.html
  bedrock/firefox/templates/firefox/new/newsletter/scene2-b.html
  bedrock/firefox/templates/firefox/new/newsletter/scene2-c.html
  bedrock/firefox/templates/firefox/new/newsletter/scene2-d.html
  bedrock/firefox/templates/firefox/new/newsletter/scene2-e.html
  bedrock/firefox/templates/firefox/new/scene1.html
  bedrock/firefox/templates/firefox/new/scene2.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/css/firefox/new/newsletter/scene1-embed.scss
  media/css/firefox/new/newsletter/scene1-pre-download.scss
  media/css/firefox/new/newsletter/scene2-centered.scss
  media/js/firefox/new/newsletter/experiment.js
  media/js/firefox/new/newsletter/scene1-embed.js
  media/js/firefox/new/newsletter/scene1-modal.js
  media/js/firefox/new/newsletter/scene2-centered.js
  media/js/firefox/new/newsletter/scene2-embed.js
  media/js/firefox/new/newsletter/variation.js
  media/static-bundles.json
  tests/functional/firefox/new/test_download.py
Labels: P1, Review: L

#7081 Remove en conditional on FxA button in global navigation (Fixes #7080)
  bedrock/base/templates/includes/protocol/navigation/index.html
Labels: P2, Review: XS

#7078 Punctuation fixes for technology/what-is-a-browser (Fixes #7032)
  bedrock/mozorg/templates/mozorg/what-is-a-browser.html
Labels: P2, Review: XS

#7069 Add send to FxA Benefits. Handle non-FxA better.
  bedrock/firefox/templates/firefox/accounts-2018.html
  media/css/firefox/accounts-2018.scss
  media/img/firefox/accounts/fxa-fxsend-high-res.png
  media/img/firefox/accounts/fxa-fxsend.png
  media/js/firefox/accounts-2018.js
  tests/functional/firefox/test_accounts.py
  tests/pages/firefox/accounts.py
Labels: Accounts Durable, P1

#7097 Adjust pre-donwload experiment percentages (Fixes #7096)
  media/js/firefox/new/newsletter/experiment.js
Labels: P1, Review: XS

#7100 Enable German locale for election page (Fixes #7099)
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
Labels: Bug :bug:, P1, Review: XS

#7073 Show whatsnew pages for Beta and Dev Edition (Fixes #7044, #7043)
  bedrock/firefox/templates/firefox/developer/whatsnew-fx68.html
  bedrock/firefox/templates/firefox/whatsnew/beta/whatsnew-fx68.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
Labels: P2, Review: S

#7048 Protocol 6.0.1
  bedrock/base/templates/base-protocol-mozilla.html
  bedrock/firefox/templates/firefox/campaign/index.html
  bedrock/firefox/templates/firefox/fights-for-you.html
  bedrock/firefox/templates/firefox/recommended.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx66.html
  bedrock/firefox/templates/firefox/windows-64-bit.html
  bedrock/foundation/templates/foundation/annualreport/2017/index.html
  bedrock/mozorg/templates/mozorg/about-2019.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/build-security.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/engage-users.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/index.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/stay-lean.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/locales.html
  bedrock/privacy/templates/privacy/email.de.html
  bedrock/privacy/templates/privacy/email.fr.html
  bedrock/privacy/templates/privacy/email.html
  media/css/firefox/accounts-2018.scss
  media/css/firefox/concerts.scss
  media/css/firefox/features/adblocker.scss
  media/css/firefox/fights-for-you.scss
  media/css/firefox/home/pre-download-newsletter-protocol.scss
  media/css/firefox/home/protocol.scss
  media/css/firefox/new/compare.scss
  media/css/firefox/new/scene2.scss
  media/css/firefox/pocket.scss
  media/css/firefox/recommended.scss
  media/css/firefox/releasenotes.scss
  media/css/firefox/releases-index.scss
  media/css/firefox/whatsnew/whatsnew-66.scss
  media/css/firefox/windows-64-bit.scss
  media/css/foundation/annual2017.scss
  media/css/mozorg/about-en.scss
  media/css/mozorg/what-is-a-browser.scss
  media/css/pebbles/components/_protocol-nav.scss
  media/css/privacy/privacy-protocol.scss
  media/css/protocol/components/_fxa-form.scss
  media/css/sandstone/protocol-nav.scss
  media/js/firefox/fights-for-you.js
  package.json
  yarn.lock
Labels: Needs Review, P2, Review: M

#7092 Update SEO page for Ad Blocker (Fixes #6879)
  bedrock/firefox/templates/firefox/features/adblocker.html
  media/css/firefox/features/adblocker.scss
  media/img/firefox/features/adblocker/content-blocking-custom-high-res.png
  media/img/firefox/features/adblocker/content-blocking-custom.png
  media/img/firefox/features/adblocker/content-blocking-high-res.png
  media/img/firefox/features/adblocker/content-blocking-title-high-res.png
  media/img/firefox/features/adblocker/content-blocking-title.png
  media/img/firefox/features/adblocker/content-blocking.png
  media/img/firefox/features/adblocker/custom-trackers-high-res.png
  media/img/firefox/features/adblocker/custom-trackers.png
  media/img/firefox/features/adblocker/dnt_screenshot-high-res.png
  media/img/firefox/features/adblocker/dnt_screenshot.png
  media/img/firefox/features/adblocker/third-party-cookies-high-res.png
  media/img/firefox/features/adblocker/third-party-cookies.png
Labels: P1, Review: S

#7098 Localize Firefox platform-specific download pages (#7056, #7057, #7058)
  bedrock/firefox/templates/firefox/new/scene1_linux.html
  bedrock/firefox/templates/firefox/new/scene1_mac.html
  bedrock/firefox/templates/firefox/new/scene1_windows.html
Labels: L10N, P2, Review: XS

#7031 [fix #6844] Don’t use Zilla Slab in Vietnamese
  media/css/l10n/vi/intl.css
Labels: P3

#7084 [fix #6779] Add Firefox Enterprise SLA
  bedrock/firefox/templates/firefox/enterprise/sla.html
  bedrock/firefox/urls.py
  media/css/firefox/enterprise-sla.scss
  media/css/firefox/fights-for-you.scss
  media/css/protocol/base/fonts/sharpsans.scss
  media/js/firefox/enterprise-sla.js
  media/static-bundles.json
Labels: P2, Review: S

#7119 Show newsletter on FF 68 /whats page for beta and dev edition (#7043)
  bedrock/firefox/views.py
Labels: Bug :bug:, Needs Review, P1, Review: XS

#7116 Update Yandex download button CTAs (Fixes #7034)
  bedrock/firefox/templates/firefox/new/yandex/base.html
  media/js/firefox/new/yandex/scene1.js
Labels: P2, Review: XS

#7120 Localize /technology/what-is-a-browser/ (#7059)
  bedrock/mozorg/templates/mozorg/what-is-a-browser.html
Labels: P2, Review: XS
