Repository mozilla/bedrock, pull requests merged in 2020-12, with the labels that each got.

#9683 Migrate /firefox platform download pages to Fluent (Fixes #9677)
  bedrock/firefox/templates/firefox/new/protocol/base.html
  bedrock/firefox/templates/firefox/new/protocol/base_download.html
  bedrock/firefox/templates/firefox/new/protocol/download_linux.html
  bedrock/firefox/templates/firefox/new/protocol/download_mac.html
  bedrock/firefox/templates/firefox/new/protocol/download_windows.html
  bedrock/firefox/urls.py
  l10n/en/firefox/new/platform.ftl
  lib/fluent_migrations/firefox/new/__init__.py
  lib/fluent_migrations/firefox/new/protocol/__init__.py
  lib/fluent_migrations/firefox/new/protocol/download.py
Labels: Needs Review, P3, Review: S

#9708 Migrate /participation/reporting/ to fluent. (#9666) [skip l10n]
  bedrock/mozorg/templates/mozorg/about/governance/policies/reporting.html
  bedrock/mozorg/urls.py
  l10n/configs/pontoon.toml
  l10n/en/mozorg/about/governance/policies/reporting.ftl
  lib/fluent_migrations/mozorg/about/governance/policies/reporting.py
Labels: Needs Review, Papercuts 💸, Review: XS

#9703 Migrate /policies/participation/ to fluent. (#9666) [skip l10n]
  bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html
  bedrock/mozorg/urls.py
  l10n/en/mozorg/about/governance/policies/participation.ftl
  lib/fluent_migrations/mozorg/about/governance/policies/participation.py
Labels: Papercuts 💸, Review: S

#9725 Unfck A/B test header for German (Fixes #9724)
  bedrock/firefox/templates/firefox/campaign/unfck/index-1.html
  bedrock/firefox/templates/firefox/campaign/unfck/index-2.html
  bedrock/firefox/templates/firefox/campaign/unfck/index.de.html
  bedrock/firefox/urls.py
  media/css/firefox/unfck-de-exp.scss
  media/img/firefox/campaign/unfck/de/exp/unfck-header-high-res.png
  media/img/firefox/campaign/unfck/de/exp/unfck-header.png
  media/js/firefox/campaign/unfck-de-experiment.js
  media/static-bundles.json
Labels: Needs Review, P1, Review: S

#9743 Update GPG pages to include new reporting email.
  bedrock/mozorg/templates/mozorg/about/governance/policies/community-hotline.html
  bedrock/mozorg/templates/mozorg/about/governance/policies/participation.html
  bedrock/mozorg/templates/mozorg/about/governance/policies/reporting.html
  l10n/en/mozorg/about/governance/policies/community-hotline.ftl
  l10n/en/mozorg/about/governance/policies/participation.ftl
  l10n/en/mozorg/about/governance/policies/reporting.ftl
Labels: Needs Review, Review: XS

#9745 Sticky promo fixes (#9721, #9728)
  bedrock/base/templates/includes/sticky-promo.html
Labels: Needs Review, P3, Review: µ

#9749 String fixes for compare/edge.ftl [fix #9748]
  l10n/en/firefox/browsers/compare/edge.ftl
Labels: Needs Review, Review: µ

#9754 Unfck landing page updates (Fixes #9747)
  bedrock/firefox/templates/firefox/campaign/unfck/index.de.html
  bedrock/firefox/templates/firefox/campaign/unfck/index.html
  media/css/firefox/unfck.scss
  media/img/firefox/campaign/unfck/en/share/fb.svg
  media/img/firefox/campaign/unfck/en/share/tw.svg
  media/img/firefox/campaign/unfck/en/still/wifi.jpg
  media/img/firefox/campaign/unfck/en/wifi-high-res.gif
  media/img/firefox/campaign/unfck/en/wifi.gif
  media/js/firefox/campaign/unfck.js
  tests/functional/firefox/test_unfck.py
  tests/pages/firefox/unfck.py
Labels: P1, Review: XS

#9776 Fix nav initialization in common-no-jquery JS bundle (Fixes #9775)
  media/static-bundles.json
Labels: Needs Review, P2, Review: µ

#9779 Update Firefox Relay in main nav, remove beta [no bug]
  bedrock/base/templates/includes/protocol/navigation/menus/products.html
  l10n/en/navigation_v2.ftl
  media/img/nav/icons/icon-relay.svg
Labels: Review: µ

#9746 Migrate /firefox/browsers/best-browser/ to Fluent (Fixes #9692)
  bedrock/firefox/templates/firefox/browsers/best-browser.html
  bedrock/firefox/urls.py
  l10n/en/firefox/browsers/best-browser.ftl
  lib/fluent_migrations/firefox/browsers/best-browser.py
Labels: P3, Review: S

#9768 Remove ARM64 UA detection for Windows downloads (Fixes #9753)
  media/css/protocol/components/_download-button.scss
  media/js/base/mozilla-utils.js
  media/js/base/site.js
  media/js/firefox/new/common/thanks.js
  tests/unit/spec/base/mozilla-utils.js
  tests/unit/spec/base/site.js
  tests/unit/spec/firefox/new/common/thanks.js
Labels: Needs Review, P3, Review: XS

#9778 Migrate /firefox/browsers/what-is-a-browser/ to Fluent (Fixes #9694)
  bedrock/firefox/templates/firefox/browsers/what-is-a-browser.html
  bedrock/firefox/urls.py
  l10n/en/firefox/browsers/history/what-is-a-browser.ftl
  lib/fluent_migrations/firefox/browsers/what-is-a-browser.py
Labels: Needs Review, P3, Review: XS

#9784 Migrate /firefox/browsers/browser-history/ to Fluent (Fixes #9693) [skip l10n]
  bedrock/firefox/templates/firefox/browsers/browser-history.html
  bedrock/firefox/urls.py
  l10n/en/firefox/browsers/history/browser-history.ftl
  lib/fluent_migrations/firefox/browsers/browser-history.py
Labels: Needs Review, P3, Review: XS

#9772 Add EOY2020 fundraising banner [fix #9765]
  bedrock/base/templates/includes/banners/fundraiser.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/views.py
  bedrock/settings/base.py
  l10n/en/banners/fundraising.ftl
Labels: Review: µ

#9789 Android native styled banners A/B test on /firefox. (#9434)
  bedrock/base/templates/includes/banners/mobile/native-android-exp.html
  bedrock/firefox/templates/firefox/home/exp/v-1.html
  bedrock/firefox/templates/firefox/home/exp/v-2.html
  bedrock/firefox/templates/firefox/home/exp/v-3.html
  bedrock/firefox/templates/firefox/home/exp/v-4.html
  bedrock/firefox/templates/firefox/home/exp/v-5.html
  bedrock/firefox/templates/firefox/home/exp/v-6.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/css/base/banners/native-android-exp.scss
  media/js/firefox/home/android-experiment.js
  media/js/firefox/home/android-native-banner-init.js
  media/static-bundles.json
Labels: Needs Review, P2, Review: S

#9798 Update header for /de/firefox/unfck/ landing page (Fixes #9797)
  bedrock/firefox/templates/firefox/campaign/unfck/index-1.html
  bedrock/firefox/templates/firefox/campaign/unfck/index-2.html
  bedrock/firefox/templates/firefox/campaign/unfck/index.de.html
  bedrock/firefox/urls.py
  media/css/firefox/unfck-de-exp.scss
  media/css/firefox/unfck.de.scss
  media/img/firefox/campaign/unfck/de/exp/unfck-header-high-res.png
  media/img/firefox/campaign/unfck/de/exp/unfck-header.png
  media/img/firefox/campaign/unfck/de/unfck-header-high-res.png
  media/img/firefox/campaign/unfck/de/unfck-header.png
  media/js/firefox/campaign/unfck-de-experiment.js
  media/static-bundles.json
Labels: Needs Review, P2, Review: XS

#9794 String fixes for feature pages and fundraising banner [fix #9802]
  bedrock/firefox/templates/firefox/features/index.html
  l10n/en/banners/fundraising.ftl
  l10n/en/firefox/features/fingerprinting.ftl
  l10n/en/firefox/features/index.ftl
  l10n/en/firefox/features/translate.ftl
  l10n/en/firefox/privacy/passwords.ftl
Labels: Needs Review, Review: XS

#9815 Fix Metropolis font for Firefox banner on home page (Fixes #9803)
  media/css/mozorg/home/home-en.scss
Labels: Needs Review, P3, Review: µ

#9813 Decommission /enterprise/signup/ page (Fixes #9788)
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/enterprise/signup-thanks.html
  bedrock/firefox/templates/firefox/enterprise/signup.html
  bedrock/firefox/urls.py
  bedrock/settings/base.py
  media/css/firefox/enterprise/signup.scss
  media/static-bundles.json
  tests/redirects/map_globalconf.py
Labels: Needs Review, P3, Papercuts 💸, Review: XS

#9793 Migrate firefox/developer pages to Fluent (Fixes #9191) [skip l10n]
  bedrock/firefox/templates/firefox/developer/firstrun.html
  bedrock/firefox/templates/firefox/developer/includes/alt-newsletter.html
  bedrock/firefox/templates/firefox/developer/includes/engage.html
  bedrock/firefox/templates/firefox/developer/includes/features.html
  bedrock/firefox/templates/firefox/developer/includes/for-developers.html
  bedrock/firefox/templates/firefox/developer/includes/highlights.html
  bedrock/firefox/templates/firefox/developer/includes/intro-features.html
  bedrock/firefox/templates/firefox/developer/includes/nightly.html
  bedrock/firefox/templates/firefox/developer/includes/performance.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/developer/whatsnew.html
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  l10n/en/firefox/developer.ftl
  lib/fluent_migrations/firefox/developer/__init__.py
  lib/fluent_migrations/firefox/developer/index.py
Labels: Needs Review, P3, Review: XS

#9799 Decommission /grants pages and redirect to /moss (Fixes #9254)
  bedrock/grants/__init__.py
  bedrock/grants/grants_db.py
  bedrock/grants/models.py
  bedrock/grants/templates/grants/base.html
  bedrock/grants/templates/grants/index.html
  bedrock/grants/templates/grants/info.html
  bedrock/grants/templates/grants/reports/gnome-haeger-report.html
  bedrock/grants/templates/grants/reports/ushahidi-chile-report.html
  bedrock/grants/tests/__init__.py
  bedrock/grants/tests/test_base.py
  bedrock/grants/urls.py
  bedrock/grants/views.py
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/about/history.html
  bedrock/settings/base.py
  bedrock/sitemaps/utils.py
  bedrock/urls.py
  media/css/grants/grants.scss
  media/static-bundles.json
  tests/redirects/map_globalconf.py
Labels: Needs Review, P3, Review: XS

#9822 Fix sub navigation on iOS devices (Fixes #9821)
  media/js/base/protocol/protocol-sub-navigation.js
Labels: Needs Review, P2, Review: µ

#9820 Misc Fluent string fixes
  bedrock/firefox/templates/firefox/developer/includes/highlights.html
  bedrock/firefox/templates/firefox/features/private-browsing.html
  l10n/en/firefox/features/private-browsing.ftl
Labels: Needs Review, P3, Review: µ

#9817 Remove legacy /firefox Quantum home page template (Fixes #9816)
  bedrock/firefox/templates/firefox/features/private-browsing.html
  bedrock/firefox/templates/firefox/home/index-quantum.html
  bedrock/firefox/templates/firefox/installer-help-redesign.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/css/firefox/home/ie9.scss
  media/css/firefox/home/quantum.scss
  media/img/firefox/home/quantum/desktop-account.svg
  media/img/firefox/home/quantum/desktop-change-high-res.png
  media/img/firefox/home/quantum/desktop-change.png
  media/img/firefox/home/quantum/desktop-smooth.svg
  media/img/firefox/home/quantum/icon-extensions.svg
  media/img/firefox/home/quantum/icon-faster.svg
  media/img/firefox/home/quantum/icon-private.svg
  media/img/firefox/home/quantum/icon-theme.svg
  media/img/firefox/home/quantum/icon-toolbar.svg
  media/img/firefox/home/quantum/icon-tracking.svg
  media/img/firefox/home/quantum/product-bg-rtl.svg
  media/img/firefox/home/quantum/product-bg.svg
  media/img/firefox/home/quantum/product.svg
  media/img/firefox/home/quantum/quantum-vs-chrome-poster.png
  media/img/firefox/home/quantum/spacer.gif
  media/img/firefox/home/quantum/wave.svg
  media/js/firefox/home/quantum.js
  media/js/libs/jquery.waypoints.min.js
  media/static-bundles.json
Labels: Needs Review, P3, Review: XS
