Repository mozilla/bedrock, pull requests merged in 2020-05, with the labels that each got.

#8865 Remove nav from /new exp page #8773
  bedrock/exp/templates/exp/firefox/new/download.html
  bedrock/exp/views.py
Labels: Needs Review, P3, Review: µ

#8883 Fix /exp/ home page error for some locales (Fixes #8882)
  bedrock/exp/views.py
Labels: Needs Review, P2, Review: µ

#8857 Fix typos in French hard-coded /welcome /whatsnew pages (Fixes #8746)
  bedrock/firefox/templates/firefox/welcome/page7.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx74.html
Labels: Needs Review, P2, Review: XS

#8856 Remove locale from hreflang x-default (Fixes #8513)
  bedrock/base/templates/includes/canonical-url.html
Labels: Needs Review, P2, Review: µ

#8858 Fix newsletter form submission on /channel page (Fixes #8690)
  media/static-bundles.json
Labels: Needs Review, P2, Review: µ

#8869 Remove screenshotgo pages (fixes #8619)
  bedrock/legal/templates/legal/terms/firefox-screenshotgo.html
  bedrock/legal/urls.py
  bedrock/privacy/templates/privacy/notices/firefox-screenshotgo.html
  bedrock/privacy/urls.py
  bedrock/privacy/views.py
Labels: Needs Review, P3, Review: µ

#8887 Remove social proof experiment on release notes.
  bedrock/firefox/templates/firefox/releases/notes.html
  bedrock/releasenotes/views.py
  media/css/firefox/releasenotes.scss
  media/js/firefox/social-proof-experiment.js
  media/static-bundles.json
Labels: Review: XS

#8889 Add functional tests for releasenotes pages (Fixes #7388)
  bedrock/firefox/templates/firefox/releases/aurora-notes.html
  bedrock/firefox/templates/firefox/releases/beta-notes.html
  bedrock/firefox/templates/firefox/releases/dev-browser-notes.html
  bedrock/firefox/templates/firefox/releases/esr-notes.html
  bedrock/firefox/templates/firefox/releases/nightly-notes.html
  bedrock/firefox/templates/firefox/releases/notes.html
  bedrock/firefox/templates/firefox/releases/release-notes.html
  tests/functional/firefox/test_releasenotes.py
  tests/pages/firefox/releasenotes.py
Labels: Needs Review, P3, Review: S

#8888 [no bug] Update newsletter form subtitle and description
  bedrock/exp/templates/exp/home/home-de.html
  bedrock/exp/templates/exp/home/home-en.html
  bedrock/exp/templates/exp/home/home-fr.html
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/firefox/templates/firefox/developer/includes/alt-newsletter.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/retention/thank-you.html
  bedrock/foundation/templates/foundation/annualreport/2009/base.html
  bedrock/foundation/templates/foundation/annualreport/2010/base.html
  bedrock/foundation/templates/foundation/base.html
  bedrock/legal/templates/legal/index.html
  bedrock/mozorg/templates/mozorg/about-base.html
  bedrock/mozorg/templates/mozorg/about.html
  bedrock/mozorg/templates/mozorg/about/manifesto.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/templates/mozorg/internet-health/decentralization.html
  bedrock/mozorg/templates/mozorg/internet-health/digital-inclusion.html
  bedrock/mozorg/templates/mozorg/internet-health/open-innovation.html
  bedrock/mozorg/templates/mozorg/internet-health/privacy-security.html
  bedrock/mozorg/templates/mozorg/internet-health/web-literacy.html
  bedrock/mozorg/templates/mozorg/mission.html
  bedrock/mozorg/templates/mozorg/moss/base.html
  bedrock/newsletter/templates/newsletter/includes/form-protocol.html
  bedrock/newsletter/templates/newsletter/includes/form.html
  bedrock/newsletter/templates/newsletter/index.html
  bedrock/newsletter/templatetags/helpers.py
  media/css/protocol/protocol.scss
Labels: Review: XS

#8885 Add functional tests for Facebook Container page (Fixes #8588)
  tests/functional/firefox/test_facebook_container.py
  tests/pages/firefox/facebook_container.py
Labels: Needs Review, P3, Review: XS

#8894 Remove GA from legacy privacy/firefox template (Fixes #8891)
  bedrock/privacy/templates/privacy/notices/firefox-old-style-notice.html
  bedrock/privacy/templates/privacy/notices/firefox.html
  bedrock/privacy/views.py
Labels: P2, Review: µ

#8842 Remove mozilla-modal.js script
  media/css/pebbles/components/_modal.scss
  media/js/base/mozilla-modal.js
  media/js/firefox/new/trailhead/join-modal.js
  media/static-bundles.json
Labels: Needs Review, P3, Review: µ

#8881 Add functional test for firefox/campaign/ page (Fixes #8631)
  tests/functional/firefox/test_campaign.py
  tests/pages/firefox/campaign.py
Labels: Needs Review, P3, Review: µ

#8866 welcome 8 [Fixes: #8839]
  bedrock/firefox/templates/firefox/welcome/page8.html
  bedrock/firefox/urls.py
  media/css/firefox/welcome.scss
  media/js/firefox/welcome/welcome8.js
  media/static-bundles.json
Labels: Needs Review, P1, Review: S

#8898 Remove /thanks variant. (fixes #8897)
  bedrock/firefox/templates/firefox/new/trailhead/thanks-b.html
  bedrock/firefox/views.py
  media/css/firefox/new/trailhead/thanks-b.scss
  media/img/firefox/new/trailhead/browser-modal.png
  media/img/firefox/new/trailhead/browser-status-bar.png
  media/static-bundles.json
Labels: Review: XS

#8896 [fix #6994] Redesigned contribute page
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/contribute/contribute-2020.html
  bedrock/mozorg/templates/mozorg/contribute/contribute-base.html
  bedrock/mozorg/templates/mozorg/contribute/index.html
  bedrock/mozorg/templates/mozorg/contribute/stories-base.html
  bedrock/mozorg/templates/mozorg/contribute/stories.html
  bedrock/mozorg/templates/mozorg/contribute/story-faye.html
  bedrock/mozorg/templates/mozorg/contribute/story-michael.html
  bedrock/mozorg/templates/mozorg/contribute/story-ruben.html
  bedrock/mozorg/templates/mozorg/contribute/story-shreyas.html
  bedrock/mozorg/tests/test_views.py
  bedrock/mozorg/urls.py
  bedrock/mozorg/views.py
  media/css/mozorg/contribute/contribute-2020.scss
  media/img/contribute/contribute-banner-gethelp-icon.svg
  media/img/contribute/contribute-card-community-lg.png
  media/img/contribute/contribute-card-community.png
  media/img/contribute/contribute-card-contribute-lg.png
  media/img/contribute/contribute-card-contribute.png
  media/img/contribute/contribute-card-support-lg.png
  media/img/contribute/contribute-card-support.png
  media/img/contribute/contribute-card-translate-lg.png
  media/img/contribute/contribute-card-translate.png
  media/img/contribute/contribute-gethelp-banner-bg.jpg
  media/img/contribute/contribute-hero-composition.jpg
  media/img/contribute/contribute-madeby-feature.jpg
  media/img/contribute/contribute-problems-banner-bg.png
  media/img/contribute/contribute-problems-bulb.svg
  media/img/contribute/contribute-problems-fly.svg
  media/img/contribute/icon/M.svg
  media/img/contribute/icon/cal.svg
  media/img/contribute/icon/heart.svg
  media/img/contribute/icon/twitter.svg
  media/img/contribute/newsletter-high-res.png
  media/img/contribute/newsletter.png
  media/img/contribute/person-faye.jpg
  media/img/contribute/person-michael.jpg
  media/img/contribute/person-ruben.jpg
  media/img/contribute/person-shreyas.jpg
  media/static-bundles.json
  tests/functional/contribute/test_contribute.py
  tests/redirects/map_globalconf.py
Labels: Review: S

#8871 Update functional tests for /welcome pages (Fixes #8687)
  bedrock/firefox/templates/firefox/welcome/page6.html
  media/js/firefox/welcome/welcome4.js
  media/js/firefox/welcome/welcome5.js
  media/js/firefox/welcome/welcome6.js
  media/static-bundles.json
  tests/functional/firefox/welcome/test_welcome_page1.py
  tests/functional/firefox/welcome/test_welcome_page2.py
  tests/functional/firefox/welcome/test_welcome_page3.py
  tests/functional/firefox/welcome/test_welcome_page4.py
  tests/functional/firefox/welcome/test_welcome_page5.py
  tests/functional/firefox/welcome/test_welcome_page6.py
  tests/functional/firefox/welcome/test_welcome_page7.py
  tests/functional/firefox/welcome/test_welcome_page8.py
  tests/pages/firefox/welcome/page5.py
  tests/pages/firefox/welcome/page6.py
  tests/pages/firefox/welcome/page7.py
  tests/pages/firefox/welcome/page8.py
Labels: Needs Review, P3, Review: XS

#8913 Typo on FR homepage (Fix #8912)
  bedrock/mozorg/templates/mozorg/home/home-fr.html
Labels: Needs Review, P3, Review: µ

#8732 Integrate FxA product button JS with China repack logic (Fixes #8328)
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  media/js/base/base-page-init.js
  media/js/base/mozilla-fxa-product-button.js
  media/js/base/mozilla-utils.js
  tests/unit/spec/base/mozilla-fxa-product-button.js
  tests/unit/spec/base/mozilla-utils.js
Labels: P3, Review: M

#8921 [no bug] Leadership, correction to Seligman’s bio
  bedrock/mozorg/templates/mozorg/about/leadership.html
Labels: Needs Review, Review: µ

#8849 Remove mozilla-fxa-form.scss (Fixes #8848)
  docs/firefox-accounts.rst
  media/css/base/mozilla-fxa-form.scss
  media/css/firefox/accounts-2019.scss
  media/css/firefox/firstrun/firstrun.scss
  media/static-bundles.json
Labels: Needs Review, P3, Review: XS

#8873 Add platform download page tests (Fixes #8604)
  tests/functional/firefox/new/test_platform.py
  tests/pages/firefox/new/platform.py
Labels: Needs Review, P3, Review: XS

#8892 Add functional test for legacy /firstrun page (Fixes #8890)
  tests/functional/firefox/test_firstrun.py
  tests/pages/firefox/firstrun.py
Labels: Needs Review, P3, Review: µ

#8893 Add functional test for Manifesto page (Fixes #8589)
  tests/functional/test_manifesto.py
  tests/pages/manifesto.py
Labels: Needs Review, P3, Review: µ

#8924 [fix #8836] Add whatsnew 77
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx77.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-77.scss
  media/img/firefox/whatsnew/whatsnew77/pip-cook.svg
  media/img/firefox/whatsnew/whatsnew77/pip-entertain.svg
  media/img/firefox/whatsnew/whatsnew77/pip-icon.svg
  media/img/firefox/whatsnew/whatsnew77/pip-lecture.svg
  media/img/firefox/whatsnew/whatsnew77/video-poster.jpg
  media/js/firefox/whatsnew/whatsnew-77.js
  media/static-bundles.json
Labels: Review: S

#8785 Migrate firefox/all to Fluent (Fixes #8511)
  bedrock/base/templates/product-all-unified-macros.html
  bedrock/firefox/firefox_details.py
  bedrock/firefox/templates/firefox/all-unified.html
  bedrock/firefox/views.py
  l10n/en/firefox/all.ftl
  lib/fluent_migrations/firefox/all-unified.py
Labels: P1, Review: S

#8803 Migrate /firefox/new/ and /thanks/ to Fluent (Fixes #8510)
  bedrock/firefox/templates/firefox/new/trailhead/base.html
  bedrock/firefox/templates/firefox/new/trailhead/download-yandex.html
  bedrock/firefox/templates/firefox/new/trailhead/download.html
  bedrock/firefox/templates/firefox/new/trailhead/thanks.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  l10n/en/firefox/new/download.ftl
  lib/fluent_migrations/firefox/new.py
Labels: P1

#8904 Add H2 2019 Transparency Report (Fixes #8870)
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2019.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2019.html
  bedrock/mozorg/urls.py
Labels: P1, Review: XS

#8939 Port installer-help page to Fluent (Fixes #8916)
  bedrock/firefox/templates/firefox/installer-help-redesign.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  l10n/en-US/firefox/installer-help.ftl
  l10n/en/firefox/installer-help.ftl
Labels: P1, Review: XS

#8901 Add firefox/mobile send-to-device experiment. (fixes #8899)
  bedrock/firefox/templates/firefox/mobile/index.html
  bedrock/firefox/urls.py
  media/css/firefox/mobile/mobile.scss
  media/js/firefox/mobile/experiment-mobile.js
  media/static-bundles.json
  tests/functional/firefox/test_mobile.py
Labels: Review: S
