Repository mozilla/bedrock, pull requests merged in 2020-03, with the labels that each got.

#8625 Upgrade Jinja2 to latest version
  requirements/base.txt
Labels: dependencies

#8627 [fix #8610] Leadership updates
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/dana-bennett-high-res.jpg
  media/img/mozorg/about/leadership/dana-bennett.jpg
  media/img/mozorg/about/leadership/jascha-kaykas-wolff-high-res.jpg
  media/img/mozorg/about/leadership/jascha-kaykas-wolff.jpg
Labels: Needs Review, Review: µ

#8541 Update notifications to use notification component (Fixes #7615)
  bedrock/exp/templates/exp/firefox/whatsnew/whatsnew-fx71.html
  bedrock/firefox/templates/firefox/new/trailhead/thanks.html
  bedrock/firefox/templates/firefox/nightly_whatsnew.html
  bedrock/firefox/templates/firefox/whatsnew/index.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx71.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx73.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx74.html
  media/css/exp/firefox/whatsnew/whatsnew-71.scss
  media/css/firefox/new/trailhead/thanks.scss
  media/css/firefox/whatsnew/includes/_header.scss
  media/css/firefox/whatsnew/whatsnew-70.scss
  media/css/firefox/whatsnew/whatsnew-71.scss
  media/css/firefox/whatsnew/whatsnew-73.scss
  media/css/firefox/whatsnew/whatsnew-74.scss
  media/css/firefox/whatsnew/whatsnew-account.scss
  media/css/firefox/whatsnew/whatsnew-nightly.scss
  media/css/firefox/whatsnew/whatsnew.scss
  media/css/protocol/protocol.scss
Labels: Needs Review, P3, Review: S

#8605 Make fundraising banner a more permanent feature (Fixes #7185)
  bedrock/base/templates/base-pebbles.html
  bedrock/base/templates/includes/banners/base.html
  bedrock/base/templates/includes/banners/fundraiser.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/templates/mozorg/home/includes/fundraiser.html
  docs/banners.rst
  docs/index.rst
  docs/l10n.rst
  media/css/base/banners/fundraiser.scss
  media/css/base/banners/includes/_base.scss
  media/js/base/mozilla-banner.js
  media/js/mozorg/home/banner-init.js
  media/js/mozorg/home/fundraiser.js
  media/static-bundles.json
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-banner.js
Labels: Needs Review, P3, Review: S

#8632 [fix #8629] fall back to WNP73 content for zh-CN
  bedrock/firefox/views.py
Labels: Needs Review, Review: µ

#8611 Use brand terms in firefox/switch Fluent migration (Fixes #8595)
  bedrock/firefox/templates/firefox/switch.html
  docs/fluent-conversion.rst
  l10n/en/brands.ftl
  l10n/en/firefox/switch-en.ftl
  l10n/en/firefox/switch.ftl
  lib/fluent_migrations/firefox/switch.py
Labels: L10N, Needs Review

#8633 Decommission /styleguide/ page (Fixes #8418)
  bedrock/legal/redirects.py
  bedrock/mozorg/redirects.py
  bedrock/settings/base.py
  bedrock/styleguide/__init__.py
  bedrock/styleguide/models.py
  bedrock/styleguide/redirects.py
  bedrock/styleguide/templates/styleguide/index.html
  bedrock/styleguide/urls.py
  bedrock/urls.py
  media/css/styleguide/styleguide.scss
  media/static-bundles.json
  tests/redirects/map_globalconf.py
Labels: Needs Review, P3, Review: XS

#8518 Error page updates [Fixes: #8407]
  bedrock/base/templates/404.html
  bedrock/base/templates/500.html
  bedrock/base/templates/base-error.html
  bedrock/base/views.py
  bedrock/urls.py
  media/css/base/page-not-found.scss
  media/img/base-error/firefox_logomark_black.svg
  media/img/co-brand/firefox_moz_co-brand_sm-high-res.png
  media/img/co-brand/firefox_moz_co-brand_sm.png
  media/js/base/error-pages.js
  media/static-bundles.json
  tests/functional/test_not_found.py
  tests/pages/not_found.py
Labels: P2, Review: S

#8646 Add experiment GitHub template.
  .github/ISSUE_TEMPLATE/experiment.md
Labels: Review: µ

#8642 Decommission /technology landing page (Fixes #6824)
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/developer/includes/sub-nav.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/templates/mozorg/technology-en.html
  bedrock/mozorg/templates/mozorg/technology.html
  bedrock/mozorg/tests/test_views.py
  bedrock/mozorg/urls.py
  bedrock/mozorg/views.py
  media/css/mozorg/technology.scss
  media/img/mozorg/technology/context-graph.svg
  media/img/mozorg/technology/emily-aaron-desktop-high-res.png
  media/img/mozorg/technology/emily-aaron-desktop.png
  media/img/mozorg/technology/emily-aaron-high-res.png
  media/img/mozorg/technology/emily-aaron-tablet-high-res.png
  media/img/mozorg/technology/emily-aaron-tablet.png
  media/img/mozorg/technology/emily-aaron.png
  media/img/mozorg/technology/gaming-background.svg
  media/img/mozorg/technology/gaming-yeti.svg
  media/img/mozorg/technology/icon-rust-hero.svg
  media/img/mozorg/technology/icon-video-play.svg
  media/img/mozorg/technology/iot.svg
  media/img/mozorg/technology/quantum.svg
  media/img/mozorg/technology/rust.svg
  media/img/mozorg/technology/shapes.svg
  media/img/mozorg/technology/vr-header.svg
  media/img/mozorg/technology/webvr-high-res.png
  media/img/mozorg/technology/webvr.png
  media/js/mozorg/technology.js
  media/static-bundles.json
  tests/functional/test_technology.py
  tests/pages/technology.py
  tests/redirects/map_globalconf.py
Labels: Needs Review, P3, Review: XS

#8649 Switch Fluent configs over to Pontoon (Fixes #8648)
  l10n/configs/pontoon.toml
  l10n/configs/vendor.toml
Labels: L10N

#8669 Remove /firefox/campaign/ fallback template (Fixes #8667)
  bedrock/firefox/templates/firefox/campaign/index-trailhead.html
  bedrock/firefox/templates/firefox/campaign/index.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  media/css/firefox/campaign/campaign.scss
  media/img/firefox/quantum/icon-faster.svg
  media/img/firefox/quantum/icon-lighter.svg
  media/img/firefox/quantum/icon-private.svg
  media/img/firefox/quantum/wave.svg
  media/static-bundles.json
Labels: P3, Papercuts 💸, Review: XS

#8673 [fix #8564] Add whatsnew page for Firefox 75
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx75.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-75.scss
  media/img/firefox/whatsnew/whatsnew75/hero-monitor.svg
  media/img/firefox/whatsnew/whatsnew75/hero-sync.svg
  media/img/icons/email-pink.svg
  media/img/icons/history-pink.svg
  media/img/icons/key-orange.svg
  media/img/icons/sendtabs-purple.svg
  media/img/icons/tracking-protection.svg
  media/img/icons/warning-blue.svg
  media/js/firefox/whatsnew/whatsnew-75.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_75.py
  tests/pages/firefox/whatsnew/whatsnew_75.py
Labels: Needs Review, Review: S

#8678 Add download call-out to bottom of /system-requirements (#8647)
  bedrock/firefox/templates/firefox/releases/system_requirements.html
  media/css/firefox/system-requirements.scss
Labels: Review: XS

#8665 Migrate navigation.lang to Fluent (Fixes #8653)
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/about.html
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/browsers.html
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/index.html
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/join.html
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/products.html
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/about.html
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/developers.html
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/firefox.html
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/index.html
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/projects.html
  bedrock/base/templates/includes/protocol/navigation/nav-cta.html
  bedrock/settings/base.py
  l10n/en/brands.ftl
  l10n/en/navigation.ftl
  lib/fluent_migrations/includes/__init__.py
  lib/fluent_migrations/includes/protocol/__init__.py
  lib/fluent_migrations/includes/protocol/navigation/__init__.py
  lib/fluent_migrations/includes/protocol/navigation/navigation.py
  lib/l10n_utils/__init__.py
  lib/l10n_utils/tests/test_template.py
Labels: L10N, Needs Review, P2, Review: S

#8679 [#8564] WNP75, hide signed-in content when signed out
  media/css/firefox/whatsnew/whatsnew-75.scss
Labels: Needs Review, Review: µ

#8655 Moments 6 [fixes 8569]
  bedrock/firefox/templates/firefox/welcome/page6.html
  bedrock/firefox/urls.py
  media/css/firefox/welcome.scss
Labels: P1, Review: S

#8689 Migrate footer to Fluent (Fixes #8663)
  bedrock/base/templates/includes/protocol/footer/firefox.html
  bedrock/base/templates/includes/protocol/footer/mozilla.html
  bedrock/base/templates/includes/protocol/lang-switcher.html
  bedrock/settings/base.py
  l10n/en/footer.ftl
  l10n/en/navigation.ftl
  lib/fluent_migrations/includes/protocol/footer/__init__.py
  lib/fluent_migrations/includes/protocol/footer/footer.py
Labels: Needs Review, P2, Review: S

#8640 Decommission Firefox /recommended/ and /dedicated-profiles/ pages (Fixes #8419, #8420)
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/dedicated-profiles.html
  bedrock/firefox/templates/firefox/recommended.html
  bedrock/firefox/urls.py
  media/css/firefox/recommended.scss
  media/img/firefox/recommended/hero-laptop-high-res.png
  media/img/firefox/recommended/hero-laptop.png
  media/img/firefox/recommended/icon-faster.svg
  media/img/firefox/recommended/icon-lighter.svg
  media/img/firefox/recommended/icon-private.svg
  media/static-bundles.json
  tests/redirects/map_globalconf.py
Labels: Needs Review, P3, Review: XS

#8694 [#8419] Delete obsolete tests
  tests/functional/firefox/test_recommended.py
  tests/pages/firefox/recommended.py
Labels: Bug :bug:, Needs Review, Review: µ

#8693 Remove Chris Beard and Michael DeAngelo from legal/impressum [no bug]
  bedrock/legal/templates/legal/impressum.html
Labels: Review: µ

#8638 Only show nightly or dev edition CTA when appropriate channel (Fixes #8579)
  bedrock/firefox/views.py
Labels: Review: XS

#8671 welcome page 7
  bedrock/firefox/templates/firefox/welcome/page6.html
  bedrock/firefox/templates/firefox/welcome/page7.html
  bedrock/firefox/urls.py
  media/css/firefox/welcome.scss
Labels: Needs Review, P1, Review: S

#8700 [#8564] Update WNP75 state logic
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx75.html
  media/css/firefox/whatsnew/whatsnew-75.scss
  media/js/firefox/whatsnew/whatsnew-75.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_75.py
  tests/pages/firefox/whatsnew/whatsnew_75.py
Labels: P1, Review: XS

#8708 Fix moco and mofo footer links (Fixes #8707)
  bedrock/base/templates/includes/protocol/footer/firefox.html
  bedrock/base/templates/includes/protocol/footer/mozilla.html
Labels: Needs Review, P2, Review: µ

#8699 Migrate download_button.lang to Fluent (Fixes #8654)
  bedrock/base/templates/base-pebbles.html
  bedrock/base/templates/includes/protocol/navigation/nav-cta.html
  bedrock/base/templates/includes/sub-nav.html
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/all-unified.html
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/campaign/index.html
  bedrock/firefox/templates/firefox/compare/chrome.html
  bedrock/firefox/templates/firefox/compare/edge.html
  bedrock/firefox/templates/firefox/compare/ie.html
  bedrock/firefox/templates/firefox/compare/opera.html
  bedrock/firefox/templates/firefox/compare/safari.html
  bedrock/firefox/templates/firefox/facebookcontainer/index.html
  bedrock/firefox/templates/firefox/home/index-quantum.html
  bedrock/firefox/templates/firefox/includes/download-button.html
  bedrock/firefox/templates/firefox/lockwise/lockwise.html
  bedrock/firefox/templates/firefox/mobile/get-app.html
  bedrock/firefox/templates/firefox/mobile/index.html
  bedrock/firefox/templates/firefox/new/protocol/base_download.html
  bedrock/firefox/templates/firefox/new/protocol/thanks.html
  bedrock/firefox/templates/firefox/new/trailhead/download.html
  bedrock/firefox/templates/firefox/releases/release-notes.html
  bedrock/firefox/templates/firefox/releases/system_requirements.html
  bedrock/firefox/templates/firefox/set-as-default/thanks.html
  bedrock/firefox/templates/firefox/welcome/page4.html
  bedrock/firefox/templates/firefox/welcome/page5.html
  bedrock/firefox/templates/firefox/welcome/page6.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx73.html
  bedrock/firefox/templatetags/helpers.py
  bedrock/firefox/tests/test_helpers.py
  bedrock/settings/base.py
  l10n/en/brands.ftl
  l10n/en/download_button.ftl
  lib/fluent_migrations/firefox/includes/__init__.py
  lib/fluent_migrations/firefox/includes/download-button.py
Labels: P1, Review: S

#8628 Convert FxA macro buttons to python helpers (Fixes #8185)
  bedrock/base/templates/includes/protocol/footer/firefox.html
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/index.html
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/join.html
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/index.html
  bedrock/base/templates/includes/protocol/navigation/nav-cta.html
  bedrock/base/templates/macros.html
  bedrock/exp/templates/exp/firefox/accounts-2019.html
  bedrock/exp/templates/exp/firefox/index.de.html
  bedrock/exp/templates/exp/firefox/index.html
  bedrock/exp/templates/exp/firefox/whatsnew/whatsnew-fx71.html
  bedrock/firefox/templates/firefox/accounts-2019.html
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/firstrun/firstrun.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/privacy/index.html
  bedrock/firefox/templates/firefox/privacy/products.html
  bedrock/firefox/templates/firefox/products/index.html
  bedrock/firefox/templates/firefox/welcome/page3.html
  bedrock/firefox/templates/firefox/whatsnew/index-account.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx71.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  docs/firefox-accounts.rst
  media/js/base/mozilla-fxa-product-button.js
  media/static-bundles.json
  tests/pages/firefox/accounts.py
  tests/unit/spec/base/mozilla-fxa-product-button.js
Labels: P2, Review: M

#8722 [fix #8578] Update Enterprise downloads section
  bedrock/firefox/templates/firefox/enterprise/index.html
  media/css/firefox/enterprise/landing.scss
  media/img/firefox/enterprise/icon-documentation.svg
  media/img/firefox/enterprise/icon-faq.svg
  media/img/firefox/enterprise/icon-notes.svg
  media/js/firefox/enterprise/landing.js
  tests/functional/firefox/test_enterprise.py
  tests/pages/firefox/enterprise/landing.py
Labels: Review: S
