Repository mozilla/bedrock, pull requests merged in 2020-06, with the labels that each got.

#8955 [no bug] WNP77, use self-hosted video for zh-CN
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx77.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-77.scss
  media/js/firefox/whatsnew/whatsnew-77-zhCN.js
  media/static-bundles.json
Labels: P1, Review: XS

#8965 [fix #8951] Leadership page updates, June 1
  bedrock/mozorg/templates/mozorg/about/leadership.html
Labels: Needs Review, P1, Review: µ

#8954 Turn CTA links into buttons on /firefox and /browsers (Fixes #8950)
  media/css/firefox/browsers-products.scss
  media/css/firefox/enterprise/landing.scss
  media/css/firefox/home/master.scss
  media/css/protocol/components/_custom-menu-list.scss
Labels: Needs Review, Review: XS

#8982 Lazy load smaller icons in Firefox products nav menu (Fix #8981)
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/join.html
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/products.html
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/developers.html
  bedrock/base/templates/includes/protocol/navigation/menu-mozilla/firefox.html
Labels: P3, Review: XS

#8990 Remove MOSS Covid fund banner (Fixes #8984)
  bedrock/base/templates/includes/banners/moss-covid.html
  bedrock/mozorg/templates/mozorg/moss/base.html
  media/css/base/banners/moss-covid.scss
  media/img/mozorg/moss/covid-banner-bg.jpg
  media/js/mozorg/moss-covid-banner-init.js
  media/static-bundles.json
Labels: Needs Review, P3, Review: µ

#8953 Remove autofill from /switch page (Fixes #8651)
  bedrock/firefox/templates/firefox/switch.html
  bedrock/firefox/urls.py
  l10n/en/firefox/switch.ftl
Labels: Needs Review, P3, Review: XS

#8998 Remove Pebbles send-to-device CSS files
  media/css/firefox/whatsnew/send-to-device.scss
Labels: Needs Review, P3, Review: µ

#8980 Migrate /firefox/accounts to Fluent (#8968)
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  l10n/en/firefox/accounts.ftl
  lib/fluent_migrations/firefox/accounts-2019.py
Labels: Needs Review, P2, Review: XS

#8977 Add vanity redirect for donate.mozilla.org (Fixes #8949)
  bedrock/mozorg/redirects.py
  tests/redirects/map_globalconf.py
Labels: Needs Review, P3, Review: µ

#8928 Add firefox mobile banner to /firefox/new/ (Fixes #8829)
  bedrock/base/templates/includes/banners/base.html
  bedrock/base/templates/includes/banners/fundraiser.html
  bedrock/base/templates/includes/banners/mobile/firefox-android.html
  bedrock/base/templates/includes/banners/mobile/firefox-ios.html
  bedrock/firefox/templates/firefox/new/trailhead/download.html
  bedrock/firefox/views.py
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/moss/base.html
  l10n/en/banners/firefox-mobile.ftl
  media/css/base/banners/firefox-mobile.scss
  media/css/base/banners/includes/_base.scss
  media/img/banners/mobile/background.svg
  media/js/base/banners/firefox-mobile-banner-init.js
  media/js/base/banners/mozilla-banner.js
  media/static-bundles.json
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-banner.js
Labels: P2, Review: XS

#8974 Migrate /firefox to Fluent (#8968)
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  l10n/en/firefox/home.ftl
  lib/fluent_migrations/firefox/home/__init__.py
  lib/fluent_migrations/firefox/home/index-master.py
Labels: P2, Review: XS

#8988 Migrate firefox/browsers to Fluent (#8968)
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/urls.py
  l10n/en/brands.ftl
  l10n/en/firefox/browsers.ftl
  lib/fluent_migrations/firefox/browsers/__init__.py
  lib/fluent_migrations/firefox/browsers/index.py
Labels: P2, Review: XS

#9020 Change terminology for allowed and disallowed entities
  bedrock/firefox/tests/test_views.py
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/about/governance/policies/policies.html
  bedrock/mozorg/templates/mozorg/about/governance/policies/security/plugin-whitelist-policy.html
  bedrock/mozorg/templates/mozorg/about/governance/policies/security/tld-idn.html
  bedrock/mozorg/urls.py
  bedrock/privacy/templates/privacy/archive/firefox-2006-10.html
  bedrock/privacy/templates/privacy/archive/firefox-2008-06.html
  bedrock/privacy/templates/privacy/archive/firefox-2009-01.html
  bedrock/privacy/templates/privacy/archive/firefox-2010-01.html
  bedrock/privacy/templates/privacy/archive/firefox-2010-12.html
  bedrock/privacy/templates/privacy/archive/firefox-2011-06.html
  bedrock/privacy/templates/privacy/archive/firefox-2012-06.html
  bedrock/privacy/templates/privacy/archive/firefox-2012-09.html
  bedrock/privacy/templates/privacy/archive/firefox-2012-12.html
  bedrock/privacy/templates/privacy/archive/firefox-2013-05.html
  docs/uitour.rst
  media/dnt/dnt-enabler.tpl
  media/js/base/core-datalayer-init.js
  media/js/base/fxa-utm-referral.js
  media/js/base/mozilla-fxa-product-button.js
  tests/redirects/map_globalconf.py
  tests/unit/spec/base/fxa-utm-referral.js
Labels: Do Not Merge :warning:

#8952 Add communication promise string to Firefox newsletters (Fixes #7460)
  bedrock/newsletter/templates/newsletter/includes/form-protocol.html
  bedrock/newsletter/templates/newsletter/includes/form.html
  l10n/en/newsletter_form.ftl
  media/css/firefox/channel.scss
Labels: P3, Review: XS

#9022 Update CONTRIBUTING.md with good-first-bug links (Fixes #8992)
  .github/CONTRIBUTING.md
  README.md
Labels: Needs Review, P3, Review: µ

#8958 Update and relaunch browser comparison pages
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/browsers/compare/brave.html
  bedrock/firefox/templates/firefox/browsers/compare/chrome.html
  bedrock/firefox/templates/firefox/browsers/compare/edge.html
  bedrock/firefox/templates/firefox/browsers/compare/ie.html
  bedrock/firefox/templates/firefox/browsers/compare/includes/download-menu-list.html
  bedrock/firefox/templates/firefox/browsers/compare/includes/subnav.html
  bedrock/firefox/templates/firefox/browsers/compare/index.html
  bedrock/firefox/templates/firefox/browsers/compare/opera.html
  bedrock/firefox/templates/firefox/browsers/compare/safari.html
  bedrock/firefox/templates/firefox/compare/chrome.html
  bedrock/firefox/templates/firefox/compare/ie.html
  bedrock/firefox/templates/firefox/compare/includes/subnav.html
  bedrock/firefox/templates/firefox/compare/index.html
  bedrock/firefox/templates/firefox/compare/opera.html
  bedrock/firefox/templates/firefox/compare/safari.html
  bedrock/firefox/urls.py
  docs/fluent-conversion.rst
  l10n/en/firefox/browsers/compare/brave.ftl
  l10n/en/firefox/browsers/compare/chrome.ftl
  l10n/en/firefox/browsers/compare/edge.ftl
  l10n/en/firefox/browsers/compare/ie.ftl
  l10n/en/firefox/browsers/compare/index.ftl
  l10n/en/firefox/browsers/compare/opera.ftl
  l10n/en/firefox/browsers/compare/safari.ftl
  l10n/en/firefox/browsers/compare/shared.ftl
  lib/fluent_migrations/firefox/browsers/compare/__init__.py
  lib/fluent_migrations/firefox/browsers/compare/chrome.py
  lib/fluent_migrations/firefox/browsers/compare/edge.py
  lib/fluent_migrations/firefox/browsers/compare/ie.py
  lib/fluent_migrations/firefox/browsers/compare/index.py
  lib/fluent_migrations/firefox/browsers/compare/opera.py
  lib/fluent_migrations/firefox/browsers/compare/safari.py
  lib/fluent_migrations/firefox/browsers/compare/shared.py
  media/css/firefox/compare/compare.scss
  media/img/firefox/compare/compare-browser-brave-high-res.png
  media/img/firefox/compare/compare-browser-brave.png
  media/img/firefox/compare/compare-browser-edge-high-res.png
  media/img/firefox/compare/compare-browser-edge.png
  media/img/firefox/compare/compare-browser-windows-high-res.png
  media/img/firefox/compare/compare-browser-windows.png
  media/img/firefox/compare/compare-privacy-eyes.svg
  media/img/firefox/compare/compare-privacy-shield.svg
  media/img/logos/brave/logo-brave-high-res.png
  media/img/logos/brave/logo-brave.png
  tests/redirects/map_globalconf.py
Labels: Review: M

#9041 Remove wnp77 experiment code. (Fixes #9036)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx77-b.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx77.html
  bedrock/firefox/views.py
  media/css/firefox/welcome.scss
  media/js/firefox/whatsnew/whatsnew-77-exp.js
  media/static-bundles.json
Labels: Needs Review, P3, Papercuts 💸, Review: XS

#9042 Remove s2d experiment code. [no bug]
  bedrock/firefox/templates/firefox/mobile/index.html
  bedrock/firefox/urls.py
  media/js/firefox/mobile/experiment-mobile.js
  media/static-bundles.json
  tests/functional/firefox/test_mobile.py
Labels: Needs Review, P3, Papercuts 💸, Review: XS

#9000 New /new page.
  bedrock/firefox/templates/firefox/new/desktop/base.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/views.py
  media/css/firefox/new/desktop/download.scss
  media/img/firefox/new/android-high-res.jpg
  media/img/firefox/new/android-high-res.png
  media/img/firefox/new/ani-purple-oval.svg
  media/img/firefox/new/desktop/android-high-res.png
  media/img/firefox/new/desktop/android.png
  media/img/firefox/new/desktop/block-high-res.jpg
  media/img/firefox/new/desktop/block.jpg
  media/img/firefox/new/desktop/comparison-noodles.svg
  media/img/firefox/new/desktop/contain.svg
  media/img/firefox/new/desktop/customize.svg
  media/img/firefox/new/desktop/dark-mode.svg
  media/img/firefox/new/desktop/devices-high-res.jpg
  media/img/firefox/new/desktop/devices.jpg
  media/img/firefox/new/desktop/etp.svg
  media/img/firefox/new/desktop/everyone.svg
  media/img/firefox/new/desktop/features/one.svg
  media/img/firefox/new/desktop/features/oval-one.svg
  media/img/firefox/new/desktop/features/oval-two.svg
  media/img/firefox/new/desktop/features/rect-one.svg
  media/img/firefox/new/desktop/features/rect-two.svg
  media/img/firefox/new/desktop/features/two.svg
  media/img/firefox/new/desktop/goog.svg
  media/img/firefox/new/desktop/hero-high-res.png
  media/img/firefox/new/desktop/hero.png
  media/img/firefox/new/desktop/highlights.svg
  media/img/firefox/new/desktop/ios-high-res.png
  media/img/firefox/new/desktop/ios.png
  media/img/firefox/new/desktop/lock.svg
  media/img/firefox/new/desktop/mobile-arrow.svg
  media/img/firefox/new/desktop/mobile/circle-bottom.svg
  media/img/firefox/new/desktop/mobile/circle-top-right.svg
  media/img/firefox/new/desktop/mobile/elbow-bottom-right.svg
  media/img/firefox/new/desktop/mobile/elbow.svg
  media/img/firefox/new/desktop/mobile/oval-bottom.svg
  media/img/firefox/new/desktop/mobile/oval-left.svg
  media/img/firefox/new/desktop/passwords.svg
  media/img/firefox/new/desktop/person-mozilla-high-res.jpg
  media/img/firefox/new/desktop/person-mozilla.jpg
  media/img/firefox/new/desktop/person-privacy-high-res.jpg
  media/img/firefox/new/desktop/person-privacy.jpg
  media/img/firefox/new/desktop/picture-in-picture.svg
  media/img/firefox/new/desktop/pinp.svg
  media/img/firefox/new/desktop/privacy.svg
  media/img/firefox/new/desktop/release-noodles.svg
  media/img/firefox/new/desktop/screen-high-res.png
  media/img/firefox/new/desktop/screen.png
  media/img/firefox/new/desktop/screenshots.svg
  media/img/firefox/new/desktop/search.svg
  media/img/firefox/new/desktop/sync.svg
  media/img/firefox/new/hero-flat-high-res.jpg
  media/img/firefox/new/hero-noodles.svg
  media/img/firefox/new/img-browser-hero-flat.png
  media/img/firefox/new/img-browser-hero-high-res.png
  media/img/firefox/new/img-ios-mobile-browser-high-res.png
  media/js/firefox/new/desktop/download.js
  media/static-bundles.json
Labels: Needs Review, P1, Review: S

#9052 [fix #9050] Remove “beta” from FPN terms and privacy policy
  bedrock/legal/templates/legal/terms/firefox-private-network.html
  bedrock/privacy/templates/privacy/notices/firefox-private-network.html
Labels: Expedite :bee:, Needs Review, Review: µ

#9046 [fix #9045] Add Navrina Singh to leadership page
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/navrina-singh-high-res.jpg
  media/img/mozorg/about/leadership/navrina-singh.jpg
Labels: Needs Review, Review: µ

#9051 Add firefox/accounts & fr /firefox exp templates. [no bug]
  bedrock/exp/templates/exp/firefox/accounts.html
  bedrock/exp/templates/exp/firefox/index.de.html
  bedrock/exp/templates/exp/firefox/index.html
  bedrock/exp/templates/exp/firefox/mobile.html
  bedrock/exp/templates/exp/home/home-de.html
  bedrock/exp/templates/exp/home/home-en.html
  bedrock/exp/templates/exp/home/home-fr.html
  bedrock/exp/urls.py
  media/css/exp/firefox/accounts.scss
  media/js/exp/firefox/accounts.js
  media/static-bundles.json
  tests/functional/test_experiment_pages.py
Labels: Needs Review, P1, Review: S

#9057 Use new string ID for facebook share string (Fixes #9056)
  bedrock/firefox/templates/firefox/switch.html
  l10n/en/firefox/switch.ftl
Labels: Needs Review, Review: µ

#9021 Redirect /products/firefox/ to /firefox/products/ (Fixes #9008)
  bedrock/firefox/redirects.py
  tests/redirects/map_301.py
  tests/redirects/map_globalconf.py
Labels: Needs Review, P3, Review: µ

#9033 Whatsnew 78 [fixes: 8971]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx78-2-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx78-2-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx78-2-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx78-3-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx78-3-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx78-3-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx78-4-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx78-4-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx78-4-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx78-5-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx78-5-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx78-5-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx78.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-78.scss
  media/js/firefox/whatsnew/whatsnew-exp-78.js
  media/static-bundles.json
Labels: Needs Review, P1, Review: S

#9072 Fix iOS app store link on /new experiment page (Fixes #9071)
  bedrock/firefox/templates/firefox/new/desktop/download.html
Labels: Needs Review, P1, Review: µ

#9074 Revert "Only show browser comparison pages in DEV mode"
  bedrock/firefox/urls.py
Labels: Needs Review, Review: µ

#9076 exp/firefox/accounts base bugfix. [no bug]
  bedrock/exp/templates/exp/firefox/accounts.html
Labels: Bug :bug:, P1, Review: µ

#9002 Port firefox/products page to Fluent (Fixes #9001)
  bedrock/firefox/templates/firefox/products/index.html
  bedrock/firefox/urls.py
  l10n/en/firefox/products.ftl
  lib/fluent_migrations/firefox/products/__init__.py
  lib/fluent_migrations/firefox/products/index.py
Labels: Needs Review, P2, Review: XS

#9015 Migrate firefox/privacy pages to Fluent (Fixes #9006)
  bedrock/firefox/templates/firefox/privacy/base.html
  bedrock/firefox/templates/firefox/privacy/includes/subnav.html
  bedrock/firefox/templates/firefox/privacy/index.html
  bedrock/firefox/templates/firefox/privacy/products.html
  bedrock/firefox/urls.py
  l10n/en/firefox/privacy-hub.ftl
  lib/fluent_migrations/firefox/privacy.py
Labels: Needs Review, P2, Review: XS

#9027 Migrate firefox/set-as-default/ pages to Fluent (Fixes #9026)
  bedrock/firefox/templates/firefox/set-as-default/landing-page.html
  bedrock/firefox/templates/firefox/set-as-default/landing.html
  bedrock/firefox/templates/firefox/set-as-default/thanks.html
  bedrock/firefox/urls.py
  l10n/en/firefox/set-as-default/landing.ftl
  l10n/en/firefox/set-as-default/thanks.ftl
  lib/fluent_migrations/firefox/set-as-default/__init__.py
  lib/fluent_migrations/firefox/set-as-default/landing.py
  lib/fluent_migrations/firefox/set-as-default/thanks.py
Labels: Needs Review, P2, Review: XS

#9017 Migrate /firefox/lockwise to Fluent (Fixes #9016)
  bedrock/base/templates/includes/protocol/footer/firefox.html
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/products.html
  bedrock/base/templates/includes/structured-data/organizations/mozilla-corporation-organisation.json
  bedrock/base/templates/includes/structured-data/software/firefox-lockwise-software.json
  bedrock/exp/templates/exp/firefox/accounts.html
  bedrock/exp/templates/exp/firefox/index.html
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/browsers/compare/brave.html
  bedrock/firefox/templates/firefox/browsers/compare/ie.html
  bedrock/firefox/templates/firefox/browsers/compare/safari.html
  bedrock/firefox/templates/firefox/features/safebrowser.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/privacy/products.html
  bedrock/firefox/templates/firefox/products/index.html
  bedrock/firefox/templates/firefox/products/lockwise.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx70-fr.html
  bedrock/firefox/urls.py
  bedrock/foundation/templates/foundation/annualreport/2018/index.html
  l10n/en/firefox/products/lockwise.ftl
  lib/fluent_migrations/firefox/lockwise/__init__.py
  lib/fluent_migrations/firefox/lockwise/lockwise.py
Labels: Needs Review, P2, Review: XS

#9035 Migrate firefox/welcome/1/ to Fluent (Fixes #9034)
  bedrock/firefox/templates/firefox/welcome/base.html
  bedrock/firefox/templates/firefox/welcome/page1.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  l10n/en/firefox/welcome/page1.ftl
  lib/fluent_migrations/firefox/welcome/__init__.py
  lib/fluent_migrations/firefox/welcome/page1.py
Labels: Needs Review, P2, Review: XS

#9091 Add link to desktop redesign experience Fix #9090
  bedrock/firefox/views.py
Labels: Needs Review, P1, Review: µ

#9079 Add missing links to FxA form on /browsers (Fixes #9073)
  bedrock/firefox/templates/firefox/browsers/index.html
Labels: Needs Review, P2, Review: µ

#9089 [fix bug #1640569] home page, clear floats in the two column section
  bedrock/mozorg/templates/mozorg/home/home.html
  media/css/mozorg/home/home.scss
Labels: Bug :bug:, Needs Review, Review: µ
