Repository mozilla/bedrock, pull requests merged in 2020-04, with the labels that each got.

#8672 Move browsers SEO pages to /firefox/browsers/ sub pages (Fixes #8641)
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/best-browser.html
  bedrock/firefox/templates/firefox/browsers/best-browser.html
  bedrock/firefox/templates/firefox/browsers/browser-history.html
  bedrock/firefox/templates/firefox/browsers/incognito-browser.html
  bedrock/firefox/templates/firefox/browsers/update-browser.html
  bedrock/firefox/templates/firefox/browsers/what-is-a-browser.html
  bedrock/firefox/templates/firefox/browsers/windows-64-bit.html
  bedrock/firefox/templates/firefox/windows-64-bit.html
  bedrock/firefox/urls.py
  bedrock/mozorg/redirects.py
  bedrock/mozorg/urls.py
  media/css/firefox/browsers/best-browser.scss
  media/css/firefox/browsers/browser-history.scss
  media/css/firefox/browsers/incognito-browser.scss
  media/css/firefox/browsers/update-browser.scss
  media/css/firefox/browsers/what-is-a-browser.scss
  media/css/firefox/browsers/windows-64-bit.scss
  media/img/firefox/browsers/best-browser/hero-pattern.png
  media/img/firefox/browsers/browser-history/browser-history-a.png
  media/img/firefox/browsers/browser-history/browser-history-b.png
  media/img/firefox/browsers/incognito-browser/incognito-browser-a.png
  media/img/firefox/browsers/incognito-browser/incognito-browser-b.png
  media/img/firefox/browsers/update-browser/device.png
  media/img/firefox/browsers/update-browser/fast.png
  media/img/firefox/browsers/what-is-a-browser/illo-browser.png
  media/static-bundles.json
  tests/functional/firefox/browsers/test_best_browser.py
  tests/functional/firefox/browsers/test_browser_history.py
  tests/functional/firefox/browsers/test_incognito_browser.py
  tests/functional/firefox/browsers/test_update_browser.py
  tests/functional/firefox/browsers/test_what_is_a_browser.py
  tests/functional/firefox/browsers/test_windows_64_bit.py
  tests/functional/firefox/test_browsers.py
  tests/pages/firefox/browsers/__init__.py
  tests/pages/firefox/browsers/best_browser.py
  tests/pages/firefox/browsers/browser_history.py
  tests/pages/firefox/browsers/incognito_browser.py
  tests/pages/firefox/browsers/landing.py
  tests/pages/firefox/browsers/update_browser.py
  tests/pages/firefox/browsers/what_is_a_browser.py
  tests/pages/firefox/browsers/windows_64_bit.py
  tests/redirects/map_globalconf.py
Labels: Needs Review, P3, Review: XS

#8661 Update newsletter preferences confirmation page (Fixes #8539)
  bedrock/newsletter/templates/newsletter/updated.html
  bedrock/newsletter/views.py
  media/css/newsletter/newsletter.scss
  media/img/newsletter/confirm/addons.png
  media/img/newsletter/confirm/mobile.png
  media/img/newsletter/confirm/monitor.png
  media/img/newsletter/confirm/mozilla.png
  media/js/newsletter/confirm.js
  media/static-bundles.json
Labels: P2, Review: S

#8717 Port FxA Email form to Fluent (Issue #8657)
  bedrock/base/templates/macros.html
  bedrock/settings/base.py
  l10n/en/fxa_form.ftl
  lib/fluent_migrations/firefox/fxa-form.py
Labels: Needs Review, P1, Review: XS

#8745 Display 4 cards in 3rd row of EN homepage if there are 17 cards (#8744)
  bedrock/mozorg/templates/mozorg/home/home-en.html
Labels: Needs Review, P1, Review: XS

#8747 [fix #8735] Leadership updates
  bedrock/mozorg/templates/mozorg/about/leadership.html
Labels: Needs Review, P1, Review: µ

#8742 [#8578] Enterprise page - align download menus, update tests
  bedrock/firefox/templates/firefox/enterprise/index.html
  media/css/firefox/enterprise/landing.scss
  tests/functional/firefox/test_enterprise.py
  tests/pages/firefox/enterprise/landing.py
Labels: Needs Review, P3, Review: XS

#8755 [no bug] update 'meet the firefox family' link to got to firefox home
  bedrock/mozorg/templates/mozorg/home/includes/macros.html
Labels: Needs Review, P3, Review: µ

#8757 Add Download string to download_button.ftl (#8657)
  bedrock/firefox/templates/firefox/channel/android.html
  bedrock/firefox/templates/firefox/channel/desktop.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/products/index.html
  l10n/en/download_button.ftl
  lib/fluent_migrations/firefox/includes/download-button.py
Labels: Needs Review, P1, Review: XS

#8743 Experiment: Add social proof block to release notes.
  bedrock/firefox/templates/firefox/releases/notes.html
  bedrock/releasenotes/views.py
  media/css/firefox/releasenotes.scss
  media/fonts/fontawesome-webfont.woff
  media/fonts/fontawesome-webfont.woff2
  media/js/firefox/social-proof-experiment.js
  media/static-bundles.json
Labels: CRO-Team, Review: S

#8748 Port newsletter form to Fluent (Issue #8657)
  bedrock/mozorg/forms.py
  bedrock/newsletter/forms.py
  bedrock/newsletter/templates/newsletter/includes/form-protocol.html
  bedrock/newsletter/templates/newsletter/includes/form.html
  bedrock/newsletter/templates/newsletter/includes/macros.html
  bedrock/newsletter/views.py
  bedrock/settings/base.py
  l10n/en/newsletter_form.ftl
  lib/fluent_migrations/newsletter/__init__.py
  lib/fluent_migrations/newsletter/includes/__init__.py
  lib/fluent_migrations/newsletter/includes/newsletter-extra.py
  lib/fluent_migrations/newsletter/includes/newsletter.py
Labels: Needs Review, P1, Review: S

#8759 Mitchell bio update [Fixes: #8758]
  bedrock/mozorg/templates/mozorg/about/leadership.html
Labels: Needs Review, P1, Review: XS

#8737 Fix broken link to adjust
  bedrock/privacy/templates/privacy/archive/firefox-cliqz-2018-06.html
Labels: Bug :bug:

#8762 Redirect /mobile to /firefox/mobile. (Fixes #8749)
  bedrock/firefox/redirects.py
  tests/redirects/map_globalconf.py
Labels: Needs Review, P3, Review: µ

#8766 [fix #8765] Remove Edge comparison page
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/compare/edge.html
  bedrock/firefox/templates/firefox/compare/includes/subnav.html
  bedrock/firefox/urls.py
  media/img/firefox/compare/compare-browser-edge-high-res.png
  media/img/firefox/compare/compare-browser-edge.png
  media/img/firefox/compare/compare-privacy-eyes.svg
  tests/redirects/map_globalconf.py
Labels: Expedite :bee:, Fire :fire:, Review: XS

#8769 [no bug] Redirect browser comparison pages
  bedrock/firefox/redirects.py
  tests/redirects/map_globalconf.py
Labels: Expedite :bee:, Fire :fire:, Review: µ

#8772 [fix #8771] Update independent features page copy
  bedrock/firefox/templates/firefox/features/independent.html
  bedrock/firefox/templates/firefox/features/index.html
Labels: Expedite :bee:, Needs Review, Review: µ

#8764 [fix #8761] Delete resources link from enterprise subnav
  bedrock/firefox/templates/firefox/enterprise/index.html
Labels: Needs Review, Review: µ

#8754 Small debugging improvement for release notes update
  bedrock/releasenotes/management/commands/update_release_notes.py
  bin/run-db-upload.py
Labels: Backend, Papercuts 💸

#8778 [fix 8730] Add COVID-19 fund banner to MOSS pages
  bedrock/base/templates/includes/banners/moss-covid.html
  bedrock/mozorg/templates/mozorg/moss/base.html
  media/css/base/banners/includes/_base.scss
  media/css/base/banners/moss-covid.scss
  media/img/mozorg/moss/covid-banner-bg.jpg
  media/js/mozorg/moss-covid-banner-init.js
  media/static-bundles.json
Labels: Needs Review, Review: XS

#8781 Show regular Sync button to signed out Firefox users on 75 WNP (Fixes #8770)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx75.html
  media/css/firefox/whatsnew/whatsnew-75.scss
  media/js/firefox/whatsnew/whatsnew-75.js
  tests/functional/firefox/whatsnew/test_whatsnew_75.py
  tests/pages/firefox/whatsnew/whatsnew_75.py
Labels: P1, Review: S

#8774 Add view to exp.firefox.new to enable variations #8773
  bedrock/exp/redirects.py
  bedrock/exp/templates/exp/firefox/new/download-nav.html
  bedrock/exp/templates/exp/firefox/new/download.html
  bedrock/exp/tests/__init__.py
  bedrock/exp/tests/test_views.py
  bedrock/exp/urls.py
  bedrock/exp/views.py
Labels: P2, Review: S

#8779 Migrate common UI strings from main.lang to Fluent (Fixes #8657)
  bedrock/base/templates/base-pebbles.html
  bedrock/base/templates/includes/banners/base.html
  bedrock/base/templates/macros-protocol.html
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/all-unified.html
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/channel/android.html
  bedrock/firefox/templates/firefox/channel/desktop.html
  bedrock/firefox/templates/firefox/channel/ios.html
  bedrock/firefox/templates/firefox/developer/includes/highlights.html
  bedrock/firefox/templates/firefox/developer/includes/intro-features.html
  bedrock/firefox/templates/firefox/developer/includes/performance.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/facebookcontainer/index.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/home/index-quantum.html
  bedrock/firefox/templates/firefox/mobile/index.html
  bedrock/firefox/templates/firefox/retention/thank-you.html
  bedrock/firefox/templates/firefox/switch.html
  bedrock/mozorg/templates/mozorg/about-base.html
  bedrock/mozorg/templates/mozorg/about/manifesto.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/internet-health/privacy-security.html
  bedrock/mozorg/templates/mozorg/manifesto-base.html
  bedrock/mozorg/templates/mozorg/moss/index.html
  bedrock/mozorg/templates/mozorg/videotag.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/newsletter/templates/newsletter/updated.html
  bedrock/privacy/templates/privacy/archive/base-resp.html
  bedrock/privacy/templates/privacy/notices/base-notice-paragraphs.html
  bedrock/settings/base.py
  l10n/en/ui.ftl
  lib/fluent_migrations/ui.py
Labels: Do Not Merge :warning:, Needs Review, P1, Review: S

#8756 Decommission /plugincheck/ page (Fixes #8374)
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/plugincheck.html
  bedrock/mozorg/urls.py
  bedrock/settings/base.py
  media/css/plugincheck/plugincheck.scss
  media/img/plugincheck/critters-high-res.png
  media/img/plugincheck/critters.png
  media/img/plugincheck/page-image.png
  media/js/base/mozilla-client.js
  media/js/plugincheck/plugincheck.js
  media/static-bundles.json
  tests/functional/newsletter/test_newsletter_embed.py
  tests/functional/test_plugincheck.py
  tests/pages/plugincheck.py
  tests/redirects/map_globalconf.py
Labels: Needs Review, P3, Review: XS

#8783 Migrate send-to-device widget to Fluent (Fixes #8658)
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/mobile/get-app.html
  bedrock/firefox/templates/firefox/mobile/index.html
  bedrock/firefox/templates/firefox/welcome/page4.html
  bedrock/firefox/templates/firefox/welcome/page5.html
  bedrock/firefox/templates/firefox/whatsnew/index-lite.html
  bedrock/firefox/templates/firefox/whatsnew/index-lite.id.html
  bedrock/firefox/templates/firefox/whatsnew/index.html
  bedrock/settings/base.py
  l10n/en/send_to_device.ftl
  lib/fluent_migrations/firefox/send-to-device.py
Labels: Do Not Merge :warning:, Needs Review, P1, Review: S

#8790 Add b and c variants of exp/firefox/new page (#8773)
  bedrock/exp/templates/exp/firefox/new/download.html
  bedrock/exp/views.py
Labels: Needs Review, P2, Review: µ

#8780 Migrate global newsletter titles to Fluent (Issue #8657)
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/mozorg/templates/mozorg/base.html
  l10n/en/newsletter_form.ftl
  lib/fluent_migrations/newsletter/includes/newsletter.py
Labels: Needs Review, P1, Review: XS

#8793 [fix #8792] Update Mitchell’s bio on leadership page
  bedrock/mozorg/templates/mozorg/about/leadership.html
Labels: Review: µ

#8782 Whatsnew 76 [Fixes #8703]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx76.html
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-76.scss
  media/img/firefox/whatsnew/whatsnew76/hero_etp.svg
  media/js/firefox/whatsnew/whatsnew-76.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_76.py
  tests/pages/firefox/whatsnew/whatsnew_76.py
Labels: P1, Review: M

#8802 Fix missing icons on /firefox/new/ for some locales (Fixes #8801)
  bedrock/firefox/templates/firefox/new/trailhead/download-yandex.html
  bedrock/firefox/templates/firefox/new/trailhead/download.html
  media/css/firefox/new/quantum/scene2.scss
  media/css/firefox/new/trailhead/download-yandex.scss
  media/css/firefox/new/trailhead/download.scss
  media/static-bundles.json
Labels: Bug :bug:, P2, Review: XS

#8791 Graduate installer-help redesign experiment into prod.
  bedrock/firefox/templates/firefox/installer-help-redesign.html
  bedrock/firefox/templates/firefox/installer-help.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/installer-help-redesign.scss
  media/js/firefox/installer-help-experiment.js
  media/static-bundles.json
Labels: Review: S

#8818 Fix missing yandex bundle name (Issue #8801)
  bedrock/firefox/templates/firefox/new/trailhead/download-yandex.html
Labels: Needs Review, P1, Review: µ

#8817 Add metrics.convertexperiments.com to CSP_CONNECT_SRC (Issue #8773)
  bedrock/settings/base.py
Labels: Needs Review, P3, Review: µ

#8804 Remove no longer needed exp templates. (#8795)
  bedrock/exp/templates/exp/firefox/accounts-2019.html
  bedrock/exp/templates/exp/firefox/lockwise.de.html
  bedrock/exp/templates/exp/firefox/lockwise.html
  bedrock/exp/templates/exp/firefox/welcome/base.html
  bedrock/exp/templates/exp/firefox/welcome/page1.html
  bedrock/exp/templates/exp/firefox/whatsnew/whatsnew-fx71.html
  bedrock/exp/urls.py
  bedrock/exp/views.py
  media/css/exp/firefox/accounts-2019.scss
  media/css/exp/firefox/lockwise.scss
  media/css/exp/firefox/welcome.scss
  media/css/exp/firefox/whatsnew/whatsnew-71.scss
  media/js/exp/firefox/accounts-2019.js
  media/js/exp/firefox/lockwise.js
  media/static-bundles.json
  tests/functional/test_experiment_pages.py
Labels: P3, Papercuts 💸, Review: XS

#8851 Remove mozorg/home/_newsletter.scss
  media/css/mozorg/home/_newsletter.scss
Labels: P3, Review: µ

#8854 Link to browsers and products pages for all locales #8298
  bedrock/base/templates/includes/protocol/footer/firefox.html
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/browsers.html
  bedrock/base/templates/includes/protocol/navigation/menu-firefox/products.html
  bedrock/firefox/templates/firefox/home/index-master.html
Labels: Needs Review, P2, Review: XS

#8816 Add pages for Privacy by Default messaging experiment.
  bedrock/firefox/templates/firefox/messaging-experiment/base.html
  bedrock/firefox/templates/firefox/messaging-experiment/control.html
  bedrock/firefox/templates/firefox/messaging-experiment/privacy_by_default.html
  bedrock/firefox/templates/firefox/messaging-experiment/privacy_tools.html
  bedrock/firefox/urls.py
  media/css/firefox/welcome.scss
  media/img/icons/cryptomining-purple.svg
  media/img/icons/extension-purple.svg
  media/img/icons/hide_password-orange.svg
  media/img/icons/laptop_warning-pink.svg
  media/img/icons/private_browsing-pink.svg
  media/img/icons/report-orange.svg
  media/img/icons/sync-orange.svg
  media/img/icons/tracking_protection-purple.svg
  media/js/firefox/privacy/messaging-experiment.js
  media/static-bundles.json
Labels: P1, Review: S, WIP :construction:

#8855 Add exp versions of the homepage and mobile (fixes #8795)
  bedrock/exp/templates/exp/firefox/mobile.html
  bedrock/exp/templates/exp/home/home-de.html
  bedrock/exp/templates/exp/home/home-en.html
  bedrock/exp/templates/exp/home/home-fr.html
  bedrock/exp/urls.py
  bedrock/exp/views.py
  media/css/exp/home/home-2018.scss
  media/css/exp/home/home.scss
  media/css/exp/mobile.scss
  media/js/exp/home.js
  media/js/exp/mobile.js
  media/static-bundles.json
  tests/functional/test_experiment_pages.py
Labels: P2

#8850 Remove pebbles import from one-off pages
  media/css/mozorg/book.scss
  media/css/mozorg/credits.scss
  media/css/mozorg/namespaces.scss
Labels: Needs Review, P3, Review: µ

#8861 Add vanity URL redirect for EKR’s blog
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/about/leadership.html
  tests/redirects/map_globalconf.py
Labels: Needs Review, P3, Review: µ

#8863 Exclude unrelated page content from search result snippets (Fixes #8739)
  bedrock/base/templates/base-pebbles.html
  bedrock/base/templates/includes/banners/base.html
  bedrock/firefox/templates/firefox/includes/download-button.html
  bedrock/firefox/tests/test_helpers.py
  media/js/base/mozilla-banner.js
  tests/unit/spec/base/mozilla-banner.js
Labels: P1, Review: XS
