Repository mozilla/bedrock, pull requests merged in 2020-10, with the labels that each got.

#9485 Copy tweaks (#9334)
  bedrock/firefox/templates/firefox/campaign/unfck/index.html
Labels: Needs Review, P1, Review: µ

#9417 Make /exp/ pages extend original templates (Fixes #9369)
  bedrock/exp/templates/exp/base/base-firefox.html
  bedrock/exp/templates/exp/base/base.html
  bedrock/exp/templates/exp/firefox/accounts.html
  bedrock/exp/templates/exp/firefox/index.html
  bedrock/exp/templates/exp/firefox/mobile.html
  bedrock/exp/templates/exp/firefox/new/base.html
  bedrock/exp/templates/exp/firefox/new/download.html
  bedrock/exp/templates/exp/home/home-de.html
  bedrock/exp/templates/exp/home/home-en.html
  bedrock/exp/templates/exp/home/home-fr.html
  bedrock/exp/templates/exp/includes/convert.html
  bedrock/exp/templates/exp/includes/id.html
  bedrock/exp/templates/exp/includes/js.html
  bedrock/exp/templates/exp/includes/stub.html
  bedrock/exp/templates/exp/opt-out.html
  bedrock/exp/urls.py
  docs/abtest.rst
  media/css/exp/firefox/accounts.scss
  media/css/exp/firefox/index-ie9.scss
  media/css/exp/firefox/index.scss
  media/css/exp/firefox/new/download.scss
  media/css/exp/home/home-2018.scss
  media/css/exp/home/home.scss
  media/css/exp/mobile.scss
  media/img/exp/firefox/new/hero-bg-rtl.svg
  media/img/exp/firefox/new/hero-bg.svg
  media/js/exp/firefox/accounts.js
  media/js/exp/firefox/index.js
  media/js/exp/firefox/new/desktop/download.js
  media/js/exp/firefox/new/desktop/join-modal.js
  media/js/exp/home.js
  media/js/exp/mobile.js
  media/static-bundles.json
Labels: Needs Review, P3, Review: M

#9493 Update browser comparison version disclaimer [fix #9481]
  bedrock/firefox/templates/firefox/browsers/compare/brave.html
  bedrock/firefox/templates/firefox/browsers/compare/chrome.html
  bedrock/firefox/templates/firefox/browsers/compare/edge.html
  bedrock/firefox/templates/firefox/browsers/compare/ie.html
  bedrock/firefox/templates/firefox/browsers/compare/index.html
  bedrock/firefox/templates/firefox/browsers/compare/opera.html
  bedrock/firefox/templates/firefox/browsers/compare/safari.html
  l10n/en/firefox/browsers/compare/shared.ftl
Labels: Needs Review, Review: µ

#9507 Update background (#9334)
  media/css/firefox/unfck.scss
  media/img/firefox/campaign/unfck/en/bg/1.jpg
  media/img/firefox/campaign/unfck/en/bg/10.jpg
  media/img/firefox/campaign/unfck/en/bg/11.jpg
  media/img/firefox/campaign/unfck/en/bg/12.jpg
  media/img/firefox/campaign/unfck/en/bg/13.jpg
  media/img/firefox/campaign/unfck/en/bg/14.jpg
  media/img/firefox/campaign/unfck/en/bg/15.jpg
  media/img/firefox/campaign/unfck/en/bg/16.jpg
  media/img/firefox/campaign/unfck/en/bg/17.jpg
  media/img/firefox/campaign/unfck/en/bg/18.jpg
  media/img/firefox/campaign/unfck/en/bg/19.jpg
  media/img/firefox/campaign/unfck/en/bg/2.jpg
  media/img/firefox/campaign/unfck/en/bg/20.jpg
  media/img/firefox/campaign/unfck/en/bg/3.jpg
  media/img/firefox/campaign/unfck/en/bg/4.jpg
  media/img/firefox/campaign/unfck/en/bg/5.jpg
  media/img/firefox/campaign/unfck/en/bg/6.jpg
  media/img/firefox/campaign/unfck/en/bg/7.jpg
  media/img/firefox/campaign/unfck/en/bg/8.jpg
  media/img/firefox/campaign/unfck/en/bg/9.jpg
  media/img/firefox/campaign/unfck/en/bg/top-high-res.png
  media/img/firefox/campaign/unfck/en/bg/top.png
Labels: Needs Review, P3, Review: XS

#9511 Update Hero copy for /de/ home page (Fixes #9510)
  bedrock/mozorg/templates/mozorg/home/home-de.html
Labels: Needs Review, P2, Review: µ

#9530 [no bug] Copy tweak
  bedrock/firefox/templates/firefox/campaign/unfck/index.html
Labels: Needs Review, P2, Review: µ

#9461 September landing page for French locale (#9424)
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/campaign/unfck/includes/macros.html
  bedrock/firefox/templates/firefox/campaign/unfck/index.de.html
  bedrock/firefox/templates/firefox/campaign/unfck/index.fr.html
  bedrock/firefox/urls.py
  media/css/firefox/unfck.de.scss
  media/css/firefox/unfck.fr.scss
  media/img/firefox/campaign/unfck/fr/button-click.gif
  media/img/firefox/campaign/unfck/fr/button-click.png
  media/img/firefox/campaign/unfck/fr/gifs/button-high-res.gif
  media/img/firefox/campaign/unfck/fr/gifs/button.gif
  media/img/firefox/campaign/unfck/fr/gifs/cat-high-res.gif
  media/img/firefox/campaign/unfck/fr/gifs/cat.gif
  media/img/firefox/campaign/unfck/fr/gifs/one-fck-given-high-res.gif
  media/img/firefox/campaign/unfck/fr/gifs/one-fck-given.gif
  media/img/firefox/campaign/unfck/fr/gifs/purrfect-high-res.gif
  media/img/firefox/campaign/unfck/fr/gifs/purrfect.gif
  media/img/firefox/campaign/unfck/fr/gifs/still/button.png
  media/img/firefox/campaign/unfck/fr/gifs/still/cat.png
  media/img/firefox/campaign/unfck/fr/gifs/still/one-fck-given.png
  media/img/firefox/campaign/unfck/fr/gifs/still/purrfect.png
  media/img/firefox/campaign/unfck/fr/gifs/still/unzuck-it.png
  media/img/firefox/campaign/unfck/fr/gifs/unzuck-it-high-res.gif
  media/img/firefox/campaign/unfck/fr/gifs/unzuck-it.gif
  media/img/firefox/campaign/unfck/fr/header-high-res.png
  media/img/firefox/campaign/unfck/fr/header.png
  media/img/firefox/campaign/unfck/fr/og.png
  media/img/firefox/campaign/unfck/fr/speckles-top-left-high-res.png
  media/img/firefox/campaign/unfck/fr/speckles-top-left.png
  media/img/firefox/campaign/unfck/fr/speckles-top-right-high-res.png
  media/img/firefox/campaign/unfck/fr/speckles-top-right.png
  media/static-bundles.json
  tests/functional/firefox/test_unfck.py
  tests/pages/firefox/unfck.py
  tests/redirects/map_globalconf.py
Labels: Do Not Merge :warning:, P1, Review: XS

#9539 Add whatsnew page for Firefox 82 [fix #9494]
  bedrock/firefox/templates/firefox/whatsnew/includes/illo-vpn-laptop.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/illo-vpn-mobile.svg
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx82.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-82.scss
  media/img/firefox/whatsnew/whatsnew82/vpn-logo.svg
Labels: Needs Review, Review: XS

#9544 Update fr unfck gifs (Fixes #9543)
  media/img/firefox/campaign/unfck/fr/gifs/one-fck-given-high-res.gif
  media/img/firefox/campaign/unfck/fr/gifs/one-fck-given.gif
  media/img/firefox/campaign/unfck/fr/gifs/purrfect-high-res.gif
  media/img/firefox/campaign/unfck/fr/gifs/purrfect.gif
  media/img/firefox/campaign/unfck/fr/gifs/still/one-fck-given.png
  media/img/firefox/campaign/unfck/fr/gifs/still/purrfect.png
  media/img/firefox/campaign/unfck/fr/gifs/still/unzuck-it.png
  media/img/firefox/campaign/unfck/fr/gifs/unzuck-it-high-res.gif
  media/img/firefox/campaign/unfck/fr/gifs/unzuck-it.gif
Labels: Needs Review, Review: µ

#9487 Fix JS error on /about/leadership/ page (Fixes #9478)
  media/js/mozorg/about-leadership.js
Labels: Needs Review, P3, Review: µ

#9546 Copy updates for US election (#9334)
  bedrock/firefox/templates/firefox/campaign/unfck/index.html
  media/css/firefox/unfck.scss
  media/img/firefox/campaign/unfck/en/computer-high-res.gif
  media/img/firefox/campaign/unfck/en/computer.gif
  media/img/firefox/campaign/unfck/en/heart-high-res.gif
  media/img/firefox/campaign/unfck/en/heart.gif
  media/img/firefox/campaign/unfck/en/smile-high-res.gif
  media/img/firefox/campaign/unfck/en/smile.gif
  media/img/firefox/campaign/unfck/en/smiley-high-res.gif
  media/img/firefox/campaign/unfck/en/smiley.gif
  media/img/firefox/campaign/unfck/en/still/computer.jpg
  media/img/firefox/campaign/unfck/en/still/heart.jpg
  media/img/firefox/campaign/unfck/en/still/heart.png
  media/img/firefox/campaign/unfck/en/still/smile.jpg
  media/img/firefox/campaign/unfck/en/still/smiley.jpg
  media/img/firefox/campaign/unfck/en/un-high-res.gif
  media/img/firefox/campaign/unfck/en/un.gif
  media/js/firefox/campaign/unfck.js
Labels: P1, Review: XS

#9551 Add firefox/more SEO page. (#9490, Fixes #9503)
  bedrock/firefox/templates/firefox/more.html
  bedrock/firefox/urls.py
  l10n/en/firefox/more.ftl
  media/css/firefox/more.scss
  media/img/firefox/more/browser-history.jpg
  media/img/firefox/more/compare-browsers.jpg
  media/img/firefox/more/firefox-64-bit.jpg
  media/img/firefox/more/firefox-adblocker.jpg
  media/img/firefox/more/firefox-all.jpg
  media/img/firefox/more/firefox-brave.jpg
  media/img/firefox/more/firefox-browsers.jpg
  media/img/firefox/more/firefox-chrome.jpg
  media/img/firefox/more/firefox-edge.jpg
  media/img/firefox/more/firefox-ie.jpg
  media/img/firefox/more/firefox-linux.jpg
  media/img/firefox/more/firefox-lockwise.jpg
  media/img/firefox/more/firefox-mac.jpg
  media/img/firefox/more/firefox-opera.jpg
  media/img/firefox/more/firefox-products.jpg
  media/img/firefox/more/firefox-safari.jpg
  media/img/firefox/more/firefox-windows.jpg
  media/img/firefox/more/incognito-browser.jpg
  media/img/firefox/more/independent.jpg
  media/img/firefox/more/private-browsing.jpg
  media/img/firefox/more/safe-browser.jpg
  media/img/firefox/more/update-browser.jpg
  media/img/firefox/more/what-is-a-browser.jpg
  media/js/firefox/more.js
  media/static-bundles.json
Labels: Needs Review, P1, Review: XS

#9552 Upate social share text
  bedrock/firefox/templates/firefox/campaign/unfck/index.html
Labels: P1, Review: µ

#9548 October 2020 Homepage (EN) Content Updates
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/views.py
  media/css/mozorg/home/home-en.scss
  media/img/home/2020/pocket-hero-high-res.jpg
  media/img/home/2020/pocket-hero.jpg
Labels: Do Not Merge :warning:, Review: XS

#9561 Add vanity redirect for openletter [fix #9560]
  bedrock/mozorg/redirects.py
  tests/redirects/map_globalconf.py
Labels: Needs Review, Review: µ

#9559 Fix #9558 - Revise Pocket hero text on the EN homepage
  bedrock/mozorg/templates/mozorg/home/home-en.html
Labels: Needs Review, Review: µ

#9550 Add Convert to the en-US unfck page (Fixes #9549)
  bedrock/exp/templates/exp/firefox/campaign/unfck/index.html
  bedrock/exp/urls.py
  bedrock/firefox/templates/firefox/campaign/unfck/index.html
Labels: Needs Review, P1, Review: XS

#9557 Update hero CTA on French home page (Fixes #9556)
  bedrock/mozorg/templates/mozorg/home/home-fr.html
Labels: P1, Review: µ

#9525 Update screenshots Fix #9337
  bedrock/firefox/templates/firefox/new/desktop/download.html
  media/img/firefox/new/desktop/block-high-res.jpg
  media/img/firefox/new/desktop/block.jpg
  media/img/firefox/new/desktop/devices-high-res.jpg
  media/img/firefox/new/desktop/devices.jpg
Labels: P3, Review: XS

#9570 Revise strings for firefox/more
  l10n/en/firefox/more.ftl
Labels: Review: XS

#9554 Add firefox/browsers/quantum SEO page. (#9490, Fixes #9499)
  bedrock/firefox/templates/firefox/browsers/quantum.html
  bedrock/firefox/urls.py
  l10n/en/brands.ftl
  l10n/en/firefox/browsers/quantum.ftl
  media/css/firefox/browsers/quantum.scss
  media/img/firefox/browsers/quantum/browser-high-res.jpg
  media/img/firefox/browsers/quantum/browser.jpg
  media/img/icons/speedometer.svg
  media/static-bundles.json
Labels: Review: XS

#9584 [no bug] fix page description, update link.
  bedrock/firefox/templates/firefox/browsers/quantum.html
  l10n/en/firefox/browsers/quantum.ftl
Labels: Review: µ

#9577 Add firefox/faq (#9490, Fixes #9491, #9498)
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/faq.html
  bedrock/firefox/templates/firefox/includes/structured-data-firefox-faq.html
  bedrock/firefox/urls.py
  l10n/en/brands.ftl
  l10n/en/firefox/browsers/quantum.ftl
  l10n/en/firefox/faq.ftl
  media/css/firefox/faq.scss
  media/static-bundles.json
  tests/redirects/map_globalconf.py
Labels: P1, Review: XS

#9595 Copy updates for firefox/faq
  bedrock/firefox/templates/firefox/faq.html
  l10n/en/firefox/faq.ftl
Labels: Review: µ

#9590 Add link to explain Pocket [no bug]
  bedrock/firefox/templates/firefox/campaign/unfck/index.html
Labels: Needs Review, P1, Review: XS

#9536 Improve GA download reporting for legacy / unknown browsers (Fixes #9535)
  media/js/base/mozilla-utils.js
  media/js/ie/mozilla-utils-ie.js
  tests/unit/spec/base/mozilla-utils.js
  tests/unit/spec/ie/mozilla-utils-ie.js
Labels: P2, Review: XS

#9609 Fix #9608 - Update mozilla-protocol/core package to v12.1.1
  package.json
  yarn.lock
Labels: Needs Review, Review: µ

#9619 Fix error on /download/thanks/ if 'try again' link is not well formatted (Fixes #9615)
  media/js/firefox/new/common/thanks-init.js
Labels: Needs Review, P2, Review: µ

#9623 update ftl IDs for firefox/quantum [no bug]
  bedrock/firefox/templates/firefox/browsers/quantum.html
  l10n/en/firefox/browsers/quantum.ftl
Labels: Papercuts 💸, Review: µ

#9586 Add firefox/browsers/chromebook (#9490 Fixes #9512, #9515)
  bedrock/firefox/templates/firefox/browsers/chromebook.html
  bedrock/firefox/urls.py
  l10n/en/brands.ftl
  l10n/en/firefox/browsers/chromebook.ftl
  media/css/firefox/browsers/chromebook.scss
  media/css/protocol/components/_custom-menu-list.scss
  media/img/firefox/browsers/chromebook/addon-high-res.png
  media/img/firefox/browsers/chromebook/addon.png
  media/img/firefox/browsers/chromebook/mobile-high-res.png
  media/img/firefox/browsers/chromebook/mobile.png
  media/img/firefox/browsers/chromebook/shield-high-res.png
  media/img/firefox/browsers/chromebook/shield.png
  media/js/firefox/browsers/chromebook.js
  media/static-bundles.json
Labels: P1, Review: S

#9618 Send-to-device JS form error when geo lookup times out (Fixes #9617)
  media/js/base/send-to-device.js
Labels: Needs Review, P2, Review: µ

#9591 Add firefox/sync (#9490, Fixes #9519, #9516)
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/sync.html
  bedrock/firefox/urls.py
  l10n/en/firefox/sync.ftl
  media/css/firefox/sync.scss
  media/static-bundles.json
  tests/redirects/map_globalconf.py
  tests/redirects/test_urls.py
Labels: P1, Review: XS

#9630 l10n updates [#9490]
  bedrock/firefox/templates/firefox/browsers/quantum.html
  l10n/en/firefox/browsers/chromebook.ftl
  l10n/en/firefox/browsers/quantum.ftl
  l10n/en/firefox/sync.ftl
Labels: Bug :bug:, Review: µ

#9627 Fix ESLint parsing depth (Fixes #9626)
  .eslintignore
  media/js/firefox/browsers/chromebook.js
  media/js/firefox/campaign/unfck.js
  media/js/firefox/whatsnew/whatsnew-account.js
  package.json
  tests/unit/spec/firefox/new/common/thanks.js
Labels: Needs Review, P2, Review: µ

#9588 Fix #9585 - WNP 83 (Code)
  bedrock/firefox/templates/firefox/whatsnew/includes/fx82/illo-vpn-laptop.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx82/illo-vpn-mobile.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx83/person1.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx83/person2.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx83/person3.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx83/pocket.svg
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx82.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx83.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  l10n/en/firefox/whatsnew/whatsnew-fx83.ftl
  media/css/firefox/whatsnew/whatsnew-83.scss
  media/js/firefox/whatsnew/whatsnew-82.js
  media/static-bundles.json
Labels: Review: S
