Repository mozilla/bedrock, pull requests merged in 2020-02, with the labels that each got.

#8483 Add coarse UA detection to stub attribution (Fixes #8405)
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/js/base/stub-attribution.js
  tests/unit/spec/base/stub-attribution.js
Labels: P1, Review: S

#8493 l10n bugfix on firefox/products & firefox/browsers. [no bug]
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/products/index.html
Labels: Review: XS

#8492 Remove enterprise packages
  bedrock/firefox/templates/firefox/enterprise/index.html
  tests/functional/firefox/test_enterprise.py
  tests/pages/firefox/enterprise/landing.py
Labels: Fire :fire:, Needs Review, P1, Review: XS

#8367 Deprecate jQuery functions with equivalent native events (Fixes #7431)
  .eslintrc.js
  package.json
  yarn.lock
Labels: Needs Review, P3, Review: XS

#8509 [fix #8496] Enterprise page, swap the Mac and Windows 32 links
  bedrock/firefox/templates/firefox/enterprise/index.html
Labels: Needs Review, P1, Review: XS

#8495 Enable Convert to pass experimental parameters to stub attribution (Fixes #8484)
  bedrock/exp/templates/exp/base/base.html
  bedrock/settings/base.py
  docs/stub-attribution.rst
  media/js/base/mozilla-convert.js
  media/js/base/stub-attribution-convert.js
  media/js/base/stub-attribution-custom.js
  media/js/base/stub-attribution.js
  media/static-bundles.json
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-convert.js
  tests/unit/spec/base/stub-attribution-custom.js
Labels: Needs Review, P2, Review: S

#8507 [fix #8465] Remove concert series page
  bedrock/firefox/templates/firefox/concerts.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  bedrock/mozorg/templates/mozorg/oauth/fxa-error.html
  bedrock/mozorg/tests/test_util.py
  bedrock/mozorg/tests/test_views.py
  bedrock/mozorg/urls.py
  bedrock/mozorg/util.py
  bedrock/mozorg/views.py
  bedrock/settings/base.py
  media/css/firefox/concerts.scss
  media/img/firefox/concerts/concert-phosphorescent.jpg
  media/img/firefox/concerts/concert.jpg
  media/img/firefox/concerts/icon-alarm.svg
  media/img/firefox/concerts/icon-ended.svg
  media/img/firefox/concerts/icon-live.svg
  media/img/firefox/concerts/illo-fxaccount-high-res.png
  media/img/firefox/concerts/illo-fxaccount.png
  media/img/firefox/concerts/page-image-phosphorescent.jpg
  media/img/firefox/concerts/page-image.jpg
  media/js/firefox/concerts-init.js
  media/js/firefox/concerts.js
  media/static-bundles.json
  requirements/base.txt
Labels: P3, Review: S

#8502 Port newsletter landing pages to Protocol (Fixes #8403)
  bedrock/newsletter/templates/newsletter/developer.html
  bedrock/newsletter/templates/newsletter/firefox.html
  bedrock/newsletter/templates/newsletter/mozilla.html
  media/css/newsletter/newsletter-developer.scss
  media/css/newsletter/newsletter-firefox.scss
  media/css/newsletter/newsletter-mozilla.scss
  media/js/newsletter/developer.js
  media/js/newsletter/firefox.js
  media/js/newsletter/mozilla.js
  media/static-bundles.json
  tests/functional/newsletter/test_newsletter_embed.py
  tests/functional/newsletter/test_newsletter_landing.py
Labels: P3, Review: S

#8519 Make RU scene1 (aka Yandex) stand alone (#8372)
  bedrock/firefox/templates/firefox/new/yandex/base.html
  bedrock/firefox/templates/firefox/new/yandex/scene1.html
  media/css/firefox/new/yandex-scene1.scss
  media/img/firefox/new/yandex/browser-high-res.png
  media/img/firefox/new/yandex/browser.png
  media/img/firefox/new/yandex/icon-alert.svg
  media/img/firefox/new/yandex/icon-check.svg
  media/img/firefox/new/yandex/icon-faster.svg
  media/img/firefox/new/yandex/icon-info.svg
  media/img/firefox/new/yandex/icon-lighter.svg
  media/img/firefox/new/yandex/icon-private.svg
  media/img/firefox/new/yandex/wave.svg
  media/img/firefox/new/yandex/yandex-high-res.jpg
  media/img/firefox/new/yandex/yandex.jpg
  media/static-bundles.json
Labels: Needs Review, P2, Review: XS

#8520 Remove feature variant of scene1 (#8372)
  bedrock/firefox/templates/firefox/new/scene1.de.html
  bedrock/firefox/templates/firefox/new/scene1.en-GB.html
  media/css/firefox/new/scene1_gb_de.scss
  media/img/firefox/new/blob.svg
  media/img/firefox/new/blob2.svg
  media/img/firefox/new/blob3.svg
  media/img/firefox/new/icon-clock.svg
  media/img/firefox/new/icon-mask.svg
  media/img/firefox/new/icon-password.svg
  media/img/firefox/new/icon-protection.svg
  media/img/firefox/new/icon-switch.svg
  media/img/firefox/new/icon-sync.svg
  media/static-bundles.json
Labels: Needs Review, P2, Review: XS

#8514 Port /contact/ pages to Protocol (Fixes #8506)
  bedrock/mozorg/templates/mozorg/contact/communities/includes/nav.html
  bedrock/mozorg/templates/mozorg/contact/contact-base.html
  bedrock/mozorg/templates/mozorg/contact/contact-landing.html
  bedrock/mozorg/templates/mozorg/contact/spaces/base.html
  bedrock/mozorg/templates/mozorg/contact/spaces/beijing.html
  bedrock/mozorg/templates/mozorg/contact/spaces/berlin.html
  bedrock/mozorg/templates/mozorg/contact/spaces/includes/nav.html
  bedrock/mozorg/templates/mozorg/contact/spaces/london.html
  bedrock/mozorg/templates/mozorg/contact/spaces/mountain-view.html
  bedrock/mozorg/templates/mozorg/contact/spaces/paris.html
  bedrock/mozorg/templates/mozorg/contact/spaces/portland.html
  bedrock/mozorg/templates/mozorg/contact/spaces/san-francisco.html
  bedrock/mozorg/templates/mozorg/contact/spaces/spaces-landing.html
  bedrock/mozorg/templates/mozorg/contact/spaces/taipei.html
  bedrock/mozorg/templates/mozorg/contact/spaces/toronto.html
  bedrock/mozorg/templates/mozorg/contact/spaces/vancouver.html
  media/css/libs/magnific-popup.css
  media/css/mozorg/contact-spaces.scss
  media/img/contact/arrow-current.png
  media/img/contact/arrow-down.png
  media/img/contact/arrow-up.png
  media/img/contact/mapbox/icons.png
  media/img/firefox/pager-tabs.png
  media/js/libs/jquery.magnific-popup.min.js
  media/js/mozorg/contact-spaces.js
  media/static-bundles.json
  tests/functional/test_contact.py
  tests/pages/contact.py
Labels: P3, Review: S

#8524 [fix #8494] Leadership updates
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/css/mozorg/leadership.scss
  media/img/mozorg/about/leadership/chris-beard-high-res.jpg
  media/img/mozorg/about/leadership/chris-beard.jpg
  media/img/mozorg/about/leadership/eric-rescorla-high-res.jpg
  media/img/mozorg/about/leadership/eric-rescorla.jpg
  media/img/mozorg/about/leadership/marissa-wood-high-res.jpg
  media/img/mozorg/about/leadership/marissa-wood.jpg
  media/img/mozorg/about/leadership/matt-koidin-high-res.jpg
  media/img/mozorg/about/leadership/matt-koidin.jpg
  media/img/mozorg/about/leadership/michael-deangelo-high-res.jpg
  media/img/mozorg/about/leadership/michael-deangelo.jpg
  media/img/mozorg/about/leadership/selena-deckelmann-high-res.jpg
  media/img/mozorg/about/leadership/selena-deckelmann.jpg
  media/js/mozorg/about-leadership.js
  media/static-bundles.json
  tests/functional/test_leadership.py
  tests/pages/leadership.py
Labels: Needs Review, P1, Review: S

#8528 Remove superfluous JS bundle from opt-out confirmation page (Fixes #8527)
  bedrock/newsletter/templates/newsletter/opt-out-confirmation.html
  media/css/newsletter/newsletter-opt-out-confirmation.scss
Labels: Needs Review, P1, Review: XS

#8531 [fix #8412] Leadership updates
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/alan-davidson-high-res.jpg
  media/img/mozorg/about/leadership/alan-davidson.jpg
  media/img/mozorg/about/leadership/bob-alotta-high-res.jpg
  media/img/mozorg/about/leadership/bob-alotta.jpg
Labels: Needs Review, Review: XS

#8534 Port manifesto page to Protocol (Fixes #8504)
  bedrock/mozorg/templates/mozorg/about/manifesto.html
  media/css/mozorg/manifesto.scss
  media/img/mozorg/about/manifesto/cta-arrow.svg
  media/static-bundles.json
Labels: Needs Review, P3, Review: XS

#8525 Port Yandex download page to Protocol (Fixes #8521)
  bedrock/firefox/templates/firefox/new/download-yandex.html
  bedrock/firefox/templates/firefox/new/trailhead/download.html
  bedrock/firefox/templates/firefox/new/yandex/base.html
  bedrock/firefox/templates/firefox/new/yandex/scene1.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/css/firefox/new/yandex-scene1.scss
  media/img/firefox/new/yandex/browser-high-res.png
  media/img/firefox/new/yandex/browser.png
  media/img/firefox/new/yandex/icon-alert.svg
  media/img/firefox/new/yandex/icon-check.svg
  media/img/firefox/new/yandex/icon-info.svg
  media/img/firefox/new/yandex/wave.svg
  media/js/firefox/new/yandex/scene1.js
  tests/functional/firefox/new/test_download_yandex.py
  tests/pages/firefox/new/download.py
  tests/pages/regions/download_button.py
  tests/unit/spec/firefox/new/yandex/scene1.js
Labels: P2, Review: S

#8543 Port Nightly /whatsnew page to Protocol (Fixes #8537)
  bedrock/firefox/templates/firefox/nightly_whatsnew.html
  media/css/firefox/whatsnew/header.scss
  media/css/firefox/whatsnew/whatsnew-nightly.scss
  media/img/firefox/whatsnew/fox-tail-small.png
  media/img/firefox/whatsnew/fox-tail.png
  tests/pages/firefox/whatsnew/whatsnew_nightly_70.py
Labels: Needs Review, P3, Review: XS

#8289 Update UITour to take advantage of new FxA capabilities (Fixes #8200)
  media/js/base/mozilla-client.js
  media/js/firefox/whatsnew/account-conditional-ctas.js
  tests/unit/spec/base/mozilla-client.js
Labels: P2, Review: S

#8535 Port MOSS pages to Protocol (Fixes #8505)
  bedrock/mozorg/templates/mozorg/moss/_alittlebitmore.html
  bedrock/mozorg/templates/mozorg/moss/base.html
  bedrock/mozorg/templates/mozorg/moss/foundational-technology.html
  bedrock/mozorg/templates/mozorg/moss/includes/alittlebitmore.html
  bedrock/mozorg/templates/mozorg/moss/index.html
  bedrock/mozorg/templates/mozorg/moss/mission-partners.html
  bedrock/mozorg/templates/mozorg/moss/secure-open-source.html
  media/css/mozorg/moss.scss
  media/css/mozorg/moss/common.scss
  media/js/mozorg/moss.js
  media/static-bundles.json
Labels: Needs Review, P3, Review: S

#8553 Remove about/partnerships/distribution template (Fixes #8552)
  bedrock/foundation/redirects.py
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/partnerships-distribution.html
  bedrock/mozorg/urls.py
  media/css/mozorg/partnerships-distribution.scss
  media/static-bundles.json
Labels: Needs Review, P3, Review: XS

#8542 Remove old /whatsnew templates (Fixes #8538)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.0.5.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx67.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68-trailhead.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx68.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx69.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-67.0.5.scss
  media/css/firefox/whatsnew/whatsnew-67.scss
  media/css/firefox/whatsnew/whatsnew-69.scss
  media/img/firefox/whatsnew_67/WNP-PDP-icon.svg
  media/img/firefox/whatsnew_67/WNP-knowledge-icon.svg
  media/img/firefox/whatsnew_67/avatar.svg
  media/img/firefox/whatsnew_67/experiments.svg
  media/img/firefox/whatsnew_67/heart_glyph.svg
  media/img/firefox/whatsnew_67/inbox.svg
  media/img/firefox/whatsnew_67/lockwise-qr.png
  media/img/firefox/whatsnew_67/lockwise.svg
  media/img/firefox/whatsnew_67/lockwise_glyph.png
  media/img/firefox/whatsnew_67/lockwise_glyph.svg
  media/img/firefox/whatsnew_67/monitor.svg
  media/img/firefox/whatsnew_67/noodles.png
  media/img/firefox/whatsnew_67/pocket-qr.png
  media/img/firefox/whatsnew_67/pocket.svg
  media/img/firefox/whatsnew_67/protects_glyph.svg
  media/img/firefox/whatsnew_67/send.svg
  media/img/firefox/whatsnew_67/send_glyph.png
  media/img/firefox/whatsnew_67/send_glyph.svg
  media/img/firefox/whatsnew_67/update.svg
  media/js/firefox/whatsnew/whatsnew-67.js
  media/js/firefox/whatsnew/whatsnew-69.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_67.py
  tests/functional/firefox/whatsnew/test_whatsnew_67_0_5.py
  tests/functional/firefox/whatsnew/test_whatsnew_68.py
  tests/functional/firefox/whatsnew/test_whatsnew_69.py
  tests/pages/firefox/whatsnew/whatsnew_67.py
  tests/pages/firefox/whatsnew/whatsnew_67_0_5.py
  tests/pages/firefox/whatsnew/whatsnew_68.py
  tests/pages/firefox/whatsnew/whatsnew_69.py
Labels: Needs Review, P3, Review: XS

#8559 Update the TOS and PN for FPN (Fixes #8558)
  bedrock/legal/templates/legal/terms/firefox-private-network.html
  bedrock/privacy/templates/privacy/notices/firefox-private-network.html
Labels: P1

#8582 [#7574] Small copy fixes for browser comparison pages
  bedrock/firefox/templates/firefox/compare/chrome.html
  bedrock/firefox/templates/firefox/compare/edge.html
  bedrock/firefox/templates/firefox/compare/ie.html
  bedrock/firefox/templates/firefox/compare/opera.html
  bedrock/firefox/templates/firefox/compare/safari.html
Labels: Needs Review, Review: XS

#8587 Fix broken accounts links on /products and /browsers/ (Fixes #8586)
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/products/index.html
  media/static-bundles.json
Labels: Bug :bug:, P2, Review: XS

#8583 Scale Structured data to locales (Fixes #8522)
  bedrock/base/templates/base-pebbles.html
  bedrock/base/templates/includes/structured-data/breadcrumb/new.json
  bedrock/base/templates/includes/structured-data/organizations/mozilla-corporation-organisation.json
  bedrock/base/templates/includes/structured-data/software/firefox-android-software.json
  bedrock/base/templates/includes/structured-data/software/firefox-beta-software.json
  bedrock/base/templates/includes/structured-data/software/firefox-browser-software.json
  bedrock/base/templates/includes/structured-data/software/firefox-developer-software.json
  bedrock/base/templates/includes/structured-data/software/firefox-enterprise-software.json
  bedrock/base/templates/includes/structured-data/software/firefox-fire-tv-software.json
  bedrock/base/templates/includes/structured-data/software/firefox-ios-software.json
  bedrock/base/templates/includes/structured-data/software/firefox-linux-software.json
  bedrock/base/templates/includes/structured-data/software/firefox-lite-software.json
  bedrock/base/templates/includes/structured-data/software/firefox-lockwise-software.json
  bedrock/base/templates/includes/structured-data/software/firefox-mac-software.json
  bedrock/base/templates/includes/structured-data/software/firefox-monitor-software.json
  bedrock/base/templates/includes/structured-data/software/firefox-nightly-software.json
  bedrock/base/templates/includes/structured-data/software/firefox-send-software.json
  bedrock/base/templates/includes/structured-data/software/firefox-windows-software.json
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/home/index-quantum.html
  bedrock/firefox/templates/firefox/lockwise/lockwise.html
  bedrock/firefox/templates/firefox/new/trailhead/download.html
  bedrock/firefox/templates/firefox/products/index.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/settings/appstores.py
  bedrock/settings/base.py
Labels: Needs Review, P1, Review: S

#8580 Port Facebook Container page to Protocol (Fixes #8554, #5766)
  bedrock/firefox/templates/firefox/facebookcontainer/index.html
  media/css/firefox/facebook-container.scss
  media/css/pebbles/components/_video-poster.scss
Labels: P3
