Repository mozilla/bedrock, pull requests merged in 2021-02, with the labels that each got.

#9885 Remove new-redesign switch (no bug)
  bedrock/firefox/views.py
Labels: Needs Review, P2, Review: µ

#9867 Update links to sync and accounts (Fix #9860)
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/mobile/index.html
  tests/redirects/map_globalconf.py
Labels: Needs Review, P3, Review: µ

#9850 Migrate error pages to Fluent (Fixes #9807) [skip l10n]
  bedrock/base/templates/404.html
  bedrock/base/templates/500.html
  bedrock/base/views.py
  l10n/en/404.ftl
  l10n/en/500.ftl
  lib/fluent_migrations/404.py
  lib/fluent_migrations/500.py
Labels: Needs Review, P3, Review: XS

#9897 Update jquery libs (Fixes #9892)
  media/js/libs/jquery-1.11.3.min.js
  media/js/libs/jquery-1.12.4.min.js
  media/js/libs/jquery-3.4.1.min.js
  media/js/libs/jquery-3.5.1.min.js
  media/static-bundles.json
  tests/unit/karma.conf.js
Labels: Needs Review, P2, Review: XS

#9907 Leadership page, update Roxi’s bio [fix #9906]
  bedrock/mozorg/templates/mozorg/about/leadership.html
Labels: Needs Review, Review: µ

#9889 Migrate /privacy pages to Fluent
  bedrock/privacy/templates/privacy/base-protocol.html
  bedrock/privacy/templates/privacy/faq.html
  bedrock/privacy/templates/privacy/index.html
  bedrock/privacy/templates/privacy/principles.html
  bedrock/privacy/urls.py
  bedrock/privacy/views.py
  docs/fluent-conversion.rst
  l10n/configs/pontoon.toml
  l10n/en/brands.ftl
  l10n/en/privacy/faq.ftl
  l10n/en/privacy/index.ftl
  l10n/en/privacy/principles.ftl
  lib/fluent_migrations/privacy/__init__.py
  lib/fluent_migrations/privacy/faq.py
  lib/fluent_migrations/privacy/index.py
  lib/fluent_migrations/privacy/principles.py
Labels: L10N, Review: XS

#9891 Migrate /legal pages to Fluent (Fixes #9808)
  bedrock/legal/templates/legal/docs-base.html
  bedrock/legal/templates/legal/eula.html
  bedrock/legal/templates/legal/eula/firefox-2-eula.html
  bedrock/legal/templates/legal/eula/firefox-3-eula.html
  bedrock/legal/templates/legal/eula/thunderbird-1.5-eula.html
  bedrock/legal/templates/legal/eula/thunderbird-2-eula.html
  bedrock/legal/templates/legal/fraud-report.html
  bedrock/legal/templates/legal/index.html
  bedrock/legal/templates/legal/report-infringement.html
  bedrock/legal/templates/legal/terms/acceptable-use.html
  bedrock/legal/templates/legal/terms/betterweb.html
  bedrock/legal/templates/legal/terms/firefox-lite-reward.html
  bedrock/legal/templates/legal/terms/firefox-lite.html
  bedrock/legal/templates/legal/terms/firefox-private-network.html
  bedrock/legal/templates/legal/terms/firefox-reality.html
  bedrock/legal/templates/legal/terms/firefox-relay.html
  bedrock/legal/templates/legal/terms/firefox.html
  bedrock/legal/templates/legal/terms/mozilla-vpn.html
  bedrock/legal/templates/legal/terms/mozilla.html
  bedrock/legal/templates/legal/terms/services.html
  bedrock/legal/templates/legal/terms/thunderbird.html
  bedrock/legal/templates/legal/terms/vpn.html
  bedrock/legal/urls.py
  bedrock/legal_docs/views.py
  l10n/configs/pontoon.toml
  l10n/en/mozorg/about/legal.ftl
  lib/fluent_migrations/legal/__init__.py
  lib/fluent_migrations/legal/index.py
Labels: P3, Review: XS

#9913 Fix Fluent string translations for privacy/archive pages (Fixes #9912)
  bedrock/privacy/templates/privacy/archive/base-resp.html
  bedrock/privacy/templates/privacy/archive/firefox-cliqz-2018-06.de.html
  bedrock/privacy/templates/privacy/archive/firefox-cliqz-2018-06.html
  bedrock/privacy/templates/privacy/archive/index.html
  bedrock/privacy/templates/privacy/base-protocol.html
  bedrock/privacy/urls.py
Labels: Needs Review, P2, Review: XS

#9914 Privacy pages, fix strings [#9388]
  l10n/en/privacy/faq.ftl
  l10n/en/privacy/index.ftl
  l10n/en/privacy/principles.ftl
Labels: Needs Review, Review: µ

#9917 Fix common strings on privacy policies
  bedrock/legal_docs/views.py
Labels: Bug :bug:, Needs Review, Review: µ

#9884 Update design on /new varients (#9266)
  bedrock/firefox/templates/firefox/new/protocol/base_download.html
  bedrock/firefox/templates/firefox/new/trailhead/base.html
  bedrock/firefox/templates/firefox/new/trailhead/download-yandex.html
  bedrock/firefox/templates/firefox/new/trailhead/download.html
  media/css/firefox/new/trailhead/download.scss
Labels: Needs Review, P3, Review: S

#9874 Revise UX/Behavior of Sticky Download Promo
  media/css/firefox/sticky-promo.scss
  media/css/protocol/components/_footer.scss
  media/js/firefox/sticky-promo.js
  tests/functional/firefox/browsers/compare/test_browsers.py
  tests/functional/firefox/browsers/test_best_browser.py
  tests/functional/firefox/browsers/test_browser_history.py
  tests/functional/firefox/browsers/test_incognito_browser.py
  tests/functional/firefox/browsers/test_what_is_a_browser.py
  tests/functional/firefox/browsers/test_windows_64_bit.py
  tests/functional/firefox/features/test_adblocker.py
  tests/functional/firefox/features/test_features.py
  tests/functional/firefox/features/test_landing.py
  tests/functional/firefox/new/test_sticky_promo.py
  tests/functional/firefox/test_home.py
  tests/functional/firefox/test_releasenotes.py
  tests/pages/firefox/browsers/best_browser.py
  tests/pages/firefox/browsers/browser_history.py
  tests/pages/firefox/browsers/compare.py
  tests/pages/firefox/browsers/incognito_browser.py
  tests/pages/firefox/browsers/what_is_a_browser.py
  tests/pages/firefox/browsers/windows_64_bit.py
  tests/pages/firefox/features/adblocker.py
  tests/pages/firefox/features/feature.py
  tests/pages/firefox/features/landing.py
  tests/pages/firefox/home.py
  tests/pages/firefox/new/sticky_promo.py
  tests/pages/firefox/releasenotes.py
Labels: Review: XS

#9919 Migrate Mozilla home page to Fluent (Fixes #9911)
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/templates/mozorg/moss/base.html
  bedrock/mozorg/views.py
  l10n/configs/pontoon.toml
  l10n/en/mozorg/home.ftl
  lib/fluent_migrations/mozorg/home/__init__.py
  lib/fluent_migrations/mozorg/home/home.py
Labels: P3, Review: XS

#9927 Migrate /firefox/retention/thank-you/ to Fluent (Fixes #9811)
  bedrock/firefox/templates/firefox/retention/thank-you.html
  bedrock/firefox/urls.py
  l10n/configs/pontoon.toml
  l10n/en/brands.ftl
  l10n/en/firefox/retention/thank-you.ftl
  lib/fluent_migrations/firefox/retention/__init__.py
  lib/fluent_migrations/firefox/retention/thank-you.py
Labels: Needs Review, P3, Review: XS

#9932 WNP 86 for /de/ and /fr/ (Fixes #9926)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-mobile-qrcode-de.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-mobile-qrcode-de.scss
  media/js/firefox/whatsnew/up-to-date.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_86.py
  tests/pages/firefox/whatsnew/whatsnew_86.py
Labels: P1, Review: XS

#9896 Update Yandex to current /new template (Fix #9883)
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/new/desktop/download_yandex.html
  bedrock/firefox/templates/firefox/new/trailhead/download-yandex.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/css/firefox/new/trailhead/download-yandex.scss
  media/css/firefox/new/yandex/download-yandex.scss
  media/img/firefox/new/yandex/icon-faster.svg
  media/img/firefox/new/yandex/icon-lighter.svg
  media/img/firefox/new/yandex/icon-private.svg
  media/img/firefox/new/yandex/yandex-high-res.jpg
  media/img/firefox/new/yandex/yandex.jpg
  media/js/firefox/new/yandex/show-yandex-init.js
  media/js/firefox/new/yandex/show-yandex.js
  media/static-bundles.json
  tests/functional/firefox/new/test_download_yandex.py
  tests/pages/firefox/new/download.py
  tests/pages/firefox/new/download_yandex.py
  tests/unit/karma.conf.js
  tests/unit/spec/firefox/new/yandex/show-yandex.js
Labels: P2, Review: S

#9936 Add English WNP for Firefox 86 [fix #9933]
  bedrock/firefox/templates/firefox/whatsnew/includes/fx86/hero-devices.svg
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx86-en.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-86.scss
  media/img/firefox/whatsnew/whatsnew86/option-toggle.svg
  media/js/firefox/whatsnew/whatsnew-86.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_86.py
Labels: P1, Review: XS

#9923 Remove legacy installer-help template (Fixes #9818)
  bedrock/firefox/templates/firefox/installer-help-redesign.html
  bedrock/firefox/templates/firefox/installer-help.html
  bedrock/firefox/views.py
  media/css/firefox/installer-help-redesign.scss
  media/css/firefox/installer-help.scss
  media/static-bundles.json
Labels: P3, Review: XS

#9951 Update Performance Regression Policy (Fixes #9947)
  bedrock/mozorg/templates/mozorg/about/governance/policies/regressions.html
Labels: Needs Review, P2, Review: S

#9928 Remove jQuery from JS unit tests
  tests/unit/spec/base/core-datalayer.js
  tests/unit/spec/base/fxa-utm-referral.js
  tests/unit/spec/base/mozilla-fxa.js
  tests/unit/spec/base/mozilla-lazy-load.js
  tests/unit/spec/base/send-to-device.js
  tests/unit/spec/base/stub-attribution-macos.js
  tests/unit/spec/base/stub-attribution.js
Labels: P3, Review: µ

#9921 Remove legacy /contribute page (Fixes #9819)
  bedrock/base/templates/includes/protocol/navigation/menus/whoweare.html
  bedrock/foundation/templates/foundation/annualreport/2010/people.html
  bedrock/foundation/templates/foundation/annualreport/2011.html
  bedrock/foundation/templates/foundation/annualreport/2015/faq.html
  bedrock/foundation/templates/foundation/annualreport/2015/index.html
  bedrock/foundation/templates/foundation/annualreport/2016/index.html
  bedrock/foundation/templates/foundation/annualreport/2017/index.html
  bedrock/foundation/templates/foundation/annualreport/2018/index.html
  bedrock/foundation/templates/foundation/annualreport/2019/index.html
  bedrock/foundation/templates/foundation/openwebfund/thanks.html
  bedrock/legal/templates/legal/index.html
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/about-base.html
  bedrock/mozorg/templates/mozorg/about/history.html
  bedrock/mozorg/templates/mozorg/about/index.html
  bedrock/mozorg/templates/mozorg/about/manifesto-details.html
  bedrock/mozorg/templates/mozorg/about/manifesto.html
  bedrock/mozorg/templates/mozorg/contact/contact-landing.html
  bedrock/mozorg/templates/mozorg/contribute.html
  bedrock/mozorg/templates/mozorg/contribute/contribute-base.html
  bedrock/mozorg/templates/mozorg/contribute/index.html
  bedrock/mozorg/templates/mozorg/mission.html
  bedrock/mozorg/tests/test_views.py
  bedrock/mozorg/urls.py
  bedrock/mozorg/views.py
  bedrock/newsletter/redirects.py
  media/css/mozorg/contribute.scss
  media/css/mozorg/contribute/contribute.scss
  media/img/contribute/video-image.png
  media/img/mozorg/about/poster-i-am.jpg
  media/js/mozorg/contribute/contribute-landing.js
  media/static-bundles.json
Labels: P3, Review: XS

#9959 Remove outdated spaces [fix #9915]
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/contact/contact-base.html
  bedrock/mozorg/templates/mozorg/contact/spaces/includes/nav.html
  bedrock/mozorg/templates/mozorg/contact/spaces/london.html
  bedrock/mozorg/templates/mozorg/contact/spaces/mountain-view.html
  bedrock/mozorg/templates/mozorg/contact/spaces/taipei.html
  bedrock/mozorg/templates/mozorg/contact/spaces/vancouver.html
  bedrock/mozorg/urls.py
  media/css/mozorg/about.scss
  media/img/contact/osm/spaces/all-large-high-res.jpg
  media/img/contact/osm/spaces/all-large.jpg
  media/img/contact/osm/spaces/london-large-high-res.jpg
  media/img/contact/osm/spaces/london-large.jpg
  media/img/contact/osm/spaces/london-small-high-res.png
  media/img/contact/osm/spaces/london-small.png
  media/img/contact/osm/spaces/mountain-view-large-high-res.jpg
  media/img/contact/osm/spaces/mountain-view-large.jpg
  media/img/contact/osm/spaces/mountain-view-small-high-res.png
  media/img/contact/osm/spaces/mountain-view-small.png
  media/img/contact/osm/spaces/taipei-large-high-res.jpg
  media/img/contact/osm/spaces/taipei-large.jpg
  media/img/contact/osm/spaces/taipei-small-high-res.png
  media/img/contact/osm/spaces/taipei-small.png
  media/img/contact/osm/spaces/vancouver-large-high-res.jpg
  media/img/contact/osm/spaces/vancouver-large.jpg
  media/img/contact/osm/spaces/vancouver-small-high-res.png
  media/img/contact/osm/spaces/vancouver-small.png
  media/img/mozorg/about/city-taipei.png
Labels: Needs Review, P2, Review: XS

#9962 Use gender neutral term in privacy/passwords.ftl (Fixes #9909)
  l10n/en/firefox/privacy/passwords.ftl
Labels: Needs Review, P3, Review: µ

#9960 Update /contact/ spaces functional test
  tests/functional/test_contact.py
Labels: Needs Review, Review: µ

#9961 Update /newsletter page copy (Fixes #9935)
  bedrock/newsletter/templates/newsletter/index.html
  l10n/en/mozorg/newsletters.ftl
Labels: Needs Review, P3, Review: µ

#9941 Pass through experiment and variation parameters to FxA links (Issue #9922)
  media/js/base/fxa-utm-referral-init.js
  media/js/base/fxa-utm-referral.js
  tests/unit/spec/base/fxa-utm-referral.js
  tests/unit/spec/ie/mozilla-utils-ie.js
Labels: Needs Review, P2, Review: XS

#9965 [no bug] Add doge logo to FxNightly firstrun and whatsnew pages
  bedrock/firefox/templates/firefox/nightly/firstrun.html
  bedrock/firefox/templates/firefox/nightly/whatsnew.html
  media/css/firefox/firstrun/nightly.scss
  media/css/firefox/whatsnew/whatsnew-nightly.scss
  media/img/logos/firefox/logo-nightdoge-lg-high-res.png
  media/img/logos/firefox/logo-nightdoge-word-hor-white-sm-high-res.png
  media/img/logos/firefox/logo-nightdoge-word-hor-white-sm.png
Labels: Needs Review, Review: µ

#9847 Pass GA visit ID to stub attribution (Fixes #9830)
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/js/base/stub-attribution.js
  tests/unit/spec/base/stub-attribution.js
Labels: Do Not Merge :warning:, Needs Review, Review: XS
