Repository mozilla/bedrock, pull requests merged in 2021-10, with the labels that each got.

#10526 Check for double-encoded RTAMO attribution data (Fixes #10524)
  media/js/base/stub-attribution.js
  tests/unit/spec/base/stub-attribution.js
Labels: P2, Needs Review, Review: XS

#10537 Update VPN copy [fix #10484]
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templates/products/vpn/more/ip-address.html
  bedrock/products/templates/products/vpn/more/what-is-a-vpn.html
  l10n/en/products/vpn/landing.ftl
  l10n/en/products/vpn/more/ip-address.ftl
  l10n/en/products/vpn/more/what-is-a-vpn.ftl
Labels: P1, Needs Review, Review: XS

#10534 Add whatsnew page for Firefox 93 [fix #10495]
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-es.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-it.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-nl.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-v1-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-v2-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-v2-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-v2-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-v3-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-v3-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-v3-fr.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-93.scss
  media/img/firefox/whatsnew/whatsnew93/hero-v1-high-res.png
  media/img/firefox/whatsnew/whatsnew93/hero-v1.png
  media/img/firefox/whatsnew/whatsnew93/hero-v2-de.webm
  media/img/firefox/whatsnew/whatsnew93/hero-v2-en.webm
  media/img/firefox/whatsnew/whatsnew93/hero-v2-fr.webm
  media/img/firefox/whatsnew/whatsnew93/hero-v2-poster-de.jpg
  media/img/firefox/whatsnew/whatsnew93/hero-v2-poster-en.jpg
  media/img/firefox/whatsnew/whatsnew93/hero-v2-poster-fr.jpg
  media/img/firefox/whatsnew/whatsnew93/hero-v3.svg
  media/img/firefox/whatsnew/whatsnew93/hero-v3.webm
  media/js/firefox/whatsnew/whatsnew93-cycle.js
  media/js/firefox/whatsnew/whatsnew93-experiment-en.js
  media/js/firefox/whatsnew/whatsnew93-experiment-fr-de.js
  media/static-bundles.json
  tests/redirects/map_globalconf.py
Labels: P1, Review: S

#10543 String fixes for VPN and Focus pages
  l10n/en/firefox/browsers/mobile/focus.ftl
  l10n/en/products/vpn/more/ip-address.ftl
  l10n/en/products/vpn/more/what-is-a-vpn.ftl
Labels: Needs Review, Review: µ

#10538 Update Focus logo [#10506]
  bedrock/base/templates/includes/protocol/navigation/menus/firefox.html
  media/css/firefox/browsers/mobile.scss
  media/img/logos/firefox/focus-logo-word-hor.svg
  media/img/logos/firefox/focus-logo.svg
Labels: Review: µ

#10546 Copy fix for "what is a vpn" page [#10484]
  bedrock/products/templates/products/vpn/more/what-is-a-vpn.html
  l10n/en/products/vpn/more/what-is-a-vpn.ftl
Labels: Bug :bug:, Needs Review, Review: µ

#10554 Update more Focus logos [fix #10552]
  bedrock/base/templates/includes/banners/mobile/focus-app-store.html
  bedrock/firefox/templates/firefox/browsers/mobile/focus.html
  media/img/banners/mobile/focus-app-icon-512.jpg
  media/img/favicons/firefox/browser/focus/apple-touch-icon.png
  media/img/favicons/firefox/browser/focus/favicon-16x16.png
  media/img/favicons/firefox/browser/focus/favicon-196x196.png
  media/img/favicons/firefox/browser/focus/favicon-32x32.png
  media/img/favicons/firefox/browser/focus/favicon.ico
  media/img/firefox/browsers/mobile/focus/page-image.png
Labels: Needs Review, Review: µ
