Repository mozilla/bedrock, pull requests merged in 2021-11, with the labels that each got.

#10648 Add relay to sticky promo (fixes #10642)
  bedrock/base/templates/includes/sticky-promo.html
  l10n/en/firefox/sticky-promo.ftl
  media/img/logos/relay/logo-white.svg
Labels: P2, Needs Review, Review: XS

#10652 Update VPN landing paging to reflect support for Windows 11 (Fixes #10633)
  bedrock/products/templates/products/vpn/landing.html
  l10n/en/products/vpn/landing.ftl
Labels: P3, Needs Review, Review: µ

#10654 Add home MR2 promo to Pontoon config
  l10n/configs/pontoon.toml
Labels: Bug :bug:, Needs Review, Review: µ

#10655 Add MR2 promo to DE/FR home pages (Fixes #10653)
  bedrock/base/templates/includes/banners/mr1/eu-banner.html
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/products/index.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/templates/mozorg/home/includes/mr2-promo-eu.html
  media/css/base/banners/eu-mr1-banner.scss
  media/img/home/2021/mr2-watercolor-de-high-res.png
  media/img/home/2021/mr2-watercolor-de.png
  media/img/home/2021/mr2-watercolor-fr-high-res.png
  media/img/home/2021/mr2-watercolor-fr.png
  media/js/base/banners/eu-mr1-banner-init.js
  media/static-bundles.json
  tests/functional/test_home.py
Labels: P2, Needs Review, Review: XS

#10659 Remove unused strings on download and Android pages
  l10n/en/firefox/browsers/mobile/android.ftl
  l10n/en/firefox/new/desktop.ftl
Labels: Needs Review, Review: µ

#10608 Use server-side geo-location for VPN landing page (Fixes #10433)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx92-vpn-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx92-vpn-fr.html
  bedrock/firefox/views.py
  bedrock/products/templates/products/vpn/base.html
  bedrock/products/templates/products/vpn/includes/footer-subscribe.html
  bedrock/products/templates/products/vpn/includes/macros.html
  bedrock/products/templates/products/vpn/includes/pricing-variable.html
  bedrock/products/templates/products/vpn/includes/templates.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templates/products/vpn/variations/cta-a.html
  bedrock/products/templates/products/vpn/variations/cta-b.html
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  bedrock/products/tests/test_views.py
  bedrock/products/views.py
  bedrock/settings/base.py
  docs/firefox-accounts.rst
  media/css/firefox/whatsnew/whatsnew-92-vpn.scss
  media/css/products/vpn/common.scss
  media/css/products/vpn/components/block.scss
  media/js/products/vpn/cta-change-experiment.js
  media/js/products/vpn/geo.js
  media/js/products/vpn/landing.js
  media/static-bundles.json
  tests/functional/products/vpn/test_landing.py
  tests/pages/products/vpn/landing.py
  tests/unit/karma.conf.js
  tests/unit/spec/vpn/geo.js
Labels: P2, Review: S

#10671 Make MR2 home promo styles more specific [#10620]
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/templates/mozorg/home/includes/mr2-promo-eu.html
  bedrock/mozorg/templates/mozorg/home/includes/mr2-promo.html
  media/css/mozorg/home/home-mr2-promo.scss
Labels: Bug :bug:, Needs Review, Review: µ

#10674 Update to Protocol 15.1.0
  bedrock/base/templates/includes/protocol/navigation/menus/products.html
  bedrock/base/templates/includes/sticky-promo.html
  media/img/logos/relay/logo-white.svg
  media/img/nav/icons/icon-relay-beta.svg
  media/img/nav/icons/icon-relay.svg
  package-lock.json
  package.json
Labels: Needs Review, Review: µ

#10665 Fix Contentful CTAs (fixes #10661, #10662)
  bedrock/contentful/templates/includes/contentful/cta.html
Labels: Needs Review, Review: XS, Contentful

#10680 Remove duplicated </main> tag
  bedrock/mozorg/templates/mozorg/contentful-homepage.html
Labels: Bug :bug:, Needs Review, Review: µ

#10679 Add Relay wordmark to Contentful home CSS
  media/css/contentful/firefox/c-logo.scss
  media/css/contentful/general.scss
  media/css/contentful/mozilla/c-logo.scss
  media/css/mozorg/home/home-contentful-en.scss
Labels: Needs Review, Review: XS, Contentful

#10681 Remove whats-new-page geo redirects (Fixes #10590)
  bedrock/base/tests/test_views.py
  bedrock/base/views.py
  bedrock/exp/urls.py
  bedrock/firefox/redirects.py
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  docs/coding.rst
  l10n/en/firefox/developer.ftl
  l10n/en/firefox/nightly/whatsnew.ftl
  l10n/en/firefox/whatsnew/whatsnew-account.ftl
  l10n/en/firefox/whatsnew/whatsnew-s2d.ftl
  l10n/en/firefox/whatsnew/whatsnew.ftl
  tests/pages/firefox/whatsnew/whatsnew.py
  tests/pages/firefox/whatsnew/whatsnew_60.py
  tests/pages/firefox/whatsnew/whatsnew_91.py
  tests/pages/firefox/whatsnew/whatsnew_92.py
  tests/pages/firefox/whatsnew/whatsnew_developer_70.py
  tests/pages/firefox/whatsnew/whatsnew_nightly_70.py
  tests/redirects/map_globalconf.py
Labels: P2, Needs Review, Review: XS

#10684 Ignore noisy non-actionable JS errors (Fixes #10683)
  media/js/base/sentry.es6.js
Labels: P3, Needs Review

#10548 Update VPN Already a subscriber? link url (Fixes #10535)
  bedrock/products/templates/products/vpn/includes/macros.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  bedrock/products/views.py
  docs/firefox-accounts.rst
  l10n/en/products/vpn/landing.ftl
  media/css/products/vpn/landing.scss
Labels: P3, Needs Review, Review: XS

#10675 External pocket pages: "Add" page
  bedrock/externalpages/templates/externalpages/pocket/add.html
  media/css/externalpages/pocket/components/_about.scss
  media/css/externalpages/pocket/components/_add.scss
  media/css/externalpages/pocket/style.scss
  media/css/externalpages/pocket/utils/_tokens.scss
  media/css/externalpages/pocket/utils/_variables.scss
  media/img/externalpages/pocket/add-any-device.jpg
  media/img/externalpages/pocket/add-pocket-header.jpg
  media/img/externalpages/pocket/apple-mac-store-badge.svg
  media/img/externalpages/pocket/save-via-email.png
Labels: Needs Review, Fire :fire:

#10705 Update links to point to FxA staging when Dev=True (#10670)
  bedrock/settings/base.py
  docs/firefox-accounts.rst
  media/js/base/fxa-utm-referral.js
  media/js/base/mozilla-fxa-link.js
  media/js/base/mozilla-fxa-product-button.js
Labels: P2, Needs Review, Review: µ

#10710 Enable firefox/welcome/10 for L10n (Fixes #10708)
  bedrock/firefox/templates/firefox/welcome/page10.html
  bedrock/firefox/urls.py
  l10n/configs/pontoon.toml
  l10n/en/firefox/welcome/page10.ftl
Labels: P1, Needs Review, Review: XS

#10716 Add Erwin and Muhlheim to leadership page [fix bug 1739206]
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/eric-muhlheim-high-res.jpg
  media/img/mozorg/about/leadership/eric-muhlheim.jpg
  media/img/mozorg/about/leadership/marshall-erwin-high-res.jpg
  media/img/mozorg/about/leadership/marshall-erwin.jpg
Labels: Needs Review, Review: µ

#10689 Supress JS errors thrown when YouTube is blocked (Fixes #10202)
  media/js/firefox/features/picture-in-picture.js
  media/js/firefox/features/tips/tips-youtube.js
  media/js/mozorg/home/youtube.js
Labels: P3, Needs Review, Review: µ

#10707 Update VPN guarantee copy (Fixes #10696)
  bedrock/products/templates/products/vpn/includes/macros.html
  bedrock/products/templates/products/vpn/includes/pricing-variable.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templates/products/vpn/more/base-article.html
  bedrock/products/templates/products/vpn/platforms/android.html
  bedrock/products/templates/products/vpn/platforms/desktop.html
  bedrock/products/templates/products/vpn/platforms/ios.html
  bedrock/products/templates/products/vpn/platforms/linux.html
  bedrock/products/templates/products/vpn/platforms/mac.html
  bedrock/products/templates/products/vpn/platforms/mobile.html
  bedrock/products/templates/products/vpn/platforms/windows.html
  l10n/en/products/vpn/landing.ftl
  media/css/products/vpn/common.scss
  media/css/products/vpn/landing.scss
Labels: P1, Needs Review, Review: XS

#10714 Clean Protocol CSS (fixes #10682)
  bedrock/contentful/templates/includes/contentful/css.html
  media/css/contentful/c-logo.scss
  media/css/contentful/firefox/c-card.scss
  media/css/contentful/general.scss
  media/css/contentful/mozilla/c-card.scss
  media/css/contentful/mozilla/c-logo.scss
  media/css/firefox/facebook-container.scss
  media/css/firefox/installer-help.scss
  media/css/firefox/lockwise/lockwise.scss
  media/css/firefox/new/desktop/download.scss
  media/css/firefox/pocket.scss
  media/css/firefox/privacy/common.scss
  media/css/firefox/privacy/products.scss
  media/css/firefox/sync.scss
  media/css/firefox/whatsnew/whatsnew-92-de.scss
  media/css/firefox/whatsnew/whatsnew-92-en.scss
  media/css/firefox/whatsnew/whatsnew-92-fr.scss
  media/css/mozorg/about.scss
  media/css/mozorg/contribute.scss
  media/css/mozorg/home/home-2018.scss
  media/css/mozorg/home/home-en.scss
  media/css/mozorg/lean-data.scss
  media/css/mozorg/moss.scss
  media/css/newsletter/newsletter.scss
  media/css/protocol/protocol-firefox.scss
  media/css/protocol/protocol-mozilla.scss
  media/static-bundles.json
Labels: P3, Needs Review, Review: S

#10719 Remove geo-location json endpoint (Fixes #10688)
  bedrock/base/templates/base-protocol.html
  bedrock/base/tests/test_views.py
  bedrock/base/views.py
  bedrock/settings/base.py
  bedrock/urls.py
  media/js/base/mozilla-traffic-cop-funnelcake-geo.js
  test_infra/test_cdn.py
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-traffic-cop-funnelcake-geo.js
Labels: P3, Needs Review, Review: XS

#10725 Check translation status when showing MR2 copy on /new (Fixes #10724|
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  l10n/en/firefox/new/desktop.ftl
Labels: P2, Needs Review, Review: µ

#10727 10593: Add support for an optional frontend-specific Sentry DSN
  bedrock/base/templates/base-protocol.html
  bedrock/settings/base.py
Labels: Infra, Papercuts 💸, Needs Review, Review: µ

#10729 Update to Protocol 16.0.0
  bedrock/contentful/api.py
  bedrock/firefox/templates/firefox/browsers/mobile/android.html
  bedrock/firefox/templates/firefox/browsers/mobile/focus.html
  bedrock/firefox/templates/firefox/browsers/mobile/ios.html
  bedrock/firefox/templates/firefox/features/index.html
  bedrock/firefox/templates/firefox/mobile/index.html
  bedrock/firefox/templates/firefox/privacy/book.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/build-security.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/engage-users.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/index.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/stay-lean.html
  package-lock.json
  package.json
Labels: Needs Review, Review: XS

#10728 Leadership page, add Imo Udom to steering committee [no bug]
  bedrock/mozorg/templates/mozorg/about/leadership.html
Labels: Needs Review, Review: µ

#10718 Remove unrelated JS bundle from safe-passwords page (Fixes #10717)
  bedrock/firefox/templates/firefox/privacy/passwords.html
Labels: P3, Needs Review, Review: µ

#10694 Fix error thrown by isFirefoxUpToDate when no version number is found (Fixes #10582)
  media/js/base/mozilla-client.js
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-client.js
Labels: P3, Review: µ

#10739 Update Twitter social links for DE/FR (fix bug 1740912)
  bedrock/base/templates/includes/protocol/footer/footer.html
  bedrock/base/templates/includes/structured-data/organizations/mozilla-corporation-organisation.json
  bedrock/mozorg/templates/mozorg/contact/contact-landing.html
  bedrock/mozorg/templates/mozorg/contribute.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/newsletter/templates/newsletter/opt-out-confirmation.html
  bedrock/settings/base.py
Labels: P3, Needs Review, Review: XS

#10770 Remove unnecessary class being added to paragraphs (Fixes #10768)
  bedrock/contentful/api.py
Labels: P2, Needs Review, Review: µ

#10747 10711: Update Contentful sync to delete absent pages from sqlite
  bedrock/contentful/constants.py
  bedrock/contentful/management/commands/update_contentful.py
  bedrock/contentful/tests/test_commands.py
Labels: Needs Review, Review: S

#10786 Fix spacing issue on VRC landing page (Fixes #10777)
  bedrock/products/templates/products/vpn/resource-center/landing.html
Labels: P3, Needs Review, Review: µ

#10732 Add fundraising 2021 banner to home page (Fixes #10700)
  bedrock/base/templates/includes/banners/fundraiser.html
  bedrock/mozorg/templates/mozorg/contentful-homepage.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/views.py
  bedrock/settings/base.py
  l10n/en/banners/fundraising.ftl
  media/css/base/banners/fundraiser.scss
  media/img/banners/fundraising/fundraising-bg-blue-high-res.jpg
  media/img/banners/fundraising/fundraising-bg-blue.jpg
  media/js/mozorg/home/banner-init.js
Labels: P1, Review: S

#10798 Update Fluent file for exp home page [no bug]
  bedrock/exp/views.py
Labels: Bug :bug:, P3, Needs Review, Review: µ

#10745 Add moment page 11 for VPN [fix #10737]
  bedrock/firefox/templates/firefox/welcome/includes/page11/cart.svg
  bedrock/firefox/templates/firefox/welcome/includes/page11/globe.svg
  bedrock/firefox/templates/firefox/welcome/includes/page11/lock.svg
  bedrock/firefox/templates/firefox/welcome/page11.html
  bedrock/firefox/urls.py
  l10n/configs/pontoon.toml
  l10n/en/firefox/welcome/page11.ftl
  media/css/firefox/welcome11.scss
  media/static-bundles.json
  tests/functional/firefox/welcome/test_welcome_page11.py
  tests/pages/firefox/welcome/page11.py
Labels: P1, Review: XS

#10789 Use image description for alt text in Contentful (Fixes #10787)
  bedrock/contentful/api.py
Labels: P3, Needs Review, Review: µ

#10788 Add default bottom margin to VRC images served in Contewntful articles (Fixes #10769)
  media/css/products/vpn/resource-center.scss
Labels: P3, Needs Review, Review: µ

#10805 Improve Contentful-related test coverage - part 2 of n
  bedrock/contentful/api.py
  bedrock/contentful/templatetags/helpers.py
  bedrock/contentful/tests/test_contentful_api.py
  bedrock/contentful/tests/test_templatetags_helpers.py
  setup.cfg
Labels: Needs Review, Review: µ

#10806 10778: Add support for VRC pages to sitemap
  bedrock/contentful/constants.py
  bedrock/sitemaps/tests/test_utils.py
  bedrock/sitemaps/utils.py
Labels: Needs Review, Review: XS

#10804 Update bedrock to NodeJS to v16 (Fixes #10803)
  .circleci/config.yml
  Dockerfile
  package-lock.json
Labels: P2, Needs Review, Review: µ

#10790 Pocket platform pages
  bedrock/externalpages/templates/externalpages/pocket/add.html
  bedrock/externalpages/templates/externalpages/pocket/android.html
  bedrock/externalpages/templates/externalpages/pocket/chrome.html
  bedrock/externalpages/templates/externalpages/pocket/edge.html
  bedrock/externalpages/templates/externalpages/pocket/ios.html
  bedrock/externalpages/templates/externalpages/pocket/opera.html
  bedrock/externalpages/templates/externalpages/pocket/platform-pages.html
  bedrock/externalpages/templates/externalpages/pocket/safari.html
  bedrock/externalpages/urls.py
  media/css/externalpages/pocket/components/_add.scss
  media/css/externalpages/pocket/components/_platforms.scss
  media/css/externalpages/pocket/utils/_variables.scss
  media/img/externalpages/pocket/welcome-android.jpg
  media/img/externalpages/pocket/welcome-chrome.jpg
  media/img/externalpages/pocket/welcome-edge.jpg
  media/img/externalpages/pocket/welcome-ios.jpg
  media/img/externalpages/pocket/welcome-opera.jpg
  media/img/externalpages/pocket/welcome-safari.jpg
  media/static-bundles.json
Labels: Needs Review, Review: S

#10822 Update Windows platform string on VPN waitlist page (Fixes #10819)
  bedrock/products/templates/products/vpn/invite.html
  l10n/en/products/vpn/landing.ftl
Labels: P3, Needs Review, Review: µ

#10816 WNP 95 for /de/ (Fixes #10800)
  bedrock/firefox/templates/firefox/whatsnew/includes/fx95-de/best-of-2021.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx95-de/save.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx95-de/top-5.svg
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx95-de.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-95-de.scss
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_95.py
  tests/pages/firefox/whatsnew/whatsnew_95.py
Labels: P1, Needs Review, Review: XS

#10833 Add docs for how to install new Python dependencies (Fixes #10831)
  docs/coding.rst
Labels: P3, Needs Review, Review: µ

#10840 Update utm_campaign for 2021 fundraising banner (Issue #10700)
  bedrock/base/templates/includes/banners/fundraiser.html
Labels: Needs Review, Review: µ

#10817 Make update commands alert to sentry on exceptions
  bedrock/base/management/commands/update_www_config.py
  bedrock/contentcards/management/commands/update_content_cards.py
  bedrock/contentful/management/commands/update_contentful.py
  bedrock/externalfiles/management/commands/update_externalfiles.py
  bedrock/legal_docs/management/commands/update_legal_docs.py
  bedrock/mozorg/management/commands/update_product_details_files.py
  bedrock/newsletter/management/commands/update_newsletter_data.py
  bedrock/pocketfeed/management/commands/update_pocketfeed.py
  bedrock/releasenotes/management/commands/update_release_notes.py
  bedrock/security/management/commands/update_security_advisories.py
  bedrock/sitemaps/management/commands/update_sitemaps_data.py
  bedrock/utils/management/decorators.py
  bedrock/utils/tests/test_decorators.py
  bedrock/wordpress/management/commands/update_wordpress.py
Labels: Review: XS
