Repository mozilla/bedrock, pull requests merged in 2021-09, with the labels that each got.

#10406 Change global navbar CTA (Fixes #10403)
  bedrock/base/templates/includes/protocol/navigation/nav-cta.html
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/products/templates/products/vpn/invite.html
  l10n/en/navigation_v2.ftl
  tests/functional/test_navigation.py
  tests/pages/base.py
Labels: P1, Needs Review, Review: XS

#10412 Fix split call on dev edition pages [no bug]
  bedrock/base/templates/macros-protocol.html
  bedrock/firefox/templates/firefox/developer/includes/for-developers.html
  bedrock/firefox/templates/firefox/developer/includes/performance.html
Labels: Bug :bug:, Needs Review, Review: µ

#10414 Update id param in Split macro calls [no bug]
  bedrock/firefox/templates/firefox/pocket.html
  bedrock/firefox/templates/firefox/privacy/book.html
  bedrock/foundation/templates/foundation/annualreport/2019/index.html
Labels: Bug :bug:, Needs Review, Review: µ

#10417 Turn shared VPN string in multiple contexts into separate strings
  bedrock/products/templates/products/vpn/includes/pricing-variable.html
  l10n/en/products/vpn/shared.ftl
Labels: P3, Needs Review, Review: µ

#10415 Add whatsnew page for Firefox 92.0 EN, FR [fix #10402]
  bedrock/firefox/templates/firefox/whatsnew/includes/fx92/illo-vpn-lock.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx92/illo-vpn-speed.svg
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx92-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx92-vpn-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx92-vpn-fr.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  bedrock/products/templates/products/vpn/includes/pricing-variable.html
  media/css/firefox/whatsnew/whatsnew-92-en.scss
  media/css/firefox/whatsnew/whatsnew-92-vpn.scss
  media/img/firefox/whatsnew/whatsnew92/vpn-one-tap.svg
  media/img/firefox/whatsnew/whatsnew92/vpn-private.svg
  media/img/firefox/whatsnew/whatsnew92/vpn-speed.svg
  media/static-bundles.json
Labels: P1, Review: XS

#10419 Add additional Pocket Collections to WNP 92 DE (Issue #10394)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx92-de.html
  media/img/firefox/whatsnew/whatsnew92/collection-1-high-res.jpg
  media/img/firefox/whatsnew/whatsnew92/collection-1.jpg
  media/img/firefox/whatsnew/whatsnew92/collection-4-high-res.jpg
  media/img/firefox/whatsnew/whatsnew92/collection-4.jpg
Labels: P2, Needs Review, Review: µ

#10420 FxA metrics calls should pass through utm_medium (Fixes #10418)
  media/js/base/mozilla-fxa-product-button.js
  tests/unit/spec/base/mozilla-fxa-product-button.js
Labels: P1, Needs Review, Review: µ

#10423 Nightly /whatsnew page show incorrect content to users in France (Fixes #10422)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx92-fr.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
Labels: P1, Needs Review, Review: µ

#10416 Added a new subsection Working with Protocol
  docs/coding.rst
Labels: P3, Documentation, Review: XS

#10448 Fix youtube_id on contentful cards (Fixes #10442)
  bedrock/contentful/templates/includes/contentful/all.html
Labels: Bug :bug:, Needs Review, Review: µ

#10455 Added Documentation section under Make it Run (fixes #10452)
  docs/install.rst
Labels: Review: µ

#10397 VPN Pages for the Firefox product team
  bedrock/products/templates/products/vpn/more/do-i-need.html
  bedrock/products/templates/products/vpn/more/what-is-a-vpn-v2.html
  bedrock/products/templates/products/vpn/more/why-mozilla-vpn.html
  bedrock/products/urls.py
  media/css/products/vpn/vpn-info.scss
  media/js/base/fxa-utm-referral.js
  media/static-bundles.json
Labels: P1, Review: S

#10454 Implement attribution flow for VPN subscription referrals (Fixes #10409)
  bedrock/base/templates/includes/protocol/navigation/nav-cta.html
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  docs/firefox-accounts.rst
  media/css/protocol/components/_navigation-ie.scss
  media/css/protocol/components/_navigation.scss
  media/js/base/fxa-utm-referral.js
  media/js/base/mozilla-cookie-helper.js
  tests/pages/base.py
  tests/unit/spec/base/fxa-utm-referral.js
Labels: P2, Review: XS

#10463 Update VPN variation to include months
  bedrock/products/templates/products/vpn/variations/cta-b.html
  media/js/products/vpn/cta-change-experiment.js
Labels: P2

#10472 String fixes for mobile pages [mozilla-l10n/www-l10n #229]
  bedrock/firefox/templates/firefox/browsers/mobile/compare.html
  l10n/en/firefox/browsers/mobile/android.ftl
  l10n/en/firefox/browsers/mobile/compare.ftl
  l10n/en/firefox/browsers/mobile/focus.ftl
  l10n/en/firefox/browsers/mobile/index.ftl
Labels: Needs Review, Review: µ

#10476 Fluent fixes [fix #10474, #10475]
  l10n/en/firefox/browsers/mobile/focus.ftl
  l10n/en/firefox/facebook_container.ftl
Labels: Needs Review, Review: µ

#10480 Update comment links for external docs (Fixes #10458)
  bedrock/base/views.py
  media/js/base/fxa-utm-referral.js
Labels: Needs Review, Review: µ

#10481 More string fixes for mobile pages [fix #10477]
  bedrock/firefox/templates/firefox/browsers/mobile/compare.html
  bedrock/firefox/templates/firefox/browsers/mobile/ios.html
  l10n/en/firefox/browsers/mobile/compare.ftl
  l10n/en/firefox/browsers/mobile/ios.ftl
  l10n/en/firefox/facebook_container.ftl
Labels: Needs Review, Review: µ

#10485 Update Impressum page (Fixes #10483)
  bedrock/legal/templates/legal/impressum.html
Labels: P1, Needs Review, Review: µ

#10491 Contentful: Card components font size is too big (Fixes #10444)
  bedrock/contentful/templates/includes/contentful/all.html
Labels: P3, Needs Review, Review: µ

#10478 Add Babel as a transpiling option for JS bundles (Fixes #10467)
  .eslintrc.js
  docs/coding.rst
  media/js/foundation/annual-report-2019.es6.js
  media/js/foundation/annual-report-2019.js
  media/static-bundles.json
  package.json
  tests/unit/karma.conf.js
  webpack.config.js
  yarn.lock
Labels: Needs Review, Review: XS

#10493 Update JS test dependencies and spec (fixes #10492)
  .eslintrc.js
  package.json
  tests/unit/spec/base/core-datalayer-page-id.js
  tests/unit/spec/base/core-datalayer.js
  tests/unit/spec/base/dnt-helper.js
  tests/unit/spec/base/fxa-utm-referral.js
  tests/unit/spec/base/mozilla-banner.js
  tests/unit/spec/base/mozilla-client.js
  tests/unit/spec/base/mozilla-convert.js
  tests/unit/spec/base/mozilla-fxa-form.js
  tests/unit/spec/base/mozilla-fxa-link.js
  tests/unit/spec/base/mozilla-fxa-product-button.js
  tests/unit/spec/base/mozilla-fxa.js
  tests/unit/spec/base/mozilla-lazy-load.js
  tests/unit/spec/base/mozilla-pixel.js
  tests/unit/spec/base/mozilla-run.js
  tests/unit/spec/base/mozilla-traffic-cop-funnelcake-geo.js
  tests/unit/spec/base/mozilla-utils.js
  tests/unit/spec/base/search-params.js
  tests/unit/spec/base/send-to-device.js
  tests/unit/spec/base/stub-attribution.js
  tests/unit/spec/firefox/all/all-downloads-unified.js
  tests/unit/spec/firefox/new/common/thanks.js
  tests/unit/spec/firefox/new/yandex/show-yandex.js
  tests/unit/spec/vpn/geo.js
  yarn.lock
Labels: P3, Needs Review, Review: S

#10489 Update to Protocol 14.1.0
  bedrock/firefox/templates/firefox/browsers/chromebook.html
  bedrock/firefox/templates/firefox/browsers/quantum.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/facebookcontainer/index.html
  bedrock/firefox/templates/firefox/faq.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/more.html
  bedrock/firefox/templates/firefox/more/misinformation.html
  bedrock/firefox/templates/firefox/pocket.html
  bedrock/firefox/templates/firefox/privacy/index.html
  bedrock/firefox/templates/firefox/products/lockwise.html
  bedrock/firefox/templates/firefox/switch.html
  bedrock/firefox/templates/firefox/sync.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx90-eu.html
  bedrock/foundation/templates/foundation/annualreport/2019/index.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  media/css/firefox/browsers/chromebook.scss
  media/css/firefox/browsers/mobile.scss
  media/css/firefox/browsers/quantum.scss
  media/css/firefox/enterprise/landing.scss
  media/css/firefox/facebook-container.scss
  media/css/firefox/faq.scss
  media/css/firefox/home/master.scss
  media/css/firefox/lockwise/lockwise.scss
  media/css/firefox/mobile/mobile.scss
  media/css/firefox/more.scss
  media/css/firefox/more/misinformation.scss
  media/css/firefox/pocket.scss
  media/css/firefox/privacy/book.scss
  media/css/firefox/privacy/products.scss
  media/css/firefox/privacy/promise.scss
  media/css/firefox/seo.scss
  media/css/firefox/switch.scss
  media/css/firefox/sync.scss
  media/css/firefox/whatsnew/whatsnew-90-eu.scss
  media/css/foundation/annual-report-2019.scss
  media/css/mozorg/about.scss
  media/css/mozorg/contribute.scss
  media/img/firefox/pocket/pocket-hero-high-res.png
  media/img/firefox/pocket/pocket-hero.png
  package.json
  yarn.lock
Labels: Review: S

#10499 Remove WNP 87/88 VPN waitlist pages (Fixes #10497)
  bedrock/firefox/templates/firefox/whatsnew/includes/fx87/illo-vpn-laptop.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx87/illo-vpn-mobile.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx87/mozilla-vpn-logo.svg
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx87-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx87-fr.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-87-eu-vpn.scss
  media/js/firefox/whatsnew/whatsnew-87-eu-vpn.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_87.py
  tests/pages/firefox/whatsnew/whatsnew_87.py
Labels: P2, Needs Review, Review: XS

#10511 Fix string ID on Android page [fix #10510]
  bedrock/firefox/templates/firefox/browsers/mobile/android.html
Labels: Bug :bug:, Needs Review, Review: µ

#10512 VPN Wave IV country expansion (Fixes #10498)
  bedrock/products/templates/products/vpn/includes/templates.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/views.py
  bedrock/settings/base.py
  l10n/en/products/vpn/shared.ftl
  media/js/products/vpn/geo.js
  tests/unit/spec/vpn/geo.js
Labels: P1, Needs Review, Review: S

#10516 Remove outdated VPN country strings (#10498)
  l10n/en/products/vpn/shared.ftl
Labels: P3, Needs Review, Review: µ

#10513 Minor docs syntax fixes
  docs/coding.rst
Labels: P3, Needs Review, Review: µ

#10502 Fix error page header logos, refactor templates [fix #10357]
  bedrock/base/templates/404.html
  bedrock/base/templates/500.html
  bedrock/base/templates/base-error.html
  bedrock/base/views.py
  l10n/en/500.ftl
  media/css/base/page-not-found.scss
Labels: Needs Review, Review: µ

#10518 Ignore Sentry JS errors without a source URL (Fixes #10515)
  .eslintrc.js
  media/js/base/sentry-init.js
  media/js/base/sentry.es6.js
  media/static-bundles.json
Labels: P3, Needs Review, Review: S

#10528 Update ESLint rules for bedrock (Fixes #10527)
  .eslintrc.js
  media/js/base/mozilla-convert.js
  media/js/base/sentry.es6.js
  media/js/firefox/whatsnew/whatsnew-88-en.js
  media/js/foundation/annual-report-2019.es6.js
Labels: P3, Needs Review, Review: XS
