Repository mozilla/bedrock, pull requests merged in 2021-08, with the labels that each got.

#10350 Limit RTAMO attribution to AMO referrals (Fixes #10337)
  media/js/base/stub-attribution.js
  tests/unit/spec/base/stub-attribution.js
Labels: Needs Review, P2, Review: XS

#10354 WNP 91 for Pocket DE (Fixes #10349)
  bedrock/firefox/templates/firefox/whatsnew/includes/fx91/person1.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx91/person2.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx91/person3.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx91/person4.svg
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx91-de.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-91-de.scss
  media/img/firefox/whatsnew/whatsnew91/pocket-outline-white.svg
  media/img/firefox/whatsnew/whatsnew91/pocket-outline.svg
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_91.py
  tests/pages/firefox/whatsnew/whatsnew_91.py
  tests/unit/spec/base/fxa-utm-referral.js
  tests/unit/spec/base/stub-attribution.js
Labels: Needs Review, P1, Review: XS

#10359 Update VPN subscription links to point to FxA (Fixes #10333)
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  bedrock/settings/base.py
  docs/firefox-accounts.rst
  media/js/base/fxa-utm-referral.js
  media/js/base/mozilla-fxa-product-button.js
Labels: Needs Review, P1, Review: XS

#10328 Remove unused macos attribution script (Fixes #9346)
  bedrock/firefox/templates/firefox/new/basic/base_download.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  media/js/base/stub-attribution-macos-init.js
  media/js/base/stub-attribution-macos.js
  media/static-bundles.json
  tests/unit/karma.conf.js
  tests/unit/spec/base/stub-attribution-macos.js
Labels: Needs Review, P3, Review: XS

#10363 Update classList polyfill (Fixes #6221)
  media/js/base/class-list-polyfill.js
  media/js/libs/classlist.js
  media/static-bundles.json
Labels: Needs Review, P3, Review: µ

#10366 2021 H1 Transparency report (Fixes #10365)
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/index.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2021.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/report-base.html
  bedrock/mozorg/urls.py
  media/css/mozorg/about-transparency.scss
Labels: P2, Review: XS

#10347 Issue #10341 Remove deprecated Picto Card components
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/firefox/templates/firefox/nightly/firstrun.html
  bedrock/firefox/templates/firefox/privacy/index.html
  bedrock/mozorg/templates/mozorg/moss/index.html
  media/css/firefox/channel.scss
  media/css/firefox/firstrun/nightly.scss
  media/css/firefox/privacy/promise.scss
  media/css/mozorg/moss.scss
Labels: Review: M

#10373 Fix dev URL in VPN page Fluent file
  l10n/en/products/vpn/more/when-to-use-a-vpn.ftl
Labels: Needs Review, Review: µ

#10375 Fix Nightly /firstrun page test selectors
  bedrock/firefox/templates/firefox/nightly/firstrun.html
Labels: Review: µ

#10361 Update deprecated components on browser and privacy pages [10341]
  bedrock/firefox/templates/firefox/browsers/chromebook.html
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/privacy/book.html
  bedrock/firefox/templates/firefox/privacy/index.html
  bedrock/firefox/templates/firefox/privacy/products.html
  media/css/firefox/browsers-products.scss
  media/css/firefox/browsers/chromebook.scss
  media/css/firefox/privacy/book.scss
  media/css/firefox/privacy/common.scss
  media/css/firefox/privacy/products.scss
  media/css/firefox/privacy/promise.scss
Labels: Papercuts 💸, P3, Needs Review, Review: XS

#10369 Break up common.js bundle (Fixes #9321)
  bedrock/base/templates/base-protocol.html
  media/static-bundles.json
Labels: P3, Needs Review, Review: XS

#10378 Update Edge logo on compare page [fix #10377]
  media/img/firefox/compare/compare-browser-windows-high-res.png
  media/img/firefox/compare/compare-browser-windows.png
Labels: Needs Review, Review: µ

#10382 Remove outdated links on /manifesto page (Fixes #10210)
  bedrock/mozorg/templates/mozorg/about/manifesto.html
  l10n/en/mozorg/about/manifesto.ftl
  media/css/mozorg/manifesto.scss
Labels: P2, Needs Review, Review: XS

#10385 Use Split on Firefox Products page, fix layout [#10341]
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/products/index.html
  media/css/firefox/browsers-products.scss
Labels: Bug :bug:, Needs Review, Review: XS

#10376 Use UA detection to serve 64bit builds Firefox Beta on Windows (Fixes #10194)
  media/css/protocol/components/_download-button.scss
Labels: P2, Needs Review, Review: XS

#10386 Remove more references to Lockwise [#10166]
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/features/safebrowser.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/more.html
  bedrock/firefox/templates/firefox/products/index.html
  bedrock/firefox/templates/firefox/sync.html
  bedrock/firefox/templates/firefox/welcome/page3.html
  l10n/en/firefox/more.ftl
  l10n/en/firefox/welcome/page3.ftl
  l10n/en/sub_navigation.ftl
Labels: Papercuts 💸, P3, Review: XS

#10372 Updating Feature Card components with Split
  bedrock/firefox/templates/firefox/sync.html
  bedrock/foundation/templates/foundation/annualreport/2019/index.html
  bedrock/mozorg/templates/mozorg/about/index.html
  bedrock/mozorg/templates/mozorg/contribute.html
  l10n/en/firefox/sync.ftl
  media/css/firefox/sync.scss
  media/css/foundation/annual-report-2019.scss
  media/css/mozorg/about.scss
  media/css/mozorg/contribute.scss
  media/img/contribute/contribute-madeby-feature.jpg
Labels: Papercuts 💸, P3, Needs Review, Review: M

#10320 Stop serving JS to legacy IE browsers (Fixes #10192)
  .eslintignore
  bedrock/base/templates/base-protocol.html
  bedrock/base/templates/includes/google-analytics.html
  bedrock/exp/templates/exp/includes/stub.html
  bedrock/firefox/templates/firefox/campaign/unfck/index.html
  bedrock/firefox/templates/firefox/includes/download-button-thanks.html
  bedrock/firefox/templates/firefox/new/basic/base.html
  bedrock/firefox/templates/firefox/new/basic/base_download.html
  bedrock/firefox/templates/firefox/new/basic/thanks.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/new/desktop/thanks.html
  bedrock/mozorg/templates/mozorg/mpl/2.0/index.html
  docs/browser-support.rst
  media/css/firefox/new/basic/download.scss
  media/css/firefox/new/basic/ie.scss
  media/css/firefox/new/common/thanks-messaging.scss
  media/css/firefox/new/desktop/download.scss
  media/css/firefox/new/desktop/ie8.scss
  media/css/firefox/new/desktop/ie9.scss
  media/css/firefox/new/desktop/thanks-ie.scss
  media/css/firefox/new/desktop/thanks.scss
  media/css/protocol/common-old-ie.scss
  media/css/protocol/components/_download-button-ie.scss
  media/css/protocol/components/_navigation-ie.scss
  media/js/base/site.js
  media/js/base/stub-attribution-init-ie.js
  media/js/ie/base-page-init-ie.js
  media/js/ie/gtm-snippet.js
  media/js/ie/libs/html5shiv.js
  media/js/ie/mozilla-utils-ie.js
  media/js/libs/jquery-1.12.4.min.js
  media/static-bundles.json
  tests/pages/base.py
  tests/unit/karma.conf.js
  tests/unit/spec/ie/mozilla-utils-ie.js
Labels: P3, Review: M

#10370 Replace deprecated components in firefox pages [10341]
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/mobile/index.html
  bedrock/firefox/templates/firefox/more.html
  bedrock/firefox/templates/firefox/more/misinformation.html
  bedrock/firefox/templates/firefox/pocket.html
  l10n/en/firefox/more/misinformation.ftl
  media/css/firefox/home/master.scss
  media/css/firefox/mobile/mobile.scss
  media/css/firefox/more.scss
  media/css/firefox/more/misinformation.scss
  media/css/firefox/pocket.scss
Labels: Papercuts 💸, P3, Review: S

#10391 Depreciate hero components
  bedrock/base/templates/macros-protocol.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/facebookcontainer/includes/video.html
  bedrock/firefox/templates/firefox/facebookcontainer/index.html
  bedrock/firefox/templates/firefox/faq.html
  l10n/en/firefox/facebook_container.ftl
  media/css/firefox/enterprise/landing.scss
  media/css/firefox/facebook-container.scss
  media/css/firefox/faq.scss
Labels: Papercuts 💸, Review: S

#10384 Update Hero components with Split
  bedrock/firefox/templates/firefox/products/lockwise.html
  bedrock/firefox/templates/firefox/switch.html
  bedrock/mozorg/templates/mozorg/home/home-en.html
  media/css/firefox/lockwise/lockwise.scss
  media/css/firefox/switch.scss
  media/css/mozorg/home/home-en.scss
Labels: Papercuts 💸, P3, WIP :construction:
