Repository mozilla/bedrock, pull requests merged in 2022-03, with the labels that each got.

#11263 Fix active locale logic for displaying VPN NWP 98 (Fixes #11262)
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
Labels: P1, Needs Review, Review: µ

#11261 Remove adjust.com links from WNP 98 badges (issue #11211)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-mobile-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-mobile-fr.html
Labels: P2, Needs Review, Review: µ

#11224 Add variation for get-app email basket id (fixes #11206)
  bedrock/firefox/templates/firefox/mobile/get-app.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/urls.py
  bedrock/settings/base.py
Labels: P1, Review: XS

#11234 Allow multi-newsletter sign up (fixes #11120)
  bedrock/mozorg/templates/mozorg/about/manifesto.html
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/templates/mozorg/mission.html
  bedrock/newsletter/templates/newsletter/firefox.html
  bedrock/newsletter/templates/newsletter/includes/form.html
  bedrock/newsletter/templates/newsletter/index.html
  bedrock/newsletter/templates/newsletter/mozilla.html
  bedrock/newsletter/templatetags/helpers.py
  bedrock/newsletter/tests/test_forms.py
  bedrock/newsletter/tests/test_views.py
  bedrock/newsletter/views.py
  l10n/en/newsletter_form.ftl
  media/css/protocol/protocol-firefox.scss
  media/css/protocol/protocol-mozilla.scss
  media/js/libs/array-from.js
  media/js/newsletter/form-protocol.es6.js
  media/static-bundles.json
Labels: Review: XS

#11273 Add English whatsnew pages for Firefox 98 [fix #11208, fix #11209]
  bedrock/firefox/templates/firefox/whatsnew/includes/fx98-vpn-en/laptop.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx98-vpn-en/mobile.svg
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-turningred-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-vpn-en.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-98-turningred-en.scss
  media/css/firefox/whatsnew/whatsnew-98-vpn-en.scss
  media/img/firefox/whatsnew/whatsnew98/circle-red.svg
  media/img/firefox/whatsnew/whatsnew98/underline-red.svg
  media/js/firefox/whatsnew/whatsnew-98-turningred-en.js
  media/static-bundles.json
Labels: P1, Needs Review, Review: S

#11284 WNP98 Turning Red: update copy, center image
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-turningred-en.html
  media/css/firefox/whatsnew/whatsnew-98-turningred-en.scss
Labels: Needs Review, Review: µ

#11298 Update last intro feature on dev
  bedrock/firefox/templates/firefox/developer/includes/for-developers.html
  bedrock/firefox/templates/firefox/developer/includes/intro-features.html
  bedrock/firefox/templates/firefox/developer/includes/performance.html
  l10n/en/firefox/developer.ftl
Labels: Needs Review, Review: µ

#11302 VPN wave 5 post-launch cleanup (Issue #11213)
  bedrock/products/templates/products/vpn/includes/macros.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/views.py
  bedrock/settings/base.py
  tests/functional/products/vpn/test_landing.py
Labels: P3, Needs Review, Review: µ

#11274 Add contribute banner (fixes #11233)
  bedrock/base/templates/includes/banners/mozilla-connect.html
  bedrock/mozorg/templates/mozorg/contribute.html
  bedrock/mozorg/urls.py
  l10n/en/banners/mozilla-connect.ftl
  l10n/en/brands.ftl
  media/css/base/banners/mozilla-connect.scss
  media/css/mozorg/contribute.scss
  media/js/base/banners/mozilla-connect-banner-init.js
  media/static-bundles.json
Labels: P2, Needs Review, Review: XS

#11314 chore: bump karma and browser-sync [no bug]
  package-lock.json
  package.json
Labels: Needs Review, Review: µ

#11319 Remove translation file for Mozilla Connect banner
  bedrock/base/templates/includes/banners/mozilla-connect.html
  bedrock/mozorg/urls.py
  l10n/en/banners/mozilla-connect.ftl
  l10n/en/brands.ftl
Labels: Needs Review, Review: µ

#11327 Remove trailing spaces after some URLs in hrefs on a D&I page
  bedrock/mozorg/templates/mozorg/diversity/2021/beyond-products.html
Labels: Needs Review, Review: µ

#11328 Add protocol-split bundle to vpn article
  bedrock/products/templates/products/vpn/resource-center/base-article.html
Labels: Bug :bug:

#11316 Update pytest-selenium and py-pom (Issue #10591)
  bin/run-integration-tests.sh
  requirements/dev.in
  requirements/dev.txt
  tests/functional/conftest.py
  tests/pages/base.py
Labels: P3, Needs Review, Review: µ

#11346 Updating `card` Protocol component to CSS bundle
  bedrock/firefox/templates/firefox/facebookcontainer/index.html
  bedrock/firefox/templates/firefox/installer-help.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/privacy/base.html
  bedrock/mozorg/templates/mozorg/diversity/2021/index.html
  bedrock/mozorg/templates/mozorg/moss/base.html
  media/css/firefox/facebook-container.scss
  media/css/firefox/installer-help.scss
  media/css/firefox/new/desktop/download.scss
  media/css/firefox/privacy/products.scss
  media/css/mozorg/diversity/2021/diversity-2021.scss
  media/css/mozorg/moss.scss
Labels: Needs Review, Review: S

#11347 Updating `call-out` Protocol component to CSS bundle
  bedrock/firefox/templates/firefox/browsers/best-browser.html
  bedrock/firefox/templates/firefox/browsers/browser-history.html
  bedrock/firefox/templates/firefox/browsers/incognito-browser.html
  bedrock/firefox/templates/firefox/browsers/update-browser.html
  bedrock/firefox/templates/firefox/browsers/windows-64-bit.html
  bedrock/firefox/templates/firefox/campaign/unfck/index.html
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/firefox/templates/firefox/features/adblocker.html
  bedrock/firefox/templates/firefox/features/safebrowser.html
  bedrock/firefox/templates/firefox/new/desktop/thanks.html
  bedrock/firefox/templates/firefox/releases/notes.html
  bedrock/firefox/templates/firefox/releases/system_requirements.html
  bedrock/mozorg/templates/mozorg/about/manifesto.html
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  media/css/firefox/browsers/best-browser.scss
  media/css/firefox/browsers/browser-history.scss
  media/css/firefox/browsers/incognito-browser.scss
  media/css/firefox/browsers/update-browser.scss
  media/css/firefox/browsers/windows-64-bit.scss
  media/css/firefox/channel.scss
  media/css/firefox/features/safebrowser.scss
  media/css/firefox/new/basic/thanks.scss
  media/css/firefox/releasenotes.scss
  media/css/firefox/system-requirements.scss
  media/css/firefox/unfck.scss
  media/css/mozorg/home/home-contentful.scss
  media/css/mozorg/manifesto.scss
Labels: Needs Review, Review: S

#11353 Add Mdn plus to produts navigation menu
  bedrock/base/templates/includes/protocol/navigation/menus/products.html
  l10n/en/navigation_v2.ftl
  media/img/nav/icons/icon-mdn-plus.svg
Labels: Do Not Merge :warning:

#11355 Updating `picto` component to CSS bundle
  bedrock/firefox/templates/firefox/new/basic/base_platform.html
  bedrock/firefox/templates/firefox/nightly/firstrun.html
  bedrock/firefox/templates/firefox/privacy/index.html
  bedrock/firefox/templates/firefox/set-as-default/landing.html
  bedrock/firefox/templates/firefox/welcome/page10.html
  bedrock/firefox/templates/firefox/welcome/page11.html
  bedrock/firefox/templates/firefox/welcome/page12.html
  bedrock/firefox/templates/firefox/welcome/page13.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx95-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx96-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx96-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx97-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx97-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-vpn-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-vpn-eu.html
  media/css/firefox/firstrun/nightly.scss
  media/css/firefox/new/basic/platform.scss
  media/css/firefox/privacy/promise.scss
  media/css/firefox/set-as-default/landing.scss
  media/css/firefox/welcome10.scss
  media/css/firefox/welcome11.scss
  media/css/firefox/welcome12.scss
  media/css/firefox/welcome13.scss
  media/css/firefox/whatsnew/whatsnew-95-de.scss
  media/css/firefox/whatsnew/whatsnew-96-eu.scss
  media/css/firefox/whatsnew/whatsnew-97-eu.scss
  media/css/firefox/whatsnew/whatsnew-98-vpn-en.scss
  media/css/firefox/whatsnew/whatsnew-98-vpn-eu.scss
Labels: Needs Review, Review: S

#11357 Add `picto` bundle to `firefox/developer` page
  bedrock/firefox/templates/firefox/developer/index.html
  media/css/firefox/developer/includes/engage.scss
Labels: Needs Review, Review: µ

#11339 Update ESLint to v8 (Fixes #11336)
  .pre-commit-config.yaml
  media/js/base/mozilla-cookie-helper.js
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#11368 Remove unused CSS bundle reference (Fixes #11367)
  bedrock/exp/templates/exp/opt-out.html
Labels: Needs Review, Review: µ

#11359 Added test suite for Mozilla.Cookies
  media/js/base/mozilla-cookie-helper.js
  tests/unit/karma.conf.js
  tests/unit/spec/base/core-datalayer-page-id.js
  tests/unit/spec/base/fxa-utm.js
  tests/unit/spec/base/mozilla-banner.js
  tests/unit/spec/base/mozilla-cookie-helper.js
  tests/unit/spec/base/stub-attribution.js
  tests/unit/spec/firefox/all/all-downloads-unified.js
Labels: Review: S

#11380 Fix missing CSS / JS when loading Contentful card components (Fixes #11378)
  bedrock/contentful/api.py
  media/css/contentful/firefox/c-card.scss
  media/css/contentful/firefox/t-card-layout.scss
  media/css/contentful/mozilla/c-card.scss
  media/css/contentful/mozilla/t-card-layout.scss
  media/static-bundles.json
Labels: P2, Needs Review, Review: XS

#11377 Add MDN Plus as a Contentful CTA option (Issue #11356)
  bedrock/contentful/api.py
  bedrock/contentful/templates/includes/contentful/cta.html
  media/css/contentful/firefox/c-hero.scss
  media/css/contentful/mozilla/c-hero.scss
  media/img/logos/mdn/mdn-plus-wordmark.svg
Labels: P2, Needs Review, Review: XS

#11388 Use correct GB country code for affiliate attribution (Issue #11212)
  bedrock/settings/base.py
Labels: P1, Needs Review, Review: µ

#11385 Add samesite attr to Cookies.SetItem calls within 1st party JS
  media/js/base/banners/mozilla-banner.js
  media/js/base/fxa-utm.es6.js
  media/js/base/mozilla-cookie-helper.js
  media/js/base/stub-attribution.js
  media/js/firefox/sticky-promo.js
  media/js/libs/mozilla-traffic-cop.js
  tests/unit/spec/base/fxa-utm.js
  tests/unit/spec/base/stub-attribution.js
Labels: Review: S

#11397 Update JS test dependencies (Fixes #11341)
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ
