Repository mozilla/bedrock, pull requests merged in 2022-05, with the labels that each got.

#11557 Code Firefox 100 masthead for mozorg homepage
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  bedrock/mozorg/templates/mozorg/home/includes/fx100-promo.html
  media/css/mozorg/home/home-fx100-promo.scss
  media/img/mozorg/fx100-wordmark.svg
  media/static-bundles.json
Labels: Review: XS

#11558 CA policy fixes [bug #1766461]
  bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html
Labels: P3, Needs Review, Review: µ

#11567 small edits to fx100 promo from design
  media/css/mozorg/home/home-fx100-promo.scss
Labels: Review: µ

#11566 Add asterisks in root store policy [bug #1766461]
  bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html
Labels: P3, Needs Review, Review: µ

#11571 fx100 promo for FR and DE
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/templates/mozorg/home/includes/fx100-promo-eu.html
  bedrock/mozorg/templates/mozorg/home/includes/fx100-promo.html
Labels: Do Not Merge :warning:, Review: µ

#11570 Add link to ISO country code table in docs (Fixes #11568)
  docs/coding.rst
Labels: Needs Review, Review: µ

#11574 Updates to FF100 home page promo (#11539)
  bedrock/mozorg/templates/mozorg/home/includes/fx100-promo-eu.html
  bedrock/mozorg/templates/mozorg/home/includes/fx100-promo.html
  media/css/mozorg/home/home-fx100-promo.scss
Labels: Needs Review, Review: µ

#11573 Add additional countries to VPN exclusion list for /whatsnew (Fixes #11572)
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  bedrock/settings/base.py
Labels: P2, Needs Review, Review: XS

#11601 Remove 'Featured in' logo block from VPN landing page (Fixes #11600)
  bedrock/firefox/templates/firefox/welcome/page9.de.html
  bedrock/firefox/templates/firefox/welcome/page9.fr.html
  bedrock/products/templates/products/vpn/includes/featured-press.html
  bedrock/products/templates/products/vpn/landing.html
  media/css/firefox/welcome.scss
  media/css/products/vpn/landing.scss
  media/img/products/vpn/landing/logos/cnet-high-res.png
  media/img/products/vpn/landing/logos/cnet-white-high-res.png
  media/img/products/vpn/landing/logos/cnet-white.png
  media/img/products/vpn/landing/logos/cnet.png
  media/img/products/vpn/landing/logos/gizmodo-high-res.png
  media/img/products/vpn/landing/logos/gizmodo-white-high-res.png
  media/img/products/vpn/landing/logos/gizmodo-white.png
  media/img/products/vpn/landing/logos/gizmodo.png
  media/img/products/vpn/landing/logos/pcgamer-high-res.png
  media/img/products/vpn/landing/logos/pcgamer-white-high-res.png
  media/img/products/vpn/landing/logos/pcgamer-white.png
  media/img/products/vpn/landing/logos/pcgamer.png
  media/img/products/vpn/landing/logos/wired-high-res.png
  media/img/products/vpn/landing/logos/wired-white-high-res.png
  media/img/products/vpn/landing/logos/wired-white.png
  media/img/products/vpn/landing/logos/wired.png
Labels: P1, Needs Review, Review: µ

#11588 Don't show Firefox download interstitial in manual update flow (#11071)
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/views.py
  media/js/base/experiment-utils.es6.js
Labels: P2, Needs Review, Review: µ

#11602 Update OS availability when comparing Firefox and Edge (Fixes #11593)
  bedrock/firefox/templates/firefox/new/desktop/download.html
Labels: P2, Needs Review, Review: µ

#11579 Adding Fluent file for Pocket Platforms pages
  bedrock/pocket/templates/pocket/android.html
  bedrock/pocket/templates/pocket/chrome.html
  bedrock/pocket/templates/pocket/edge.html
  bedrock/pocket/templates/pocket/ios.html
  bedrock/pocket/templates/pocket/opera.html
  bedrock/pocket/templates/pocket/safari.html
  bedrock/pocket/templates/pocket/welcome.html
  bedrock/pocket/urls.py
  l10n-pocket/en/brands.ftl
  l10n-pocket/en/pocket/platforms.ftl
Labels: Review: XS

#11609 Serve full Firefox installer for users on Windows 7 (Fixes #11606)
  bedrock/firefox/templates/firefox/new/basic/thanks.html
  bedrock/firefox/templates/firefox/new/desktop/thanks.html
  bedrock/firefox/templatetags/helpers.py
  bedrock/firefox/tests/test_helpers.py
  bedrock/mozorg/tests/test_views.py
  media/css/firefox/new/basic/thanks.scss
  media/css/firefox/new/desktop/thanks.scss
  media/js/firefox/new/common/thanks.js
  tests/unit/spec/base/site.js
  tests/unit/spec/firefox/new/common/thanks.js
Labels: P1, Needs Review, Review: XS

#11597 Add no-important rule to Stylelint (Fixes #11594)
  .stylelintrc
  media/css/pocket/components/add.scss
  media/css/pocket/components/new-tab-learn-more.scss
  media/css/pocket/components/platforms.scss
  media/css/pocket/components/pocket-features.scss
Labels: P3, Needs Review, Review: µ

#11612 Add ftl file for pocket contact-info (fixes #11598)
  bedrock/pocket/templates/pocket/contact-info.html
  bedrock/pocket/urls.py
  l10n-pocket/en/brands.ftl
  l10n-pocket/en/pocket/contact-info.ftl
Labels: Needs Review, Review: XS

#11605 Add table of contents to CA policy [bug #1766461]
  bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html
Labels: P3, Needs Review, Review: µ

#11625 Add missing protocol-call-out bundle to /thanks/ page (Fixes #11608)
  bedrock/firefox/templates/firefox/new/basic/thanks.html
Labels: P2, Needs Review, Review: µ

#11626 Update billboard macro to make link optional (Fixes #11569)
  bedrock/base/templates/macros-protocol.html
Labels: P3, Needs Review, Review: µ

#11624 Convert save-to-pocket to use FTL strings (fixes #11623)
  bedrock/pocket/templates/pocket/includes/pocket-premium.html
  bedrock/pocket/templates/pocket/save-to-pocket.html
  bedrock/pocket/urls.py
  l10n-pocket/en/pocket/banners/pocket-premium.ftl
  l10n-pocket/en/pocket/save-to-pocket.ftl
Labels: L10N, Review: XS

#11402 Add glean.js analytics to home page
  .circleci/config.yml
  .gitignore
  Dockerfile
  Makefile
  bedrock/base/templates/base-protocol.html
  bedrock/mozorg/templates/mozorg/home/base.html
  docs/analytics.rst
  docs/testing.rst
  glean/docs/metrics.md
  glean/metrics.yaml
  glean/pings.yaml
  media/js/base/banners/mozilla-banner.js
  media/js/base/protocol/init-lang-switcher.js
  media/js/glean/elements.es6.js
  media/js/glean/init.es6.js
  media/js/glean/page.es6.js
  media/js/glean/utils.es6.js
  media/js/newsletter/form-protocol.es6.js
  media/static-bundles.json
  package-lock.json
  package.json
  requirements/dev.in
  requirements/dev.txt
  requirements/docs.in
  requirements/docs.txt
  requirements/prod.in
  requirements/prod.txt
  tests/unit/karma.conf.js
  tests/unit/spec/glean/elements.js
  tests/unit/spec/glean/page.js
  tests/unit/spec/glean/utils.js
  webpack.config.js
Labels: Review: S

#11640 Replace Lockwise copy shown when trying to re-download Firefox (Fixes #10795)
  bedrock/firefox/templates/firefox/new/desktop/download.html
  l10n/en/firefox/new/desktop.ftl
Labels: P2, Needs Review, Review: µ

#11599 fix bug 11476 - Adds css selector for hidden attribute
  media/css/protocol/common-old-ie.scss
  media/css/protocol/protocol-firefox.scss
  media/css/protocol/protocol-mozilla.scss
Labels: Bug :bug:, P3, Needs Review, Review: µ

#11617 convert fluent strings for add page
  bedrock/pocket/templates/pocket/add.html
  bedrock/pocket/urls.py
  l10n-pocket/en/brands.ftl
  l10n-pocket/en/pocket/add.ftl
  media/css/pocket/components/add.scss
  media/css/pocket/utils/_variables.scss
  media/img/pocket/save-via-email.png
Labels: L10N, Review: XS

#11589 Link hover contrast issue on Nightly /whatsnew page
  media/css/firefox/whatsnew/whatsnew-nightly.scss
Labels: Bug :bug:, Review: µ, a11y

#11628 Link to about:preferences in Nightly /whatsnew page (Fixes #11487)
  bedrock/firefox/templates/firefox/nightly/whatsnew.html
  l10n/en/firefox/nightly/whatsnew.ftl
  media/js/firefox/whatsnew/nightly.js
  media/static-bundles.json
Labels: P3, Needs Review, Review: µ

#11653 Set bg color on Nightly /whatsnew page for rubber band scrolling (Fixes #10251)
  media/css/firefox/whatsnew/whatsnew-nightly.scss
Labels: P3, Needs Review, Review: µ

#11592 Pocket homepage migration
  bedrock/pocket/templates/pocket/home.html
  bedrock/pocket/templates/pocket/includes/footer.html
  bedrock/pocket/templates/pocket/includes/platform-footer.html
  bedrock/pocket/templates/pocket/includes/platform-nav.html
  bedrock/pocket/urls.py
  l10n-pocket/en/brands.ftl
  l10n-pocket/en/footer.ftl
  l10n-pocket/en/nav.ftl
  l10n-pocket/en/pocket/about.ftl
  l10n-pocket/en/pocket/home.ftl
  media/css/pocket/components/add.scss
  media/css/pocket/components/home.scss
  media/css/pocket/components/platforms.scss
  media/css/pocket/includes/_platform-footer.scss
  media/css/pocket/includes/_platform-nav.scss
  media/css/pocket/utils/_tokens.scss
  media/css/pocket/utils/_variables.scss
  media/img/l10n/de/pocket/pocket-home-articles.png
  media/img/l10n/de/pocket/pocket-list-mobile.png
  media/img/l10n/en/pocket/pocket-home-articles.png
  media/img/l10n/en/pocket/pocket-list-mobile.png
  media/img/pocket/pocket-audio-icon.svg
  media/img/pocket/pocket-border-1.svg
  media/img/pocket/pocket-border-2.svg
  media/img/pocket/pocket-colorful-books.svg
  media/img/pocket/pocket-tag-icon.svg
  media/img/pocket/pocket-text-icon.svg
  media/static-bundles.json
Labels: Review: M

#11661 Lint Pocket Fluent files (Fixes #11660)
  bin/run-tests.sh
Labels: Needs Review, Review: µ

#11657 Convert jobs page to use fluent
  bedrock/pocket/templates/pocket/jobs.html
  bedrock/pocket/urls.py
  l10n-pocket/en/pocket/jobs.ftl
Labels: L10N, Needs Review, Review: XS

#11663 Add pocket 404 and 500 pages (fixes #11542)
  bedrock/pocket/templates/pocket/404.html
  bedrock/pocket/templates/pocket/500.html
  bedrock/pocket/templates/pocket/includes/platform-footer.html
  bedrock/pocket/views.py
  l10n-pocket/en/pocket/404.ftl
  l10n-pocket/en/pocket/500.ftl
  media/css/pocket/components/error-page.scss
  media/css/pocket/includes/_platform-footer.scss
  media/static-bundles.json
Labels: Review: XS

#11669 Remove autogenerated Glean docs (Issue #10746)
  docs/analytics.rst
  glean/docs/metrics.md
  package.json
Labels: P3, Needs Review, Review: µ

#11664 convert tos to use fluent
  bedrock/pocket/templates/pocket/tos.html
  bedrock/pocket/urls.py
  l10n-pocket/en/brands.ftl
  l10n-pocket/en/pocket/tos.ftl
Labels: L10N, Needs Review, Review: S

#11662 Remove affiliate marketing cookie if aic id is unknown and there's no cjevent param (Fixes #11506)
  media/js/products/vpn/affiliate-attribution.es6.js
  tests/unit/spec/products/vpn/affiliate-attribution.js
Labels: P3, Needs Review, Review: XS

#11675 Update social footer icons (Fixes #11668)
  bedrock/base/templates/includes/protocol/footer/footer.html
  l10n/en/brands.ftl
  l10n/en/footer.ftl
  media/css/firefox/welcome11.scss
  media/css/firefox/welcome12.scss
  media/css/firefox/welcome13.scss
  media/css/firefox/whatsnew/includes/_dark-mode.scss
  media/css/protocol/components/_footer.scss
  media/img/logos/social/linkedin-black.svg
  media/img/logos/social/linkedin-white.svg
  media/img/logos/social/spotify-black.svg
  media/img/logos/social/spotify-white.svg
  media/img/logos/social/tiktok-black.svg
  media/img/logos/social/tiktok-white.svg
Labels: P2, Needs Review, Review: XS

#11677 Fix missing link href on VPN SEO page (Fixes #11676)
  bedrock/products/templates/products/vpn/more/ip-address.html
Labels: P3, Needs Review, Review: µ

#11670 Convert pocket/privacy to use fluent strings
  bedrock/pocket/templates/pocket/privacy.html
  bedrock/pocket/urls.py
  l10n-pocket/en/brands.ftl
  l10n-pocket/en/pocket/privacy.ftl
Labels: L10N, Review: XS

#11665 Fluent-size firefox/new_tab_learn_more
  bedrock/pocket/templates/pocket/firefox/new-tab-learn-more.html
  bedrock/pocket/urls.py
  l10n-pocket/en/pocket/firefox/new-tab.ftl
  media/css/pocket/components/new-tab-learn-more.scss
Labels: L10N

#11678 Add WNP for Firefox 101 [fix #11658]
  bedrock/firefox/templates/firefox/whatsnew/includes/fx101-vpn-mobile/qr-de.html
  bedrock/firefox/templates/firefox/whatsnew/includes/fx101-vpn-mobile/qr-en-v2.html
  bedrock/firefox/templates/firefox/whatsnew/includes/fx101-vpn-mobile/qr-en-v3.html
  bedrock/firefox/templates/firefox/whatsnew/includes/fx101-vpn-mobile/qr-fr.html
  bedrock/firefox/templates/firefox/whatsnew/includes/fx101-vpn-mobile/qr.html
  bedrock/firefox/templates/firefox/whatsnew/includes/header.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx101-vpn-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx101-vpn-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx101-vpn-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx101-vpn-mobile-unfree-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx101-vpn-mobile.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  l10n/configs/pontoon.toml
  l10n/en/firefox/whatsnew/whatsnew-101-vpn-mobile.ftl
  l10n/en/firefox/whatsnew/whatsnew.ftl
  media/css/firefox/whatsnew/includes/_dark-mode.scss
  media/css/firefox/whatsnew/includes/_header.scss
  media/css/firefox/whatsnew/whatsnew-101-vpn-en.scss
  media/css/firefox/whatsnew/whatsnew-101-vpn-mobile.scss
  media/img/firefox/whatsnew/logo-word-hor-white.svg
  media/img/firefox/whatsnew/logo-word-hor.svg
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-de.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-en-v2.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-en-v3.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-es.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-fi.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-fr.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-it.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-nl.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-sv.png
  media/js/firefox/whatsnew/whatsnew-101-en-experiment.js
  media/static-bundles.json
Labels: P1, Review: XS

#11671 Create SEM landing pages
  bedrock/landing/__init__.py
  bedrock/landing/models.py
  bedrock/landing/templates/landing/base-landing.html
  bedrock/landing/templates/landing/firefox/fx100.html
  bedrock/landing/templates/landing/includes/footer.html
  bedrock/landing/urls.py
  bedrock/settings/base.py
  bedrock/urls/mozorg_mode.py
  media/css/landing/landing-shared.scss
  media/js/landing/landing-shared.js
  media/static-bundles.json
Labels: Review: XS

#11690 WNP 101, update QR codes [#11658]
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-de.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-en-v2.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-en-v3.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-es.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-fi.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-fr.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-it.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-nl.png
  media/img/firefox/whatsnew/whatsnew101/qr-vpn-sv.png
Labels: P2, Needs Review, Review: XS

#11667 Migrate Mozilla VPN download page to bedrock (Fixes #11659)
  bedrock/products/templates/products/vpn/download.html
  bedrock/products/templates/products/vpn/includes/macros.html
  bedrock/products/templates/products/vpn/includes/subnav-download.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/tests/test_views.py
  bedrock/products/urls.py
  bedrock/products/views.py
  bedrock/settings/base.py
  docs/analytics.rst
  l10n/configs/pontoon.toml
  l10n/en/products/vpn/download.ftl
  l10n/en/products/vpn/landing.ftl
  l10n/en/products/vpn/shared.ftl
  media/css/products/vpn/common.scss
  media/css/products/vpn/download.scss
  media/img/products/vpn/download/platform-android-black.svg
  media/img/products/vpn/download/platform-ios-black.svg
  media/img/products/vpn/download/platform-linux-black.svg
  media/img/products/vpn/download/platform-mac-black.svg
  media/img/products/vpn/download/platform-windows-black.svg
  media/static-bundles.json
  tests/functional/products/vpn/test_download.py
  tests/pages/products/vpn/download.py
Labels: P2, Needs Review, Review: XS

#11697 Update glean debug tag name in analytics docs (Issue #10746)
  docs/analytics.rst
Labels: P3, Needs Review, Review: µ

#11696 Fix typo in SEM landing pages function
  bedrock/landing/templates/landing/base-landing.html
  media/js/landing/landing-shared.js
Labels: Review: µ

#11704 Add Glean to /products/vpn/ landing page (Issue #10746)
  bedrock/products/templates/products/vpn/landing.html
Labels: P3, Needs Review, Review: µ

#11695 Add WNP for Dev Edition promoting MDN Plus [fix #11633]
  bedrock/firefox/templates/firefox/developer/whatsnew-mdnplus.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  l10n/configs/pontoon.toml
  l10n/en/firefox/whatsnew/whatsnew-developer-mdnplus.ftl
  media/css/firefox/developer/whatsnew-mdnplus.scss
  media/static-bundles.json
Labels: Needs Review, Review: XS
