Repository mozilla/bedrock, pull requests merged in 2022-01, with the labels that each got.

#11084 Bump Django to 2.2.26
  requirements/base.txt
Labels: Needs Review, Review: XS

#11083 Add Protocol and Macro paths to Bedrock documentation
  docs/coding.rst
Labels: P3, Needs Review, Documentation, Review: XS

#10862 Fixes #10834 - Removes Linkchecker
  bedrock/mozorg/templates/mozorg/robots.txt
  bin/run-linkchecker.sh
  docker/dockerfiles/bedrock_linkchecker
  requirements/linkchecker.txt
Labels: Needs Review, Review: µ

#11033 Deprecate lazy_img in favour of loading=lazy (fixes #8752)
  bedrock/base/templates/macros-protocol.html
  bedrock/base/templates/macros.html
  bedrock/base/tests/test_macros.py
  bedrock/firefox/templates/firefox/more.html
  bedrock/firefox/templates/firefox/more/misinformation.html
  bedrock/firefox/templates/firefox/pocket.html
  bedrock/foundation/templates/foundation/annualreport/2019/index.html
  bedrock/foundation/templates/foundation/annualreport/2020/index.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/products/templates/products/vpn/resource-center/landing.html
  docs/coding.rst
  docs/index.rst
  docs/javascript-libs.rst
  docs/mozilla-lazy-load.rst
  media/css/base/mozilla-lazy-image.scss
  media/js/base/mozilla-lazy-load.js
  media/js/contentful/lazyload-init.js
  media/js/firefox/features/tips/tips.js
  media/js/firefox/home/master.js
  media/js/firefox/more.js
  media/js/firefox/pocket.js
  media/js/foundation/annual-report-2019-2020.es6.js
  media/js/mozorg/about.js
  media/js/mozorg/home/home.js
  media/js/mozorg/moss.js
  media/js/newsletter/confirm.js
  media/js/products/vpn/resource-center-article.es6.js
  media/js/products/vpn/resource-center.js
  media/static-bundles.json
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-lazy-load.js
Labels: Papercuts 💸, Needs Review, Review: S

#11078 Use VPN client ID for service parameter referrals (Fixes #11074)
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  bedrock/settings/base.py
Labels: P3, Needs Review, Review: µ

#11061 Contentful l10n support - all-in-one PR
  bedrock/base/cache.py
  bedrock/contentful/api.py
  bedrock/contentful/constants.py
  bedrock/contentful/management/commands/update_contentful.py
  bedrock/contentful/migrations/0004_update_unique_constraint_on_contentfulentry.py
  bedrock/contentful/models.py
  bedrock/contentful/tests/test_contentful_api.py
  bedrock/contentful/tests/test_contentful_commands.py
  bedrock/contentful/tests/test_contentful_models.py
  bedrock/contentful/tests/test_contentful_utils.py
  bedrock/contentful/utils.py
  bedrock/mozorg/views.py
  bedrock/products/tests/test_views.py
  bedrock/products/views.py
  bedrock/settings/base.py
  lib/l10n_utils/__init__.py
  requirements/dev.txt
Labels: Needs Review, Review: M

#11087 Add EN WNP for Firefox 96 [fix #11070]
  bedrock/firefox/templates/firefox/whatsnew/includes/fx96-en/qr.html
  bedrock/firefox/templates/firefox/whatsnew/includes/fx96-en/s2d.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx96-en-qr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx96-en-rally.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx96-en-s2d.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  bedrock/settings/base.py
  media/css/firefox/whatsnew/whatsnew-96-en-mobile.scss
  media/css/firefox/whatsnew/whatsnew-96-en-rally.scss
  media/img/firefox/whatsnew/whatsnew96-en/logo-rally-black.svg
  media/img/firefox/whatsnew/whatsnew96-en/logo-rally-white.svg
  media/img/firefox/whatsnew/whatsnew96-en/moz-rally-high-res.png
  media/img/firefox/whatsnew/whatsnew96-en/moz-rally.png
  media/img/firefox/whatsnew/whatsnew96-en/qr-firefox.svg
  media/img/firefox/whatsnew/whatsnew96-en/watercolor-high-res.png
  media/img/firefox/whatsnew/whatsnew96-en/watercolor.png
  media/js/firefox/whatsnew/whatsnew-96-en-experiment.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_96.py
  tests/pages/firefox/whatsnew/whatsnew_96.py
Labels: Review: XS

#11089 Update Adjust links on EN WNP96 [#11070]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx96-en-qr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx96-en-s2d.html
Labels: P1, Needs Review, Review: µ

#11088 Clean up pocket banner (fixes #11050)
  bedrock/base/templates/includes/banners/pocket.html
  bedrock/mozorg/templates/mozorg/about/index.html
  bedrock/mozorg/templates/mozorg/about/manifesto.html
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  media/css/base/banners/pocket.scss
  media/img/banners/pocket/best-of-2021.svg
  media/js/base/banners/pocket-banner-init.js
  media/static-bundles.json
Labels: Papercuts 💸, Needs Review, Review: µ

#11091 Update EN WNP96 send-to-device form [#11070]
  bedrock/firefox/templates/firefox/whatsnew/includes/fx96-en/s2d.html
Labels: Needs Review, Review: µ

#11097 Transparency report amendment h1 2021 (Fixes #11095)
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2021.html
Labels: P3, Needs Review, Review: µ

#11096 Fix typo in WNP 96 DE (Issue #11059)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx96-de.html
Labels: P1, Needs Review, Review: µ

#11098 Add JS unit tests with Firefox v100 UA string (Issue #9575)
  tests/unit/spec/base/dnt-helper.js
  tests/unit/spec/base/mozilla-client.js
Labels: P3, Needs Review, Review: S

#11063 Add a timeout to cron tasks, to avoid a long-running blockage
  bin/cron.py
Labels: Do Not Merge :warning:, WIP :construction:, Review: µ

#11099 Fix /whatsnew URL version number logic for Firefox 100 (Issue #9575)
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
Labels: P1, Needs Review, Review: S

#11102 Update android-sys-req helper for FF100+
  bedrock/releasenotes/tests/test_views.py
  bedrock/releasenotes/views.py
Labels: Needs Review, Review: µ

#11104 Deal with warning during test collection of bedrock/utils
  bedrock/utils/tests/test_decorators.py
Labels: Needs Review, Review: µ

#11101 Shrink QR code on EN WNP96 [#11070]
  bedrock/firefox/templates/firefox/whatsnew/includes/fx96-en/qr.html
  media/css/firefox/whatsnew/whatsnew-96-en-mobile.scss
Labels: P3, Needs Review, Review: µ

#11122 Update jasmine docs link [NO BUG]
  tests/unit/spec/base/core-datalayer-page-id.js
  tests/unit/spec/base/core-datalayer.js
  tests/unit/spec/base/dnt-helper.js
  tests/unit/spec/base/experiment-utils.js
  tests/unit/spec/base/fxa-utm-referral.js
  tests/unit/spec/base/mozilla-banner.js
  tests/unit/spec/base/mozilla-convert.js
  tests/unit/spec/base/mozilla-fxa-form.js
  tests/unit/spec/base/mozilla-fxa-link.js
  tests/unit/spec/base/mozilla-fxa.js
  tests/unit/spec/base/search-params.js
  tests/unit/spec/base/send-to-device.js
  tests/unit/spec/base/site.js
  tests/unit/spec/firefox/all/all-downloads-unified.js
  tests/unit/spec/firefox/new/common/thanks.js
Labels: Needs Review, Documentation, Review: µ

#11066 Remove legacy FxA sync flows (Fixes #9144)
  bedrock/base/templates/base-protocol.html
  bedrock/base/templates/macros.html
  bedrock/careers/templates/careers/base.html
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/index.html
  bedrock/firefox/templates/firefox/firstrun/firstrun.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/nightly/whatsnew.html
  bedrock/firefox/templates/firefox/pocket.html
  bedrock/firefox/templates/firefox/privacy/products.html
  bedrock/firefox/templates/firefox/products/index.html
  bedrock/firefox/templates/firefox/sync.html
  bedrock/firefox/templates/firefox/welcome/page1.html
  bedrock/firefox/templates/firefox/welcome/page2.html
  bedrock/firefox/templates/firefox/welcome/page3.html
  bedrock/firefox/templates/firefox/whatsnew/index-account.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-es.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-it.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx93-nl.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx95-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx95-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx96-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx96-fr.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/products/templates/products/vpn/landing.html
  bedrock/settings/base.py
  docs/firefox-accounts.rst
  media/js/base/fxa-bundle-init.es6.js
  media/js/base/fxa-form-init.es6.js
  media/js/base/fxa-form.es6.js
  media/js/base/fxa-link.es6.js
  media/js/base/fxa-product-button-init.es6.js
  media/js/base/fxa-product-button.es6.js
  media/js/base/fxa-utm-referral.js
  media/js/base/fxa-utm.es6.js
  media/js/base/mozilla-fxa-form-init.js
  media/js/base/mozilla-fxa-form.js
  media/js/base/mozilla-fxa-link-init.js
  media/js/base/mozilla-fxa-link.js
  media/js/base/mozilla-fxa-product-button.js
  media/js/firefox/accounts-2019.es6.js
  media/js/firefox/accounts-2019.js
  media/js/firefox/whatsnew/account-conditional-ctas.js
  media/js/products/vpn/landing.js
  media/static-bundles.json
  tests/unit/karma.conf.js
  tests/unit/spec/base/fxa-form.js
  tests/unit/spec/base/fxa-link.js
  tests/unit/spec/base/fxa-product-button.js
  tests/unit/spec/base/fxa-utm.js
Labels: P3, Review: M

#11136 Leaderhip updates; remove DCamp [fix #11133]
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/dave-camp-high-res.jpg
  media/img/mozorg/about/leadership/dave-camp.jpg
Labels: Review: µ

#11124 Remove unused cookie helper 404 script (#11123)
  bedrock/externalpages/templates/externalpages/pocket/base.html
Labels: P3, Needs Review, Review: µ

#11135 11106: Disable logging of DisallowedHost to reduce log noise
  bedrock/settings/base.py
Labels: Needs Review, Review: µ

#11110 Add tests to pocket mobile navigation (fixes #11029)
  bedrock/externalpages/templates/externalpages/pocket/base.html
  bedrock/externalpages/templates/externalpages/pocket/includes/nav.html
  media/css/externalpages/pocket/includes/_mobile-nav.scss
  media/js/externalpages/pocket/base.js
  media/js/externalpages/pocket/mobile-nav-init.es6.js
  media/js/externalpages/pocket/mobile-nav.es6.js
  media/static-bundles.json
  tests/functional/externalpages/pocket/__init__.py
  tests/functional/externalpages/pocket/test_navigation.py
  tests/pages/externalpages/pocket/__init__.py
  tests/pages/externalpages/pocket/about.py
  tests/pages/externalpages/pocket/base.py
  tests/unit/karma.conf.js
  tests/unit/spec/externalpages/pocket/mobile-nav.es6.js
Labels: Needs Review, Review: S
