Repository mozilla/bedrock, pull requests merged in 2022-06, with the labels that each got.

#11705 Remove blank target on pocket support links, fix typo, (fixes #11666)
  bedrock/pocket/templates/pocket/add.html
  bedrock/pocket/templates/pocket/jobs.html
Labels: Needs Review, Review: µ

#11710 Fix logo size on Nightly WNP [fix #11708]
  media/css/firefox/whatsnew/whatsnew-nightly.scss
Labels: Needs Review, Review: µ

#11706 Update to Sentry v7.0.0 (Fixes #10473)
  bedrock/settings/base.py
  media/js/base/sentry.es6.js
  package-lock.json
  package.json
  webpack.config.js
Labels: P3, Needs Review, Review: XS

#11729 Removed UTM param from same-site link
  bedrock/base/templates/includes/sticky-promo.html
Labels: Bug :bug:, Needs Review, Review: µ, analytics

#11728 String fix for MDNPlus Dev WNP [#11633]
  l10n/en/firefox/whatsnew/whatsnew-developer-mdnplus.ftl
Labels: Needs Review, Review: µ

#11731 Update browser support docs (Fixes #11709)
  docs/browser-support.rst
Labels: P3, Needs Review, Review: µ

#11722 Add Glean to core /firefox pages (Issue #10746)
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/new/basic/base.html
  bedrock/firefox/templates/firefox/new/desktop/base.html
Labels: Needs Review, Review: µ

#11741 Add spaces in L10N strings
  l10n/en/firefox/new/download.ftl
Labels: L10N, Needs Review, Review: µ

#11747 Another string fix for MDNPlus Dev WNP [#11633]
  l10n/en/firefox/whatsnew/whatsnew-developer-mdnplus.ftl
Labels: Needs Review, Review: µ

#11746 Replace TrafficCop with NPM package
  docs/abtest.rst
  docs/architecture/decisions/0003-use-cloudflare-workers-and-convert-for-multi-variant-testing.md
  docs/install.rst
  media/js/firefox/browsers/firefox-ios-sms-experiment.js
  media/js/firefox/welcome/welcome8-traffic-cop.js
  media/js/firefox/whatsnew/whatsnew-101-en-experiment.js
  media/js/firefox/whatsnew/whatsnew-99-en-experiment.js
  media/js/libs/mozilla-traffic-cop.js
  media/static-bundles.json
  package-lock.json
  package.json
Labels: Needs Review, Review: S, Javascript, Frontend

#11749 Stop sending people to the legacy VPN download page (Fixes #11748)
  bedrock/products/templates/products/vpn/includes/macros.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  docs/firefox-accounts.rst
Labels: P2, Needs Review, Review: µ

#11752 fix regression from Trafficcop PR
  media/js/firefox/whatsnew/whatsnew-99-en-experiment.js
Labels: Needs Review

#11751 Add pocket home 10 year badge (fixes #11730)
  bedrock/pocket/templates/pocket/home.html
  l10n-pocket/en/pocket/home.ftl
  media/css/pocket/components/about.scss
  media/css/pocket/components/add.scss
  media/css/pocket/components/home.scss
  media/css/pocket/components/platforms.scss
  media/css/pocket/includes/_nav.scss
Labels: Needs Review, Review: XS

#11777 Add region1.google-analytics.com to CSP list (Fixes #11768)
  bedrock/settings/__init__.py
Labels: Needs Review, Review: µ

#11776 Update @mozmeao/trafficcop to v2.0.0 (Fixes #11775)
  docs/abtest.rst
  media/js/firefox/browsers/firefox-ios-sms-experiment.js
  media/js/firefox/welcome/welcome8-traffic-cop.js
  media/js/firefox/whatsnew/whatsnew-101-en-experiment.js
  media/js/firefox/whatsnew/whatsnew-99-en-experiment.js
  package-lock.json
  package.json
Labels: Needs Review, Review: µ

#11774 Code variations for set to default page (fixes #11772)
  bedrock/firefox/templates/firefox/set-as-default/landing.html
  bedrock/firefox/urls.py
  l10n/en/firefox/set-as-default/landing.ftl
  media/js/firefox/set-as-default/landing.js
  media/static-bundles.json
Labels: Needs Review, Review: XS

#11712 update the contentful API to use Split
  bedrock/contentful/api.py
  bedrock/contentful/templates/includes/contentful/all.html
  media/css/contentful/mozilla/c-split.scss
  media/css/mozorg/home/home-contentful.scss
Labels: Review: S, Contentful

#11782 FIx Android experiment JS bundle [#11119]
  media/static-bundles.json
Labels: Review: µ

#11756 Knowledge is Power Newsletter
  bedrock/newsletter/templates/newsletter/knowledge-is-power.html
  bedrock/newsletter/urls.py
  l10n/en/mozorg/newsletters.ftl
  media/css/newsletter/newsletter-knowledge-is-power.scss
  media/static-bundles.json
  tests/functional/newsletter/test_newsletter_embed.py
  tests/pages/newsletter/knowledge_is_power.py
Labels: Review: XS, Frontend

#11783 Add Glean click delay for a few more CTAs (Fixes #11770)
  bedrock/base/templates/includes/protocol/navigation/nav-cta.html
  bedrock/firefox/templates/firefox/new/basic/base_download.html
  bedrock/firefox/templates/firefox/new/basic/download_windows.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/products/templates/products/vpn/includes/pricing-variable.html
  media/js/firefox/new/desktop/join-modal.js
  media/js/glean/elements.es6.js
Labels: Needs Review, Review: XS

#11794 Make MDN Plus animated SVG more performant (Fixes #11793)
  bedrock/firefox/templates/firefox/developer/whatsnew-mdnplus.html
Labels: Needs Review, Review: µ

#11800 Update Windows logo on /download/thanks/ (Fixes #11799)
  bedrock/firefox/templates/firefox/new/basic/thanks.html
  bedrock/firefox/templates/firefox/new/desktop/thanks.html
  l10n/en/firefox/new/desktop.ftl
  l10n/en/firefox/new/download.ftl
  media/css/firefox/new/common/thanks-messaging.scss
  media/img/logos/windows/logo-windows-10-black.svg
  media/img/logos/windows/logo-windows-10.svg
  media/img/logos/windows/logo-windows-black.svg
  media/js/base/site.js
Labels: P3, Needs Review, Review: µ

#11804 Only run Glean probe-scraper GitHub action on mozilla/bedrock (Fixes #11803)
  .github/workflows/glean-probe-scraper.yml
Labels: Needs Review, Review: µ

#11802 What’s new page for Firefox 102 [fix #11797]
  bedrock/firefox/templates/firefox/whatsnew/includes/fx102/newsletter-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx102-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx102-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx102-fr.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-102-de.scss
  media/css/firefox/whatsnew/whatsnew-102-en.scss
  media/css/firefox/whatsnew/whatsnew-102-fr.scss
  media/img/firefox/whatsnew/whatsnew102/icon-pocket-white.svg
  media/img/firefox/whatsnew/whatsnew102/icon-pocket.svg
  media/img/firefox/whatsnew/whatsnew102/pocket-discover-high-res.png
  media/img/firefox/whatsnew/whatsnew102/pocket-discover.png
  media/img/firefox/whatsnew/whatsnew102/pocket-library.svg
  media/img/firefox/whatsnew/whatsnew102/pocket-mobile-high-res.png
  media/img/firefox/whatsnew/whatsnew102/pocket-mobile.png
  media/static-bundles.json
Labels: P1, Review: XS

#11818 WNP 102 EN copy change [#11797]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx102-en.html
Labels: P2, Needs Review, Review: µ

#11820 Update Mozilla trademark list (Fixes #11819)
  bedrock/foundation/templates/foundation/trademarks/list.html
  media/img/trademarks/cargo-logo.png
  media/img/trademarks/rust-logo.png
  media/img/trademarks/seamonkey-logo-r.png
  media/img/trademarks/seamonkey-wordmark-r.png
Labels: P3, Needs Review, Review: µ

#11830 Add country and language newsletter field labels (Fixes #11829)
  bedrock/newsletter/forms.py
  bedrock/newsletter/templates/newsletter/includes/form.html
  l10n/en/newsletter_form.ftl
  media/css/firefox/developer/includes/newsletter.scss
Labels: P3, Needs Review, Review: XS

#11824 Update CookieHelper lib via NPM (Fixes #11784)
  media/js/base/core-datalayer-page-id.js
  media/js/base/mozilla-cookie-helper.js
  media/js/privacy/data-preferences.es6.js
  media/js/products/vpn/affiliate-attribution.es6.js
  package-lock.json
  package.json
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-cookie-helper.js
  tests/unit/spec/products/vpn/affiliate-attribution.js
Labels: P3, Needs Review, Review: XS
