Repository mozilla/bedrock, pull requests merged in 2022-11, with the labels that each got.

#12318 Fix Firefox Relay wordmark alignment for l10n (Fixes #12317)
  media/css/products/vpn/components/block.scss
Labels: P3, Needs Review, Review: µ

#12299 Remove image macro from billboard macro
  bedrock/base/templates/macros-protocol.html
  bedrock/mozorg/templates/mozorg/about/index.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/templates/mozorg/home/home.html
  docs/coding.rst
Labels: Review: XS

#12316 Pocket: New base template (fixes #12302)
  bedrock/pocket/templates/pocket/404.html
  bedrock/pocket/templates/pocket/500.html
  bedrock/pocket/templates/pocket/about.html
  bedrock/pocket/templates/pocket/add.html
  bedrock/pocket/templates/pocket/android.html
  bedrock/pocket/templates/pocket/base-platform.html
  bedrock/pocket/templates/pocket/base.html
  bedrock/pocket/templates/pocket/chrome.html
  bedrock/pocket/templates/pocket/contact-info.html
  bedrock/pocket/templates/pocket/edge.html
  bedrock/pocket/templates/pocket/get-inspired.html
  bedrock/pocket/templates/pocket/home.html
  bedrock/pocket/templates/pocket/includes/footer-platform.html
  bedrock/pocket/templates/pocket/includes/nav-platform.html
  bedrock/pocket/templates/pocket/ios.html
  bedrock/pocket/templates/pocket/jobs.html
  bedrock/pocket/templates/pocket/opera.html
  bedrock/pocket/templates/pocket/platform-pages.html
  bedrock/pocket/templates/pocket/pocket-and-firefox.html
  bedrock/pocket/templates/pocket/privacy.html
  bedrock/pocket/templates/pocket/safari.html
  bedrock/pocket/templates/pocket/save-to-pocket.html
  bedrock/pocket/templates/pocket/tos.html
  bedrock/pocket/templates/pocket/welcome.html
  tests/functional/pocket/test_navigation_platform.py
  tests/pages/pocket/add.py
  tests/pages/pocket/base.py
Labels: Needs Review, Review: XS

#12305 Pocket mode: improve line spacing of headers
  media/css/pocket/components/about.scss
Labels: Review: XS

#12342 Fix broken styles in /new-tab-learn-more
  bedrock/pocket/templates/pocket/includes/footer.html
  media/css/pocket/components/new-tab-learn-more.scss
Labels: Needs Review, Review: µ

#12341 Fix French string on /new page [bug #1799474]
  bedrock/firefox/templates/firefox/new/desktop/download.html
Labels: Needs Review, Review: µ

#12321 Remove image from card macro (Fixes #12300)
  bedrock/base/templates/macros-protocol.html
  bedrock/contentful/templates/includes/contentful/all.html
  bedrock/firefox/templates/firefox/features/tips/tips.html
  bedrock/firefox/templates/firefox/more.html
  bedrock/firefox/templates/firefox/pocket.html
  bedrock/foundation/templates/foundation/annualreport/2020/index.html
  bedrock/mozorg/templates/mozorg/about/index.html
  bedrock/mozorg/templates/mozorg/diversity/2021/beyond-products.html
  bedrock/mozorg/templates/mozorg/diversity/2021/index.html
  bedrock/mozorg/templates/mozorg/diversity/2021/what-we-build.html
  bedrock/mozorg/templates/mozorg/diversity/2021/who-we-are.html
  bedrock/mozorg/templates/mozorg/moss/index.html
  bedrock/newsletter/templates/newsletter/updated.html
  docs/coding.rst
Labels: Review: XS

#12348 Add English WNP for Firefox 107 [fix #12229]
  bedrock/firefox/templates/firefox/whatsnew/includes/fx107/vpn-shopping.svg
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx107-en.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-107-en.scss
  media/js/firefox/whatsnew/whatsnew-107-en.js
  media/static-bundles.json
Labels: P1, Needs Review, Review: XS

#12356 Add legal staycation terms (fixes #12332)
  bedrock/legal/templates/legal/terms/staycation.html
  bedrock/legal/urls.py
Labels: P1, Needs Review, Legal Docs :scroll:, Review: XS

#12390 Fix Pocket about illustration overlap (fixes #12371)
  media/css/pocket/components/about.scss
Labels: Bug :bug:, Needs Review, Review: µ

#12388 Add fundraising banner for Giving Tuesday, 2022 [fix #12373]
  bedrock/base/templates/includes/banners/fundraiser.html
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/settings/base.py
  media/css/base/banners/fundraiser.scss
  media/img/banners/fundraising/dear-internet-bg-lg-high-res.png
  media/img/banners/fundraising/dear-internet-bg-lg-simple-high-res.png
  media/img/banners/fundraising/dear-internet-bg-lg-simple.png
  media/img/banners/fundraising/dear-internet-bg-lg.png
  media/img/banners/fundraising/dear-internet-bg-sm-high-res.png
  media/img/banners/fundraising/dear-internet-bg-sm.png
  media/img/banners/fundraising/giving-high-res.jpg
  media/img/banners/fundraising/giving-rtl-high-res.jpg
  media/img/banners/fundraising/giving-rtl.jpg
  media/img/banners/fundraising/giving.jpg
Labels: Review: S

#12394 Fix fundraising banner destination
  bedrock/base/templates/includes/banners/fundraiser.html
  media/css/base/banners/fundraiser.scss
Labels: P1, Needs Review, Review: µ

#12354 Remove image macro from split (/firefox)
  bedrock/base/templates/macros-protocol.html
  bedrock/firefox/templates/firefox/browsers/chromebook.html
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/android.html
  bedrock/firefox/templates/firefox/browsers/mobile/compare.html
  bedrock/firefox/templates/firefox/browsers/mobile/focus.html
  bedrock/firefox/templates/firefox/browsers/mobile/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/ios.html
  bedrock/firefox/templates/firefox/browsers/quantum.html
  bedrock/firefox/templates/firefox/developer/includes/for-developers.html
  bedrock/firefox/templates/firefox/developer/includes/nightly.html
  bedrock/firefox/templates/firefox/developer/includes/performance.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/features/bookmarks.html
  bedrock/firefox/templates/firefox/features/fast.html
  bedrock/firefox/templates/firefox/features/fingerprinting.html
  bedrock/firefox/templates/firefox/features/independent.html
  bedrock/firefox/templates/firefox/features/index.html
  bedrock/firefox/templates/firefox/features/memory.html
  bedrock/firefox/templates/firefox/features/password-manager.html
  bedrock/firefox/templates/firefox/features/picture-in-picture.html
  bedrock/firefox/templates/firefox/features/private-browsing.html
  bedrock/firefox/templates/firefox/features/translate.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/mobile/index.html
  bedrock/firefox/templates/firefox/more.html
  bedrock/firefox/templates/firefox/more/misinformation.html
  bedrock/firefox/templates/firefox/pocket.html
  bedrock/firefox/templates/firefox/privacy/book.html
  bedrock/firefox/templates/firefox/privacy/index.html
  bedrock/firefox/templates/firefox/privacy/passwords.html
  bedrock/firefox/templates/firefox/privacy/products.html
  bedrock/firefox/templates/firefox/products/index.html
  bedrock/firefox/templates/firefox/switch.html
  bedrock/firefox/templates/firefox/sync.html
Labels: Needs Review, Review: S

#12402 Fix more typos in SOM
  bedrock/foundation/templates/foundation/annualreport/2021/article/innovation.html
  bedrock/foundation/templates/foundation/annualreport/2021/article/mark-surman.html
  bedrock/foundation/templates/foundation/annualreport/2021/includes/modal-blog.html
Labels: Review: µ

#12408 Add Pocket Best of 2022 home promo (Fixes #12406)
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/includes/pocket-10-years-promo.html
  bedrock/mozorg/templates/mozorg/home/includes/pocket-best-2022-promo.html
  media/css/mozorg/home/home-pocket-10-years-promo.scss
  media/css/mozorg/home/home-pocket-best-2022-promo.scss
  media/img/home/2021/pocket-10-years-1000.jpg
  media/img/home/2021/pocket-10-years-1200.jpg
  media/img/home/2021/pocket-10-years-1400.jpg
  media/img/home/2021/pocket-10-years-700.jpg
  media/img/home/2021/pocket-10-years-850.jpg
  media/img/home/2022/pocket-best-promo/desktop.svg
  media/img/home/2022/pocket-best-promo/mobile.svg
  media/static-bundles.json
Labels: P1, Needs Review, Review: XS

#12391 Import DNT helper via NPM (Fixes #11475)
  docs/coding.rst
  media/js/base/dnt-helper.js
  package-lock.json
  package.json
  tests/unit/karma.conf.js
  tests/unit/spec/base/dnt-helper.js
  tests/unit/spec/base/fxa-utm.js
  tests/unit/spec/base/mozilla-pixel.js
  tests/unit/spec/base/stub-attribution.js
Labels: P3, Needs Review, Review: µ

#12421 Migrate newsletter/country/ page to post directly to Basket (Fixes #12376)
  bedrock/newsletter/redirects.py
  bedrock/newsletter/templates/newsletter/country.html
  bedrock/newsletter/templates/newsletter/country_success.html
  bedrock/newsletter/tests/test_views.py
  bedrock/newsletter/urls.py
  bedrock/newsletter/views.py
  media/css/newsletter/newsletter-country.scss
  media/css/newsletter/newsletter.scss
  media/js/newsletter/country-init.es6.js
  media/js/newsletter/country.es6.js
  media/js/newsletter/form-utils.es6.js
  media/static-bundles.json
  tests/redirects/map_globalconf.py
  tests/unit/karma.conf.js
  tests/unit/spec/newsletter/country.js
Labels: P3, Needs Review, Review: XS

#12430 Fix intermittent test failure on /leadership page
  bedrock/mozorg/templates/mozorg/about/leadership/index.html
Labels: P3, Needs Review, Review: µ

#12410 Add /whatsnew page for Firefox 108 (Fixes #12231)
  bedrock/firefox/templates/firefox/whatsnew/includes/fx108/macros.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx108-curation-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx108-curation-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx108-feature-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx108-feature-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx108-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx108-uk.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-108-fr.scss
  media/css/firefox/whatsnew/whatsnew-108.scss
  media/img/firefox/whatsnew/whatsnew108/desktop.svg
  media/img/firefox/whatsnew/whatsnew108/fr/header-1100.jpg
  media/img/firefox/whatsnew/whatsnew108/fr/header-550.jpg
  media/img/firefox/whatsnew/whatsnew108/fr/header-825.jpg
  media/img/firefox/whatsnew/whatsnew108/mobile.svg
  media/js/firefox/whatsnew/whatsnew-108-experiment-de.es6.js
  media/js/firefox/whatsnew/whatsnew-108-experiment-en.es6.js
  media/js/firefox/whatsnew/whatsnew-108.es6.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_108.py
  tests/pages/firefox/whatsnew/whatsnew_108.py
Labels: P1, Needs Review, Review: S

#12344 Contribute card fix overflow (fixes #12343)
  media/css/mozorg/contribute.scss
Labels: Bug :bug:, Needs Review, Review: XS
