Repository mozilla/bedrock, pull requests merged in 2022-02, with the labels that each got.

#11185 Remove Firefox Reality (fixes #11118)
  bedrock/base/templates/includes/protocol/navigation/menus/innovation.html
  bedrock/firefox/templates/firefox/browsers/browser-history.html
  bedrock/firefox/templates/firefox/browsers/index.html
  l10n/en/firefox/browsers/history/browser-history.ftl
  media/css/firefox/browsers-products.scss
  media/img/firefox/browsers/dev-high-res.png
  media/img/firefox/browsers/dev.png
  media/img/firefox/browsers/reality-high-res.jpg
  media/img/firefox/browsers/reality.jpg
Labels: P1

#11186 Add whatsnew page for Firefox 97 [fix #11172]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx97-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx97-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx97-fr.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-97-en.scss
  media/css/firefox/whatsnew/whatsnew-97-eu.scss
  media/img/firefox/whatsnew/whatsnew97/mozillavpn-high-res.png
  media/img/firefox/whatsnew/whatsnew97/mozillavpn.png
  media/img/firefox/whatsnew/whatsnew97/pocket-de-high-res.jpg
  media/img/firefox/whatsnew/whatsnew97/pocket-de.jpg
  media/img/firefox/whatsnew/whatsnew97/pocket-fr-high-res.jpg
  media/img/firefox/whatsnew/whatsnew97/pocket-fr.jpg
  media/img/firefox/whatsnew/whatsnew97/pocket-hero-en-high-res.jpg
  media/img/firefox/whatsnew/whatsnew97/pocket-hero-en.jpg
  media/img/firefox/whatsnew/whatsnew97/video-hero.jpg
  media/js/firefox/whatsnew/whatsnew-97-eu.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_97.py
  tests/pages/firefox/whatsnew/whatsnew_97.py
Labels: P1, Needs Review, Review: S

#11176 Upgrade Bedrock to Python 3.9 and update dependency management tooling
  .circleci/config.yml
  Dockerfile
  Makefile
  bedrock/settings/base.py
  bin/compile-requirements.sh
  bin/pip-compile-multi-header-message.txt
  docker-compose.yml
  docs/coding.rst
  docs/install.rst
  pyproject.toml
  requirements/base.txt
  requirements/dev.in
  requirements/dev.txt
  requirements/docs.in
  requirements/docs.txt
  requirements/migration.txt
  requirements/prod.in
  requirements/prod.txt
Labels: Needs Review, Review: S

#11222 Fix docs syntax [no bug]
  docs/install.rst
Labels: Documentation

#11223 Add WNP 98 for EU (VPN) (Fixes #11210)
  bedrock/firefox/templates/firefox/whatsnew/includes/fx98-vpn-eu/heart.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx98-vpn-eu/one-tap.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx98-vpn-eu/vpn-header.svg
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-vpn-eu.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  l10n/configs/pontoon.toml
  l10n/en/firefox/whatsnew/whatsnew-98-vpn-eu.ftl
  media/css/firefox/whatsnew/whatsnew-98-vpn-eu.scss
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_98.py
  tests/pages/firefox/whatsnew/whatsnew_98.py
Labels: P1, Needs Review, Review: XS

#11230 Add new supported countries to VPN landing page (Fixes #11213)
  bedrock/products/templates/products/vpn/includes/macros.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/tests/test_helper_misc.py
  bedrock/products/views.py
  bedrock/settings/base.py
  l10n/en/products/vpn/shared.ftl
Labels: P1, Needs Review, Review: XS

#11237 Add basket docs link [no bug]
  docs/newsletters.rst
Labels: Needs Review, Documentation, Review: µ

#11245 Minor fix to the label element when showing the XUL namespace page
  bedrock/mozorg/templates/mozorg/namespaces.html
Labels: Needs Review, Review: µ

#11238 Add Transparency Report for H2 2021 (Fixes #11214)
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2021.html
  bedrock/mozorg/urls.py
Labels: P2, Needs Review, Review: XS

#11253 Update diversity link in careers page
  bedrock/careers/templates/careers/home.html
Labels: Review: µ, Careers

#11218 Add Turning Red promo banner [fix #11195]
  bedrock/base/templates/includes/banners/turning-red.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/mozorg/templates/mozorg/about/index.html
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  media/css/base/banners/turning-red.scss
  media/img/banners/turningred/button-fun.png
  media/img/banners/turningred/close-x.svg
  media/img/banners/turningred/underline.svg
  media/js/base/banners/turning-red-banner-init.js
  media/static-bundles.json
Labels: P1, Review: XS

#11248 WNP 98 for DE/FR (Fixes #11211)
  bedrock/firefox/templates/firefox/whatsnew/includes/fx98-mobile-de/qr.html
  bedrock/firefox/templates/firefox/whatsnew/includes/fx98-mobile-fr/qr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-mobile-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx98-mobile-fr.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-98-mobile-eu.scss
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_98.py
  tests/pages/firefox/whatsnew/whatsnew_98.py
Labels: P1, Review: XS
