Repository mozilla/bedrock, pull requests merged in 2022-04, with the labels that each got.

#11404 Add whatsnew pages for Firefox 99 [fix #11393]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx99-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx99-en-rally.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx99-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx99-fr.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-99-en-rally.scss
  media/css/firefox/whatsnew/whatsnew-99-en.scss
  media/css/firefox/whatsnew/whatsnew-99-eu.scss
  media/img/firefox/whatsnew/whatsnew99/icon-pocket-white.svg
  media/img/firefox/whatsnew/whatsnew99/icon-pocket.svg
  media/img/firefox/whatsnew/whatsnew99/icon-share-white.svg
  media/img/firefox/whatsnew/whatsnew99/icon-share.svg
  media/img/firefox/whatsnew/whatsnew99/logo-rally-black.svg
  media/img/firefox/whatsnew/whatsnew99/logo-rally-white.svg
  media/img/firefox/whatsnew/whatsnew99/moz-rally-high-res.png
  media/img/firefox/whatsnew/whatsnew99/moz-rally.png
  media/img/firefox/whatsnew/whatsnew99/pocket-discover-high-res.png
  media/img/firefox/whatsnew/whatsnew99/pocket-discover.png
  media/img/firefox/whatsnew/whatsnew99/pocket-hero-eu-high-res.png
  media/img/firefox/whatsnew/whatsnew99/pocket-hero-eu.png
  media/img/firefox/whatsnew/whatsnew99/pocket-mobile-high-res.png
  media/img/firefox/whatsnew/whatsnew99/pocket-mobile.png
  media/js/firefox/whatsnew/whatsnew-99-en-experiment.js
  media/static-bundles.json
Labels: P1, Review: S

#11400 Update Stylelint (Fixes #11340)
  .pre-commit-config.yaml
  .stylelintrc
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#11343 Update Sentry JS
  media/js/base/sentry.es6.js
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#11350 Update to Selenium 4 (Fixes #10591)
  bin/run-integration-tests.sh
  docs/testing.rst
  requirements/dev.in
  requirements/dev.txt
  tests/pages/firefox/ios_testflight.py
  tests/pages/regions/newsletter.py
Labels: P3, Needs Review, Review: S

#11443 Restore missing images on /firefox/browsers/mobile/ page (Fixes #11405)
  media/css/firefox/browsers-products.scss
  media/img/firefox/browsers/dev-high-res.png
  media/img/firefox/browsers/dev.png
Labels: P2, Needs Review, Review: µ

#11444 Render sidebar at the end of /privacy pages for mobile (Fixes #10628)
  bedrock/privacy/templates/privacy/base-protocol.html
Labels: P3, Needs Review, Review: µ

#11447 Lazy load Contentful images on home page (Fixes #10669)
  bedrock/contentful/api.py
  bedrock/contentful/templates/includes/contentful/all.html
  bedrock/contentful/tests/test_contentful_api.py
Labels: P3, Needs Review, Review: µ

#11445 Make home page footer CTA more obvious about which product it relates to (Fixes #10706)
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
Labels: P3, Needs Review, Review: µ

#11446 Update CJMS endpoint for prod (Issue #11212)
  bedrock/settings/base.py
  media/css/products/vpn/components/affiliate.scss
Labels: P2, Needs Review, Review: µ

#11452 Set nativeEvents to false for IE SauceLabs tests
  docs/testing.rst
  tests/functional/conftest.py
Labels: P3, Needs Review, Review: µ

#11358 Add Third-Party Software Injection Policy (Fixes #11276)
  bedrock/security/templates/security/base.html
  bedrock/security/templates/security/third-party-injection-policy.html
  bedrock/security/urls.py
Labels: P3, Review: XS

#11458 Update governance discussion forum link (fixes #10866)
  bedrock/mozorg/templates/mozorg/about/governance/governance.html
Labels: Bug :bug:, Needs Review, Review: µ

#11455 Add 'OK' button to VPN affiliate banner (Fixes #11454)
  bedrock/products/templates/products/vpn/includes/cookie-notification.html
  l10n/en/products/vpn/shared.ftl
  media/css/products/vpn/components/affiliate.scss
  media/js/products/vpn/affiliate-init.es6.js
Labels: P1, Needs Review, Review: XS

#11451 Reduce content layout shift (CLS) caused by sub navigation. (Fixes #9823)
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/browsers/browser-history.html
  bedrock/firefox/templates/firefox/browsers/chromebook.html
  bedrock/firefox/templates/firefox/browsers/compare/includes/subnav.html
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/android.html
  bedrock/firefox/templates/firefox/browsers/mobile/compare.html
  bedrock/firefox/templates/firefox/browsers/mobile/focus.html
  bedrock/firefox/templates/firefox/browsers/mobile/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/ios.html
  bedrock/firefox/templates/firefox/browsers/what-is-a-browser.html
  bedrock/firefox/templates/firefox/browsers/windows-64-bit.html
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/faq.html
  bedrock/firefox/templates/firefox/features/includes/subnav.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/mobile/index.html
  bedrock/firefox/templates/firefox/new/basic/base_download.html
  bedrock/firefox/templates/firefox/new/desktop/includes/sub_nav.html
  bedrock/firefox/templates/firefox/privacy/base.html
  bedrock/firefox/templates/firefox/privacy/book.html
  bedrock/firefox/templates/firefox/releases/notes.html
  bedrock/firefox/templates/firefox/sync.html
  bedrock/mozorg/templates/mozorg/diversity/2021/index.html
  bedrock/products/templates/products/vpn/includes/subnav-more.html
  bedrock/products/templates/products/vpn/includes/subnav.html
  bedrock/products/templates/products/vpn/platforms/includes/subnav-desktop.html
  bedrock/products/templates/products/vpn/platforms/includes/subnav-mobile.html
  media/css/protocol/components/_sub-navigation.scss
Labels: P3, Needs Review, Review: XS

#11466 Fix remaining selectors for new footer styles (fixes #11465)
  media/css/firefox/welcome11.scss
  media/css/firefox/welcome12.scss
  media/css/firefox/welcome13.scss
  media/css/firefox/whatsnew/includes/_dark-mode.scss
  media/css/firefox/whatsnew/includes/_footer.scss
  media/css/firefox/whatsnew/whatsnew-99-en.scss
Labels: Bug :bug:, Needs Review, Review: S

#11470 Hide checkboxes on single newsletters (Fixes #11469)
  bedrock/firefox/templates/firefox/testflight.html
  bedrock/newsletter/templates/newsletter/includes/form.html
  bedrock/products/templates/products/vpn/invite.html
Labels: Needs Review, Review: µ

#11468 Add AMO referrer check for /thanks/?s=direct page (Fixes #11467)
  media/js/firefox/new/common/thanks-direct.js
Labels: P2, Needs Review, Review: XS

#11477 Webpack dependency updates (Fixes #11337)
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: XS

#11482 (Fixes #11464) Set up variation page for focus page
  bedrock/firefox/templates/firefox/browsers/mobile/focus.html
  bedrock/firefox/templates/firefox/browsers/mobile/includes/s2d-focus.html
  bedrock/firefox/urls.py
  media/img/firefox/browsers/mobile/qr-variation.svg
Labels: Needs Review, Review: XS

#11486 Set up SMS to Download experiment
  bedrock/firefox/forms.py
  bedrock/firefox/templates/firefox/browsers/mobile/includes/s2d-ios-email.html
  bedrock/firefox/templates/firefox/browsers/mobile/includes/s2d-ios-qr.html
  bedrock/firefox/templates/firefox/browsers/mobile/includes/s2d-ios-sms.html
  bedrock/firefox/templates/firefox/browsers/mobile/ios.html
  bedrock/firefox/tests/test_forms.py
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  bedrock/settings/base.py
  media/img/firefox/browsers/mobile/ios/qr-ios-experiment.png
  media/js/base/send-to-device-sms.js
  media/js/firefox/browsers/firefox-ios-sms-experiment.js
  media/js/firefox/browsers/mobile-sms.js
  media/static-bundles.json
  requirements/dev.txt
  requirements/prod.in
  requirements/prod.txt
Labels: Needs Review, Review: S

#11387 Migrate Webvision to Bedrock
  bedrock/mozorg/management/commands/update_webvision_docs.py
  bedrock/mozorg/migrations/0001_initial.py
  bedrock/mozorg/migrations/0001_squashed_0004_squash.py
  bedrock/mozorg/migrations/0002_blogarticle.py
  bedrock/mozorg/migrations/0002_webvisiondoc.py
  bedrock/mozorg/migrations/0003_delete_blogarticle.py
  bedrock/mozorg/migrations/0004_auto_20200122_0957.py
  bedrock/mozorg/models.py
  bedrock/mozorg/templates/mozorg/about-base.html
  bedrock/mozorg/templates/mozorg/about/index.html
  bedrock/mozorg/templates/mozorg/about/manifesto-details.html
  bedrock/mozorg/templates/mozorg/about/webvision/full.html
  bedrock/mozorg/templates/mozorg/about/webvision/summary.html
  bedrock/mozorg/tests/test_views.py
  bedrock/mozorg/urls.py
  bedrock/mozorg/views.py
  bedrock/settings/base.py
  bin/run-db-update.sh
  l10n/en/mozorg/about.ftl
  l10n/en/mozorg/about/shared.ftl
  media/css/mozorg/webvision.scss
  media/img/mozorg/about/purple-bg.jpg
  media/static-bundles.json
Labels: Do Not Merge :warning:, WIP :construction:, Review: S

#11492 Remove Turning Red banner (Fixes #11490)
  bedrock/base/templates/includes/banners/turning-red.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/views.py
  bedrock/mozorg/templates/mozorg/about/index.html
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  media/css/base/banners/turning-red.scss
  media/js/base/banners/turning-red-banner-init.js
  media/static-bundles.json
Labels: P3, Needs Review, Review: XS

#11497 Update Adjust URLs for SMS experiment [#11119]
  bedrock/firefox/templates/firefox/browsers/mobile/includes/s2d-ios-qr.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/img/firefox/browsers/mobile/ios/qr-ios-experiment.png
  media/img/firefox/browsers/mobile/ios/qr-ios-experiment.svg
Labels: Review: µ

#11491 Update VPN affiliate docs with addition of OK button
  docs/vpn-affiliate-attribution.rst
Labels: P3, Needs Review, Review: µ

#11520 Update gunicorn dependency
  requirements/dev.txt
  requirements/prod.in
  requirements/prod.txt
Labels: Fire :fire:

#11527 Add `:abbr:` tags for common abbreviations
  docs/abtest.rst
  docs/analytics.rst
  docs/banners.rst
  docs/browser-support.rst
  docs/coding.rst
  docs/contentful.rst
  docs/download-buttons.rst
  docs/firefox-accounts.rst
  docs/install.rst
  docs/l10n.rst
  docs/redirects.rst
  docs/send-to-device.rst
  docs/vpn-affiliate-attribution.rst
Labels: Documentation

#11526 Document CSS bundles updates
  docs/coding.rst
Labels: Documentation

#11534 Initiate new CJMS POST when issued with a 404 for unknown aic id (Fixes #11506)
  media/js/products/vpn/affiliate-attribution.es6.js
  tests/unit/spec/products/vpn/affiliate-attribution.js
Labels: P2, Needs Review, Review: XS

#11545 Updated subsection underline for visibility
  docs/coding.rst
Labels: Needs Review, Documentation, Review: µ

#11549 Add get-app page experiment variations [fix #11547]
  bedrock/firefox/templates/firefox/mobile/get-app.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/urls.py
  bedrock/settings/base.py
Labels: P1, Needs Review, Review: XS

#11512 Remove gap space on firefox pages (fixes #11457)
  bedrock/firefox/templates/firefox/features/tips/tips.html
  bedrock/firefox/templates/firefox/more.html
  bedrock/firefox/templates/firefox/more/misinformation.html
  bedrock/firefox/templates/firefox/pocket.html
  bedrock/firefox/templates/firefox/privacy/index.html
  bedrock/firefox/templates/firefox/privacy/passwords.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/build-security.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/engage-users.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/index.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/stay-lean.html
  media/css/firefox/privacy/common.scss
  media/css/protocol/components/split.scss
Labels: Bug :bug:, Needs Review, Review: XS

#11554 Update PR template to use checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Review: µ

#11394 Add sub_nav macro and current page styling (fixes #10038)
  bedrock/base/templates/macros.html
  bedrock/base/tests/test_macros.py
  bedrock/firefox/templates/firefox/browsers/chromebook.html
  bedrock/firefox/templates/firefox/browsers/compare/includes/subnav.html
  bedrock/firefox/templates/firefox/browsers/mobile/android.html
  bedrock/firefox/templates/firefox/browsers/mobile/compare.html
  bedrock/firefox/templates/firefox/browsers/mobile/focus.html
  bedrock/firefox/templates/firefox/browsers/mobile/includes/sub-nav.html
  bedrock/firefox/templates/firefox/browsers/mobile/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/ios.html
  bedrock/firefox/templates/firefox/browsers/windows-64-bit.html
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/firefox/templates/firefox/includes/desktop-platform-sub-nav.html
  bedrock/firefox/templates/firefox/new/basic/base_download.html
  bedrock/firefox/templates/firefox/privacy/base.html
  bedrock/firefox/templates/firefox/privacy/book.html
  bedrock/firefox/templates/firefox/privacy/includes/sub-nav.html
  bedrock/firefox/templates/firefox/releases/notes.html
  bedrock/mozorg/templates/mozorg/diversity/2021/index.html
  bedrock/products/templates/products/vpn/includes/subnav-more.html
  bedrock/products/templates/products/vpn/platforms/includes/subnav-desktop.html
  bedrock/products/templates/products/vpn/platforms/includes/subnav-mobile.html
  media/css/protocol/components/_sub-navigation.scss
Labels: P3, Needs Review, Review: S
