Repository mozilla/bedrock, pull requests merged in 2022-12, with the labels that each got.

#12431 Fix #12234 annual-report-2019-2020.scss
  media/css/foundation/annual-report-2019-2020.scss
Labels: Needs Review, Review: µ

#12420 Add Stories Article (fixes #12379)
  bedrock/stories/templates/stories/articles/art-of-engagement.html
  bedrock/stories/templates/stories/articles/build-together.html
  bedrock/stories/templates/stories/articles/community-champion.html
  bedrock/stories/templates/stories/articles/joy-of-color.html
  bedrock/stories/templates/stories/articles/raising-technology-eq.html
  bedrock/stories/templates/stories/includes/macros.html
  bedrock/stories/templates/stories/includes/stories-landing-featured.html
  bedrock/stories/templates/stories/landing.html
  bedrock/stories/templates/stories/stories-base-article.html
  bedrock/stories/urls.py
  media/css/stories/includes/lib.scss
  media/css/stories/stories-article.scss
  media/css/stories/stories-landing.scss
  media/css/stories/stories-shared.scss
  media/img/stories/credit/amber-case-credit-high-res.jpg
  media/img/stories/credit/ingrid-fetell-lee-credit-high-res.jpg
  media/img/stories/credit/keely-alexis-credit-high-res.jpg
  media/img/stories/credit/mikal-lewis-credit-high-res.png
  media/img/stories/credit/pamela-pavliscak-credit.jpg
  media/img/stories/raising-technology-eq-1000.jpg
  media/img/stories/raising-technology-eq-1500.jpg
  media/img/stories/raising-technology-eq-500.jpg
  media/img/stories/social/raising-technology-eq-social.jpg
Labels: Review: S

#12453 Update impressum page (Fixes #12452)
  bedrock/legal/templates/legal/impressum.html
Labels: P2, Needs Review, Review: µ

#12448 Newsletter /updated page should post directly to Basket (Fixes #12377)
  bedrock/newsletter/templates/newsletter/base.html
  bedrock/newsletter/templates/newsletter/country.html
  bedrock/newsletter/templates/newsletter/updated.html
  bedrock/newsletter/views.py
  l10n/en/mozorg/newsletters.ftl
  media/css/newsletter/newsletter-updated.scss
  media/css/newsletter/newsletter.scss
  media/js/newsletter/confirm.js
  media/js/newsletter/form-utils.es6.js
  media/js/newsletter/unsubscribed-init.es6.js
  media/js/newsletter/unsubscribed.es6.js
  media/js/newsletter/updated.es6.js
  media/static-bundles.json
  tests/unit/karma.conf.js
  tests/unit/spec/newsletter/unsubscribed.js
Labels: P3, Review: XS

#12407 Update Mozilla Hubs logo (#12399)
  bedrock/base/templates/includes/protocol/navigation/menus/innovation.html
  media/img/nav/icons/icon-mozilla-hubs.svg
Labels: Review: µ

#12451 Add functional tests for VPN / Relay bundle offer (Fixes #12424)
  bedrock/products/views.py
  tests/functional/products/vpn/test_landing.py
  tests/pages/products/vpn/landing.py
Labels: P3, Needs Review, Review: µ

#12475 Update trademark logos (Fixes #12352)
  bedrock/foundation/templates/foundation/trademarks/list.html
  media/img/trademarks/firefox-focus-logo.png
  media/img/trademarks/thunderbird-logo-r.png
  media/img/trademarks/thunderbird-logo.svg
  media/img/trademarks/thunderbird_logo_100.png
Labels: P3, Needs Review, Review: µ

#12476 Add SUMO link to /whatsnew page update notification (Fixes #12444)
  bedrock/firefox/templates/firefox/whatsnew/includes/header.html
  l10n/en/firefox/whatsnew/whatsnew.ftl
Labels: P3, Needs Review, Review: µ

#12474 Update meta data on home page when 'Choose your own language' is displayed (Fixes #12468)
  bedrock/base/templates/404-locale.html
Labels: P3, Needs Review, Review: µ

#12473 Remove outdated Wiki link from firefox/privacy page (Fixes #12469)
  bedrock/firefox/templates/firefox/privacy/index.html
  l10n/en/firefox/privacy-hub.ftl
Labels: P3, Needs Review, Review: µ

#12472 Bump @sentry/browser to v7.25.0
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#12479 Remove image macro use from split macro (mozorg) (Issue #12331)
  bedrock/base/templates/macros-protocol.html
  bedrock/contentful/templates/includes/contentful/all.html
  bedrock/firefox/templates/firefox/browsers/compare/index.html
  bedrock/firefox/templates/firefox/faq.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-de-coupon.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-en-coupon.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-fr-coupon.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx105-de-1.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx105-de-2.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx105-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx105-uk-1.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx105-uk-2.html
  bedrock/foundation/templates/foundation/annualreport/2019/index.html
  bedrock/foundation/templates/foundation/annualreport/2020/index.html
  bedrock/foundation/templates/foundation/annualreport/2021/index.html
  bedrock/mozorg/templates/mozorg/about/index.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/build-security.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/engage-users.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/index.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/stay-lean.html
  bedrock/mozorg/templates/mozorg/contribute.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/templates/mozorg/home/includes/firefox-family-promo.html
  bedrock/mozorg/templates/mozorg/home/includes/firefox-mr106-promo.html
  bedrock/mozorg/templates/mozorg/home/includes/mr2-promo.html
  bedrock/newsletter/templates/newsletter/family.html
  bedrock/products/templates/products/vpn/resource-center/base-article.html
  bedrock/products/templates/products/vpn/resource-center/landing.html
Labels: P3, Needs Review, Review: XS

#12483 Update contentful preview docs
  docs/contentful.rst
Labels: Needs Review, Review: µ

#12489 Remove duplicate Mozilla from home page title (Fixes #12488)
  bedrock/base/templates/404-locale.html
Labels: P3, Needs Review, Review: µ

#12492 Fix careers listings filtering (Fixes #12490)
  media/js/careers/listings/filters.es6.js
  tests/unit/spec/careers/filters.js
Labels: P1, Needs Review, Review: µ

#12482 Remove image macro use from split macro (pocket) (Issue #12331)
  bedrock/pocket/templates/pocket/add.html
  bedrock/pocket/templates/pocket/base-platform.html
  bedrock/pocket/templates/pocket/firefox/new-tab-learn-more.html
  bedrock/pocket/templates/pocket/get-inspired.html
  bedrock/pocket/templates/pocket/home.html
  bedrock/pocket/templates/pocket/pocket-and-firefox.html
  bedrock/pocket/templates/pocket/save-to-pocket.html
Labels: P3, Needs Review, Review: µ

#12495 Fix typo in Careers testimonials section
  bedrock/careers/templates/careers/includes/testimonials.html
Labels: Needs Review, Review: µ, Careers

#12510 Update firefox/browsers page title and desc (Fixes #12486)
  bedrock/firefox/templates/firefox/browsers/index.html
  l10n/en/firefox/browsers.ftl
Labels: P3, Needs Review, Review: µ

#12509 Updates to Firefox Focus page (Fixes #12499)
  bedrock/firefox/templates/firefox/browsers/mobile/focus.html
  l10n/en/firefox/browsers/mobile/focus.ftl
Labels: P2, Needs Review, Review: µ

#12511 Force client proxy server to use IPv4 (Issue #12508)
  webpack.config.js
Labels: Needs Review, Review: µ

#12512 Add Santa Locator page
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/santa-locator.html
  bedrock/mozorg/urls.py
  media/css/mozorg/santa-locator.scss
  media/img/mozorg/santa-locator/apple-touch-icon.png
  media/img/mozorg/santa-locator/favicon-196x196.png
  media/img/mozorg/santa-locator/favicon.png
  media/img/mozorg/santa-locator/page-image.png
  media/img/mozorg/santa-locator/panda-clause-sprite.png
  media/img/mozorg/santa-locator/panda-clause.png
  media/js/mozorg/santa-locator.js
  media/static-bundles.json
Labels: P1, Needs Review, Review: XS

#12518 Grammar and linting fixes for Santa Locator page
  bedrock/mozorg/templates/mozorg/santa-locator.html
  media/css/mozorg/santa-locator.scss
Labels: Needs Review, Review: µ

#12516 Add recommended extensions for VSCode (Fixes #12515)
  .gitignore
  .vscode/extensions.json
Labels: P3, Needs Review, Review: µ

#12514 Board member updates (Fixes #12498)
  bedrock/mozorg/templates/mozorg/about/leadership/boards.html
  media/css/mozorg/leadership.scss
Labels: P2, Needs Review, Review: µ

#12485 Simplify split() macro image handling (Fixes #12331)
  bedrock/base/templates/macros-protocol.html
  bedrock/careers/templates/careers/diversity.html
  bedrock/careers/templates/careers/includes/footer.html
  bedrock/firefox/templates/firefox/browsers/mobile/android.html
  bedrock/firefox/templates/firefox/privacy/book.html
  bedrock/mozorg/templates/mozorg/home/includes/mr2-promo-eu.html
  docs/coding.rst
Labels: P3, Needs Review, Review: XS
