Repository mozilla/bedrock, pull requests merged in 2022-08, with the labels that each got.

#11992 Create vanity redirect for transparency policy (Fixes #11991)
  bedrock/mozorg/redirects.py
  tests/redirects/map_globalconf.py
Labels: P3, Needs Review, Review: µ

#11995 Product blog bug fixes [#11634]
  bedrock/stories/templates/stories/articles/art-of-engagement.html
  media/css/stories/stories-article.scss
  media/css/stories/stories-landing.scss
  media/css/stories/stories-shared.scss
Labels: P1, Needs Review, Review: µ

#11993 Update supported iOS version on VPN pages (Fixes #11980)
  bedrock/products/templates/products/vpn/download.html
  bedrock/products/templates/products/vpn/landing.html
  l10n/en/products/vpn/landing.ftl
Labels: P2, Needs Review, Review: µ

#11996 content and style fixes post-launch
  bedrock/stories/templates/stories/articles/art-of-engagement.html
  media/css/stories/stories-landing.scss
Labels: Needs Review, Review: µ

#12001 Article tweaks and typo fixes
  bedrock/stories/templates/stories/articles/art-of-engagement.html
  bedrock/stories/templates/stories/articles/build-together.html
Labels: Needs Review, Review: µ

#12012 Fix Fixes for 'Licensed to Build Together' Page #12003
  bedrock/stories/templates/stories/articles/build-together.html
  bedrock/stories/templates/stories/articles/community-champion.html
Labels: Needs Review, Review: µ

#11994 Add responsive image helpers (Fixes #11833)
  bedrock/base/templates/macros-protocol.html
  bedrock/base/templates/macros.html
  bedrock/base/tests/test_macros.py
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/android.html
  bedrock/firefox/templates/firefox/browsers/mobile/focus.html
  bedrock/firefox/templates/firefox/browsers/mobile/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/ios.html
  bedrock/firefox/templates/firefox/more.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/privacy/index.html
  bedrock/mozorg/templates/mozorg/contact/includes/macros.html
  bedrock/mozorg/templates/mozorg/contribute.html
  bedrock/mozorg/templates/mozorg/home/includes/pocket-10-years-promo.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/products/templates/products/vpn/includes/macros.html
  docs/coding.rst
  media/img/firefox/browsers/hero-1100.jpg
  media/img/firefox/browsers/hero-1300.jpg
  media/img/firefox/browsers/hero-500.jpg
  media/img/firefox/browsers/hero-700.jpg
  media/img/firefox/browsers/hero-900.jpg
  media/img/firefox/browsers/hero-high-res.jpg
  media/img/firefox/browsers/hero.jpg
  media/img/firefox/browsers/mobile/about-hero-1100.png
  media/img/firefox/browsers/mobile/about-hero-500.png
  media/img/firefox/browsers/mobile/about-hero-800.png
  media/img/firefox/browsers/mobile/about-hero-high-res.png
  media/img/firefox/browsers/mobile/about-hero.png
  media/img/firefox/privacy/promise/privacy-hero-1100.png
  media/img/firefox/privacy/promise/privacy-hero-500.png
  media/img/firefox/privacy/promise/privacy-hero-700.png
  media/img/firefox/privacy/promise/privacy-hero-900.png
  media/img/firefox/privacy/promise/privacy-hero-high-res.png
  media/img/firefox/privacy/promise/privacy-hero.png
  media/img/home/2021/pocket-10-years-1000.jpg
  media/img/home/2021/pocket-10-years-1200.jpg
  media/img/home/2021/pocket-10-years-1400.jpg
  media/img/home/2021/pocket-10-years-700.jpg
  media/img/home/2021/pocket-10-years-850.jpg
  media/img/home/2021/pocket-10-years-high-res.jpg
  media/img/home/2021/pocket-10-years.jpg
Labels: Needs Review, Review: S

#12020 Update Protocol macro docs (Fixes #12019)
  bedrock/base/templates/macros-protocol.html
  docs/coding.rst
Labels: P3, Needs Review, Review: XS

#12002 Split Leadership onto multiple pages with navigation [fix #11878]
  bedrock/base/templates/includes/protocol/navigation/menus/whoweare.html
  bedrock/foundation/templates/foundation/moco.html
  bedrock/mozorg/templates/mozorg/about-base.html
  bedrock/mozorg/templates/mozorg/about/leadership.html
  bedrock/mozorg/templates/mozorg/about/leadership/base.html
  bedrock/mozorg/templates/mozorg/about/leadership/boards.html
  bedrock/mozorg/templates/mozorg/about/leadership/index.html
  bedrock/mozorg/templates/mozorg/about/leadership/mofo.html
  bedrock/mozorg/templates/mozorg/about/leadership/reps.html
  bedrock/mozorg/templates/mozorg/about/leadership/senior.html
  bedrock/mozorg/templates/mozorg/about/manifesto-details.html
  bedrock/mozorg/templates/mozorg/diversity/2021/racial-justice.html
  bedrock/mozorg/urls.py
  media/css/mozorg/leadership.scss
  media/img/mozorg/about/leadership/kristin-skogen-lund-high-res.jpg
  media/img/mozorg/about/leadership/kristin-skogen-lund.jpg
  media/js/mozorg/about-leadership.js
  media/static-bundles.json
  tests/functional/test_leadership.py
  tests/pages/leadership.py
Labels: P1, Review: XS

#12026 Fix broken Firefox mobile page (Fixes #12025)
  bedrock/firefox/templates/firefox/mobile/index.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/css/firefox/mobile/mobile.scss
  tests/functional/firefox/browsers/mobile/test_landing.py
  tests/pages/firefox/browsers/mobile_landing.py
Labels: P1, Needs Review, Review: XS

#11999 Stop making CJMS calls if FxA flow params are undefined (Fixes #11998)
  media/js/products/vpn/affiliate-attribution.es6.js
  media/js/products/vpn/affiliate-init.es6.js
  tests/unit/spec/products/vpn/affiliate-attribution.js
Labels: P2, Needs Review, Review: XS

#12036 Fix VPN coupon experiment redirect (Fixes #12013)
  bedrock/products/templates/products/vpn/landing.html
  docs/abtest.rst
  media/js/base/experiment-utils.es6.js
  media/js/products/vpn/coupon-promo-experiment.es6.js
  media/js/products/vpn/coupon-promo-experiment.js
  media/static-bundles.json
  tests/unit/spec/base/experiment-utils.js
Labels: Needs Review, Review: XS

#12038 Add Teixera to leadership page [fix #11878]
  bedrock/mozorg/templates/mozorg/about/leadership/index.html
  bedrock/mozorg/templates/mozorg/about/leadership/senior.html
  media/img/mozorg/about/leadership/steve-teixeira-high-res.jpg
  media/img/mozorg/about/leadership/steve-teixeira.jpg
Labels: Needs Review, Review: µ

#12039 Leadership page, delete extra period [no bug]
  bedrock/mozorg/templates/mozorg/about/leadership/index.html
Labels: Review: µ

#12037 2022-08-15 Dependency bumps
  Makefile
  requirements/dev.txt
  requirements/docs.in
  requirements/docs.txt
  requirements/prod.in
  requirements/prod.txt
Labels: Review: XS

#12040 Add WNP for Firefox 104 for ES, IT, PL [#12015]
  bedrock/firefox/templates/firefox/whatsnew/includes/fx104/tcp.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-default.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  l10n/configs/pontoon.toml
  l10n/en/firefox/whatsnew/whatsnew-104-default.ftl
  media/css/firefox/whatsnew/whatsnew-104-default.scss
  media/img/firefox/whatsnew/whatsnew104/orange-check.svg
  media/js/firefox/whatsnew/whatsnew-104-default.js
  media/static-bundles.json
Labels: Needs Review, Review: XS

#12053 Leadership: link to Teixeira photos, update headshot, remove steering from Bryant and Koidin
  bedrock/mozorg/templates/mozorg/about/leadership/index.html
  bedrock/mozorg/templates/mozorg/about/leadership/senior.html
  media/img/mozorg/about/leadership/steve-teixeira-high-res.jpg
  media/img/mozorg/about/leadership/steve-teixeira.jpg
Labels: Needs Review, Review: µ

#12045 Add WNP for Firefox 104 in EN, FR, DE [fix #12015]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-de-coupon.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-en-coupon.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-fr-coupon.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx104-vpn-fr.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-104-vpn.scss
  media/img/firefox/whatsnew/whatsnew104/vpn.svg
  media/js/firefox/whatsnew/whatsnew-104-vpn-coupon.js
  media/static-bundles.json
Labels: Needs Review, Review: XS

#12060 Update transive dependencies in package-lock.json
  package-lock.json
Labels: P3, Needs Review, Review: XS

#12011 Newsletter recovery page should post directly to basket (Fixes #11963)
  .eslintrc.js
  bedrock/newsletter/templates/newsletter/opt-out-confirmation.html
  bedrock/newsletter/templates/newsletter/recovery.html
  bedrock/newsletter/tests/test_views.py
  bedrock/newsletter/views.py
  media/css/newsletter/newsletter-opt-out-confirmation.scss
  media/css/newsletter/newsletter-recovery.scss
  media/js/newsletter/form-utils.es6.js
  media/js/newsletter/recovery-init.es6.js
  media/js/newsletter/recovery.es6.js
  media/static-bundles.json
  tests/functional/newsletter/test_newsletter_recovery.py
  tests/pages/newsletter/recovery.py
  tests/unit/karma.conf.js
  tests/unit/spec/base/fxa-form.js
  tests/unit/spec/base/fxa-link.js
  tests/unit/spec/base/mozilla-banner.js
  tests/unit/spec/base/mozilla-pixel.js
  tests/unit/spec/base/send-to-device.js
  tests/unit/spec/base/site.js
  tests/unit/spec/base/stub-attribution.js
  tests/unit/spec/newsletter/form-utils.js
  tests/unit/spec/newsletter/recovery.js
Labels: P3, Needs Review, Review: XS

#12064 Update get-ios Adjust link
  bedrock/firefox/templates/firefox/browsers/mobile/get-ios.html
Labels: Needs Review, Review: µ

#12065 Style public wifi section
  bedrock/firefox/templates/firefox/family/includes/modules/public-wifi.html
  media/css/firefox/family/components/modules/_public-wifi.scss
Labels: Needs Review, Review: XS

#12058 Make data privacy prefs page work across '.mozilla.org' domains (Fixes #12056)
  bedrock/privacy/templates/privacy/data-preferences.html
  bedrock/privacy/urls.py
  docs/analytics.rst
  l10n/en/brands.ftl
  l10n/en/privacy/data-preferences.ftl
  media/js/privacy/data-preferences-cookie.es6.js
  media/js/privacy/data-preferences-init.es6.js
  media/static-bundles.json
  tests/unit/karma.conf.js
  tests/unit/spec/privacy/data-preferences-cookie.js
Labels: Needs Review, Review: XS

#12076 Also clear preference cookies that specify www.mozilla.org sub domain (issue #12056)
  media/js/privacy/data-preferences-cookie.es6.js
  tests/unit/spec/privacy/data-preferences-cookie.js
Labels: Needs Review, Review: µ

#12068 Responsive layout for Hero section
  bedrock/firefox/templates/firefox/family/includes/hero.html
  media/css/firefox/family/components/_hero.scss
Labels: Needs Review

#12083 Privacy fx family
  bedrock/firefox/templates/firefox/family/includes/modules/privacy.html
  media/css/firefox/family/components/modules/_privacy.scss
Labels: Needs Review

#12084 Fix subnav, add dividers
  bedrock/firefox/templates/firefox/family/index.html
  media/css/firefox/family/_utils.scss
  media/css/firefox/family/components/_subnav.scss
  media/css/firefox/family/components/_typography.scss
  media/css/firefox/family/components/modules/_bullying.scss
  media/css/firefox/family/components/modules/_passwords.scss
  media/css/firefox/family/components/modules/_privacy.scss
  media/css/firefox/family/styles.scss
  media/js/firefox/family/subnav.js
  media/static-bundles.json
Labels: Needs Review, Review: S
