Repository mozilla/bedrock, pull requests merged in 2022-07, with the labels that each got.

#11848 Fix up URL name for Set As Default page, to stop retention page from 500ing
  bedrock/firefox/templates/firefox/retention/thank-you.html
Labels: Review: µ

#11847 Remove unused functions from Mozilla.Client lib (Fixes #11845)
  media/js/base/mozilla-client.js
  tests/unit/spec/base/mozilla-client.js
Labels: P3, Needs Review, Review: XS

#11853 Remove obsolete firefox_new_download JS bundle (Fixes #11852)
  bedrock/firefox/templates/firefox/new/basic/base_download.html
  media/js/firefox/new/basic/download.js
  media/static-bundles.json
Labels: P3, Needs Review, Review: XS

#11844 Remove Glean delay ping code (#11770)
  bedrock/base/templates/includes/protocol/navigation/nav-cta.html
  bedrock/firefox/templates/firefox/new/basic/base_download.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/products/templates/products/vpn/includes/pricing-variable.html
  media/js/firefox/new/desktop/join-modal.js
  media/js/glean/elements.es6.js
Labels: P3, Needs Review, Review: µ

#11828 Add VPN coupon promo (fixes #11826)
  bedrock/base/templates/includes/banners/vpn-coupon-variations/vpn-coupon-promo-1.html
  bedrock/base/templates/includes/banners/vpn-coupon-variations/vpn-coupon-promo-2.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/tests/test_views.py
  bedrock/products/views.py
  media/css/base/banners/vpn-coupon-promo.scss
  media/img/banners/vpn/white-plane.svg
  media/js/base/banners/mozilla-banner.js
  media/js/base/banners/vpn-coupon-promo-init.js
  media/js/products/vpn/coupon-promo-experiment.js
  media/static-bundles.json
Labels: Do Not Merge :warning:, Needs Review, Review: S

#11888 Fix typos in /de/ VPN promo banner (Issue #11826)
  bedrock/base/templates/includes/banners/vpn-coupon-variations/vpn-coupon-promo-1.html
Labels: Needs Review, Review: µ

#11894 Leadership, add Bryant and Shah
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/david-bryant-high-res.jpg
  media/img/mozorg/about/leadership/david-bryant.jpg
  media/img/mozorg/about/leadership/mika-shah-high-res.jpg
  media/img/mozorg/about/leadership/mika-shah.jpg
Labels: Needs Review, Review: µ

#11834 Use Client Hints to get high entropy platform info (Fixes #8440)
  bedrock/base/templates/base-protocol.html
  media/css/protocol/components/_download-button.scss
  media/js/base/site.js
  media/js/firefox/new/common/thanks.js
  tests/unit/spec/base/site.js
  tests/unit/spec/firefox/new/common/thanks.js
Labels: P1, Review: S

#11903 Bump front-end linters to latest versions
  .pre-commit-config.yaml
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#11904 Bump Jasmine, Karma and Sinon to latest versions
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#11908 Exclude non-VPN countries from banner experiment [fix #11907]
  bedrock/products/templates/products/vpn/landing.html
Labels: Needs Review, Review: µ

#11885 Bump @mozmeao/trafficcop to v2.0.1 (Fixes #11884)
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#11916 Update Webpack dependencies
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: XS

#11919 Use country code for donation links/form instead of locale (Fixes #10741)
  bedrock/base/templates/includes/banners/fundraiser.html
  bedrock/base/templates/includes/protocol/footer/footer.html
  bedrock/firefox/templates/firefox/campaign/unfck/index.html
  bedrock/foundation/templates/foundation/annualreport/2009/broadening-our-scope.html
  bedrock/foundation/templates/foundation/openwebfund/more.html
  bedrock/mozorg/templates/mozorg/contact/contact-landing.html
  bedrock/mozorg/templates/mozorg/contribute.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/mozorg/tests/test_views.py
  bedrock/mozorg/views.py
  bedrock/settings/base.py
Labels: P3, Needs Review, Review: XS

#11902 Bump @sentry/browser to v7.6.0
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#11832 Update Contentful docs (fixes #11815)
  docs/contentful.rst
Labels: Review: XS

#11825 Update contentful split api and css
  bedrock/contentful/api.py
  bedrock/contentful/templates/includes/contentful/all.html
  media/css/contentful/firefox/c-split.scss
  media/css/contentful/mozilla/c-split.scss
Labels: Review: µ

#11805 Notify users about pinning Firefox in Windows (Fixes #11759)
  bedrock/firefox/templates/firefox/new/basic/thanks.html
  bedrock/firefox/templates/firefox/new/desktop/thanks.html
  l10n/en/firefox/new/desktop.ftl
  l10n/en/firefox/new/download.ftl
  media/css/firefox/new/basic/thanks.scss
  media/css/firefox/new/desktop/thanks.scss
Labels: P1, Needs Review, Review: XS

#11954 L10n fix for about/this-site.ftl
  l10n/en/mozorg/about/this-site.ftl
Labels: P3, Needs Review, Review: µ

#11951 Decommission Firefox retention thank you page (Fixes #11891)
  bedrock/firefox/templates/firefox/retention/thank-you.html
  bedrock/firefox/urls.py
  bedrock/mozorg/redirects.py
  bedrock/settings/base.py
  l10n/configs/pontoon.toml
  l10n/en/firefox/retention/thank-you.ftl
  media/css/firefox/retention/thank-you.scss
  media/fonts/fx-lifestyle/antonio-bold-webfont.woff
  media/fonts/fx-lifestyle/antonio-bold-webfont.woff2
  media/fonts/fx-lifestyle/antonio-regular-webfont.woff
  media/fonts/fx-lifestyle/antonio-regular-webfont.woff2
  media/js/firefox/retention/confetti.js
  media/static-bundles.json
  tests/redirects/map_globalconf.py
Labels: P3, Needs Review, Review: XS

#11955 Updated CTA link on Rally WNP103 [#11940]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx103-en-rally.html
Labels: Needs Review, Review: µ

#11959 Add Jeff Garver to leadership page [fix #11958]
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/jeff-garver-high-res.jpg
  media/img/mozorg/about/leadership/jeff-garver.jpg
Labels: Needs Review, Review: µ

#11970 Update meta description on WNP 103 Rally page [#11940]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx103-en-rally.html
Labels: Needs Review, Review: µ

#11976 Leadership updates: add Karakash, Lang, Madeiros
  bedrock/mozorg/templates/mozorg/about/leadership.html
  media/img/mozorg/about/leadership/christina-lang.jpg
  media/img/mozorg/about/leadership/mike-madeiros-high-res.jpg
  media/img/mozorg/about/leadership/mike-madeiros.jpg
  media/img/mozorg/about/leadership/robin-karakash-high-res.jpg
  media/img/mozorg/about/leadership/robin-karakash.jpg
Labels: Needs Review, Review: XS

#11978 Leadership: add Madeiros bio
  bedrock/mozorg/templates/mozorg/about/leadership.html
Labels: Needs Review, Review: µ
