Repository mozilla/bedrock, pull requests merged in 2023-08, with the labels that each got.

#13473 Update Brave browser comparison page for screenshot feature (Fixes #13471)
  bedrock/firefox/templates/firefox/browsers/compare/brave.html
Labels: P3, Needs Review, Review: µ

#13483 Fix typo in WNP 116 for DE
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx116-de.html
Labels: P2, Needs Review, Review: µ

#13485 Fix disappearing reader mode icon on WNP (Fixes #13484)
  media/js/firefox/whatsnew/whatsnew-116-na.js
Labels: P2, Needs Review, Review: µ

#13479 Update euro currency formatting for English locales (Issue #13476)
  bedrock/products/tests/test_helper_misc.py
  bedrock/settings/base.py
Labels: P2, Needs Review, Review: µ

#13482 Update glean server endpoint (Fixes #13481)
  media/js/glean/init.es6.js
Labels: P3, Needs Review, Review: µ

#13472 Remove high_res_img() helper (Fixes #13227)
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/browsers/chromebook.html
  bedrock/firefox/templates/firefox/browsers/compare/brave.html
  bedrock/firefox/templates/firefox/browsers/compare/chrome.html
  bedrock/firefox/templates/firefox/browsers/compare/edge.html
  bedrock/firefox/templates/firefox/browsers/compare/ie.html
  bedrock/firefox/templates/firefox/browsers/compare/opera.html
  bedrock/firefox/templates/firefox/browsers/compare/safari.html
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/index.html
  bedrock/firefox/templates/firefox/developer/includes/highlights.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/features/adblocker.html
  bedrock/firefox/templates/firefox/flashback/index.html
  bedrock/firefox/templates/firefox/more/misinformation.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/products/index.html
  bedrock/foundation/templates/foundation/annualreport/2011.html
  bedrock/foundation/templates/foundation/trademarks/list.html
  bedrock/legal/templates/legal/index.html
  bedrock/mozorg/templates/mozorg/about/index.html
  bedrock/mozorg/templates/mozorg/about/leadership/boards.html
  bedrock/mozorg/templates/mozorg/about/leadership/index.html
  bedrock/mozorg/templates/mozorg/about/leadership/mofo.html
  bedrock/mozorg/templates/mozorg/about/leadership/reps.html
  bedrock/mozorg/templates/mozorg/about/leadership/senior.html
  bedrock/mozorg/templates/mozorg/about/manifesto.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/build-security.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/engage-users.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/index.html
  bedrock/mozorg/templates/mozorg/about/policy/lean-data/stay-lean.html
  bedrock/mozorg/templates/mozorg/contact/spaces/beijing.html
  bedrock/mozorg/templates/mozorg/contact/spaces/berlin.html
  bedrock/mozorg/templates/mozorg/contact/spaces/paris.html
  bedrock/mozorg/templates/mozorg/contact/spaces/san-francisco.html
  bedrock/mozorg/templates/mozorg/contact/spaces/toronto.html
  bedrock/mozorg/templates/mozorg/contribute.html
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/templates/mozorg/moss/base.html
  bedrock/mozorg/templates/mozorg/moss/includes/alittlebitmore.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/pocket/templates/pocket/jobs.html
  bedrock/products/templates/products/vpn/includes/macros.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templates/products/vpn/platforms/android.html
  bedrock/products/templates/products/vpn/platforms/desktop.html
  bedrock/products/templates/products/vpn/platforms/ios.html
  bedrock/products/templates/products/vpn/platforms/linux.html
  bedrock/products/templates/products/vpn/platforms/mac.html
  bedrock/products/templates/products/vpn/platforms/mobile.html
  bedrock/products/templates/products/vpn/platforms/platform-base.html
  bedrock/products/templates/products/vpn/platforms/windows.html
  bedrock/products/templates/products/vpn/pricing-refresh.html
  bedrock/products/templates/products/vpn/pricing.html
  docs/coding.rst
Labels: P3, Needs Review, Review: S

#13488 Fix typo in alt-text for Sustainability page
  bedrock/mozorg/templates/mozorg/sustainability/index.html
  media/img/mozorg/sustainability/sustainability-venn-diagram.png
Labels: Needs Review, Review: µ

#13490 Fix meta titles and add meta description for sustainability pages
  bedrock/mozorg/templates/mozorg/sustainability/carbon-neutral.html
  bedrock/mozorg/templates/mozorg/sustainability/emissions-data.html
  bedrock/mozorg/templates/mozorg/sustainability/index.html
Labels: Needs Review, Review: µ

#13146 Update protocol to v18.0.0
  bedrock/products/templates/products/relay/includes/waitlist-base.html
  media/css/firefox/all/all-unified.scss
  media/css/firefox/browsers/best-browser.scss
  media/css/firefox/browsers/windows-64-bit.scss
  media/css/firefox/challenge-the-default/index.scss
  media/css/firefox/family/components/_dad-jokes-banner.scss
  media/css/firefox/features/safebrowser.scss
  media/css/firefox/firstrun/nightly.scss
  media/css/firefox/welcome10.scss
  media/css/firefox/welcome11.scss
  media/css/firefox/welcome12.scss
  media/css/firefox/welcome13.scss
  media/css/firefox/whatsnew/whatsnew-115-eu-ctd.scss
  media/css/firefox/whatsnew/whatsnew-115-eu-mobile.scss
  media/css/firefox/whatsnew/whatsnew-115-eu-vpn.scss
  media/css/firefox/whatsnew/whatsnew-account.scss
  media/css/firefox/whatsnew/whatsnew-nightly.scss
  media/css/firefox/whatsnew/whatsnew.scss
  media/css/foundation/annual-report-2019-2020.scss
  media/css/foundation/annual-report-2021.scss
  media/css/legal/legal.scss
  media/css/mozorg/about-transparency.scss
  media/css/mozorg/contribute.scss
  media/css/mozorg/diversity/diversity.scss
  media/css/mozorg/home/home-mr2-promo.scss
  media/css/mozorg/home/home.scss
  media/css/newsletter/newsletter-recovery.scss
  media/css/pocket/components/updates-signup.scss
  media/css/products/relay/waitlist.scss
  media/css/products/vpn/components/pricing-basic.scss
  media/css/protocol/basic-article.scss
  media/css/protocol/protocol-firefox.scss
  media/css/protocol/protocol-mozilla.scss
  package-lock.json
  package.json
Labels: Enhancement, Frontend

#13491 Add WNP 117 for EU (Reader mode) (Fixes #13480)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx117-de-reader-view.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx117-fr-reader-view.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx117-uk-reader-view.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-117-eu-reader-view.scss
  media/img/firefox/whatsnew/whatsnew117-eu/reader-icon.svg
  media/js/base/uitour-lib.js
  media/js/firefox/whatsnew/whatsnew-117-eu-reader-view.js
  media/js/firefox/whatsnew/whatsnew-117-experiment-eu-reader-view.es6.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_117.py
  tests/pages/firefox/whatsnew/whatsnew_117.py
Labels: P1, Needs Review, Review: XS

#13523 Update NA WNP116 CTA [#13421]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx116-na.html
  media/js/firefox/whatsnew/whatsnew-116-na.js
Labels: Needs Review, Review: µ

#13494 Update Glean.js to v2.0.0 (Fixes #13493)
  package-lock.json
  package.json
  requirements/dev.txt
  requirements/prod.in
  requirements/prod.txt
Labels: P3, Needs Review, Review: µ

#13531 update laser-cat static images with animated pngs
  media/img/firefox/challenge-the-default/laser-cat-desktop.png
  media/img/firefox/challenge-the-default/laser-cat-mobile.png
Labels: Needs Review, Review: µ

#13526 Bump Node to v18 (Fixes #13525)
  .github/workflows/pull_request_tests.yml
  Dockerfile
Labels: P3, Needs Review, Review: µ

#13533 Add Monitor waitlist subscription page [fix #13522]
  bedrock/newsletter/templates/newsletter/monitor-waitlist.html
  bedrock/newsletter/urls.py
  media/css/newsletter/newsletter-monitor-waitlist.scss
  media/static-bundles.json
  tests/functional/newsletter/test_monitor_waitlist.py
  tests/pages/newsletter/monitor_waitlist.py
  tests/unit/spec/newsletter/data.js
Labels: P1, Needs Review, Review: XS

#13447 Homepage redesign 2023
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/templates/mozorg/home/home-new.html
  bedrock/mozorg/templates/mozorg/home/home-old.html
  bedrock/mozorg/templates/mozorg/home/includes/featured-vpn.html
  bedrock/mozorg/templates/mozorg/home/includes/firefox-mr106-promo.html
  bedrock/mozorg/templates/mozorg/home/includes/macros.html
  bedrock/mozorg/templates/mozorg/home/includes/mr2-promo-eu.html
  bedrock/mozorg/templates/mozorg/home/includes/mr2-promo.html
  bedrock/mozorg/tests/test_views.py
  bedrock/mozorg/urls.py
  bedrock/mozorg/views.py
  l10n/configs/pontoon.toml
  l10n/en/mozorg/home-mr2-promo.ftl
  l10n/en/mozorg/home-new.ftl
  media/css/mozorg/home/home-contentful.scss
  media/css/mozorg/home/home-eu.scss
  media/css/mozorg/home/home-firefox-mr106-promo.scss
  media/css/mozorg/home/home-mr2-promo.scss
  media/css/mozorg/home/home-new.scss
  media/css/mozorg/home/home-old.scss
  media/css/mozorg/home/includes/_home-base.scss
  media/css/mozorg/home/includes/featured-vpn.scss
  media/img/home/2018/bg-primary.svg
  media/img/home/2018/bg-secondary.svg
  media/img/home/2018/browser-high-res.png
  media/img/home/2018/browser.png
  media/img/home/2018/home-high-res.jpg
  media/img/home/2018/home.jpg
  media/img/home/2018/shield.svg
  media/img/home/2021/mr2-watercolor-de-high-res.png
  media/img/home/2021/mr2-watercolor-de.png
  media/img/home/2021/mr2-watercolor-fr-high-res.png
  media/img/home/2021/mr2-watercolor-fr.png
  media/img/home/2021/mr2-watercolor-high-res.png
  media/img/home/2021/mr2-watercolor.png
  media/img/home/2022/mr-hero-custom.svg
  media/img/home/2022/mr-hero-sync.svg
  media/img/home/2023/contribute-split-high-res.png
  media/img/home/2023/contribute-split.png
  media/img/home/2023/mofo-split-high-res.jpg
  media/img/home/2023/mofo-split.png
  media/img/home/2023/mozilla-dino.svg
  media/img/home/2023/vpn-on.svg
  media/js/mozorg/home/feature-vpn-experiment.es6.js
  media/static-bundles.json
  tests/functional/test_home.py
  tests/pages/home.py
Labels: Moz.org, Needs Review, Review: M, Frontend

#13528 Load Stripe JS on VPN lead pages (Fixes #13527)
  bedrock/base/templates/base-protocol.html
  bedrock/products/templates/products/vpn/base.html
  bedrock/products/templates/products/vpn/resource-center/base-article.html
  bedrock/settings/__init__.py
Labels: P2, Needs Review, Review: XS

#13551 Update sys requirements for Mozilla VPN on Linux (Fixes #13442)
  bedrock/products/templates/products/vpn/download.html
  bedrock/products/templates/products/vpn/landing.html
  l10n/en/products/vpn/landing.ftl
Labels: P3, Needs Review, Review: µ

#13573 Bump Glean JS to v2.0.1
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#13557 Update leadership page layout
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/about/leadership/base.html
  bedrock/mozorg/templates/mozorg/about/leadership/boards.html
  bedrock/mozorg/templates/mozorg/about/leadership/includes/boards.html
  bedrock/mozorg/templates/mozorg/about/leadership/includes/executive.html
  bedrock/mozorg/templates/mozorg/about/leadership/includes/mofo.html
  bedrock/mozorg/templates/mozorg/about/leadership/includes/reps.html
  bedrock/mozorg/templates/mozorg/about/leadership/includes/senior.html
  bedrock/mozorg/templates/mozorg/about/leadership/index.html
  bedrock/mozorg/templates/mozorg/about/leadership/mofo.html
  bedrock/mozorg/templates/mozorg/about/leadership/reps.html
  bedrock/mozorg/urls.py
  media/css/mozorg/leadership.scss
Labels: Review: S

#13582 Distinguish 404 in Glean page metrics (Fixes #13581)
  bedrock/base/templates/404.html
  glean/metrics.yaml
  media/js/glean/page.es6.js
  media/js/glean/utils.es6.js
  tests/unit/spec/glean/page.js
  tests/unit/spec/glean/utils.js
Labels: P3, Review: XS

#13584 Filter newsletter token from path name in Glean page pings (Fixes #13583)
  media/js/glean/utils.es6.js
  tests/unit/spec/glean/utils.js
Labels: P3, Review: XS

#13532 Update Glean ping helpers
  docs/attribution/0001-analytics.rst
  glean/metrics.yaml
  media/js/glean/elements.es6.js
  media/js/glean/init.es6.js
  media/js/glean/page.es6.js
  tests/unit/spec/glean/elements.js
  tests/unit/spec/glean/page.js
Labels: P3, Review: XS

#13578 Update title fonts in Firefox pages (fixes #13577)
  media/css/firefox/browsers/best-browser.scss
  media/css/firefox/features/safebrowser.scss
  media/css/firefox/releasenotes.scss
Labels: Review: XS

#13587 Adding some l10n comments to home page strings
  l10n/en/mozorg/home-new.ftl
Labels: Needs Review, Review: µ

#13590 Fix 500 error on pages due to leadership page redsign (Fixes #13589)
  bedrock/foundation/templates/foundation/moco.html
  bedrock/mozorg/templates/mozorg/diversity/2021/racial-justice.html
Labels: P1, Needs Review, Review: µ

#13591 Remove brand names from vpn download string (Issue #13551)
  l10n/en/products/vpn/landing.ftl
Labels: Needs Review, Review: µ

#13595 Add Suba Vasudevan to leadership (Fixes #13588)
  bedrock/mozorg/templates/mozorg/about/leadership/includes/senior.html
  media/img/mozorg/about/leadership/suba-vasudevan-high-res.png
  media/img/mozorg/about/leadership/suba-vasudevan.png
Labels: Needs Review, Review: XS

#13597 Set VPN refresh to 100% of English [#13558]
  bedrock/products/templates/products/vpn/landing-refresh.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/tests/test_views.py
  bedrock/products/views.py
  media/js/products/vpn/landing-refresh-experiment.es6.js
  media/static-bundles.json
  tests/functional/products/vpn/test_landing_refresh.py
Labels: P1, Needs Review, Review: XS

#13596 Fix protocol issue in pocket mode
  media/css/pocket/style.scss
Labels: Needs Review

#13605 Add WNP 117 for VPN and Relay [fix #13496, fix #13495]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx117-na-relay.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx117-vpn.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  l10n/en/firefox/whatsnew/whatsnew.ftl
  media/css/firefox/whatsnew/whatsnew-117-relay.scss
  media/css/firefox/whatsnew/whatsnew-117-vpn.scss
  media/img/firefox/whatsnew/whatsnew117-na/check.svg
  media/img/firefox/whatsnew/whatsnew117-na/relay-inverse.svg
  media/js/firefox/whatsnew/whatsnew-117-experiment-na-vpn-relay.es6.js
  media/js/firefox/whatsnew/whatsnew-117-na-relay.es6.js
  media/static-bundles.json
Labels: P1, Review: XS

#13580 VPN wave VI expansion post-launch cleanup (Fixes #13552)
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  bedrock/products/templates/products/vpn/includes/macros.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templates/products/vpn/pricing.html
  bedrock/products/views.py
  bedrock/settings/base.py
Labels: P3, Needs Review, Review: XS

#13576 Make VPN affiliate code re-usable for other products (fix #13575)
  bedrock/base/templates/includes/affiliate-banner.html
  bedrock/products/templates/products/vpn/includes/cookie-notification.html
  bedrock/products/templates/products/vpn/landing-refresh.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templates/products/vpn/pricing-refresh.html
  bedrock/products/templates/products/vpn/pricing.html
  bedrock/settings/base.py
  docs/attribution/0005-affiliate-marketing.rst
  l10n/en/affiliate.ftl
  l10n/en/products/relay/waitlist.ftl
  l10n/en/products/vpn/shared.ftl
  media/css/products/affiliate.scss
  media/css/products/shared/affiliate.scss
  media/js/products/shared/affiliate-attribution.es6.js
  media/js/products/shared/affiliate-init.es6.js
  media/static-bundles.json
  tests/unit/karma.conf.js
  tests/unit/spec/products/shared/affiliate-attribution.js
Labels: P1, Review: XS

#13609 WNP117 Relay, copy updates [#13495]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx117-na-relay.html
Labels: Needs Review, Review: µ

#13610 Misc fixes for feature pages [#11144]
  bedrock/firefox/templates/firefox/more.html
  bedrock/firefox/urls.py
  l10n/en/firefox/more.ftl
  media/img/firefox/more/private.png
Labels: Bug :bug:, Needs Review, Review: XS

#13616 Add VPN refresh pricing experiment [fix #13558]
  bedrock/products/templates/products/vpn/landing-refresh.html
  bedrock/products/views.py
  media/js/products/vpn/experiment-refresh-pricing-layout.es6.js
  media/static-bundles.json
Labels: Review: XS

#13534 Use currency formatting for VPN display prices (Fixes #13476)
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  bedrock/settings/base.py
Labels: P2, Needs Review, Review: S
