Repository mozilla/bedrock, pull requests merged in 2023-07, with the labels that each got.

#13343 Revert to using old logo
  bedrock/firefox/templates/firefox/challenge-the-default/landing.html
  media/css/firefox/challenge-the-default/_hero.scss
  media/js/firefox/challenge-the-default/animate-pop-in.es6.js
Labels: P1, Needs Review, Review: µ

#13334 Direct Beta/Dev/Nightly downloads on old OS versions to ESR (Issue #13317)
  bedrock/firefox/templates/firefox/includes/download-button.html
  l10n/en/download_button.ftl
  media/css/firefox/developer/includes/intro.scss
  media/css/protocol/components/_download-button-ie.scss
  media/css/protocol/components/_download-button.scss
  media/js/base/site.js
  tests/unit/spec/base/site.js
Labels: P1, Needs Review, Review: XS

#13302 [July 5th] Add new strings to newsletter-strings.json (Fixes #13250)
  bedrock/newsletter/templates/newsletter/includes/newsletter-strings.json
Labels: Do Not Merge :warning:, Review: µ

#13354 Update Client Hints Windows version detection (Issue #13317)
  media/js/base/site.js
  tests/unit/spec/base/site.js
Labels: P1, Needs Review, Review: XS

#13377 Update welcome/15 referral_id if no variation is set (Issue #13303)
  bedrock/firefox/templates/firefox/welcome/page15/base.html
Labels: P1, Needs Review, Review: µ

#13386 Update WNP 115 view logic to show English to target countries [#13215]
  bedrock/firefox/views.py
Labels: P1, Needs Review, Review: XS

#13381 Leadership updates: Add Keating, remove Singh [fix #13379]
  bedrock/mozorg/templates/mozorg/about/leadership/boards.html
  media/img/mozorg/about/leadership/amy-keating-high-res.jpg
  media/img/mozorg/about/leadership/amy-keating.jpg
Labels: Needs Review, Review: µ

#13356 Send dataLayer event for GA4 for newsletter subscriptions
  media/js/newsletter/newsletter.es6.js
Labels: P1, Needs Review, Review: XS

#13385 Remove doubleclick pixel from /thanks/ (Fixes #13083)
  bedrock/firefox/templates/firefox/new/basic/thanks.html
  bedrock/firefox/templates/firefox/new/basic/thanks_direct.html
  bedrock/firefox/templates/firefox/new/desktop/thanks.html
  bedrock/firefox/templates/firefox/new/desktop/thanks_direct.html
  bedrock/settings/__init__.py
  media/js/base/mozilla-pixel-init.js
  media/js/base/mozilla-pixel.js
  media/js/firefox/new/common/thanks-direct.js
  media/js/firefox/new/common/thanks-init.js
  media/static-bundles.json
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-pixel.js
Labels: P3, Needs Review, Review: XS

#13351 Add documentation to add GA4 begin_checkout event
  docs/attribution/0001-analytics.rst
  docs/attribution/0006-pocket-analytics.rst
  docs/vpn-subscriptions.rst
Labels: P2, Needs Review, Review: XS

#13394 Remove names from senior leadership
  bedrock/mozorg/templates/mozorg/about/leadership/senior.html
  media/img/mozorg/about/leadership/mardi-douglass-high-res.jpg
  media/img/mozorg/about/leadership/mardi-douglass.jpg
  media/img/mozorg/about/leadership/matt-koidin-high-res.jpg
  media/img/mozorg/about/leadership/matt-koidin.jpg
Labels: Needs Review, Review: µ

#13391 Remove Firefox Pioneer from privacy FAQ page (Fixes #13387)
  bedrock/privacy/templates/privacy/faq.html
  l10n/en/privacy/faq.ftl
Labels: P3, Needs Review, Review: µ

#13393 CTD bug fixes
  bedrock/firefox/templates/firefox/challenge-the-default/landing.html
  media/css/firefox/challenge-the-default/_compare-table.scss
  media/css/firefox/challenge-the-default/_hero.scss
  media/css/firefox/challenge-the-default/index.scss
  media/img/firefox/challenge-the-default/ctd-logo.svg
  media/img/firefox/challenge-the-default/ctd-sprite-100.png
  media/img/firefox/challenge-the-default/logo-firefox.svg
  media/js/firefox/challenge-the-default/challenge-the-default.es6.js
Labels: Review: XS

#13397 Remove old home page promos (Fixes #13305)
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  bedrock/mozorg/templates/mozorg/home/includes/firefox-family-promo.html
  bedrock/mozorg/templates/mozorg/home/includes/ijustine-promo-image.html
  bedrock/mozorg/templates/mozorg/home/includes/ijustine-promo.html
  bedrock/mozorg/templates/mozorg/home/includes/vpn-beautiful.html
  media/css/mozorg/home/home-firefox-family-promo.scss
  media/css/mozorg/home/ijustine-promo.scss
  media/css/mozorg/home/vpn-beautiful.scss
  media/img/home/2023/ijustine-promo/ijustine-promo-1000.jpg
  media/img/home/2023/ijustine-promo/ijustine-promo-1500.jpg
  media/img/home/2023/ijustine-promo/ijustine-promo-500.jpg
  media/img/home/2023/ijustine-promo/ijustine-promo-700.jpg
  media/img/home/2023/vpn-beautiful-1100.jpg
  media/img/home/2023/vpn-beautiful-1300.jpg
  media/img/home/2023/vpn-beautiful-1500.jpg
  media/img/home/2023/vpn-beautiful-300.jpg
  media/img/home/2023/vpn-beautiful-500.jpg
  media/img/home/2023/vpn-beautiful-700.jpg
  media/img/home/2023/vpn-beautiful-900.jpg
  media/img/home/firefox-family-promo.svg
  media/js/mozorg/home/includes/ijustine-modal-video.js
  media/static-bundles.json
Labels: P3, Needs Review, Review: µ

#13389 Update VPN iOS app store URL (Fixes #13384)
  bedrock/products/tests/test_views.py
  bedrock/products/views.py
Labels: P2, Needs Review, Review: µ

#13414 Change name of productDownload event handler
  media/js/base/datalayer-productdownload.es6.js
  media/js/firefox/all/all-downloads-unified-init.es6.js
  tests/unit/spec/base/datalayer-productdownload.js
Labels: P1, Needs Review, Review: µ

#13420 Update browser support documentation for Firefox (Fixes #13378)
  docs/browser-support.rst
  docs/pipeline.rst
Labels: P3, Needs Review, Review: XS

#13396 Bump webpack and related dependencies to latest versions
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#13390 Direct Win 8.1 / macOs 10.14 users to ESR for FF release channel (Fixes #13317)
  bedrock/firefox/templates/firefox/browsers/windows-64-bit.html
  bedrock/firefox/templates/firefox/features/safebrowser.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/includes/download-button-thanks.html
  bedrock/firefox/templates/firefox/includes/download-button.html
  bedrock/firefox/templates/firefox/includes/download-unsupported.html
  bedrock/firefox/templates/firefox/new/basic/base_download.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  l10n/en/download_button.ftl
  media/css/firefox/browsers-products.scss
  media/css/firefox/challenge-the-default/_hero.scss
  media/css/firefox/developer/includes/intro.scss
  media/css/firefox/home/ie9.scss
  media/css/firefox/home/master.scss
  media/css/firefox/new/basic/ie.scss
  media/css/firefox/new/common/thanks-messaging.scss
  media/css/firefox/new/desktop/download.scss
  media/css/firefox/new/desktop/ie8.scss
  media/css/firefox/new/desktop/ie9.scss
  media/css/firefox/releasenotes.scss
  media/css/mozorg/home/home-eu.scss
  media/css/mozorg/home/includes/_home-base.scss
  media/css/protocol/components/_download-button-ie.scss
  media/css/protocol/components/_download-button.scss
  media/css/protocol/components/_fx-unsupported-ie.scss
  media/js/base/site.js
  media/js/firefox/new/common/thanks-direct.js
  media/js/firefox/new/common/thanks-init.js
  media/js/firefox/new/common/thanks.js
  tests/unit/spec/base/site.js
  tests/unit/spec/firefox/new/common/thanks.js
Labels: P1, Needs Review, Review: M

#13424 Update new product testing newsletter description (Fixes #13399)
  bedrock/newsletter/templates/newsletter/includes/newsletter-strings.json
  l10n/en/mozorg/newsletters.ftl
Labels: P3, Needs Review, Review: µ

#13412 Add WNP 116 for EU (Fixes #13383)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx116-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx116-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx116-uk.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-116-eu.scss
  media/img/firefox/whatsnew/whatsnew116-eu/big-picture-thumbnail.png
  media/img/firefox/whatsnew/whatsnew116-eu/pip-cook.svg
  media/img/firefox/whatsnew/whatsnew116-eu/pip-entertain.svg
  media/img/firefox/whatsnew/whatsnew116-eu/pip-icon.svg
  media/img/firefox/whatsnew/whatsnew116-eu/pip-lecture.svg
  media/img/firefox/whatsnew/whatsnew116-eu/video-thumbnail.jpg
  media/js/firefox/whatsnew/whatsnew-116-eu.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_116.py
  tests/pages/firefox/whatsnew/whatsnew_116.py
Labels: P1, Needs Review, Review: XS

#13428 Add documentation for GA4 product_download event
  docs/attribution/0001-analytics.rst
Labels: P2, Needs Review, Review: XS

#13449 Add CTA buttons to VPN features page [fix #13445]
  bedrock/products/templates/products/vpn/features.html
  media/css/products/vpn/features.scss
Labels: P1, Needs Review, Review: XS

#13452 Update J. Bob Alotta's title
  bedrock/foundation/templates/foundation/annualreport/2021/article/innovation.html
  bedrock/mozorg/templates/mozorg/about/leadership/mofo.html
Labels: Needs Review, Review: µ

#13422 Bump front-end linters and test runner
  .pre-commit-config.yaml
  package-lock.json
  package.json
  tests/unit/spec/base/fxa-form.js
  tests/unit/spec/base/stub-attribution.js
Labels: P3, Needs Review, Review: µ

#13430 Bump Glean to v1.4.0
  bedrock/base/templates/base-protocol.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/new/basic/base.html
  bedrock/firefox/templates/firefox/new/desktop/base.html
  bedrock/mozorg/templates/mozorg/home/base.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templates/products/vpn/pricing.html
  docs/attribution/0001-analytics.rst
  glean/metrics.yaml
  media/js/base/banners/mozilla-banner.js
  media/js/base/protocol/init-lang-switcher.es6.js
  media/js/glean/init.es6.js
  media/js/glean/page.es6.js
  media/js/glean/utils.es6.js
  package-lock.json
  package.json
  requirements/dev.txt
  requirements/prod.in
  requirements/prod.txt
  tests/unit/karma.conf.js
  tests/unit/spec/glean/page.js
  tests/unit/spec/glean/utils.js
Labels: P3, Needs Review, Review: XS

#13454 Use existing subnav on refreshed VPN pages [fix #13453]
  bedrock/products/templates/products/vpn/includes/subnav-refresh.html
  bedrock/products/templates/products/vpn/includes/subnav.html
  bedrock/products/templates/products/vpn/landing-refresh.html
  bedrock/products/views.py
Labels: P1, Needs Review, Review: µ

#13459 Fix missing trailing slash on sustainability pages
  bedrock/mozorg/urls.py
Labels: Needs Review, Review: µ

#13455 WNP for Firefox 116, NA [fix #13421]
  bedrock/firefox/templates/firefox/whatsnew/base.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx116-na.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-116-na.scss
  media/img/firefox/whatsnew/whatsnew116-na/reader-icon.svg
  media/js/base/uitour-lib.js
  media/js/firefox/whatsnew/whatsnew-116-na.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_116.py
Labels: P1, Needs Review, Review: XS

#13456 Fluent string fixes for Relay migration
  bedrock/products/templates/products/relay/faq.html
  bedrock/products/templates/products/relay/includes/bundle.html
  bedrock/products/templates/products/relay/includes/features.html
  bedrock/products/templates/products/relay/includes/matrix.html
  bedrock/products/templates/products/relay/landing.html
  bedrock/products/templates/products/relay/premium.html
  bedrock/products/templates/products/relay/pricing.html
  bedrock/products/templatetags/misc.py
  bedrock/settings/base.py
  l10n/en/products/relay/bundle.ftl
  l10n/en/products/relay/faq.ftl
  l10n/en/products/relay/features.ftl
  l10n/en/products/relay/matrix.ftl
Labels: P1, Needs Review, Review: XS

#13463 Relay l10n review changes
  bedrock/products/templates/products/relay/faq.html
  bedrock/products/templates/products/relay/includes/matrix.html
  bedrock/products/templates/products/relay/includes/waitlist-base.html
  bedrock/products/templates/products/relay/landing.html
  bedrock/products/templates/products/relay/waitlist/bundle.html
  bedrock/products/templates/products/relay/waitlist/phone.html
  bedrock/products/templates/products/relay/waitlist/premium.html
  bedrock/products/views.py
  bedrock/settings/base.py
  l10n/en/products/relay/faq.ftl
  l10n/en/products/relay/landing.ftl
  l10n/en/products/relay/matrix.ftl
  l10n/en/products/relay/waitlist.ftl
Labels: P1, Needs Review, Review: XS

#13461 Update San Francisco address [fix #13352]
  bedrock/legal/templates/legal/impressum.html
  bedrock/mozorg/templates/mozorg/contact/spaces/san-francisco.html
  bedrock/pocket/templates/pocket/contact-info.html
  bedrock/privacy/templates/privacy/index.html
  media/img/contact/osm/spaces/san-francisco-large-high-res.jpg
  media/img/contact/osm/spaces/san-francisco-large.jpg
  media/img/contact/osm/spaces/san-francisco-small-high-res.jpg
  media/img/contact/osm/spaces/san-francisco-small-high-res.png
  media/img/contact/osm/spaces/san-francisco-small.jpg
  media/img/contact/osm/spaces/san-francisco-small.png
  root_files/info.txt
Labels: Needs Review, Review: µ

#13448 Fix newsletter management page form submission when cookie has expired (Fixes #13324)
  media/js/newsletter/form-utils.es6.js
  tests/unit/spec/newsletter/form-utils.js
  tests/unit/spec/newsletter/management.js
Labels: P3, Needs Review, Review: XS

#13470 Update access request link on privacy page [fix #13466]
  bedrock/privacy/templates/privacy/index.html
Labels: Needs Review, Review: µ

#13467 Remove legacy firefox mobile template (Fixes #13039)
  bedrock/firefox/templates/firefox/mobile/includes/s2d-hero.html
  bedrock/firefox/templates/firefox/mobile/index.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  media/css/firefox/mobile/mobile.scss
  media/img/firefox/mobile/img-mobile-noodles.svg
  media/img/firefox/mobile/protocol/account.svg
  media/img/firefox/mobile/protocol/extend-eye.svg
  media/img/firefox/mobile/protocol/extend-key.svg
  media/img/firefox/mobile/protocol/extend-star.svg
  media/img/firefox/mobile/protocol/focus-bg-lg.png
  media/img/firefox/mobile/protocol/focus-bg-md.png
  media/img/firefox/mobile/protocol/focus-bg.png
  media/img/firefox/mobile/protocol/hero-high-res-rtl.jpg
  media/img/firefox/mobile/protocol/hero-high-res.jpg
  media/img/firefox/mobile/protocol/hero-rtl.jpg
  media/img/firefox/mobile/protocol/hero-small-high-res-rtl.jpg
  media/img/firefox/mobile/protocol/hero-small-high-res.jpg
  media/img/firefox/mobile/protocol/hero-small-rtl.jpg
  media/img/firefox/mobile/protocol/hero-small.jpg
  media/img/firefox/mobile/protocol/hero.jpg
  media/img/firefox/mobile/protocol/icon-block.svg
  media/img/firefox/mobile/protocol/icon-erase.svg
  media/img/firefox/mobile/protocol/qr-firefox-mozillaonline.png
  media/img/firefox/mobile/protocol/qr-firefox.png
  media/img/firefox/mobile/protocol/qr-focus.png
  media/img/firefox/mobile/protocol/screen-frame.svg
  media/img/firefox/mobile/protocol/screen-private.svg
  media/img/firefox/mobile/protocol/screen-tracking.svg
  media/img/firefox/mobile/protocol/theme-pink.svg
  media/img/firefox/mobile/protocol/theme-violet.svg
  media/img/firefox/mobile/protocol/theme-yellow.svg
  media/js/firefox/mobile/mobile.es6.js
  media/static-bundles.json
  media/static-bundles.json.orig
  tests/functional/firefox/browsers/mobile/test_landing.py
  tests/pages/firefox/browsers/mobile_landing.py
Labels: P3, Needs Review, Review: XS
