Repository mozilla/bedrock, pull requests merged in 2023-12, with the labels that each got.

#13973 Add fundraising banner A/B test (Fixes #13880)
  bedrock/base/templates/includes/banners/fundraiser.html
  bedrock/mozorg/templates/mozorg/home/home-new.html
  bedrock/mozorg/templates/mozorg/home/home-old.html
  bedrock/mozorg/templates/mozorg/home/includes/featured-vpn.html
  bedrock/mozorg/views.py
  media/css/base/banners/fundraiser.scss
  media/img/banners/fundraising/ctrl-alt-del-1000.png
  media/img/banners/fundraising/ctrl-alt-del-1200.png
  media/img/banners/fundraising/ctrl-alt-del-1400.png
  media/img/banners/fundraising/ctrl-alt-del-600.png
  media/img/banners/fundraising/ctrl-alt-del-800.png
  media/img/banners/fundraising/hand-heart-1000.png
  media/img/banners/fundraising/hand-heart-1200.png
  media/img/banners/fundraising/hand-heart-1400.png
  media/img/banners/fundraising/hand-heart-600.png
  media/img/banners/fundraising/hand-heart-800.png
  media/img/banners/fundraising/hourglass-1000.png
  media/img/banners/fundraising/hourglass-1200.png
  media/img/banners/fundraising/hourglass-1400.png
  media/img/banners/fundraising/hourglass-600.png
  media/img/banners/fundraising/hourglass-800.png
  media/js/mozorg/home/banner-experiment.es6.js
  media/js/mozorg/home/feature-vpn-experiment.es6.js
  media/js/mozorg/home/youtube.js
  media/static-bundles.json
Labels: P1, Needs Review, Review: XS

#13972 Test pricing position on VPN landing page
  bedrock/products/templates/products/vpn/landing-refresh.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templates/products/vpn/variants/landing-1.html
  bedrock/products/templates/products/vpn/variants/landing-2.html
  bedrock/products/templates/products/vpn/variants/landing-refresh-1.html
  bedrock/products/templates/products/vpn/variants/landing-refresh-2.html
  bedrock/products/tests/test_views.py
  bedrock/products/views.py
  media/css/products/vpn/landing.scss
  media/js/products/vpn/landing-experiment-pricing-position.es6.js
  media/static-bundles.json
Labels: Needs Review, Review: XS

#13952 Add Anti-Harassment Tool landing page
  bedrock/mozorg/templates/mozorg/antiharassment-tool.html
  bedrock/mozorg/urls.py
  bedrock/mozorg/views.py
  media/css/mozorg/antiharassment-tool.scss
  media/img/mozorg/antiharassment-tool/Badge.png
  media/img/mozorg/antiharassment-tool/firefox.svg
  media/img/mozorg/antiharassment-tool/monitor.png
  media/img/mozorg/antiharassment-tool/relay.svg
  media/img/mozorg/antiharassment-tool/vpn.svg
  media/static-bundles.json
Labels: Do Not Merge :warning:, Needs Review, Review: XS

#13983 13971 about page update
  bedrock/mozorg/templates/mozorg/about/index.html
  l10n/en/mozorg/about.ftl
  media/img/mozorg/about/irl-high-res.jpg
  media/img/mozorg/about/irl-high-res.png
  media/img/mozorg/about/irl.jpg
  media/img/mozorg/about/irl.png
Labels: Needs Review, Review: µ

#13984 Add Ramona Blake to leadership page [fix #13889]
  bedrock/mozorg/templates/mozorg/about/leadership/includes/senior.html
  media/img/mozorg/about/leadership/ramona-blake-high-res.jpg
  media/img/mozorg/about/leadership/ramona-blake.jpg
Labels: Needs Review, Review: µ

#13986 Update to Glean 4.0.0-pre.2
  media/js/glean/init.es6.js
  media/js/glean/page.es6.js
  media/js/glean/utils.es6.js
  package-lock.json
  package.json
  tests/unit/spec/glean/page.js
  tests/unit/spec/glean/utils.js
Labels: Needs Review, Review: XS

#13996 Add Innovation Projects to main nav [fix #13994]
  bedrock/base/templates/includes/protocol/navigation/menus/innovation.html
  l10n/en/navigation_v2.ftl
  media/img/nav/icons/icon-innovation-projects.svg
Labels: Needs Review, Review: µ

#14000 Fundraising banner A/B test round 2 (Fixes #13999)
  bedrock/base/templates/includes/banners/fundraiser.html
  media/img/banners/fundraising/ctrl-alt-del-1000.png
  media/img/banners/fundraising/ctrl-alt-del-1200.png
  media/img/banners/fundraising/ctrl-alt-del-1400.png
  media/img/banners/fundraising/ctrl-alt-del-600.png
  media/img/banners/fundraising/ctrl-alt-del-800.png
  media/img/banners/fundraising/hand-heart-1000.png
  media/img/banners/fundraising/hand-heart-1200.png
  media/img/banners/fundraising/hand-heart-1400.png
  media/img/banners/fundraising/hand-heart-600.png
  media/img/banners/fundraising/hand-heart-800.png
  media/img/banners/fundraising/thermometer-1000.png
  media/img/banners/fundraising/thermometer-1200.png
  media/img/banners/fundraising/thermometer-1400.png
  media/img/banners/fundraising/thermometer-600.png
  media/img/banners/fundraising/thermometer-800.png
  media/js/mozorg/home/banner-experiment.es6.js
Labels: P1, Needs Review, Review: XS

#14002 Leadership: Add bio for Amy Keating [fix #14001]
  bedrock/mozorg/templates/mozorg/about/leadership/includes/boards.html
Labels: Needs Review, Review: µ

#13995 Add WNP 121
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx120-eu.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx121.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-121.scss
  media/img/firefox/whatsnew/whatsnew121/puzzle.svg
  media/img/firefox/whatsnew/whatsnew121/star-1.svg
  media/img/firefox/whatsnew/whatsnew121/star-2.svg
  media/img/firefox/whatsnew/whatsnew121/star-3.svg
  media/img/firefox/whatsnew/whatsnew121/sync.svg
  media/img/l10n/de/firefox/wnp-121/presents-and-qr.svg
  media/img/l10n/en-GB/firefox/wnp-121/presents-and-qr.svg
  media/img/l10n/en-US/firefox/wnp-121/presents-and-qr.svg
  media/img/l10n/fr/firefox/wnp-121/presents-and-qr.svg
  media/static-bundles.json
Labels: Needs Review, Review: S

#13997 VPN website should inform visitors if app is not yet localized in their language (Fixes #13161)
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/products/templates/products/vpn/includes/pricing-refresh.html
  bedrock/products/templates/products/vpn/includes/unsupported-language.html
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  bedrock/products/views.py
  bedrock/settings/base.py
  l10n/en/products/vpn/shared.ftl
  media/css/products/affiliate.scss
  media/css/products/vpn/components/unsupported-language.scss
  media/css/products/vpn/pricing-refresh.scss
  media/img/products/vpn/common/lang-bubble.svg
Labels: P2, Needs Review, Review: XS

#14006 Add links for querying Glean data to docs
  docs/attribution/0001-analytics.rst
  docs/images/glean-dictionary.png
  docs/images/l10n-blocks.jpg
Labels: P3, Review: µ
