Repository mozilla/bedrock, pull requests merged in 2023-09, with the labels that each got.

#13631 Distinguish NA from EU in WNP117 WPN attribution [#13496]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx117-vpn.html
Labels: Needs Review, Review: XS

#13642 Migrate to Glean events from custom pings (Fixes #13639)
  docs/attribution/0001-analytics.rst
  glean/metrics.yaml
  glean/pings.yaml
  media/js/base/send-to-device.es6.js
  media/js/glean/elements.es6.js
  media/js/glean/init.es6.js
  media/js/glean/page.es6.js
  media/js/newsletter/newsletter.es6.js
  media/js/products/relay/waitlist.es6.js
  media/js/products/vpn/invite.es6.js
  tests/unit/spec/glean/elements.js
  tests/unit/spec/glean/page.js
Labels: P3, Needs Review, Review: XS

#13636 Add H1 2023 transparency report [fix #13633]
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2023.html
  bedrock/mozorg/urls.py
Labels: Needs Review, Review: XS

#13641 String fixes for Firefox feature pages
  bedrock/firefox/templates/firefox/features/fast.html
  l10n/en/firefox/features/fast-2023.ftl
  l10n/en/firefox/features/password-manager-2023.ftl
  l10n/en/firefox/features/private-browsing-2023.ftl
  l10n/en/firefox/features/shared.ftl
  l10n/en/firefox/features/sync-2023.ftl
Labels: Needs Review, Review: µ

#13644 Hard-code copy for Translate feature page
  bedrock/firefox/templates/firefox/features/translate.html
  bedrock/firefox/views.py
  l10n/en/firefox/features/translate.ftl
Labels: Needs Review, Review: µ

#13645 Center images in VPN resource center articles
  media/css/products/vpn/resource-center.scss
Labels: Needs Review, Review: µ

#13649 Add Monitor global page (Issue #13643)
  bedrock/products/templates/products/monitor/base.html
  bedrock/products/templates/products/monitor/includes/macros.html
  bedrock/products/templates/products/monitor/includes/sub-footer.html
  bedrock/products/templates/products/monitor/includes/sub-nav.html
  bedrock/products/templates/products/monitor/landing.html
  bedrock/products/urls.py
  bedrock/products/views.py
  bedrock/settings/base.py
  l10n/configs/pontoon.toml
  l10n/en/brands.ftl
  l10n/en/products/monitor/landing.ftl
  l10n/en/products/monitor/shared.ftl
  media/css/products/monitor/common.scss
  media/css/products/monitor/includes/_tokens.scss
  media/css/products/monitor/landing.scss
  media/css/protocol/components/_sub-navigation.scss
  media/img/favicons/monitor/favicon.ico
  media/img/favicons/monitor/favicon.png
  media/img/products/monitor/common/check.svg
  media/img/products/monitor/common/press/cnet.svg
  media/img/products/monitor/common/press/forbes.svg
  media/img/products/monitor/common/press/google.svg
  media/img/products/monitor/common/press/pc-mag.svg
  media/img/products/monitor/common/press/tech-crunch.svg
  media/img/products/monitor/global/exposures.svg
  media/img/products/monitor/global/hero.svg
  media/img/products/monitor/global/risk.svg
  media/js/products/monitor/common.es6.js
  media/static-bundles.json
Labels: P1, Needs Review, Review: S

#13621 Pass Traffic Cop custom referrer to attribution scripts (Fixes #13593)
  media/js/base/core-datalayer-page-id.js
  media/js/base/fxa-attribution.es6.js
  media/js/base/stub-attribution.js
  media/js/glean/utils.es6.js
  tests/unit/spec/base/core-datalayer-page-id.js
  tests/unit/spec/base/fxa-attribution.js
  tests/unit/spec/base/stub-attribution.js
  tests/unit/spec/glean/utils.js
Labels: P2, Needs Review, Review: XS

#13657 String fixes for products/monitor/landing.ftl
  l10n/en/products/monitor/landing.ftl
Labels: Needs Review, Review: µ

#13637 Update root store policy to 2.9 [fix bug #1851326]
  bedrock/mozorg/templates/mozorg/about/governance/policies/security/certs/policy.html
Labels: Needs Review, Review: XS

#13416 Trigger TrackProductDownload for all mobile and desktop downloads
  bedrock/base/templates/includes/banners/mobile/firefox-app-store.html
  bedrock/base/templates/includes/banners/mobile/focus-app-store.html
  bedrock/firefox/templates/firefox/browsers/chromebook.html
  bedrock/firefox/templates/firefox/browsers/compare/includes/download-menu-list.html
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/index.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/includes/download-button.html
  bedrock/firefox/templates/firefox/includes/download-unsupported.html
  bedrock/firefox/templates/firefox/products/index.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  docs/attribution/0001-analytics.rst
  media/js/base/datalayer-productdownload-init.es6.js
  media/js/base/datalayer-productdownload.es6.js
  media/js/firefox/all/all-downloads-unified-init.es6.js
  media/js/firefox/new/common/thanks-direct.js
  media/js/firefox/new/common/thanks-init.js
  media/static-bundles.json
  tests/unit/spec/base/datalayer-productdownload.js
Labels: P1, Needs Review, Review: M, analytics 📈

#13668 Add L10n images to Monitor page (Fixes #13643)
  bedrock/products/templates/products/monitor/landing.html
  media/img/l10n/de/products/monitor/global/exposures.svg
  media/img/l10n/de/products/monitor/global/hero.svg
  media/img/l10n/de/products/monitor/global/risk.svg
  media/img/l10n/en-US/products/monitor/global/exposures.svg
  media/img/l10n/en-US/products/monitor/global/hero.svg
  media/img/l10n/en-US/products/monitor/global/risk.svg
  media/img/l10n/es-ES/products/monitor/global/exposures.svg
  media/img/l10n/es-ES/products/monitor/global/hero.svg
  media/img/l10n/es-ES/products/monitor/global/risk.svg
  media/img/l10n/fr/products/monitor/global/exposures.svg
  media/img/l10n/fr/products/monitor/global/hero.svg
  media/img/l10n/fr/products/monitor/global/risk.svg
  media/img/l10n/it/products/monitor/global/exposures.svg
  media/img/l10n/it/products/monitor/global/hero.svg
  media/img/l10n/it/products/monitor/global/risk.svg
  media/img/l10n/ja/products/monitor/global/exposures.svg
  media/img/l10n/ja/products/monitor/global/hero.svg
  media/img/l10n/ja/products/monitor/global/risk.svg
  media/img/l10n/pl/products/monitor/global/exposures.svg
  media/img/l10n/pl/products/monitor/global/hero.svg
  media/img/l10n/pl/products/monitor/global/risk.svg
  media/img/l10n/pt-BR/products/monitor/global/exposures.svg
  media/img/l10n/pt-BR/products/monitor/global/hero.svg
  media/img/l10n/pt-BR/products/monitor/global/risk.svg
  media/img/l10n/pt-PT/products/monitor/global/exposures.svg
  media/img/l10n/pt-PT/products/monitor/global/hero.svg
  media/img/l10n/pt-PT/products/monitor/global/risk.svg
  media/img/l10n/ru/products/monitor/global/exposures.svg
  media/img/l10n/ru/products/monitor/global/hero.svg
  media/img/l10n/ru/products/monitor/global/risk.svg
  media/img/l10n/zh-CN/products/monitor/global/exposures.svg
  media/img/l10n/zh-CN/products/monitor/global/hero.svg
  media/img/l10n/zh-CN/products/monitor/global/risk.svg
  media/img/products/monitor/global/exposures.svg
  media/img/products/monitor/global/hero.svg
  media/img/products/monitor/global/risk.svg
Labels: P1, Review: XS

#13677 Fix bug with Relay plan toggle
  media/css/products/relay/components/matrix.scss
Labels: P3, Needs Review, Review: µ

#13347 Remove Sidebar Menu JS from /all Fix #13236
  bedrock/firefox/templates/firefox/all-unified.html
  media/css/firefox/all/all-unified.scss
  media/js/firefox/all/all-downloads-unified-init.es6.js
Labels: P3, Review: XS

#13679 Add Masayo Nobe to leadership page [fix #13674]
  bedrock/mozorg/templates/mozorg/about/leadership/includes/senior.html
  media/img/mozorg/about/leadership/masayo-nobe-high-res.jpg
  media/img/mozorg/about/leadership/masayo-nobe.jpg
Labels: Needs Review, Review: µ

#13671 Re-adding CTD promo to German homepage
  bedrock/mozorg/templates/mozorg/home/home-new.html
Labels: Needs Review, Review: XS

#13682 String fixes for /firefox/features/customize
  bedrock/firefox/templates/firefox/features/customize.html
  l10n/en/firefox/features/customize-2023.ftl
Labels: Needs Review, Review: µ

#13684 Add GA4/GTM tracking for send_to_device (#13683)
  media/js/base/send-to-device.es6.js
Labels: P1, Review: S

#13702 Re-adding Firefox icons to Firefox Accounts page
  bedrock/firefox/templates/firefox/accounts.html
Labels: Needs Review, Review: µ

#13688 Update monitor page legal footer links
  bedrock/products/templates/products/monitor/includes/sub-footer.html
  l10n/en/products/monitor/shared.ftl
Labels: P2, Needs Review, Review: µ

#13710 Update D&I report link [fix #13709]
  bedrock/careers/templates/careers/diversity.html
Labels: Needs Review, Review: L

#13666 Add new supported EU countries to Relay #13656
  bedrock/products/templates/products/relay/includes/bundle.html
  bedrock/products/templates/products/relay/includes/macros.html
  bedrock/products/templates/products/relay/includes/matrix.html
  bedrock/products/templates/products/relay/landing.html
  bedrock/products/templates/products/relay/premium.html
  bedrock/products/templates/products/relay/pricing.html
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  bedrock/products/views.py
  bedrock/settings/base.py
Labels: P1, Needs Review, Review: M

#13711 update social-content-policies page
  bedrock/mozorg/templates/mozorg/about/governance/policies/social-content-policies.html
Labels: Needs Review

#13680 Adding landing page for lapsed users
  bedrock/mozorg/templates/mozorg/try-picture-in-picture.html
  bedrock/mozorg/urls.py
  l10n/configs/pontoon.toml
  l10n/en/mozorg/try-picture-in-picture.ftl
  media/css/mozorg/try-picture-in-picture.scss
  media/img/mozorg/try-picture-in-picture/pip-cook.svg
  media/img/mozorg/try-picture-in-picture/pip-entertain.svg
  media/img/mozorg/try-picture-in-picture/pip-icon.svg
  media/img/mozorg/try-picture-in-picture/pip-lecture.svg
  media/img/mozorg/try-picture-in-picture/video-thumbnail-alt.jpg
  media/img/mozorg/try-picture-in-picture/video-thumbnail.jpg
  media/js/mozorg/try-picture-in-picture.js
  media/static-bundles.json
Labels: Review: XS

#13713 Improve l10n docs
  docs/l10n.rst
Labels: P3, Needs Review, Review: XS

#13655 WNP 118 (#13619)
  bedrock/firefox/templates/firefox/whatsnew/includes/fx118/arrow-blue.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx118/arrow-white.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx118/translate-icon.svg
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx118-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx118-en-CA.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx118-en-GB.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx118-en-US.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx118-fr.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-118.scss
  media/js/firefox/whatsnew/whatsnew-118.es6.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_118_eu.py
  tests/functional/firefox/whatsnew/test_whatsnew_118_na.py
  tests/pages/firefox/whatsnew/whatsnew_118_eu.py
  tests/pages/firefox/whatsnew/whatsnew_118_na.py
Labels: P1, Review: S

#13689 Remove Glean custom page view ping (Fixes #13652)
  docs/attribution/0001-analytics.rst
  glean/pings.yaml
  media/js/glean/page.es6.js
  package.json
Labels: P3, Needs Review, Review: µ

#13706 Fix Fluent files for Moz accounts update
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/browsers/compare/safari.html
  bedrock/firefox/templates/firefox/features/sync.html
  bedrock/security/templates/security/third-party-injection-policy.html
  l10n/en/firefox/browsers.ftl
  l10n/en/firefox/browsers/compare/safari.ftl
  l10n/en/firefox/features/password-manager-2023.ftl
  l10n/en/firefox/features/sync-2023.ftl
  l10n/en/firefox/privacy-hub.ftl
  l10n/en/sub_navigation.ftl
Labels: Do Not Merge :warning:, Needs Review, Review: XS

#13728 Add Dani Chehak to leadership page [#13722]
  bedrock/mozorg/templates/mozorg/about/leadership/includes/executive.html
  media/img/mozorg/about/leadership/dani-chehak-high-res.jpg
  media/img/mozorg/about/leadership/dani-chehak.jpg
Labels: Needs Review, Review: µ

#13721 Update mana link on MPL license policy page [fix #13720]
  bedrock/mozorg/templates/mozorg/mpl/license-policy.html
Labels: Needs Review, Review: µ

#13733 Decommission /firefox/welcome/3/ page (Fixes #13732)
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/welcome/page3.html
  bedrock/firefox/urls.py
  l10n/configs/pontoon.toml
  l10n/en/firefox/welcome/page3.ftl
  tests/functional/firefox/welcome/test_welcome_page3.py
  tests/pages/firefox/welcome/page3.py
  tests/redirects/map_globalconf.py
Labels: P2, Needs Review, Review: µ
