Repository mozilla/bedrock, pull requests merged in 2023-10, with the labels that each got.

#13730 Bump Glean.js to v2.0.3
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#13745 Fix color contrast issue on link focus in /new modal (Fixes #13585)
  media/css/firefox/new/desktop/download.scss
Labels: P3, Needs Review, Review: µ

#13747 Add mozsocial waitlist page [fix #13635]
  bedrock/newsletter/templates/newsletter/monitor-waitlist.html
  bedrock/products/forms.py
  bedrock/products/templates/products/mozsocial/invite.html
  bedrock/products/urls.py
  bedrock/products/views.py
  l10n/en/brands.ftl
  l10n/en/products/mozsocial/invite.ftl
  media/css/products/mozsocial/invite.scss
  media/img/products/mozsocial/waitlist-tree-high-res.png
  media/img/products/mozsocial/waitlist-tree.png
  media/js/products/mozsocial/invite.es6.js
  media/static-bundles.json
  tests/functional/products/mozsocial/test_invite.py
  tests/pages/products/mozsocial/invite.py
Labels: Review: XS

#13729 Update Monitor product name
  bedrock/base/templates/includes/protocol/navigation/menus/products.html
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/browsers/best-browser.html
  bedrock/firefox/templates/firefox/browsers/compare/brave.html
  bedrock/firefox/templates/firefox/browsers/compare/chrome.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/privacy/book.html
  bedrock/firefox/templates/firefox/privacy/passwords.html
  bedrock/firefox/templates/firefox/privacy/products.html
  bedrock/firefox/templates/firefox/products/index.html
  bedrock/firefox/templates/firefox/welcome/page1.html
  bedrock/firefox/templates/firefox/welcome/page7.html
  bedrock/firefox/templates/firefox/welcome/page8.html
  bedrock/newsletter/templates/newsletter/updated.html
  l10n/en/brands.ftl
  l10n/en/firefox/accounts.ftl
  l10n/en/firefox/browsers/best-browser.ftl
  l10n/en/firefox/browsers/compare/brave.ftl
  l10n/en/firefox/browsers/compare/chrome.ftl
  l10n/en/firefox/home.ftl
  l10n/en/firefox/new/desktop.ftl
  l10n/en/firefox/privacy-hub.ftl
  l10n/en/firefox/privacy/book.ftl
  l10n/en/firefox/privacy/passwords.ftl
  l10n/en/firefox/products.ftl
  l10n/en/firefox/welcome/page1.ftl
  l10n/en/firefox/welcome/page7.ftl
  l10n/en/firefox/welcome/page8.ftl
  l10n/en/mozorg/newsletters.ftl
  l10n/en/navigation.ftl
  l10n/en/navigation_v2.ftl
  media/css/protocol/protocol-firefox.scss
  media/css/protocol/protocol-mozilla.scss
  media/img/logos/mozilla/monitor/wordmark.svg
  media/img/newsletter/confirm/mozilla-monitor.png
Labels: P1, Needs Review, Review: XS

#13748 Add VPN button to navbar on in resource center [fix #13622]
  bedrock/products/templates/products/vpn/includes/macros.html
  bedrock/products/templates/products/vpn/resource-center/base-article.html
  bedrock/products/templates/products/vpn/resource-center/landing.html
  bedrock/products/views.py
Labels: Needs Review, Review: XS

#13760 Update ESR link alias for unsupported messaging (Fixes #13752)
  bedrock/firefox/templates/firefox/includes/download-unsupported.html
Labels: P3, Needs Review, Review: µ

#13746 OS specific FF download pages should always return the same build (Fixes #12192)
  bedrock/firefox/templates/firefox/all-unified.html
  bedrock/firefox/templates/firefox/browsers/chromebook.html
  bedrock/firefox/templates/firefox/browsers/windows-64-bit.html
  bedrock/firefox/templates/firefox/includes/macros.html
  bedrock/firefox/templates/firefox/new/basic/base_download.html
  bedrock/firefox/templates/firefox/new/basic/base_platform.html
  bedrock/firefox/templates/firefox/new/basic/download_linux.html
  bedrock/firefox/templates/firefox/new/basic/download_mac.html
  bedrock/firefox/templates/firefox/new/basic/download_windows.html
  l10n/en/firefox/browsers/windows-64-bit.ftl
  media/css/firefox/browsers/windows-64-bit.scss
  media/css/protocol/components/_download-button.scss
  media/js/base/stub-attribution.js
  media/static-bundles.json
  tests/functional/firefox/browsers/test_windows_64_bit.py
  tests/functional/firefox/new/test_platform.py
  tests/pages/firefox/browsers/windows_64_bit.py
  tests/pages/firefox/new/platform.py
Labels: P3, Needs Review, Review: XS

#13772 Add legal links to redsigned VPN page footer (Fixes #13771)
  bedrock/products/templates/products/vpn/landing-refresh.html
  bedrock/products/templates/products/vpn/pricing-refresh.html
  media/css/products/vpn/common-refresh.scss
  tests/functional/products/vpn/test_landing_refresh.py
  tests/functional/products/vpn/test_pricing_refresh.py
  tests/pages/products/vpn/landing_refresh.py
  tests/pages/products/vpn/pricing_refresh.py
Labels: P2, Needs Review, Review: µ

#13775 Move Ian Carmichael to Executive Steering Committee section
  bedrock/mozorg/templates/mozorg/about/leadership/includes/executive.html
  bedrock/mozorg/templates/mozorg/about/leadership/includes/senior.html
Labels: Needs Review, Review: µ

#13715 Update l10n docs with guidance on obsolete strings
  docs/l10n.rst
  l10n/en/banners/fundraising.ftl
  l10n/en/brands.ftl
  l10n/en/firefox/browsers.ftl
  l10n/en/firefox/browsers/compare/chrome.ftl
  l10n/en/firefox/browsers/mobile/focus.ftl
  l10n/en/firefox/developer.ftl
  l10n/en/firefox/facebook_container.ftl
  l10n/en/firefox/new/desktop.ftl
  l10n/en/firefox/new/download.ftl
  l10n/en/firefox/nightly/whatsnew.ftl
  l10n/en/firefox/privacy/passwords.ftl
  l10n/en/footer.ftl
  l10n/en/mozorg/mission.ftl
  l10n/en/mozorg/newsletters.ftl
  l10n/en/navigation.ftl
  l10n/en/privacy/faq.ftl
  l10n/en/products/monitor/shared.ftl
  l10n/en/products/vpn/landing.ftl
  l10n/en/products/vpn/shared.ftl
Labels: P3, Needs Review, Review: XS

#13776 Updated og:image for firefox/new page
  bedrock/firefox/templates/firefox/new/desktop/download.html
  media/img/firefox/new/desktop/meta-img-en.png
  media/img/firefox/new/desktop/meta-img-es.png
  media/img/firefox/new/desktop/meta-img-global.png
Labels: Review: XS

#13788 Removed Mozilla Reps Council from Leadership page and Governance pages
  bedrock/mozorg/templates/mozorg/about/governance/roles.html
  bedrock/mozorg/templates/mozorg/about/leadership/base.html
  bedrock/mozorg/templates/mozorg/about/leadership/includes/reps.html
  bedrock/mozorg/templates/mozorg/about/leadership/index.html
  media/img/mozorg/about/leadership/francesca-minelli-high-res.jpg
  media/img/mozorg/about/leadership/francesca-minelli.jpg
  media/img/mozorg/about/leadership/konstantina-papadea-high-res.jpg
  media/img/mozorg/about/leadership/konstantina-papadea.jpg
  media/img/mozorg/about/leadership/mehul-patel-high-res.jpg
  media/img/mozorg/about/leadership/mehul-patel.jpg
  media/img/mozorg/about/leadership/paul-wright-high-res.jpg
  media/img/mozorg/about/leadership/paul-wright.jpg
  media/img/mozorg/about/leadership/pranshu-khanna-high-res.jpg
  media/img/mozorg/about/leadership/pranshu-khanna.jpg
  media/img/mozorg/about/leadership/robby-sayles-high-res.jpg
  media/img/mozorg/about/leadership/robby-sayles.jpg
  media/img/mozorg/about/leadership/robert-reyes-high-res.jpg
  media/img/mozorg/about/leadership/robert-reyes.jpg
  media/img/mozorg/about/leadership/siddhartha-rao-high-res.jpg
  media/img/mozorg/about/leadership/siddhartha-rao.jpg
  media/img/mozorg/about/leadership/yuliana-reyna-high-res.jpg
  media/img/mozorg/about/leadership/yuliana-reyna.jpg
Labels: Needs Review, Review: XS

#13789 Bump Glean.js to v2.0.4
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#13786 Vpn moment 16 2.0
  bedrock/firefox/templates/firefox/welcome/page16.html
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  media/css/firefox/welcome16.scss
  media/img/firefox/welcome/page16/copy-dark.svg
  media/img/firefox/welcome/page16/copy-light.svg
  media/img/firefox/welcome/page16/devices-dark.svg
  media/img/firefox/welcome/page16/devices-light.svg
  media/img/firefox/welcome/page16/firefox-wordmark-dark.svg
  media/img/firefox/welcome/page16/firefox-wordmark-light.svg
  media/img/firefox/welcome/page16/shield-dark.svg
  media/img/firefox/welcome/page16/shield-light.svg
  media/js/firefox/welcome/welcome16.js
Labels: Needs Review, Review: XS

#13793 Fix img 404 in JS tests
  tests/unit/spec/pocket/updates-signup.js
Labels: P3, Needs Review, Review: µ

#13791 Bump ESLint, Prettier, Stylelint to latest versions
  .pre-commit-config.yaml
  package-lock.json
  package.json
  tests/unit/spec/glean/page.js
Labels: P3, Needs Review, Review: µ

#13790 Bump webpack, babel, sass to latest versions
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#13778 Remove newsletter-strings.json from sitemap.xml (Fixes #13777)
  bedrock/settings/base.py
Labels: P3, Needs Review, Review: µ

#13800 Update jasmine, Sinon, Stylelint to latest versions
  .pre-commit-config.yaml
  media/css/careers/components/locations.scss
  media/css/careers/components/testimonials.scss
  media/css/firefox/challenge-the-default/index.scss
  media/css/firefox/family/components/_agreement.scss
  media/css/firefox/family/components/_dad-jokes-banner.scss
  media/css/firefox/family/components/_hero.scss
  media/css/firefox/family/components/modules/_passwords.scss
  media/css/firefox/family/components/modules/_privacy.scss
  media/css/mozorg/webvision.scss
  media/css/products/monitor/common.scss
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: XS

#13804 VPN Moment 16 updates from leadership
  bedrock/firefox/templates/firefox/welcome/page16.html
  media/css/firefox/welcome16.scss
  media/img/firefox/welcome/page16/logo-dark.svg
  media/img/firefox/welcome/page16/logo-light.svg
Labels: Needs Review

#13807 Title update for Vpn Moment 16
  bedrock/firefox/templates/firefox/welcome/page16.html
Labels: Needs Review

#13812 Bump Glean.js to v2.0.5
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#13814 Update docs to reference Mozilla accounts (Fixes #137240)
  bedrock/mozorg/templatetags/misc.py
  bedrock/settings/base.py
  docs/attribution/0001-analytics.rst
  docs/attribution/0004-mozilla-accounts.rst
  docs/attribution/0005-affiliate-marketing.rst
  docs/browser-support.rst
  docs/index.rst
  docs/mozilla-accounts.rst
  docs/newsletters.rst
  docs/testing.rst
  docs/uitour.rst
  docs/vpn-subscriptions.rst
  media/js/base/experiment-utils.es6.js
  media/js/base/fxa-attribution.es6.js
  media/js/base/fxa-bundle-init.es6.js
  media/js/base/mozilla-client.js
  media/js/base/uitour-lib.js
  media/js/newsletter/management.es6.js
  tests/unit/spec/base/fxa-attribution.js
Labels: P3, Needs Review, Review: XS

#13816 Rename Firefox account to Mozilla account on /firefox/pocket page (Fixes #13815)
  bedrock/firefox/templates/firefox/pocket.html
Labels: P2, Needs Review, Review: µ

#13822 Remove extra quotation mark from L10N string
  l10n/en/firefox/new/desktop.ftl
Labels: Needs Review, Review: µ

#13824 Add Mozilla Monitor waitlist pages (Fixes #13823)
  bedrock/products/templates/products/monitor/waitlist/base.html
  bedrock/products/templates/products/monitor/waitlist/plus.html
  bedrock/products/templates/products/monitor/waitlist/scan.html
  bedrock/products/tests/test_views.py
  bedrock/products/urls.py
  bedrock/products/views.py
  bedrock/settings/base.py
  media/css/products/monitor/waitlist.scss
  media/static-bundles.json
  tests/functional/products/monitor/test_waitlist.py
  tests/pages/products/monitor/waitlist.py
Labels: P1, Needs Review, Review: XS

#13825 Remove Mozilla Monitor landing page (Fixes #13820)
  bedrock/products/templates/products/monitor/base.html
  bedrock/products/templates/products/monitor/includes/macros.html
  bedrock/products/templates/products/monitor/includes/sub-footer.html
  bedrock/products/templates/products/monitor/includes/sub-nav.html
  bedrock/products/templates/products/monitor/landing.html
  bedrock/products/urls.py
  bedrock/products/views.py
  bedrock/settings/base.py
  l10n/configs/pontoon.toml
  l10n/en/products/monitor/landing.ftl
  l10n/en/products/monitor/shared.ftl
  media/css/products/monitor/common.scss
  media/css/products/monitor/includes/_tokens.scss
  media/css/products/monitor/landing.scss
  media/img/products/monitor/common/check.svg
  media/img/products/monitor/common/press/cnet.svg
  media/img/products/monitor/common/press/forbes.svg
  media/img/products/monitor/common/press/google.svg
  media/img/products/monitor/common/press/pc-mag.svg
  media/img/products/monitor/common/press/tech-crunch.svg
  media/js/products/monitor/common.es6.js
  media/static-bundles.json
Labels: P3, Needs Review, Review: XS

#13813 Update Selenium and pytest-selenium
  requirements/dev.in
  requirements/dev.txt
Labels: P3, Needs Review, Review: µ

#13834 Update legal page ToS links (Fixes #13833)
  bedrock/legal/templates/legal/index.html
  l10n/en/mozorg/about/legal.ftl
Labels: P2, Needs Review, Review: µ
