Repository mozilla/bedrock, pull requests merged in 2023-01, with the labels that each got.

#12359 Move email preference center to the front-end (Fixes #11946)
  bedrock/newsletter/forms.py
  bedrock/newsletter/templates/newsletter/base.html
  bedrock/newsletter/templates/newsletter/country.html
  bedrock/newsletter/templates/newsletter/existing.html
  bedrock/newsletter/templates/newsletter/includes/newsletter-strings.json
  bedrock/newsletter/templates/newsletter/index.html
  bedrock/newsletter/templates/newsletter/management.html
  bedrock/newsletter/templates/newsletter/recovery.html
  bedrock/newsletter/tests/test_forms.py
  bedrock/newsletter/tests/test_views.py
  bedrock/newsletter/urls.py
  bedrock/newsletter/views.py
  docs/contentful.rst
  docs/install.rst
  docs/newsletters.rst
  gcp/bedrock-demos/cloudrun/mozorg-demo.env.yaml
  l10n/en/mozorg/newsletters.ftl
  media/css/newsletter/newsletter-management.scss
  media/css/newsletter/newsletter.scss
  media/js/base/send-to-device.es6.js
  media/js/newsletter/form-utils.es6.js
  media/js/newsletter/management-init.es6.js
  media/js/newsletter/management.es6.js
  media/js/newsletter/newsletter.es6.js
  media/js/newsletter/recovery.es6.js
  media/js/products/vpn/invite.es6.js
  media/static-bundles.json
  tests/unit/karma.conf.js
  tests/unit/spec/newsletter/data.js
  tests/unit/spec/newsletter/management.js
Labels: P3, Needs Review, Review: M

#12546 Remove Pocket best-of 2022 home page banner (Fixes #12543)
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/includes/pocket-best-2022-promo.html
  media/css/mozorg/home/home-pocket-best-2022-promo.scss
  media/img/home/2022/pocket-best-promo/desktop.svg
  media/img/home/2022/pocket-best-promo/mobile.svg
  media/static-bundles.json
Labels: P2, Needs Review, Review: µ

#12534 Update webpack dependencies
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#12433 Add GA4 to pocket pages
  bedrock/pocket/templates/pocket/base.html
  bedrock/pocket/templates/pocket/includes/google-analytics.html
  bedrock/settings/__init__.py
  bedrock/settings/base.py
  gcp/bedrock-demos/cloudrun/pocket-demo.env.yaml
Labels: Needs Review, Review: XS, analytics

#12570 Fix Mastodon icon to be white in WNP's dark mode
  media/css/firefox/whatsnew/includes/_dark-mode.scss
Labels: Needs Review, Review: µ, Frontend

#12556 Set maximum field length on newsletter/updated form field (Fixes #12539)
  bedrock/newsletter/templates/newsletter/updated.html
  l10n/en/mozorg/newsletters.ftl
  media/js/newsletter/form-utils.es6.js
  tests/unit/spec/newsletter/form-utils.js
  tests/unit/spec/newsletter/unsubscribed.js
Labels: P3, Needs Review, Review: XS

#12581 Remove PBJ stories card image macros
  bedrock/stories/templates/stories/articles/art-of-engagement.html
  bedrock/stories/templates/stories/articles/build-together.html
  bedrock/stories/templates/stories/articles/community-champion.html
  bedrock/stories/templates/stories/articles/joy-of-color.html
  bedrock/stories/templates/stories/articles/raising-technology-eq.html
  bedrock/stories/templates/stories/includes/macros.html
  bedrock/stories/templates/stories/landing.html
  bedrock/stories/templates/stories/stories-base-article.html
  media/img/stories/joy-of-color-high-res.jpg
  media/img/stories/joy-of-color.jpg
Labels: P3, Review: XS

#12562 Simplify picto macro image handling (Fixes #12513)
  bedrock/base/templates/macros-protocol.html
  bedrock/careers/templates/careers/benefits.html
  bedrock/careers/templates/careers/home.html
  bedrock/careers/templates/careers/teams.html
  bedrock/contentful/templates/includes/contentful/all.html
  bedrock/firefox/templates/firefox/browsers/quantum.html
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/firefox/templates/firefox/developer/includes/engage.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/features/includes/features-content.html
  bedrock/firefox/templates/firefox/features/index.html
  bedrock/firefox/templates/firefox/features/picture-in-picture.html
  bedrock/firefox/templates/firefox/more/misinformation.html
  bedrock/firefox/templates/firefox/new/basic/base_platform.html
  bedrock/firefox/templates/firefox/nightly/firstrun.html
  bedrock/firefox/templates/firefox/privacy/book.html
  bedrock/firefox/templates/firefox/privacy/index.html
  bedrock/firefox/templates/firefox/privacy/products.html
  bedrock/firefox/templates/firefox/set-as-default/landing.html
  bedrock/firefox/templates/firefox/sync.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/templates/mozorg/moss/index.html
  bedrock/pocket/templates/pocket/home.html
  bedrock/products/templates/products/vpn/download.html
  docs/coding.rst
Labels: P3, Needs Review, Review: XS

#12555 Bump front-end dependencies
  .pre-commit-config.yaml
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#12596 Fix newsletter management error in chrome/safari (Fixes #12595)
  media/js/newsletter/management.es6.js
Labels: P1

#12572 Add Privacy is Beautiful VPN banner to homepage (Fix #12540)
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  bedrock/mozorg/templates/mozorg/home/includes/vpn-beautiful.html
  media/css/mozorg/home/vpn-beautiful.scss
  media/img/home/2023/vpn-beautiful-1100.jpg
  media/img/home/2023/vpn-beautiful-1300.jpg
  media/img/home/2023/vpn-beautiful-1500.jpg
  media/img/home/2023/vpn-beautiful-300.jpg
  media/img/home/2023/vpn-beautiful-500.jpg
  media/img/home/2023/vpn-beautiful-700.jpg
  media/img/home/2023/vpn-beautiful-900.jpg
  media/static-bundles.json
Labels: P2

#12592 Show price + tax for VPN in US and Canada (Fixes #12589)
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  l10n/en/products/vpn/shared.ftl
Labels: P3, Needs Review, Review: µ

#12604 Update Glean.js and glean_parser
  package-lock.json
  package.json
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.in
  requirements/prod.txt
Labels: P3, Needs Review, Review: µ

#12577 Remove unused /exp/ app from bedrock (Fixes #12563)
  bedrock/base/templates/base-protocol.html
  bedrock/exp/__init__.py
  bedrock/exp/models.py
  bedrock/exp/redirects.py
  bedrock/exp/templates/exp/firefox/accounts.html
  bedrock/exp/templates/exp/firefox/index.html
  bedrock/exp/templates/exp/firefox/new/download.html
  bedrock/exp/templates/exp/includes/convert.html
  bedrock/exp/templates/exp/includes/id.html
  bedrock/exp/templates/exp/includes/stub.html
  bedrock/exp/tests/__init__.py
  bedrock/exp/tests/test_views.py
  bedrock/exp/urls.py
  bedrock/exp/views.py
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  bedrock/mozorg/redirects.py
  bedrock/newsletter/urls.py
  bedrock/privacy/templates/privacy/convert-opt-out.html
  bedrock/privacy/urls.py
  bedrock/settings/base.py
  bedrock/urls/mozorg_mode.py
  docs/abtest.rst
  media/js/base/convert-snippet.js
  media/js/base/mozilla-convert.js
  media/js/base/stub-attribution-convert.js
  media/static-bundles.json
  tests/functional/test_experiment_pages.py
  tests/redirects/map_globalconf.py
  tests/unit/karma.conf.js
  tests/unit/spec/base/mozilla-convert.js
Labels: P3, Needs Review, Review: XS

#12610 Add EN whatsnew 109 templates to the VPN excluded list [#12541, #12583]
  bedrock/firefox/views.py
Labels: Bug :bug:, P1, Needs Review, Review: µ

#12609 Add cursor declaration for F3 page banner
  media/css/firefox/family/components/_dad-jokes-banner.scss
Labels: Needs Review, Review: µ

#12611 Add region1 to Pocket CSP (fixes #12608)
  bedrock/settings/__init__.py
Labels: Bug :bug:, Needs Review, Review: µ

#12612 Move region1 to correct Pocket CSP setting
  bedrock/settings/__init__.py
Labels: Needs Review, Review: µ

#12620 Remove background video on careers (#12619)
  bedrock/careers/templates/careers/diversity.html
  bedrock/careers/templates/careers/home.html
  media/css/careers/components/hero-video.scss
Labels: Needs Review, Review: XS

#12614 Moved protocol macro docs to macro file (Fixes #12022)
  bedrock/base/templates/macros-protocol.html
  docs/coding.rst
Labels: Needs Review, Documentation, Review: XS

#11687 Remove hero component where possible
  bedrock/contentful/templates/includes/contentful/all.html
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/firefox/templates/firefox/features/adblocker.html
  bedrock/firefox/templates/firefox/features/safebrowser.html
  bedrock/firefox/templates/firefox/installer-help.html
  bedrock/firefox/templates/firefox/new/basic/base_download.html
  bedrock/firefox/templates/firefox/nightly/firstrun.html
  bedrock/firefox/templates/firefox/pocket.html
  bedrock/firefox/templates/firefox/privacy/book.html
  bedrock/firefox/templates/firefox/set-as-default/landing.html
  bedrock/firefox/templates/firefox/set-as-default/thanks.html
  bedrock/firefox/templates/firefox/testflight.html
  bedrock/firefox/templates/firefox/welcome/page1.html
  bedrock/firefox/templates/firefox/welcome/page2.html
  bedrock/firefox/templates/firefox/welcome/page3.html
  bedrock/firefox/templates/firefox/welcome/page4.html
  bedrock/firefox/templates/firefox/welcome/page6.html
  bedrock/firefox/templates/firefox/welcome/page7.html
  bedrock/firefox/templates/firefox/welcome/page8.html
  bedrock/firefox/templates/firefox/welcome/page9.de.html
  bedrock/firefox/templates/firefox/welcome/page9.fr.html
  bedrock/foundation/templates/foundation/reimagine-open.html
  bedrock/mozorg/templates/mozorg/about/index.html
  media/css/contentful/firefox/c-hero.scss
  media/css/contentful/mozilla/c-hero.scss
  media/css/firefox/channel.scss
  media/css/firefox/features/adblocker.scss
  media/css/firefox/features/safebrowser.scss
  media/css/firefox/firstrun/nightly.scss
  media/css/firefox/installer-help.scss
  media/css/firefox/mobile/mobile.scss
  media/css/firefox/new/basic/download.scss
  media/css/firefox/pocket.scss
  media/css/firefox/privacy/book.scss
  media/css/firefox/set-as-default/landing.scss
  media/css/firefox/set-as-default/thanks.scss
  media/css/firefox/sync.scss
  media/css/firefox/testflight.scss
  media/css/firefox/welcome.scss
  media/css/foundation/annual-report-2019-2020.scss
  media/css/foundation/reimagine-open.scss
  media/css/mozorg/about.scss
  media/css/mozorg/diversity/2021/diversity-2021.scss
  media/css/mozorg/home/home.scss
  media/css/mozorg/lean-data.scss
  media/css/protocol/components/call-out.scss
  media/static-bundles.json
Labels: Papercuts 💸, Needs Review, Review: S

#12522 Use webpack-dev-server for local development
  docker-compose.yml
  docs/install.rst
  package-lock.json
  package.json
  webpack.config.js
Labels: P3, Needs Review, Review: XS

#12587 Prevent overflow on parent tips (Fix #12586)
  media/css/firefox/family/components/_pro-tip.scss
Labels: Needs Review, Review: µ

#12645 Code Pocket home page banner - DE
  bedrock/pocket/templates/pocket/base.html
  bedrock/pocket/templates/pocket/home.html
  media/css/pocket/components/home.scss
  media/img/pocket/home/de-banner-cropped-high-res.png
  media/img/pocket/home/de-banner-cropped.png
  media/img/pocket/home/de-banner-high-res.png
  media/img/pocket/home/de-banner.png
Labels: Pocket

#12658 Update stub attribution documentation
  docs/firefox-stub-attribution.rst
Labels: P3, Needs Review, Review: µ

#12659 Add apple-touch-icon.png to root_files (Fixes #12636)
  root_files/apple-touch-icon.png
Labels: P3, Needs Review, Review: µ
