Repository mozilla/bedrock, pull requests merged in 2023-05, with the labels that each got.

#13063 Activate en-GB locale for WNP 113 (Issue #12961)
  bedrock/firefox/views.py
Labels: Needs Review, Review: µ

#13048 Remove Gitlab CI config, stopping it running
  .github/workflows/gitlab-mirror.yml
  .gitlab-ci.yml
Labels: Infra

#13078 Leadership updates [fix #13077]
  bedrock/mozorg/templates/mozorg/about/leadership/senior.html
  media/img/mozorg/about/leadership/marshall-erwin-high-res.jpg
  media/img/mozorg/about/leadership/marshall-erwin.jpg
  media/img/mozorg/about/leadership/oscar-murillo-high-res.jpg
  media/img/mozorg/about/leadership/oscar-murillo.jpg
Labels: Needs Review, Review: µ

#13070 Add NA WNP for Firefox 113 [fix #13060]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx113-en.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-113-en.scss
  media/img/firefox/whatsnew/whatsnew113-en/pip-cook.svg
  media/img/firefox/whatsnew/whatsnew113-en/pip-entertain.svg
  media/img/firefox/whatsnew/whatsnew113-en/pip-icon.svg
  media/img/firefox/whatsnew/whatsnew113-en/pip-lecture.svg
  media/img/firefox/whatsnew/whatsnew113-en/video-thumbnail.jpg
  media/js/firefox/whatsnew/whatsnew-113-en.js
  media/static-bundles.json
Labels: P1, Review: XS

#13015 Update Firefox Desktop Attribution docs
  docs/firefox-desktop-attribution.rst
  docs/firefox-stub-attribution.rst
  docs/index.rst
Labels: P3, Needs Review, Review: XS

#13082 Add message to email preference center on timing of unsubscribes (Fixes #13050)
  bedrock/newsletter/templates/newsletter/management.html
  l10n/en/mozorg/newsletters.ftl
Labels: P3, Needs Review, Review: µ

#13067 Use local newsletter data for email prefs page instead of basket (Fixes #13031)
  bedrock/newsletter/tests/test_views.py
  bedrock/newsletter/urls.py
  bedrock/newsletter/views.py
  media/js/newsletter/management.es6.js
Labels: Needs Review, Review: XS

#13104 Updated to NA WNP 113 [#13060]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx113-en.html
  media/img/firefox/whatsnew/whatsnew113-en/video-thumbnail.jpg
Labels: P1, Needs Review, Review: µ

#13101 Fix string ID for about page description [no bug]
  bedrock/mozorg/templates/mozorg/about/index.html
Labels: Needs Review, Review: µ

#13017 VPN post-download pages for Windows & Mac
  bedrock/base/redirects.py
  bedrock/mozorg/redirects.py
  bedrock/products/redirects.py
  bedrock/products/templates/products/vpn/download.html
  bedrock/products/templates/products/vpn/includes/download-faq.html
  bedrock/products/templates/products/vpn/mac-download.html
  bedrock/products/templates/products/vpn/windows-download.html
  bedrock/products/urls.py
  bedrock/products/views.py
  l10n/configs/pontoon.toml
  l10n/en/products/vpn/platform-post-download.ftl
  media/css/products/vpn/download.scss
  media/css/products/vpn/platform-download.scss
  media/img/logos/vpn/vpn-dark-logo.svg
  media/img/products/vpn/download/mac-installer-500.png
  media/img/products/vpn/download/mac-installer-700.png
  media/img/products/vpn/download/mac-installer-960.png
  media/img/products/vpn/download/vpn-app-mac-500.png
  media/img/products/vpn/download/vpn-app-mac-700.png
  media/img/products/vpn/download/vpn-app-mac-960.png
  media/img/products/vpn/download/vpn-app-on-mac-500.png
  media/img/products/vpn/download/vpn-app-on-mac-700.png
  media/img/products/vpn/download/vpn-app-on-mac-960.png
  media/img/products/vpn/download/vpn-app-on-windows-500.png
  media/img/products/vpn/download/vpn-app-on-windows-700.png
  media/img/products/vpn/download/vpn-app-on-windows-960.png
  media/img/products/vpn/download/vpn-app-windows-500.png
  media/img/products/vpn/download/vpn-app-windows-700.png
  media/img/products/vpn/download/vpn-app-windows-960.png
  media/img/products/vpn/download/vpn-app.png
  media/img/products/vpn/download/vpn-file-mac-500.png
  media/img/products/vpn/download/vpn-file-mac-700.png
  media/img/products/vpn/download/vpn-file-mac-960.png
  media/img/products/vpn/download/vpn-file-windows-500.png
  media/img/products/vpn/download/vpn-file-windows-700.png
  media/img/products/vpn/download/vpn-file-windows-960.png
  media/img/products/vpn/download/vpn-unavailable-country.svg
  media/img/products/vpn/download/windows-installer-500.png
  media/img/products/vpn/download/windows-installer-700.png
  media/img/products/vpn/download/windows-installer-960.png
  media/js/products/vpn/thanks.js
  media/static-bundles.json
  tests/redirects/map_globalconf.py
Labels: Do Not Merge :warning:, Review: S

#13107 Reduce padding on VPN download pages
  media/css/products/vpn/download.scss
  media/css/products/vpn/platform-download.scss
Labels: Needs Review, Review: µ

#13128 Lint careers scss files
  .stylelintrc
  media/css/careers/_utils.scss
Labels: P3, Needs Review, Review: µ

#13116 Pass coupon URL parameter to FxA subscription links (Fixes #13043)
  docs/firefox-accounts.rst
  media/js/base/fxa-attribution.es6.js
  media/js/base/fxa-bundle-init.es6.js
  media/static-bundles.json
  tests/unit/karma.conf.js
  tests/unit/spec/base/fxa-attribution.js
Labels: P2, Needs Review, Review: S

#13093 Adds a class to App and Play Store badges for GA4 tracking.
  bedrock/base/templates/macros.html
  bedrock/base/templates/product-all-unified-macros.html
  bedrock/firefox/templates/firefox/all-unified.html
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/compare.html
  bedrock/firefox/templates/firefox/browsers/mobile/focus.html
  bedrock/firefox/templates/firefox/browsers/mobile/get-ios.html
  bedrock/firefox/templates/firefox/browsers/mobile/ios.html
  bedrock/firefox/templates/firefox/facebookcontainer/index.html
  bedrock/firefox/templates/firefox/mobile/get-app.html
  bedrock/firefox/templates/firefox/mobile/index.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/releases/release-notes.html
  bedrock/firefox/templates/firefox/welcome/page4.html
  bedrock/firefox/templates/firefox/welcome/page6.html
  bedrock/landing/templates/landing/firefox/fx100.html
Labels: P1, Needs Review, Review: S, analytics

#13145 Remove FPN [fix #12571]
  bedrock/base/templates/includes/protocol/navigation/menus/products.html
  bedrock/firefox/templates/firefox/faq.html
  bedrock/firefox/templates/firefox/includes/structured-data-firefox-faq.html
  l10n/en/firefox/faq.ftl
  l10n/en/navigation_v2.ftl
Labels: P1, Review: µ

#13124 Create temporary Updates page for Pocket
  bedrock/pocket/templates/pocket/updates-signup.html
  bedrock/pocket/urls.py
  media/css/pocket/components/updates-signup.scss
  media/img/pocket/pocket-update-signup.png
  media/static-bundles.json
Labels: Pocket

#13155 Refresh attribution documentation
  docs/analytics.rst
  docs/attribution.rst
  docs/attribution/0001-analytics.rst
  docs/attribution/0002-firefox-desktop.rst
  docs/attribution/0003-firefox-mobile.rst
  docs/attribution/0004-firefox-accounts.rst
  docs/attribution/0005-affiliate-marketing.rst
  docs/firefox-accounts.rst
  docs/index.rst
Labels: P3, Needs Review, Review: XS

#13174 Use Firefox Account brand name in platform-post-download.ftl
  l10n/en/products/vpn/platform-post-download.ftl
Labels: P3, Needs Review, Review: µ

#13182 Fluent string fixes
  bedrock/products/templates/products/vpn/includes/download-faq.html
  l10n/en/firefox/faq.ftl
  l10n/en/products/vpn/platform-post-download.ftl
Labels: Needs Review, Review: µ

#13012 Track VPN button clicks as GA4 "begin_checkout" event
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templates/products/vpn/pricing.html
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  bedrock/settings/base.py
  media/js/base/datalayer-begincheckout-init.es6.js
  media/js/base/datalayer-begincheckout.es6.js
  media/static-bundles.json
  tests/unit/karma.conf.js
  tests/unit/spec/base/datalayer-addtocart.js
Labels: Review: L

#13118 Add Relay FAQ Page
  bedrock/products/templates/products/relay/base.html
  bedrock/products/templates/products/relay/faq.html
  bedrock/products/urls.py
  l10n/en/products/relay/faq.ftl
  l10n/en/products/relay/shared.ftl
  media/css/products/relay/faq.scss
  media/static-bundles.json
Labels: Do Not Merge :warning:, Needs Review, Review: XS

#13061 Relay waitlist
  bedrock/products/forms.py
  bedrock/products/templates/products/relay/includes/waitlist-base.html
  bedrock/products/templates/products/relay/waitlist/phone.html
  bedrock/products/templates/products/relay/waitlist/vpn.html
  bedrock/products/urls.py
  bedrock/products/views.py
  l10n/en/products/relay/waitlist.ftl
  media/css/products/relay/waitlist.scss
  media/js/products/relay/waitlist.es6.js
  media/static-bundles.json
Labels: Review: S
