Repository mozilla/bedrock, pull requests merged in 2023-02, with the labels that each got.

#12593 Remove platform fields from VPN waitlist form (Fixes #12590)
  bedrock/products/forms.py
  bedrock/products/templates/products/vpn/invite.html
  l10n/en/products/vpn/landing.ftl
  media/js/products/vpn/invite.es6.js
  tests/unit/spec/products/vpn/invite.js
Labels: P3, Needs Review, Review: µ

#12676 Remove bg image from LCP element on /new (#12675)
  media/css/firefox/new/desktop/download.scss
  media/img/firefox/new/desktop/mobile/circle-bottom.svg
  media/img/firefox/new/desktop/mobile/circle-top-right.svg
  media/img/firefox/new/desktop/mobile/elbow-bottom-right.svg
  media/img/firefox/new/desktop/mobile/elbow.svg
  media/img/firefox/new/desktop/mobile/oval-bottom.svg
  media/img/firefox/new/desktop/mobile/oval-left.svg
Labels: Needs Review, Review: µ

#12684 Add utm params to de pocket banner
  bedrock/pocket/templates/pocket/home.html
Labels: Needs Review, Review: µ

#12585 Family page: add new FAQ & Resource sections (fixes #12226)
  bedrock/firefox/templates/firefox/family/includes/hero.html
  bedrock/firefox/templates/firefox/family/includes/modules/faq.html
  bedrock/firefox/templates/firefox/family/includes/resources.html
  bedrock/firefox/templates/firefox/family/includes/subnav.html
  bedrock/firefox/templates/firefox/family/index.html
  media/css/firefox/family/_utils.scss
  media/css/firefox/family/components/_agreement.scss
  media/css/firefox/family/components/_hero.scss
  media/css/firefox/family/components/_resources.scss
  media/css/firefox/family/components/_subnav.scss
  media/css/firefox/family/components/modules/_bullying.scss
  media/css/firefox/family/components/modules/_faq.scss
  media/css/firefox/family/styles.scss
  media/img/firefox/family/ask-firefox-high-res.jpg
  media/img/firefox/family/ask-firefox.jpg
  media/img/firefox/family/logo-common-sense-media.svg
  media/img/firefox/family/parental-controls-high-res.jpg
  media/img/firefox/family/parental-controls.jpg
  media/img/firefox/family/parenting-survey-high-res.jpg
  media/img/firefox/family/parenting-survey.jpg
  media/js/firefox/family/animate-pop-in.es6.js
  media/js/firefox/family/default-open-first-detail-init.es6.js
  media/js/firefox/family/default-open-first-detail.es6.js
  media/js/firefox/family/subnav.js
  media/static-bundles.json
Labels: P1, Needs Review, Review: S

#12671 Load Pocket GA only after OneTrust active signal (Fixes #12670)
  bedrock/pocket/templates/pocket/base.html
  bedrock/pocket/templates/pocket/includes/google-analytics.html
  bedrock/settings/__init__.py
  media/js/pocket/google-analytics.es6.js
  media/js/pocket/google-analytics.js
  media/static-bundles.json
Labels: P1, Needs Review, Review: XS

#12692 Family: fix horizontal spacing in hero CTA (fixes #12691)
  media/css/firefox/family/components/_hero.scss
Labels: Bug :bug:, Needs Review, Review: µ

#12632 Allow stub attribution data to be added to bouncer staging links (Fixes #12631)
  media/js/base/stub-attribution.js
  tests/unit/spec/base/stub-attribution.js
Labels: P3, Needs Review, Review: µ

#12623 Remove token from newsletter URLs (Fixes #12389)
  bedrock/newsletter/templates/newsletter/confirm.html
  bedrock/newsletter/templates/newsletter/country.html
  bedrock/newsletter/templates/newsletter/management.html
  bedrock/newsletter/templates/newsletter/updated.html
  bedrock/newsletter/tests/test_views.py
  bedrock/newsletter/urls.py
  bedrock/newsletter/views.py
  docs/newsletters.rst
  media/css/newsletter/newsletter-confirm.scss
  media/js/base/send-to-device.es6.js
  media/js/newsletter/country.es6.js
  media/js/newsletter/form-utils.es6.js
  media/js/newsletter/management.es6.js
  media/js/newsletter/newsletter.es6.js
  media/js/newsletter/recovery.es6.js
  media/js/newsletter/unsubscribed.es6.js
  media/js/products/vpn/invite.es6.js
  media/static-bundles.json
  tests/unit/spec/newsletter/country.js
  tests/unit/spec/newsletter/form-utils.js
  tests/unit/spec/newsletter/management.js
  tests/unit/spec/newsletter/unsubscribed.js
Labels: P3, Needs Review, Review: M

#12695 Add empty alt attribute for homepage contentful images
  bedrock/contentful/templates/includes/contentful/all.html
Labels: P2, Review: µ

#12688 Add WNP 110 for EU (Fixes #12664)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx110-de-v1.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx110-de-v2.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx110-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx110-uk.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-110-de.scss
  media/css/firefox/whatsnew/whatsnew-110-eu.scss
  media/img/firefox/whatsnew/whatsnew110-eu/pocket-de.gif
  media/img/firefox/whatsnew/whatsnew110-eu/pocket-de.png
  media/img/firefox/whatsnew/whatsnew110-eu/pocket-en.gif
  media/img/firefox/whatsnew/whatsnew110-eu/pocket-en.png
  media/img/firefox/whatsnew/whatsnew110-eu/pocket-fr.gif
  media/img/firefox/whatsnew/whatsnew110-eu/pocket-fr.png
  media/img/firefox/whatsnew/whatsnew110-eu/pocket-von-mozilla.svg
  media/img/firefox/whatsnew/whatsnew110-eu/pod-1000.jpg
  media/img/firefox/whatsnew/whatsnew110-eu/pod-500.jpg
  media/img/firefox/whatsnew/whatsnew110-eu/pod-750.jpg
  media/js/firefox/whatsnew/whatsnew-110-eu.js
  media/js/firefox/whatsnew/whatsnew-110-experiment-de.es6.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_110.py
  tests/pages/firefox/whatsnew/whatsnew_110.py
Labels: P1, Review: XS

#12672 Add February Product Story (fixes #12641)
  bedrock/stories/templates/stories/articles/dreaming-then-building.html
  bedrock/stories/templates/stories/articles/raising-technology-eq.html
  bedrock/stories/templates/stories/landing.html
  bedrock/stories/urls.py
  media/css/stories/stories-shared.scss
  media/img/stories/credit/karen-kim-credit.jpg
  media/img/stories/platform-discovery-1000.jpg
  media/img/stories/platform-discovery-1500.jpg
  media/img/stories/platform-discovery-500.jpg
Labels: P2, Review: S

#12697 Expired token error message should link to recovery form (Fixes ##12685)
  bedrock/newsletter/templates/newsletter/management.html
  bedrock/newsletter/views.py
  l10n/en/mozorg/newsletters.ftl
Labels: P3, Needs Review, Review: µ

#12606 Bump @sentry/browser to v7.31.0
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#12594 Remove image() macro (Fixes #12190)
  bedrock/base/templates/macros-protocol.html
  bedrock/base/templates/macros.html
  bedrock/base/tests/test_macros.py
  bedrock/careers/templates/careers/internships.html
  bedrock/contentful/api.py
  bedrock/contentful/tests/test_contentful_api.py
  bedrock/firefox/templates/firefox/browsers/windows-64-bit.html
  bedrock/firefox/templates/firefox/mobile/index.html
  bedrock/firefox/templates/firefox/pocket.html
  bedrock/foundation/templates/foundation/annualreport/2019/index.html
  bedrock/foundation/templates/foundation/annualreport/2020/index.html
  bedrock/foundation/templates/foundation/annualreport/2021/base.html
  bedrock/mozorg/templates/mozorg/diversity/2021/beyond-products.html
  bedrock/mozorg/templates/mozorg/diversity/2021/index.html
  bedrock/mozorg/templates/mozorg/diversity/2021/what-we-build.html
  bedrock/mozorg/templates/mozorg/diversity/2021/who-we-are.html
  bedrock/stories/templates/stories/includes/macros.html
  bedrock/stories/templates/stories/landing.html
  bedrock/stories/templates/stories/stories-base-article.html
  docs/coding.rst
  media/css/careers/components/internships.scss
  media/css/firefox/browsers/windows-64-bit.scss
  media/css/firefox/enterprise/landing.scss
  media/css/firefox/mobile/mobile.scss
  media/css/firefox/new/basic/download.scss
  media/css/firefox/pocket.scss
  media/css/firefox/set-as-default/thanks.scss
  media/css/mozorg/lean-data.scss
Labels: P3, Needs Review, Review: XS

#12715 Replace quote formatting with cite element around book title (fixes #12714)
  bedrock/stories/templates/stories/articles/dreaming-then-building.html
Labels: P2, Needs Review, Review: µ

#12707 Lazy load images in the sticky promo
  bedrock/base/templates/includes/sticky-promo.html
Labels: Performance ⚡️, Needs Review, Review: XS

#12711 Add width to images in /foundation
  bedrock/foundation/templates/foundation/annualreport/2009/a-competitive-world.html
  bedrock/foundation/templates/foundation/annualreport/2011.html
  bedrock/foundation/templates/foundation/annualreport/2019/index.html
  bedrock/foundation/templates/foundation/annualreport/2020/index.html
  bedrock/foundation/templates/foundation/feed-icon-guidelines/index.html
  bedrock/foundation/templates/foundation/licensing/website-content.html
Labels: Performance ⚡️, Needs Review, Review: XS

#12723 Move footnote under heading (Fix #12713)
  bedrock/privacy/templates/privacy/base-protocol.html
  bedrock/privacy/templates/privacy/notices/base-notice-headings.html
  media/css/privacy/privacy-protocol.scss
Labels: P1, Needs Review, Legal Docs :scroll:, Review: XS

#12712 Add English WNP for Firefox 110 [fix #12669]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx110-en.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-110-en.scss
  media/img/firefox/whatsnew/whatsnew110/phone.svg
  media/img/firefox/whatsnew/whatsnew110/qrcode.svg
  media/js/firefox/whatsnew/whatsnew-110-en.js
  media/static-bundles.json
Labels: P1, Needs Review, Review: S

#12726 Configure Snowplow analytics based on cookie consent (Fixes #12693)
  bedrock/pocket/templates/pocket/base.html
  bedrock/settings/__init__.py
  media/js/pocket/analytics.es6.js
  media/js/pocket/google-analytics.es6.js
  media/js/pocket/snowplow.es6.js
  media/static-bundles.json
  tests/unit/karma.conf.js
  tests/unit/spec/pocket/analytics.js
Labels: P1, Needs Review, Review: XS

#12724 Add width to images in /careers
  bedrock/careers/templates/careers/diversity.html
  bedrock/careers/templates/careers/includes/big-picture-video.html
  bedrock/careers/templates/careers/includes/blogposts.html
  bedrock/careers/templates/careers/includes/diversity-video.html
  bedrock/careers/templates/careers/internships.html
  bedrock/careers/templates/careers/locations.html
  media/img/careers/internships/work-high-res.jpg
  media/img/careers/internships/work.jpg
Labels: P3, Performance ⚡️, Needs Review, Review: XS

#12721 Add width to images in /firefox
  bedrock/firefox/templates/firefox/browsers/browser-history.html
  bedrock/firefox/templates/firefox/browsers/incognito-browser.html
  bedrock/firefox/templates/firefox/browsers/mobile/compare.html
  bedrock/firefox/templates/firefox/browsers/mobile/index.html
  bedrock/firefox/templates/firefox/browsers/update-browser.html
  bedrock/firefox/templates/firefox/browsers/what-is-a-browser.html
  bedrock/firefox/templates/firefox/developer/includes/features.html
  bedrock/firefox/templates/firefox/developer/includes/highlights.html
  bedrock/firefox/templates/firefox/developer/includes/intro-features.html
  bedrock/firefox/templates/firefox/family/includes/download-firefox.html
  bedrock/firefox/templates/firefox/features/bookmarks.html
  bedrock/firefox/templates/firefox/features/fast.html
  bedrock/firefox/templates/firefox/features/includes/pip-video.html
  bedrock/firefox/templates/firefox/features/memory.html
  bedrock/firefox/templates/firefox/features/password-manager.html
  bedrock/firefox/templates/firefox/features/private-browsing.html
  bedrock/firefox/templates/firefox/features/safebrowser.html
  bedrock/firefox/templates/firefox/features/translate.html
  bedrock/firefox/templates/firefox/firstrun/firstrun.html
  bedrock/firefox/templates/firefox/mobile/get-app.html
  bedrock/firefox/templates/firefox/mobile/includes/s2d-hero.html
  bedrock/firefox/templates/firefox/mobile/index.html
  bedrock/firefox/templates/firefox/privacy/book.html
  bedrock/firefox/templates/firefox/releases/release-notes.html
Labels: Performance ⚡️, Review: XS

#12736 Family FAQ: update screentime answer (fixes #12735)
  bedrock/firefox/templates/firefox/family/includes/modules/faq.html
Labels: P2, Needs Review, Review: µ

#12733 Pass search referrals through to VPN subscription link utms (Fixes #12706)
  media/js/base/fxa-utm.es6.js
  tests/unit/spec/base/fxa-utm.js
Labels: P3, Needs Review, Review: XS

#12753 Add scroll offset to anchors on channel pages [fix #12751]
  bedrock/firefox/templates/firefox/channel/android.html
  bedrock/firefox/templates/firefox/channel/desktop.html
  bedrock/firefox/templates/firefox/channel/ios.html
Labels: Needs Review, Review: µ

#12738 Stub out WNP 111 page for EU locales [#12720]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx111-eu.html
  bedrock/firefox/views.py
  l10n/configs/pontoon.toml
  l10n/en/firefox/whatsnew/whatsnew-111-pdf.ftl
  media/css/firefox/whatsnew/whatsnew-111-eu.scss
  media/static-bundles.json
Labels: Needs Review, Review: XS

#12747 Add T&C legal page for Pocket PoD raffle (Fixes #12699)
  bedrock/legal/templates/legal/terms/peopleofdeutschland.de.html
  bedrock/legal/templates/legal/terms/peopleofdeutschland.html
  bedrock/legal/urls.py
Labels: P1, Needs Review, Review: µ

#12760 Update protocol/core to v16.1.0 (Fixes #12759)
  media/css/protocol/common-old-ie.scss
  media/css/protocol/protocol-firefox.scss
  media/css/protocol/protocol-mozilla.scss
  media/js/careers/testimonials-modal.es6.js
  media/js/foundation/annual-report-modal.es6.js
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: XS

#12758 Add Transparency Report H2 2022 (Fixes #12748)
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2022.html
  bedrock/mozorg/urls.py
Labels: P1, Needs Review, Review: XS

#12766 Update donation links and fundraising form (Fixes #12628, #12698)
  bedrock/base/templates/includes/banners/fundraiser.html
  bedrock/base/templates/includes/protocol/footer/footer.html
  bedrock/base/templatetags/helpers.py
  bedrock/base/tests/test_helpers.py
  bedrock/foundation/templates/foundation/annualreport/2009/broadening-our-scope.html
  bedrock/foundation/templates/foundation/annualreport/2021/index.html
  bedrock/foundation/templates/foundation/openwebfund/more.html
  bedrock/mozorg/templates/mozorg/contact/contact-landing.html
  bedrock/mozorg/templates/mozorg/contribute.html
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/home-fr.html
  bedrock/mozorg/templates/mozorg/home/home.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/mozorg/tests/test_views.py
  bedrock/mozorg/views.py
  bedrock/settings/base.py
  docs/banners.rst
  media/css/base/banners/fundraiser.scss
Labels: P2, Needs Review, Review: XS

#12757 Migrate snowplow to v3 for pocket marketing pages
  bedrock/settings/__init__.py
  media/js/pocket/analytics.es6.js
Labels: Needs Review, Review: XS, Pocket

#12767 Add iJustine promo banner to homepage (fixes #12765)
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  bedrock/mozorg/templates/mozorg/home/includes/ijustine-promo.html
  media/css/mozorg/home/ijustine-promo.scss
  media/img/home/2023/ijustine-promo/ijustine-promo-1000.jpg
  media/img/home/2023/ijustine-promo/ijustine-promo-1500.jpg
  media/img/home/2023/ijustine-promo/ijustine-promo-500.jpg
  media/img/home/2023/ijustine-promo/ijustine-promo-700.jpg
  media/js/mozorg/home/includes/ijustine-modal-video.js
  media/static-bundles.json
Labels: Review: XS, Frontend

#12783 Add missing cookie preferences link to pocket platform footer (Fixes #12678)
  bedrock/pocket/templates/pocket/includes/footer-platform.html
  media/css/pocket/includes/_platform-footer.scss
Labels: P2, Needs Review, Review: µ

#12782 Remove pocket saves switch (fixes #12284)
  bedrock/pocket/templates/pocket/includes/mobile-nav.html
  bedrock/pocket/templates/pocket/includes/nav.html
  bedrock/security/templates/security/bug-bounty/web-eligible-sites.html
Labels: P3, Needs Review, Review: µ

#12780 Family page: reduce grid size on mobile (fixes #12663)
  media/css/firefox/family/components/_hero.scss
  media/css/firefox/family/components/modules/_mental-health.scss
  media/css/firefox/family/components/modules/_private-mode.scss
  media/css/firefox/family/components/modules/_public-wifi.scss
  media/img/firefox/family/grid-doomscrollhole-mobile.svg
Labels: P3, Needs Review, Review: XS

#12798 Updates to iJustine home promo [fix #12765]
  bedrock/mozorg/templates/mozorg/home/includes/ijustine-promo-image.html
  bedrock/mozorg/templates/mozorg/home/includes/ijustine-promo.html
  media/css/mozorg/home/ijustine-promo.scss
  media/img/logos/firefox/logo-word-hor-white.svg
  media/img/logos/firefox/logo-word-hor.svg
  media/js/mozorg/home/includes/ijustine-modal-video.js
Labels: Needs Review, Review: XS

#12800 Add Sales Force param to donation links (Fixes #12796)
  bedrock/base/templates/includes/banners/fundraiser.html
  bedrock/base/templates/includes/protocol/footer/footer.html
  bedrock/foundation/templates/foundation/annualreport/2009/broadening-our-scope.html
  bedrock/foundation/templates/foundation/annualreport/2021/index.html
  bedrock/foundation/templates/foundation/openwebfund/more.html
  bedrock/mozorg/templates/mozorg/contact/contact-landing.html
  bedrock/mozorg/templates/mozorg/contribute.html
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/settings/base.py
Labels: P2, Needs Review, Review: µ

#12815 Leadership updates [fix #12814]
  bedrock/mozorg/templates/mozorg/about/leadership/index.html
  bedrock/mozorg/templates/mozorg/about/leadership/mofo.html
  media/css/mozorg/leadership.scss
  media/img/mozorg/about/leadership/leigh-felton-high-res.jpg
  media/img/mozorg/about/leadership/leigh-felton.jpg
Labels: P1, Needs Review, Review: µ

#12816 Leadership: remove Mitchell’s mastodon link [#12814]
  bedrock/mozorg/templates/mozorg/about/leadership/index.html
Labels: Review: µ

#12818 Leadership: update K. Bose’s title [#12814]
  bedrock/mozorg/templates/mozorg/about/leadership/senior.html
Labels: Review: µ
