Repository mozilla/bedrock, pull requests merged in 2023-06, with the labels that each got.

#13208 Add WNP for Firefox 114 [fix #13185, fix #13186]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx114-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx114-en-gb.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx114-en.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx114-fr.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-114-eu.scss
  media/css/firefox/whatsnew/whatsnew-114-na.scss
  media/fonts/whatsnew114/Metropolis-BoldItalic.woff
  media/fonts/whatsnew114/Metropolis-BoldItalic.woff2
  media/img/firefox/whatsnew/whatsnew114/firefox-mobile-high-res.jpg
  media/img/firefox/whatsnew/whatsnew114/firefox-mobile.jpg
  media/img/firefox/whatsnew/whatsnew114/pocket-de-high-res.jpg
  media/img/firefox/whatsnew/whatsnew114/pocket-de.jpg
  media/img/firefox/whatsnew/whatsnew114/pocket-high-res.jpg
  media/img/firefox/whatsnew/whatsnew114/pocket.jpg
  media/img/firefox/whatsnew/whatsnew114/qr-code.png
  media/static-bundles.json
Labels: P1, Needs Review, Review: XS

#13216 Remove outdated string with error
  l10n/en/products/vpn/platform-post-download.ftl
Labels: Needs Review, Review: µ

#13233 added static image helper
  bedrock/pocket/templates/pocket/firefox/new-tab-learn-more.html
Labels: Needs Review, Review: µ, Frontend, Pocket

#13170 Update copy on careers/benefits
  bedrock/careers/templates/careers/benefits.html
Labels: Review: µ

#13249 Revert "Add Convert experiment block to /firefox/flashback (#13230)"
  bedrock/firefox/templates/firefox/flashback/index.html
Labels: P3, Needs Review, Review: µ

#13237 Update test filename to reflect contents
  tests/unit/spec/base/datalayer-begincheckout.js
Labels: P3, Needs Review, Review: µ

#13232 Update Convert CDN URL
  bedrock/privacy/templates/privacy/convert-opt-out.html
  bedrock/settings/__init__.py
  media/js/base/convert-snippet.js
Labels: P2, Needs Review, Review: µ

#13254 Update VPN tracking for GA4
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  bedrock/settings/base.py
  docs/vpn-subscriptions.rst
  media/js/base/datalayer-begincheckout.es6.js
  tests/unit/spec/base/datalayer-begincheckout.js
Labels: P1, Needs Review, Review: S

#13261 Fix dataLayer test failure #13259
  media/js/base/datalayer-begincheckout.es6.js
  media/js/base/datalayer-productdownload.es6.js
  tests/unit/spec/base/datalayer-begincheckout.js
  tests/unit/spec/base/datalayer-productdownload.js
Labels: P1, Needs Review, Review: µ

#13231 Update SEO & Content for VPN Platform pages
  bedrock/products/templates/products/vpn/platforms/ipad.html
  bedrock/products/templates/products/vpn/platforms/platform-base.html
  bedrock/products/templates/products/vpn/platforms/v2/android.html
  bedrock/products/templates/products/vpn/platforms/v2/desktop.html
  bedrock/products/templates/products/vpn/platforms/v2/ios.html
  bedrock/products/templates/products/vpn/platforms/v2/linux.html
  bedrock/products/templates/products/vpn/platforms/v2/mac.html
  bedrock/products/templates/products/vpn/platforms/v2/mobile.html
  bedrock/products/templates/products/vpn/platforms/v2/windows.html
  bedrock/products/templates/products/vpn/platforms/windows.html
  bedrock/products/urls.py
  bedrock/products/views.py
  docs/l10n.rst
  l10n/en/products/vpn/platforms/android_v2.ftl
  l10n/en/products/vpn/platforms/desktop_v2.ftl
  l10n/en/products/vpn/platforms/ios_v2.ftl
  l10n/en/products/vpn/platforms/ipad.ftl
  l10n/en/products/vpn/platforms/linux_v2.ftl
  l10n/en/products/vpn/platforms/mac_v2.ftl
  l10n/en/products/vpn/platforms/mobile_v2.ftl
  l10n/en/products/vpn/platforms/windows.ftl
  l10n/en/products/vpn/platforms/windows_v2.ftl
  l10n/en/products/vpn/shared.ftl
  lib/l10n_utils/__init__.py
  lib/l10n_utils/tests/test_base.py
  media/css/products/vpn/common.scss
Labels: P1, Needs Review, Review: S

#13260 Add Advertising page
  bedrock/mozorg/templates/mozorg/advertising.html
  bedrock/mozorg/urls.py
  media/css/mozorg/advertising.scss
  media/img/mozorg/advertising/addon.svg
  media/img/mozorg/advertising/badge.svg
  media/img/mozorg/advertising/mask.svg
  media/img/mozorg/advertising/mountain.svg
  media/static-bundles.json
Labels: Do Not Merge :warning:, Needs Review, Review: XS, Frontend

#13274 Remove pontoon.js script (Fixes #13273)
  bedrock/base/templates/base-protocol.html
Labels: P3, Needs Review, Review: µ

#13276 Set default value for dlsource to 'mozorg' instead of '(not set)' (Bug 1836278)
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
Labels: P3, Needs Review, Review: µ

#13291 Add new translated newsletter strings (Issue #13250)
  l10n/en/mozorg/newsletters.ftl
Labels: Needs Review, Review: µ

#13295 Update advertising page heading and class names (Fixes #13294)
  bedrock/mozorg/templates/mozorg/advertising.html
  media/css/mozorg/advertising.scss
Labels: P2, Needs Review, Review: µ

#13271 add pocket promo
  bedrock/mozorg/templates/mozorg/home/home-contentful.html
  bedrock/mozorg/templates/mozorg/home/includes/pocket-promo.html
  media/css/mozorg/home/includes/pocket-promo.scss
  media/img/home/2023/pocket-promo/pocket-promo-mobile-520.jpg
  media/img/home/2023/pocket-promo/pocket-promo-mobile-650.jpg
  media/img/home/2023/pocket-promo/pocket-promo-text-1280.jpg
  media/img/home/2023/pocket-promo/pocket-promo-text-700.jpg
  media/img/home/2023/pocket-promo/pocket-promo-text-900.jpg
  media/static-bundles.json
Labels: Do Not Merge :warning:, Needs Review, Review: XS

#13300 Update VPN pricing for Romania, Bulgaria, and Hungary [fix #13299]
  bedrock/products/tests/test_helper_misc.py
  bedrock/settings/base.py
Labels: P1, Needs Review, Review: S

#13298 Generalize FxA/VPN attribution JS class fix #13297
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  media/js/base/fxa-attribution.es6.js
  tests/unit/spec/base/fxa-attribution.js
Labels: P1, Needs Review, Review: µ

#13285 Archive FPN legal pages (Fixes #13272)
  bedrock/legal/redirects.py
  bedrock/legal/templates/legal/terms/betterweb.html
  bedrock/legal/templates/legal/terms/firefox-private-network.html
  bedrock/legal/templates/legal/terms/firefox-reality.html
  bedrock/legal/urls.py
  bedrock/privacy/redirects.py
  bedrock/privacy/templates/privacy/archive/firefox-betterweb-2023-06.html
  bedrock/privacy/templates/privacy/archive/firefox-fire-tv-2023-06.html
  bedrock/privacy/templates/privacy/archive/firefox-private-network-notice-2023-06.html
  bedrock/privacy/templates/privacy/archive/firefox-private-network-tos-2023-06.html
  bedrock/privacy/templates/privacy/archive/firefox-reality-notice-2023-06.html
  bedrock/privacy/templates/privacy/archive/firefox-reality-tos-2023-06.html
  bedrock/privacy/templates/privacy/archive/index.html
  bedrock/privacy/templates/privacy/base-protocol.html
  bedrock/privacy/templates/privacy/notices/firefox-betterweb.html
  bedrock/privacy/templates/privacy/notices/firefox-fire-tv.html
  bedrock/privacy/templates/privacy/notices/firefox-private-network.html
  bedrock/privacy/templates/privacy/notices/firefox-reality.html
  bedrock/privacy/urls.py
  bedrock/privacy/views.py
  tests/redirects/map_globalconf.py
Labels: P3, Needs Review, Review: XS

#13304 German Homepage - CTD promo (fixes #13301)
  bedrock/mozorg/templates/mozorg/home/home-de.html
  bedrock/mozorg/templates/mozorg/home/includes/ctd-promo-de.html
  media/css/mozorg/home/ctd-promo-de.scss
  media/img/home/2023/ctd-onboarding-mobile.png
  media/img/home/2023/ctd-onboarding.png
  media/static-bundles.json
Labels: Review: XS

#13316 Quick CTD fixes
  bedrock/mozorg/templates/mozorg/home/includes/ctd-promo-de.html
  media/css/firefox/challenge-the-default/_hero.scss
  media/css/firefox/challenge-the-default/index.scss
Labels: Needs Review, Review: µ

#13287 remove references to FPN and Lockwise
  bedrock/security/templates/security/bug-bounty/faq.html
Labels: Do Not Merge :warning:

#13313 Update VPN stage endpoint [fix #13312]
  bedrock/settings/base.py
  docs/firefox-accounts.rst
  media/js/base/fxa-attribution.es6.js
  media/js/base/fxa-product-button.es6.js
Labels: Needs Review, Review: µ

#13311 Add WNP 115 for EU (CTD / mobile) (Fixes #13296)
  bedrock/firefox/templates/firefox/whatsnew/includes/fx115-eu/qr-de.html
  bedrock/firefox/templates/firefox/whatsnew/includes/fx115-eu/qr-fr.html
  bedrock/firefox/templates/firefox/whatsnew/includes/fx115-eu/qr-uk.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx115-eu-ctd-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx115-eu-mobile-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx115-eu-mobile-uk.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-115-eu-ctd.scss
  media/css/firefox/whatsnew/whatsnew-115-eu-mobile.scss
  media/img/firefox/whatsnew/whatsnew115-eu-ctd/wordmark.svg
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_115.py
  tests/pages/firefox/whatsnew/whatsnew_115.py
Labels: P1, Review: XS

#13320 Add WNP for Firefox 115 for NA [fix #13277]
  bedrock/firefox/templates/firefox/whatsnew/includes/fx115/addons.svg
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx115-eu-mobile-uk.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx115-eu-vpn.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx115-na-addons.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx115-na-windows.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-115-na-addons.scss
  media/css/firefox/whatsnew/whatsnew-115-na-windows.scss
  media/img/firefox/whatsnew/whatsnew115-na/sync-high-res.png
  media/img/firefox/whatsnew/whatsnew115-na/sync.png
  media/js/firefox/whatsnew/whatsnew-115-na-win7.js
  media/static-bundles.json
  media/static-bundles.json.orig
Labels: P1, Needs Review, Review: XS

#13323 Add VPN moments page (Fixes #13303)
  bedrock/firefox/templates/firefox/welcome/base.html
  bedrock/firefox/templates/firefox/welcome/page15/base.html
  bedrock/firefox/templates/firefox/welcome/page15/page15.de.html
  bedrock/firefox/templates/firefox/welcome/page15/page15.en-GB.html
  bedrock/firefox/templates/firefox/welcome/page15/page15.fr.html
  bedrock/firefox/templates/firefox/welcome/page15/page15.html
  bedrock/firefox/urls.py
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  docs/attribution/0004-firefox-accounts.rst
  media/css/firefox/welcome15.scss
  media/img/firefox/welcome/page15/devices-dark.svg
  media/img/firefox/welcome/page15/devices-light.svg
  media/img/firefox/welcome/page15/hero-dark.svg
  media/img/firefox/welcome/page15/hero-light.svg
  media/img/firefox/welcome/page15/shield-dark.svg
  media/img/firefox/welcome/page15/shield-light.svg
  media/js/firefox/welcome/welcome15-experiment.es6.js
  media/static-bundles.json
  tests/functional/firefox/welcome/test_welcome_page15.py
  tests/pages/firefox/welcome/page15.py
Labels: P1, Review: XS

#13326 Update WNP 115 to target Windows 8.1 and lower [#13277]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx115-na-windows.html
  media/js/firefox/whatsnew/whatsnew-115-na-win7.js
Labels: P1, Needs Review, Review: µ

#13333 Leadership updates [fix #13330]
  bedrock/mozorg/templates/mozorg/about/leadership/boards.html
  bedrock/mozorg/templates/mozorg/about/leadership/mofo.html
Labels: Needs Review, Review: µ
