Repository mozilla/bedrock, pull requests merged in 2024-07, with the labels that each got.

#14756 Ensure Docker builds include any CSS needed when the CMS Admin mode is active, too
  docker/bin/build_staticfiles.sh
Labels: Backend

#14746 New mofo leader
  bedrock/mozorg/templates/mozorg/about/leadership/includes/mofo.html
  media/img/mozorg/about/leadership/nabiha-syed-high-res.jpg
  media/img/mozorg/about/leadership/nabiha-syed.jpg
Labels: Do Not Merge :warning:, P1, Needs Review, Review: µ, Frontend

#14777 Add note to testing docs about Playwright
  docs/testing.rst
Labels: P3, Needs Review, Review: µ

#14736 Update Glean documentation
  docs/attribution/0001-analytics.rst
  docs/cms.rst
  docs/images/glean-dictionary.png
Labels: P3, Review: XS

#14789 Add Juy fundraising banner with experiment [fix #14747]
  bedrock/base/templates/includes/banners/fundraiser.html
  bedrock/mozorg/templates/mozorg/home/home-new.html
  bedrock/mozorg/templates/mozorg/home/home-old.html
  media/css/base/banners/fundraiser.scss
  media/img/banners/fundraising/hand-heart-1000.png
  media/img/banners/fundraising/hand-heart-1200.png
  media/img/banners/fundraising/hand-heart-1400.png
  media/img/banners/fundraising/hand-heart-600.png
  media/img/banners/fundraising/hand-heart-800.png
  media/js/mozorg/home/fundraising-banner-experiment.es6.js
  media/js/mozorg/home/fundraising-banner.es6.js
  media/static-bundles.json
Labels: Review: S

#14780 Bump VPN client system requirements for macOS and iOS (Fixes #14727)
  bedrock/products/templates/products/vpn/download.html
  bedrock/products/templates/products/vpn/landing.html
Labels: P2, Needs Review, Review: µ

#14779 Remove fx meta for rebranded products
  bedrock/firefox/templates/firefox/welcome/base.html
  bedrock/firefox/templates/firefox/welcome/page1.html
  bedrock/mozorg/templates/mozorg/account.html
  media/img/firefox/template/page-image-master.jpg
Labels: Frontend

#14768 Remove UA client ID from stub attribution data (Fixes #14406)
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  docs/attribution/0002-firefox-desktop.rst
  media/js/base/stub-attribution/stub-attribution.js
  tests/unit/spec/base/stub-attribution/stub-attribution.js
Labels: P2, Needs Review, Review: XS, Frontend

#14807 Update NA WNP128 image and layout [#14713]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx128-na.html
  media/css/firefox/whatsnew/whatsnew-128-na.scss
  media/img/firefox/whatsnew/whatsnew128-na/gymnast-high-res.jpg
  media/img/firefox/whatsnew/whatsnew128-na/gymnast.jpg
  media/img/firefox/whatsnew/whatsnew128-na/gymnast.png
Labels: Needs Review, Review: µ

#14811 Fix Playwright test failure on /firefox/new/
  tests/playwright/specs/products/firefox/firefox-home.spec.js
  tests/playwright/specs/products/firefox/firefox-new.spec.js
Labels: P2, Needs Review, Review: µ

#14810 Add moment page for Fakespot summer sales [fix #14740]
  bedrock/firefox/templates/firefox/welcome/page18.html
  bedrock/firefox/urls.py
  media/css/firefox/welcome18.scss
  media/img/firefox/welcome/page18/fakespot-hero-high-res.png
  media/img/firefox/welcome/page18/fakespot-hero.png
  media/img/firefox/welcome/page18/icon-best.svg
  media/img/firefox/welcome/page18/icon-time.svg
  media/img/firefox/welcome/page18/icon-trust.svg
  media/static-bundles.json
Labels: Review: XS, Frontend

#14813 Support bootstrapping a Django/Wagtail admin user as part of `make preflight`
  Makefile
  bedrock/cms/management/commands/bootstrap_local_admin.py
  bedrock/cms/tests/test_commands.py
Labels: Backend, Wagtail

#14409 Remove archType and isARM() from site.js (Fixes #14404)
  media/js/base/site.js
  tests/unit/spec/base/site.js
  tests/unit/spec/firefox/new/common/thanks.js
Labels: P3, Review: XS, Frontend

#14751 Sub nav updates:
  bedrock/firefox/templates/firefox/all-unified.html
  bedrock/firefox/templates/firefox/base/base-protocol.html
  bedrock/firefox/templates/firefox/browsers/compare/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/android.html
  bedrock/firefox/templates/firefox/browsers/mobile/focus.html
  bedrock/firefox/templates/firefox/browsers/mobile/get-app.html
  bedrock/firefox/templates/firefox/browsers/mobile/includes/sub-nav.html
  bedrock/firefox/templates/firefox/browsers/mobile/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/ios.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/facebookcontainer/index.html
  bedrock/firefox/templates/firefox/features/index.html
  bedrock/firefox/templates/firefox/includes/sub-nav-firefox.html
  bedrock/firefox/templates/firefox/index.html
  bedrock/firefox/templates/firefox/more.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/new/desktop/includes/sub_nav.html
  l10n/en/firefox/more.ftl
  l10n/en/navigation.ftl
  l10n/en/sub_navigation.ftl
  media/img/firefox/more/firefox-adblocker.jpg
  media/img/firefox/more/firefox-brave.jpg
  media/img/firefox/more/firefox-chrome.jpg
  media/img/firefox/more/firefox-edge.jpg
  media/img/firefox/more/firefox-opera.jpg
  media/img/firefox/more/firefox-safari.jpg
  media/img/firefox/more/firefox-sync.jpg
  media/img/firefox/more/private-browsing.jpg
  media/img/firefox/more/private.png
Labels: P2, Review: S, Frontend

#14815 Leadership page updates (Fixes #14814)
  bedrock/mozorg/templates/mozorg/about/leadership/includes/executive.html
  bedrock/mozorg/templates/mozorg/about/leadership/includes/senior.html
  media/img/mozorg/about/leadership/brad-smallwood-high-res.jpg
  media/img/mozorg/about/leadership/brad-smallwood.jpg
  media/img/mozorg/about/leadership/graham-mudd-high-res.jpg
  media/img/mozorg/about/leadership/graham-mudd.jpg
  media/img/mozorg/about/leadership/jesse-goranson-high-res.jpg
  media/img/mozorg/about/leadership/jesse-goranson.jpg
  media/img/mozorg/about/leadership/tamara-greasby-high-res.jpg
  media/img/mozorg/about/leadership/tamara-greasby.jpg
Labels: P2, Needs Review, Review: µ

#14745 Add localized Microsoft Store badge / button (Fixes #14738)
  bedrock/base/templates/macros.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/settings/appstores.py
  bedrock/settings/base.py
  l10n/en/download_button.ftl
  media/css/protocol/components/_download-button.scss
  media/img/l10n/ar/firefox/windows/ms-store-badge.svg
  media/img/l10n/be/firefox/windows/ms-store-badge.svg
  media/img/l10n/bg/firefox/windows/ms-store-badge.svg
  media/img/l10n/bn/firefox/windows/ms-store-badge.svg
  media/img/l10n/bs/firefox/windows/ms-store-badge.svg
  media/img/l10n/cs/firefox/windows/ms-store-badge.svg
  media/img/l10n/da/firefox/windows/ms-store-badge.svg
  media/img/l10n/de/firefox/windows/ms-store-badge.svg
  media/img/l10n/el/firefox/windows/ms-store-badge.svg
  media/img/l10n/en-US/firefox/windows/ms-store-badge.svg
  media/img/l10n/es-ES/firefox/windows/ms-store-badge.svg
  media/img/l10n/et/firefox/windows/ms-store-badge.svg
  media/img/l10n/fi/firefox/windows/ms-store-badge.svg
  media/img/l10n/fr/firefox/windows/ms-store-badge.svg
  media/img/l10n/he/firefox/windows/ms-store-badge.svg
  media/img/l10n/hi-IN/firefox/windows/ms-store-badge.svg
  media/img/l10n/hr/firefox/windows/ms-store-badge.svg
  media/img/l10n/hu/firefox/windows/ms-store-badge.svg
  media/img/l10n/id/firefox/windows/ms-store-badge.svg
  media/img/l10n/it/firefox/windows/ms-store-badge.svg
  media/img/l10n/ja/firefox/windows/ms-store-badge.svg
  media/img/l10n/ko/firefox/windows/ms-store-badge.svg
  media/img/l10n/lt/firefox/windows/ms-store-badge.svg
  media/img/l10n/lv/firefox/windows/ms-store-badge.svg
  media/img/l10n/ms/firefox/windows/ms-store-badge.svg
  media/img/l10n/nb-NO/firefox/windows/ms-store-badge.svg
  media/img/l10n/nl/firefox/windows/ms-store-badge.svg
  media/img/l10n/pl/firefox/windows/ms-store-badge.svg
  media/img/l10n/pt-BR/firefox/windows/ms-store-badge.svg
  media/img/l10n/pt-PT/firefox/windows/ms-store-badge.svg
  media/img/l10n/ro/firefox/windows/ms-store-badge.svg
  media/img/l10n/ru/firefox/windows/ms-store-badge.svg
  media/img/l10n/sk/firefox/windows/ms-store-badge.svg
  media/img/l10n/sl/firefox/windows/ms-store-badge.svg
  media/img/l10n/sr/firefox/windows/ms-store-badge.svg
  media/img/l10n/sv-SE/firefox/windows/ms-store-badge.svg
  media/img/l10n/th/firefox/windows/ms-store-badge.svg
  media/img/l10n/tr/firefox/windows/ms-store-badge.svg
  media/img/l10n/uk/firefox/windows/ms-store-badge.svg
  media/img/l10n/vi/firefox/windows/ms-store-badge.svg
  media/img/l10n/zh-CN/firefox/windows/ms-store-badge.svg
  media/img/l10n/zh-TW/firefox/windows/ms-store-badge.svg
  media/js/base/datalayer-productdownload.es6.js
  tests/unit/spec/base/datalayer-productdownload.js
Labels: P2, Needs Review, Review: XS

#14804 Add MoFo donation nav CTA for the homepage for July 2024
  bedrock/mozorg/templates/mozorg/home/home-new.html
  media/css/mozorg/home/home-new.scss
  media/js/mozorg/home/fundraising-nav-cta.es6.js
  media/static-bundles.json
Labels: Needs Review, Review: XS, Frontend

#14818 Updates to Fakespot moment page [#14740]
  bedrock/firefox/templates/firefox/welcome/page18.html
  media/css/firefox/welcome18.scss
  media/img/firefox/welcome/page18/fakespot-hero-high-res.png
  media/img/firefox/welcome/page18/fakespot-hero.png
  media/img/firefox/welcome/page18/fakespot-rc-high-res.png
  media/img/firefox/welcome/page18/fakespot-rc.png
  media/img/firefox/welcome/page18/icon-tag-white.svg
  media/img/firefox/welcome/page18/icon-tag.svg
Labels: Review: µ

#14819 Update Review Checker moment page title [#14740]
  bedrock/firefox/templates/firefox/welcome/page18.html
  media/css/firefox/welcome18.scss
  media/img/firefox/welcome/page18/icon-best.svg
  media/img/firefox/welcome/page18/icon-time.svg
  media/img/firefox/welcome/page18/icon-trust.svg
Labels: Needs Review, Review: µ

#14735 Support configurable CSP reporting percentage
  bedrock/base/middleware.py
  bedrock/base/tests/test_middleware.py
  bedrock/settings/__init__.py
  bin/qa/check_csp_report.py
  gcp/bedrock-demos/cloudrun/mozorg-demo.env.yaml
Labels: Backend, Frontend

#14845 Use square QR code on fallback WNP [fix #14844]
  media/img/firefox/whatsnew/qrcode-firefox-whatsnew.png
Labels: Needs Review, Review: µ

#14833 Add MS Store install experiment (Fixes #11090)
  bedrock/firefox/templates/firefox/new/desktop/download-ms-store.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/new/desktop/thanks-install-win.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/settings/appstores.py
  bedrock/settings/base.py
  media/css/firefox/new/desktop/thanks-install-win.scss
  media/img/firefox/new/desktop/thanks/win-step-1.svg
  media/img/firefox/new/desktop/thanks/win-step-2.svg
  media/img/firefox/new/desktop/thanks/win-step-3.svg
  media/js/base/datalayer-productdownload.es6.js
  media/js/firefox/new/desktop/download-ms-store-exp.es6.js
  media/js/firefox/new/desktop/thanks-install-win.es6.js
  media/static-bundles.json
  tests/unit/spec/base/datalayer-productdownload.js
Labels: Do Not Merge :warning:, P2, Needs Review, Review: XS

#14852 Add docs for creating new page models in Wagtail (Fixes #14797)
  docs/cms.rst
Labels: P3, Needs Review, Review: XS

#14794 Add wagtail-localize-smartling to the project, for Smartling L10N support
  bedrock/cms/management/commands/run_smartling_sync.py
  bedrock/settings/base.py
  docs/cms.rst
  requirements/dev.txt
  requirements/prod.in
  requirements/prod.txt
Labels: Backend, Wagtail

#14849 Remove suprefluous selenium tests
  tests/functional/firefox/channel/test_ios.py
  tests/functional/firefox/new/test_download.py
  tests/functional/firefox/new/test_thank_you.py
  tests/functional/firefox/test_home.py
  tests/functional/firefox/test_ios_testflight.py
  tests/functional/products/vpn/test_download.py
  tests/functional/products/vpn/test_invite.py
  tests/functional/products/vpn/test_landing_refresh.py
  tests/functional/products/vpn/test_pricing_refresh.py
  tests/functional/test_account.py
  tests/functional/test_consent_banner.py
  tests/functional/test_home.py
  tests/functional/test_l10n.py
  tests/functional/test_leadership.py
  tests/pages/account.py
  tests/pages/base.py
  tests/pages/firefox/channel/ios.py
  tests/pages/firefox/home.py
  tests/pages/firefox/ios_testflight.py
  tests/pages/firefox/new/download.py
  tests/pages/firefox/new/thank_you.py
  tests/pages/home.py
  tests/pages/leadership.py
  tests/pages/products/vpn/download.py
  tests/pages/products/vpn/invite.py
  tests/pages/products/vpn/landing_refresh.py
  tests/pages/products/vpn/pricing_refresh.py
  tests/pages/regions/consent_banner.py
Labels: P3, Needs Review, Review: µ

#14866 Update Rise25 nomination page, link to honorees
  bedrock/mozorg/templates/mozorg/rise25/includes/hero-video.html
  bedrock/mozorg/templates/mozorg/rise25/includes/social-share.html
  bedrock/mozorg/templates/mozorg/rise25/landing.html
  bedrock/mozorg/templates/mozorg/rise25/thanks.html
  bedrock/mozorg/urls.py
  media/css/mozorg/rise25/components/blog.scss
  media/css/mozorg/rise25/components/category.scss
  media/css/mozorg/rise25/components/faq.scss
  media/css/mozorg/rise25/components/hero.scss
  media/css/mozorg/rise25/components/promote.scss
  media/css/mozorg/rise25/components/social.scss
  media/css/mozorg/rise25/rise25.scss
  media/img/mozorg/rise25/blog-thumbnail-high-res.jpg
  media/img/mozorg/rise25/blog-thumbnail.jpg
  media/img/mozorg/rise25/hero-thumb-high-res.jpg
  media/img/mozorg/rise25/hero-thumb.jpg
  media/img/mozorg/rise25/play-button.svg
  media/img/mozorg/rise25/winners-poster-high-res.jpg
  media/img/mozorg/rise25/winners-poster.jpg
Labels: Review: XS

#14861 Add URL query param to show consent banner in the EU (Fixes #14853)
  docs/attribution/0007-consent-management.rst
  media/js/base/consent/init.es6.js
  media/js/base/consent/utils.es6.js
  tests/unit/spec/base/consent/consent-utils.js
Labels: P2, Needs Review, Review: XS

#14879 Update applicant privacy notice on job postings [fix #14875]
  bedrock/careers/templates/careers/position.html
Labels: Needs Review, Review: µ

#14881 Fixes for Nothing Personal page [#14824]
  bedrock/firefox/templates/firefox/nothing-personal/index.html
  media/css/firefox/nothing-personal/_animations.scss
  media/css/firefox/nothing-personal/_browser.scss
  media/css/firefox/nothing-personal/_primary-cta.scss
  media/css/firefox/nothing-personal/_sticky-note.scss
  media/css/firefox/nothing-personal/styles.scss
Labels: Needs Review, Review: XS

#14870 Add KIP newsletter confirmation page (Fixes #14823)
  bedrock/newsletter/templates/newsletter/knowledge-is-power-confirm.html
  bedrock/newsletter/tests/test_views.py
  bedrock/newsletter/urls.py
  bedrock/newsletter/views.py
  media/css/newsletter/newsletter-knowledge-is-power-confirm.scss
  media/js/newsletter/confirm-init.es6.js
  media/js/newsletter/confirm.es6.js
  media/js/newsletter/form-utils.es6.js
  media/static-bundles.json
  tests/unit/spec/newsletter/confirm.js
Labels: Needs Review, Review: XS

#14883 Nothing Personal page, right align window titles [#14824]
  media/css/firefox/nothing-personal/_browser.scss
Labels: Review: µ

#14891 Reemhamz sei 2024
  bedrock/base/templates/includes/protocol/navigation/menus/whoweare.html
  bedrock/careers/templates/careers/diversity.html
  bedrock/mozorg/templates/mozorg/impact-report/index.html
  bedrock/mozorg/urls.py
  bedrock/mozorg/views.py
  l10n/en/navigation_v2.ftl
  media/css/mozorg/impact.scss
  media/img/mozorg/impact/arrow.png
  media/img/mozorg/impact/fight-racism.jpg
  media/img/mozorg/impact/green-planet.jpg
  media/img/mozorg/impact/mofo-fellows.jpg
  media/img/mozorg/impact/moz-a11y.jpg
  media/img/mozorg/impact/report-cover-high-res.jpg
  media/img/mozorg/impact/report-cover.jpg
  media/static-bundles.json
Labels: Needs Review, Review: XS

#14898 Ignore NS_ERROR_ABORT No error message alerts in Sentry front-end
  media/js/base/sentry-consent.es6.js
Labels: P3, Review: µ, Frontend

#14895 Fix CC license CSP error
  bedrock/foundation/templates/foundation/licensing/website-content.html
  bedrock/settings/__init__.py
  media/img/foundation/licensing/cc-by-sa.svg
Labels: P3, Frontend

#14880 Simplify spinners
  bedrock/firefox/templates/firefox/includes/send-to-device.html
  media/css/newsletter/newsletter-management.scss
  media/css/protocol/components/send-to-device.scss
  media/img/icons/loading.svg
  media/js/base/send-to-device.es6.js
  media/js/libs/spin.min.js
  media/js/newsletter/management.es6.js
  tests/unit/spec/base/send-to-device.js
Labels: P3, Frontend

#14888 Remove VPN headline experiment code (Fixes #14721)
  bedrock/products/templates/products/vpn/landing-refresh.html
  bedrock/products/views.py
  media/js/products/vpn/landing-experiment-headlines.es6.js
  media/static-bundles.json
Labels: Papercuts 💸, P3, Review: µ, Frontend

#14874 Update Speaker Request form
  bedrock/press/templates/press/speaker-request.html
  media/js/libs/modernizr.custom.inputtypes.js
  media/js/press/speaker-request.js
  media/static-bundles.json
Labels: P3, Needs Review, Frontend

#14906 Ignore NS_ABORT_FAILURE error in Sentry JS
  media/js/base/sentry-consent.es6.js
Labels: P3, Needs Review, Review: µ, Frontend

#14903 Enable dependabot for Playwright dependencies
  .github/dependabot.yml
Labels: P3, Review: µ, Frontend

#14905 Add Playwright testing docs
  docs/pipeline.rst
  docs/testing.rst
  tests/playwright/README.md
Labels: P3, Documentation, Review: XS, Frontend

#14943 Remove repeated banner include from legacy home page [fix #14941]
  bedrock/mozorg/templates/mozorg/home/home-old.html
Labels: Bug :bug:, Needs Review, Review: µ

#14945 Add vanity URL redirect for Nothing Personal page [fix #14944]
  bedrock/firefox/redirects.py
  bedrock/mozorg/redirects.py
  tests/redirects/map_globalconf.py
Labels: Needs Review, Review: µ
