Repository mozilla/bedrock, pull requests merged in 2024-10, with the labels that each got.

#15223 Add newsletter form to nothing-personal page (Fixes #15218)
  bedrock/firefox/templates/firefox/nothing-personal/includes/browser-macro.html
  bedrock/firefox/templates/firefox/nothing-personal/index.html
  bedrock/newsletter/forms.py
  bedrock/newsletter/templatetags/helpers.py
  bedrock/newsletter/tests/test_footer_form.py
  media/css/firefox/nothing-personal/_browser.scss
  media/css/firefox/nothing-personal/_header.scss
  media/css/firefox/nothing-personal/_primary-cta.scss
  media/css/firefox/nothing-personal/_sticky-note.scss
  media/css/firefox/nothing-personal/styles.scss
Labels: P2, Review: XS

#15228 Add new Mozilla advertising pages [fix #15198]
  bedrock/base/templates/includes/protocol/footer/footer-refresh.html
  bedrock/base/templates/includes/protocol/footer/footer.html
  bedrock/mozorg/templates/mozorg/advertising.html
  bedrock/mozorg/templates/mozorg/advertising/formats.html
  bedrock/mozorg/templates/mozorg/advertising/includes/blog-articles.html
  bedrock/mozorg/templates/mozorg/advertising/includes/product-fakespot-media.html
  bedrock/mozorg/templates/mozorg/advertising/includes/product-firefox-media.html
  bedrock/mozorg/templates/mozorg/advertising/includes/product-mdn-media.html
  bedrock/mozorg/templates/mozorg/advertising/includes/product-pocket-media.html
  bedrock/mozorg/templates/mozorg/advertising/includes/sub-nav.html
  bedrock/mozorg/templates/mozorg/advertising/landing.html
  bedrock/mozorg/templates/mozorg/advertising/principles.html
  bedrock/mozorg/urls.py
  l10n/en/footer.ftl
  media/css/mozorg/advertising.scss
  media/img/mozorg/advertising/addon.svg
  media/img/mozorg/advertising/ads-hero-15x.png
  media/img/mozorg/advertising/ads-hero.png
  media/img/mozorg/advertising/badge.svg
  media/img/mozorg/advertising/blog/blog-fallback.jpg
  media/img/mozorg/advertising/blog/firefox-android-new-privacy.jpg
  media/img/mozorg/advertising/blog/google-protected-audience.jpg
  media/img/mozorg/advertising/blog/introducing-anonym.jpg
  media/img/mozorg/advertising/blog/privacy-preserving-attribution.jpg
  media/img/mozorg/advertising/blog/som-fallback.jpg
  media/img/mozorg/advertising/icon-copy.svg
  media/img/mozorg/advertising/icon-eye.svg
  media/img/mozorg/advertising/icon-globe.svg
  media/img/mozorg/advertising/icon-star.svg
  media/img/mozorg/advertising/logo-anonym.svg
  media/img/mozorg/advertising/mask.svg
  media/img/mozorg/advertising/mountain.svg
  media/img/mozorg/advertising/principle-advertising.svg
  media/img/mozorg/advertising/principle-community.svg
  media/img/mozorg/advertising/principle-privacy.svg
  media/img/mozorg/advertising/principle-safe.svg
  media/img/mozorg/advertising/product-fakespot-15x.png
  media/img/mozorg/advertising/product-fakespot.png
  media/img/mozorg/advertising/product-firefox-15x.png
  media/img/mozorg/advertising/product-firefox.png
  media/img/mozorg/advertising/product-mdn-15x.png
  media/img/mozorg/advertising/product-mdn.png
  media/img/mozorg/advertising/product-pocket-15x.png
  media/img/mozorg/advertising/product-pocket.png
Labels: Review: S

#15178 Update Makefile to check for `uv pip`
  Makefile
Labels: Backend

#15195 Waffles Part 1: Import config waffles to django waffles 🧇
  bedrock/base/management/commands/import_waffle_switches.py
  bedrock/firefox/firefox_details.py
  bedrock/firefox/templatetags/helpers.py
  bedrock/firefox/tests/test_firefox_details.py
  bedrock/mozorg/context_processors.py
  bedrock/mozorg/tests/test_context_processors.py
  bedrock/mozorg/tests/test_views.py
  bedrock/settings/base.py
  docs/funnelcake.rst
  docs/index.rst
  requirements/dev.txt
  requirements/prod.in
  requirements/prod.txt
Labels: Do Not Merge :warning:

#15234 Remove mozilla.social links and invite page
  bedrock/base/templates/includes/protocol/footer/footer-refresh.html
  bedrock/base/templates/includes/protocol/footer/footer.html
  bedrock/products/forms.py
  bedrock/products/redirects.py
  bedrock/products/templates/products/mozsocial/invite.html
  bedrock/products/urls.py
  bedrock/products/views.py
  l10n/configs/pontoon.toml
  l10n/en/products/mozsocial/invite.ftl
  media/css/products/mozsocial/invite.scss
  media/img/products/mozsocial/waitlist-tree-high-res.png
  media/img/products/mozsocial/waitlist-tree.png
  media/js/products/mozsocial/invite.es6.js
  media/static-bundles.json
  tests/functional/products/mozsocial/test_invite.py
  tests/pages/products/mozsocial/invite.py
  tests/redirects/map_globalconf.py
Labels: Review: XS

#15244 Fix app store url examples in the docs
  docs/attribution/0003-firefox-mobile.rst
Labels: P3, Needs Review, Review: µ

#15243 Decommission old VPN landing page template (Fixes #15226)
  bedrock/products/templates/products/vpn/includes/footer-subscribe.html
  bedrock/products/templates/products/vpn/includes/macros.html
  bedrock/products/templates/products/vpn/includes/pricing-basic.html
  bedrock/products/templates/products/vpn/includes/pricing-plus-relay.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templates/products/vpn/more/base-article.html
  bedrock/products/templates/products/vpn/platforms/platform-base.html
  bedrock/products/templates/products/vpn/pricing.html
  bedrock/products/tests/test_views.py
  bedrock/products/views.py
  l10n/configs/pontoon.toml
  l10n/en/products/vpn/landing.ftl
  l10n/en/products/vpn/shared.ftl
  media/css/products/vpn/components/hero.scss
  media/css/products/vpn/components/pricing-basic.scss
  media/css/products/vpn/components/pricing-plus-relay.scss
  media/css/products/vpn/landing.scss
  media/img/products/vpn/landing/vpn-cntwell-01-high-res.png
  media/img/products/vpn/landing/vpn-cntwell-01.png
  media/img/products/vpn/landing/vpn-cntwell-02-high-res.png
  media/img/products/vpn/landing/vpn-cntwell-02.png
  media/img/products/vpn/landing/vpn-cntwell-03-high-res.png
  media/img/products/vpn/landing/vpn-cntwell-03.png
  media/img/products/vpn/landing/vpn-cntwell-05-high-res.png
  media/img/products/vpn/landing/vpn-cntwell-05-v2-high-res.png
  media/img/products/vpn/landing/vpn-cntwell-05-v2.png
  media/img/products/vpn/landing/vpn-cntwell-05.png
  media/img/products/vpn/landing/vpn-cntwell-06-high-res.png
  media/img/products/vpn/landing/vpn-cntwell-06.png
  media/img/products/vpn/landing/vpn-hero-02-high-res.png
  media/img/products/vpn/landing/vpn-hero-02.png
  media/img/products/vpn/landing/vpn-hero-03-high-res.png
  media/img/products/vpn/landing/vpn-hero-03.png
  media/img/products/vpn/landing/vpn-hero-04-high-res.png
  media/img/products/vpn/landing/vpn-hero-04.png
  media/img/products/vpn/landing/vpn-hero-05-high-res.png
  media/img/products/vpn/landing/vpn-hero-05.png
  media/js/products/vpn/landing.js
  media/static-bundles.json
  tests/playwright/specs/products/vpn/vpn-landing-old.spec.js
  tests/playwright/specs/products/vpn/vpn-pricing-old.spec.js
Labels: P3, Review: XS

#15212 Moments page for Root Certification expiration (1 of 6)
  bedrock/firefox/templates/firefox/welcome/base.html
  bedrock/firefox/templates/firefox/welcome/page16.html
  bedrock/firefox/templates/firefox/welcome/page17/page17-a.html
  bedrock/firefox/templates/firefox/welcome/page17/page17-b.html
  bedrock/firefox/templates/firefox/welcome/page17/page17-c.html
  bedrock/firefox/templates/firefox/welcome/page18.html
  bedrock/firefox/templates/firefox/welcome/page19.html
  bedrock/firefox/urls.py
  media/css/firefox/welcome19.scss
  media/img/firefox/welcome/page16/firefox-wordmark-dark.svg
  media/img/firefox/welcome/page16/firefox-wordmark-light.svg
  media/img/firefox/welcome/page17/firefox-wordmark-dark.svg
  media/img/firefox/welcome/page17/firefox-wordmark-light.svg
  media/img/firefox/welcome/page19/fast.svg
  media/img/firefox/welcome/page19/private.svg
  media/img/firefox/welcome/page19/yours.svg
  media/static-bundles.json
Labels: Review: XS, Frontend

#15249 Decommission old VPN platform pages (Fixes #15245)
  bedrock/products/templates/products/vpn/platforms/android.html
  bedrock/products/templates/products/vpn/platforms/desktop.html
  bedrock/products/templates/products/vpn/platforms/ios.html
  bedrock/products/templates/products/vpn/platforms/ipad.html
  bedrock/products/templates/products/vpn/platforms/linux.html
  bedrock/products/templates/products/vpn/platforms/mac.html
  bedrock/products/templates/products/vpn/platforms/mobile.html
  bedrock/products/templates/products/vpn/platforms/platform-base.html
  bedrock/products/templates/products/vpn/platforms/v2/android.html
  bedrock/products/templates/products/vpn/platforms/v2/desktop.html
  bedrock/products/templates/products/vpn/platforms/v2/ios.html
  bedrock/products/templates/products/vpn/platforms/v2/linux.html
  bedrock/products/templates/products/vpn/platforms/v2/mac.html
  bedrock/products/templates/products/vpn/platforms/v2/mobile.html
  bedrock/products/templates/products/vpn/platforms/v2/windows.html
  bedrock/products/templates/products/vpn/platforms/windows.html
  bedrock/products/urls.py
  bedrock/products/views.py
  l10n/en/products/vpn/platforms/android.ftl
  l10n/en/products/vpn/platforms/desktop.ftl
  l10n/en/products/vpn/platforms/ios.ftl
  l10n/en/products/vpn/platforms/linux.ftl
  l10n/en/products/vpn/platforms/mac.ftl
  l10n/en/products/vpn/platforms/mobile.ftl
  l10n/en/products/vpn/platforms/windows.ftl
  media/img/products/vpn/platforms/vpn-cntwell-check-mark-high-res.png
  media/img/products/vpn/platforms/vpn-cntwell-check-mark.png
  media/img/products/vpn/platforms/vpn-cntwell-devices-high-res.png
  media/img/products/vpn/platforms/vpn-cntwell-devices.png
  media/img/products/vpn/platforms/vpn-cntwell-globe-high-res.png
  media/img/products/vpn/platforms/vpn-cntwell-globe.png
  media/img/products/vpn/platforms/vpn-cntwell-one-click-high-res.png
  media/img/products/vpn/platforms/vpn-cntwell-one-click.png
  media/img/products/vpn/platforms/vpn-cntwell-privacy-high-res.png
  media/img/products/vpn/platforms/vpn-cntwell-privacy-promise-high-res.png
  media/img/products/vpn/platforms/vpn-cntwell-privacy-promise.png
  media/img/products/vpn/platforms/vpn-cntwell-privacy.png
  media/img/products/vpn/platforms/vpn-cntwell-public-wifi-desktop-high-res.png
  media/img/products/vpn/platforms/vpn-cntwell-public-wifi-desktop.png
  media/img/products/vpn/platforms/vpn-cntwell-public-wifi-mobile-high-res.png
  media/img/products/vpn/platforms/vpn-cntwell-public-wifi-mobile.png
  media/img/products/vpn/platforms/vpn-cntwell-speed-guage-high-res.png
  media/img/products/vpn/platforms/vpn-cntwell-speed-guage.png
  media/img/products/vpn/platforms/vpn-hero-mobile-high-res.png
  media/img/products/vpn/platforms/vpn-hero-mobile.png
  media/static-bundles.json
Labels: P3, Review: XS

#14996 Remove fixed Fluent linter brand exclusions
  .github/l10n/linter_config.yml
Labels: Needs Review, Frontend

#15254 Update bug writing guidelines link on /contact page (Fixes bug 1923262)
  bedrock/mozorg/templates/mozorg/contact/contact-landing.html
Labels: P3, Needs Review, Review: µ

#15255 Prevent aria-hidden elements from receiving keyboard focus (Fixes #15137)
  bedrock/firefox/templates/firefox/challenge-the-default/includes/toggles.html
  bedrock/firefox/templates/firefox/challenge-the-default/landing-base.html
Labels: P3, Needs Review, Review: µ

#15241 H1 2024 Transparency Report
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2024.html
  bedrock/mozorg/urls.py
Labels: Review: XS, Frontend

#15260 Added ESR link and updated primary link in Moments Page
  bedrock/firefox/templates/firefox/welcome/page19.html
  media/css/firefox/welcome19.scss
  media/js/firefox/welcome/welcome19.js
  media/static-bundles.json
Labels: Review: XS, Frontend

#15264 Remove superfluous templates (Fixes #15263)
  bedrock/products/templates/products/mozsocial/invite.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templates/products/vpn/pricing.html
Labels: P3, Review: µ

#14936 Simplify WNP templates
  bedrock/firefox/templates/firefox/developer/firstrun.html
  bedrock/firefox/templates/firefox/nightly/whatsnew.html
  bedrock/firefox/templates/firefox/whatsnew/base.html
  bedrock/firefox/templates/firefox/whatsnew/index-thanks.html
  bedrock/firefox/templates/firefox/whatsnew/index.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx125-eu.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx125-na.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx126-eu.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx126-na.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx126beta-de.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx126beta-en-CA.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx126beta-en-GB.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx126beta-en-US.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx126beta-fr.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx127-eu.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx127-na.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx128-eu-addons.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx128-eu-donate.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx128-na.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx129-eu.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx129-na.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx130.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx131-eu.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx131-na.html
  media/css/firefox/whatsnew/includes/_dark-mode.scss
  media/css/firefox/whatsnew/includes/_header.scss
  media/css/firefox/whatsnew/whatsnew-nightly.scss
  media/fonts/whatsnew114/Metropolis-BoldItalic.woff
  media/fonts/whatsnew114/Metropolis-BoldItalic.woff2
  media/img/firefox/whatsnew/icon-green-check.svg
  media/img/firefox/whatsnew/logo-word-hor-white.svg
  media/img/firefox/whatsnew/logo-word-hor.svg
  media/img/firefox/whatsnew/nightly-background.svg
  media/img/firefox/whatsnew/qrcode-mozillaonline.png
Labels: P3, Needs Review, Frontend

#15222 update nav to remove existing nav styles
  bedrock/base/templates/base-protocol.html
  bedrock/base/templates/includes/protocol/navigation/menus-refresh/about-us.html
  bedrock/base/templates/includes/protocol/navigation/menus-refresh/firefox.html
  bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html
  bedrock/base/templates/includes/protocol/navigation/navigation-refresh.html
  media/css/m24/components/navigation-refresh.scss
  media/js/base/protocol/init-m24-navigation.js
  media/js/base/protocol/m24-menu.js
  media/js/base/protocol/m24-navigation.js
  media/static-bundles.json
Labels: Frontend, Refresh 🦖

#15277 Add Fluent strings for VPN wave vii expansion (issue #15262)
  l10n/en/products/vpn/pricing-2023.ftl
Labels: P1, Needs Review, Review: µ

#15280 Refresh: update font names
  media/css/m24/vars/fonts.scss
  media/css/protocol/protocol-mozilla-2024.scss
  media/fonts/m24/mozilla-headline/MozillaHeadline-Bold.woff
  media/fonts/m24/mozilla-headline/MozillaHeadline-Bold.woff2
  media/fonts/m24/mozilla-headline/MozillaHeadline-Regular.woff
  media/fonts/m24/mozilla-headline/MozillaHeadline-Regular.woff2
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-Bold.woff
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-Bold.woff2
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-BoldIt.woff
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-BoldIt.woff2
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-Italic.woff
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-Italic.woff2
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-Medium.woff
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-Medium.woff2
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-MediumIt.woff
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-MediumIt.woff2
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-Regular.woff
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-Regular.woff2
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-SemiBold.woff
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-SemiBold.woff2
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-SemiBoldIt.woff
  media/fonts/m24/mozilla-sans-text/MozillaSansTextBETA-SemiBoldIt.woff2
  media/fonts/m24/mozilla-semi-slab/MozillaSemiSlab-Bold.woff
  media/fonts/m24/mozilla-semi-slab/MozillaSemiSlab-Bold.woff2
  media/fonts/m24/mozilla-semi-slab/MozillaSemiSlab-BoldIt.woff
  media/fonts/m24/mozilla-semi-slab/MozillaSemiSlab-BoldIt.woff2
  media/fonts/m24/mozilla-semi-slab/MozillaSemiSlab-Italic.woff
  media/fonts/m24/mozilla-semi-slab/MozillaSemiSlab-Italic.woff2
  media/fonts/m24/mozilla-semi-slab/MozillaSemiSlab-Regular.woff
  media/fonts/m24/mozilla-semi-slab/MozillaSemiSlab-Regular.woff2
  media/fonts/m24/mozilla-semi-slab/MozillaSemiSlab-SemiBold.woff
  media/fonts/m24/mozilla-semi-slab/MozillaSemiSlab-SemiBold.woff2
  media/fonts/m24/mozilla-semi-slab/MozillaSemiSlab-SemiBoldIt.woff
  media/fonts/m24/mozilla-semi-slab/MozillaSemiSlab-SemiBoldIt.woff2
  media/fonts/m24/mozilla-text/MozillaText-Bold.woff
  media/fonts/m24/mozilla-text/MozillaText-Bold.woff2
  media/fonts/m24/mozilla-text/MozillaText-BoldItalic.woff
  media/fonts/m24/mozilla-text/MozillaText-BoldItalic.woff2
  media/fonts/m24/mozilla-text/MozillaText-Italic.woff
  media/fonts/m24/mozilla-text/MozillaText-Italic.woff2
  media/fonts/m24/mozilla-text/MozillaText-Regular.woff
  media/fonts/m24/mozilla-text/MozillaText-Regular.woff2
  media/fonts/m24/mozilla-text/MozillaText-SemiBold.woff
  media/fonts/m24/mozilla-text/MozillaText-SemiBold.woff2
  media/fonts/m24/mozilla-text/MozillaText-SemiBoldItalic.woff
  media/fonts/m24/mozilla-text/MozillaText-SemiBoldItalic.woff2
Labels: Needs Review, Review: XS

#15170 Refactor vars files to not out put CSS vars in files multiple times
  bedrock/base/templates/base-protocol-mozilla.html
  bedrock/base/templates/base-protocol.html
  bedrock/firefox/templates/firefox/new/basic/base.html
  bedrock/firefox/templates/firefox/new/desktop/base.html
  bedrock/mozorg/templates/mozorg/about/index-m24.html
  bedrock/mozorg/templates/mozorg/home/home-m24.html
  media/css/m24/base.scss
  media/css/m24/grid.scss
  media/css/m24/root.scss
  media/css/m24/theme.scss
  media/css/m24/vars/_animation.scss
  media/css/m24/vars/_color.scss
  media/css/m24/vars/_fonts.scss
  media/css/m24/vars/_grid.scss
  media/css/m24/vars/_spacing.scss
  media/css/m24/vars/_text.scss
  media/css/m24/vars/fonts.scss
  media/css/m24/vars/spacing.scss
  media/css/m24/vars/text.scss
  media/static-bundles.json
Labels: Needs Review, Review: XS, Frontend, Refresh 🦖

#15273 Remove obsolete strings for September 2024 + old navigation files
  bedrock/base/templates/includes/protocol/navigation/menus/firefox.html
  bedrock/base/templates/includes/protocol/navigation/menus/innovation.html
  bedrock/base/templates/includes/protocol/navigation/menus/products.html
  bedrock/base/templates/includes/protocol/navigation/menus/whoweare.html
  bedrock/firefox/templates/firefox/includes/desktop-platform-sub-nav.html
  bedrock/firefox/templates/firefox/releases/notes.html
  bedrock/mozorg/templates/mozorg/includes/mozilla-account-promo.html
  bedrock/privacy/templates/privacy/faq.html
  l10n/en/mozilla-account-promo.ftl
  l10n/en/navigation.ftl
  l10n/en/navigation_v2.ftl
  l10n/en/privacy/faq.ftl
Labels: Needs Review, Review: XS, Frontend

#15294 Update Nothing Personal page app store URLs [fix #15274]
  bedrock/firefox/templates/firefox/nothing-personal/index.html
Labels: Needs Review, Review: XS

#15290 Remove VPN + Relay bundle code (Fixes #15288)
  bedrock/products/templates/products/vpn/landing-refresh.html
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  bedrock/products/tests/test_views.py
  bedrock/products/views.py
  bedrock/settings/base.py
  docs/mozilla-accounts.rst
Labels: P3, Needs Review, Review: XS

#15287 Add URL redirector for VPN mobile app store links (Fixes #15286)
  bedrock/firefox/redirects.py
  bedrock/products/redirects.py
  bedrock/settings/appstores.py
  bedrock/settings/base.py
  tests/redirects/map_globalconf.py
Labels: P1, Needs Review, Review: XS

#15279 Static nav for reduced motion fixes (#15275)
  media/css/m24/components/navigation-refresh.scss
Labels: Review: µ, Frontend, Refresh 🦖

#15200 Fix m24-logo in 2024 style for old footer
  media/css/protocol/protocol-mozilla-2024.scss
Labels: Needs Review, Frontend, Refresh 🦖

#15177 Fix new logo sizing in base-error
  media/css/protocol/protocol-mozilla.scss
Labels: Needs Review, Frontend, Refresh 🦖

#15313 Refresh: consolidate under a single waffle switch [fix #15289]
  bedrock/base/templates/base-error.html
  bedrock/base/templates/base-protocol-mozilla.html
  bedrock/base/templates/base-protocol.html
  bedrock/base/templates/includes/protocol/footer/footer.html
  bedrock/base/templates/includes/protocol/navigation/navigation.html
  bedrock/firefox/templates/firefox/new/basic/base.html
  bedrock/firefox/templates/firefox/new/desktop/base.html
  bedrock/mozorg/views.py
Labels: Review: XS, Refresh 🦖

#15314 VPN market expansion (Fixes #15262)
  bedrock/base/templates/macros.html
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/products/templates/products/vpn/download.html
  bedrock/products/templates/products/vpn/includes/mobile-subscribe.html
  bedrock/products/templates/products/vpn/landing-refresh.html
  bedrock/products/templates/products/vpn/pricing-refresh.html
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  bedrock/products/tests/test_views.py
  bedrock/products/views.py
  bedrock/settings/base.py
  media/css/products/vpn/pricing-refresh.scss
  media/img/products/vpn/landing-refresh/devices.svg
  media/img/products/vpn/landing-refresh/icons/info.svg
  media/img/products/vpn/landing-refresh/qrcode-background.svg
  media/js/base/datalayer-productdownload.es6.js
  tests/unit/spec/base/datalayer-productdownload.js
Labels: P1, Review: S

#15197 Add Fx News one-click-subscribe page (Fixes #15142)
  bedrock/newsletter/templates/newsletter/firefox-confirm.html
  bedrock/newsletter/urls.py
  bedrock/newsletter/views.py
  media/css/newsletter/newsletter-firefox-confirm.scss
  media/js/newsletter/confirm-init.es6.js
  media/js/newsletter/confirm.es6.js
  media/static-bundles.json
  tests/unit/spec/newsletter/confirm.js
Labels: P2, Needs Review, Review: XS

#15320 Prevent aria-hidden button receiving focus (#15137)
  bedrock/firefox/templates/firefox/challenge-the-default/includes/wednesday.html
Labels: P3, Needs Review, Review: µ

#15325 Prevent showing guarantee copy for VPN mobile subscription countries (Fixes #15262)
  bedrock/products/templates/products/vpn/includes/macros.html
  bedrock/products/templates/products/vpn/more/base-article.html
  bedrock/products/templates/products/vpn/platforms/platform-base.html
  bedrock/products/templates/products/vpn/resource-center/landing.html
  bedrock/products/views.py
  bedrock/settings/base.py
Labels: P1, Needs Review, Review: XS

#15321 Expand a11y test coverage (#14773)
  tests/playwright/specs/a11y/includes/urls.js
  tests/playwright/specs/a11y/pages.spec.js
Labels: P3, Needs Review, Review: µ

#15329 Update VPN supported landuages (Fixes #15326)
  bedrock/settings/base.py
Labels: P2, Review: µ

#15332 Show Google Play Store CTA when on an iOS device in Android only country (Fixes #15328)
  bedrock/products/templates/products/vpn/includes/mobile-subscribe.html
  l10n/en/products/vpn/pricing-2023.ftl
Labels: P1, Needs Review, Review: XS

#15333 Fix Andriod link on Nothing Personal page [#15274]
  bedrock/firefox/templates/firefox/nothing-personal/index.html
Labels: Bug :bug:, Needs Review, Review: µ

#15319 Add remaining Moments Pages for Root Certification update
  bedrock/firefox/templates/firefox/welcome/page19.html
  bedrock/firefox/templates/firefox/welcome/page20.html
  bedrock/firefox/templates/firefox/welcome/page21.html
  bedrock/firefox/templates/firefox/welcome/page22.html
  bedrock/firefox/templates/firefox/welcome/page23.html
  bedrock/firefox/templates/firefox/welcome/page24.html
  bedrock/firefox/urls.py
  l10n/en/firefox/welcome/page20-21.ftl
  l10n/en/firefox/welcome/page22.ftl
  l10n/en/firefox/welcome/page23.ftl
  l10n/en/firefox/welcome/page24.ftl
  media/css/firefox/welcome19-to-24.scss
  media/img/firefox/welcome/page20-21/add-ons.svg
  media/img/firefox/welcome/page20-21/back-up.svg
  media/img/firefox/welcome/page20-21/community.svg
  media/img/firefox/welcome/root-ceritification-alert.svg
  media/js/firefox/welcome/welcome19-to-24.js
  media/static-bundles.json
Labels: Review: S

#15236 Migrate VPN resource center to Wagtail (#14860)
  bedrock/cms/decorators.py
  bedrock/cms/models/pages.py
  bedrock/mozorg/migrations/0004_alter_leadershippage_leadership_sections.py
  bedrock/mozorg/templates/mozorg/cms/about/leadership.html
  bedrock/products/migrations/0001_initial.py
  bedrock/products/migrations/0002_vpncalltoactionsnippet_locale_and_more.py
  bedrock/products/migrations/0003_alter_vpncalltoactionsnippet_options.py
  bedrock/products/migrations/__init__.py
  bedrock/products/models.py
  bedrock/products/templates/products/vpn/cms/resource-center/base.html
  bedrock/products/templates/products/vpn/cms/resource-center/detail.html
  bedrock/products/templates/products/vpn/cms/resource-center/includes/macros.html
  bedrock/products/templates/products/vpn/cms/resource-center/includes/voting-widget.html
  bedrock/products/templates/products/vpn/cms/resource-center/index.html
  bedrock/products/templates/products/vpn/cms/snippets/call_to_action.html
  bedrock/products/templates/products/vpn/cms/snippets/call_to_action_save.html
  bedrock/products/tests/__init__.py
  bedrock/products/tests/factories.py
  bedrock/products/tests/test_models.py
  bedrock/products/urls.py
  bedrock/settings/base.py
  media/css/cms/rich-text.scss
  media/css/products/vpn/resource-center.scss
  requirements/dev.txt
  requirements/prod.in
  requirements/prod.txt
Labels: P2, Review: S

#15193 Add French transcreated content for edit PDF feature
  bedrock/firefox/templates/firefox/features/pdf-complete-fr.html
  bedrock/firefox/templates/firefox/features/pdf-editor-fr.html
  bedrock/firefox/templates/firefox/features/pdf-editor.html
  bedrock/firefox/templates/firefox/features/pdf-free-fr.html
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  media/css/firefox/features/article.scss
  media/img/firefox/features/edit-pdf/edit-pdf-alt-text-high-res.png
  media/img/firefox/features/edit-pdf/edit-pdf-alt-text.png
  media/img/firefox/features/edit-pdf/edit-pdf-draw-high-res.png
  media/img/firefox/features/edit-pdf/edit-pdf-draw.png
  media/img/firefox/features/edit-pdf/edit-pdf-highlight-high-res.png
  media/img/firefox/features/edit-pdf/edit-pdf-highlight.png
  media/img/firefox/features/edit-pdf/edit-pdf-text-high-res.png
  media/img/firefox/features/edit-pdf/edit-pdf-text.png
  media/img/firefox/features/edit-pdf/fr-edit-pdf-dessin-high-res.png
  media/img/firefox/features/edit-pdf/fr-edit-pdf-dessin.png
  media/img/firefox/features/edit-pdf/fr-edit-pdf-modifier-high-res.png
  media/img/firefox/features/edit-pdf/fr-edit-pdf-modifier.png
  media/img/firefox/features/edit-pdf/fr-edit-pdf-ouvrir-high-res.png
  media/img/firefox/features/edit-pdf/fr-edit-pdf-ouvrir.png
  media/img/firefox/features/edit-pdf/fr-edit-pdf-sauvegarder-high-res.png
  media/img/firefox/features/edit-pdf/fr-edit-pdf-sauvegarder.png
  media/img/firefox/features/edit-pdf/fr-edit-pdf-surligner-high-res.png
  media/img/firefox/features/edit-pdf/fr-edit-pdf-surligner.png
  media/img/firefox/features/edit-pdf/fr-edit-pdf-texte-high-res.png
  media/img/firefox/features/edit-pdf/fr-edit-pdf-texte.png
Labels: P1, Review: XS, Frontend

#15356 VPN mobile subscription misc fixes (Fixes #15328)
  bedrock/products/templates/products/vpn/includes/mobile-subscribe.html
Labels: P1, Needs Review, Review: XS

#15353 Refresh: Separate nav and footer styles from protocol base
  bedrock/base/templates/base-protocol-mozilla.html
  bedrock/base/templates/base-protocol.html
  bedrock/firefox/templates/firefox/new/basic/base.html
  bedrock/firefox/templates/firefox/new/desktop/base.html
  media/css/m24/components/footer-refresh.scss
  media/css/m24/navigation-and-footer.scss
  media/css/protocol/components/_footer.scss
  media/css/protocol/navigation-and-footer.scss
  media/css/protocol/protocol-firefox.scss
  media/css/protocol/protocol-mozilla-2024.scss
  media/css/protocol/protocol-mozilla.scss
  media/static-bundles.json
Labels: Needs Review, Review: XS, Refresh 🦖

#15369 Add paths to legacy nav and footer styles [#15120]
  media/css/protocol/navigation-and-footer.scss
Labels: Bug :bug:, Needs Review, Review: µ

#15366 String fix for welcome 23 [#15162]
  l10n/en/firefox/welcome/page23.ftl
Labels: Needs Review, Review: µ

#15361 [Refresh] Navigation positioning fix
  bedrock/base/templates/includes/protocol/navigation/navigation-refresh.html
  media/css/m24/components/navigation-refresh.scss
Labels: P2, Review: XS, Frontend, Refresh 🦖

#15272 Refresh: Add CTA pencil banner
  bedrock/base/templates/includes/protocol/navigation/navigation.html
  bedrock/base/templates/includes/protocol/navigation/pencil-banner.html
  bedrock/settings/base.py
  l10n/en/banners/m24-pencil-banner.ftl
  media/css/m24/components/navigation-refresh.scss
  media/css/m24/components/pencil-banner.scss
  media/css/m24/navigation-and-footer.scss
  media/static-bundles.json
Labels: Review: XS, Frontend

#15384 add wnp 132 na+eu pages (fix #15295)
  bedrock/firefox/templates/firefox/whatsnew/includes/fx132/video.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx132-eu.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx132-na.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-132.scss
  media/img/firefox/whatsnew/whatsnew132/firefox-20th.png
  media/img/firefox/whatsnew/whatsnew132/sticker-chat.svg
  media/img/firefox/whatsnew/whatsnew132/sticker-fox.svg
  media/img/firefox/whatsnew/whatsnew132/sticker-happy.svg
  media/img/firefox/whatsnew/whatsnew132/sticker-heart.svg
  media/img/firefox/whatsnew/whatsnew132/video-high-res.jpg
  media/img/firefox/whatsnew/whatsnew132/video.jpg
  media/js/firefox/whatsnew/whatsnew-132.js
  media/static-bundles.json
Labels: P1, Needs Review, Review: XS

#15396 Updated video image on WNP132 [#15295]
  media/img/firefox/whatsnew/whatsnew132/video-high-res.jpg
  media/img/firefox/whatsnew/whatsnew132/video.jpg
Labels: Needs Review, Review: µ

#15392 Add data-cta-name to documentation
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx132-eu.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx132-na.html
  docs/attribution/0001-analytics.rst
Labels: Needs Review, Documentation :memo:, Review: µ, Analytics 📈

#15408 VPN landing pages locale fix
  bedrock/products/views.py
  l10n/en/products/vpn/landing.ftl
Labels: P2, Needs Review, Review: XS

#15362 update about page hero and media section (fix #15302)
  bedrock/mozorg/templates/mozorg/about/includes/m24/hero.html
  media/css/m24/copy.scss
  media/css/m24/hero.scss
  media/img/icons/m24-small/icon-bell.svg
  media/img/icons/m24-small/icon-dollar.svg
  media/img/icons/m24-small/icon-glasses.svg
  media/img/icons/m24-small/icon-pencil.svg
  media/img/m24/about/about-hero-high-res.jpeg
  media/img/m24/about/about-hero.jpeg
Labels: Frontend, Refresh 🦖

#15414 Update product brand names in nav and on home page (Fixes #15351)
  bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/products.html
  l10n/en/navigation_refresh.ftl
Labels: P2, Needs Review, Review: µ, Refresh 🦖
