Repository mozilla/bedrock, pull requests merged in 2024-06, with the labels that each got.

#14639 Bump Webpack and related dependencies
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: XS

#14619 Add what’s new page for Firefox 127 [fix #14615]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx127-eu.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx127-na.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-127-eu.scss
  media/css/firefox/whatsnew/whatsnew-127-na.scss
  media/img/firefox/whatsnew/whatsnew127-eu/pip-cook.svg
  media/img/firefox/whatsnew/whatsnew127-eu/pip-entertain.svg
  media/img/firefox/whatsnew/whatsnew127-eu/pip-icon.svg
  media/img/firefox/whatsnew/whatsnew127-eu/pip-lecture.svg
  media/img/firefox/whatsnew/whatsnew127-eu/video-poster.jpg
  media/img/firefox/whatsnew/whatsnew127-na/hand.svg
  media/img/firefox/whatsnew/whatsnew127-na/join-community-high-res.jpg
  media/img/firefox/whatsnew/whatsnew127-na/join-community.jpg
  media/img/firefox/whatsnew/whatsnew127-na/puzzle.svg
  media/img/firefox/whatsnew/whatsnew127-na/rocket.svg
  media/js/firefox/whatsnew/whatsnew-127-eu.js
  media/js/firefox/whatsnew/whatsnew-127-na.js
  media/static-bundles.json
Labels: Review: S

#14648 Remove Mozilla Hubs legal pages (Fixes #14647)
  bedrock/legal/redirects.py
  bedrock/legal/templates/legal/index.html
  bedrock/legal/templates/legal/terms/hubs.html
  bedrock/legal/urls.py
  bedrock/privacy/redirects.py
  bedrock/privacy/templates/privacy/archive/index.html
  bedrock/privacy/templates/privacy/archive/mozilla-hubs-notice-2024-06.html
  bedrock/privacy/templates/privacy/archive/mozilla-hubs-tos-2024-06.html
  bedrock/privacy/templates/privacy/base-protocol.html
  bedrock/privacy/templates/privacy/notices/hubs.html
  bedrock/privacy/urls.py
  bedrock/privacy/views.py
  l10n/en/brands.ftl
  l10n/en/mozorg/about/legal.ftl
  l10n/en/privacy/index.ftl
  tests/redirects/map_globalconf.py
Labels: P2, Needs Review, Review: XS

#14658 Update Sentry JS client to v8.8.0
  media/js/base/sentry-consent.es6.js
  package-lock.json
  package.json
  webpack.config.js
Labels: P3, Needs Review, Review: XS

#14663 Update copy in `/privacy/faq` page
  bedrock/privacy/templates/privacy/faq.html
  l10n/en/privacy/faq.ftl
Labels: Review: XS

#14677 Add in setting to control whether or not Wagtail's page-serving logic is enabled
  bedrock/cms/tests/test_models.py
  bedrock/cms/tests/test_rendering.py
  bedrock/settings/base.py
  bedrock/urls/mozorg_mode.py
Labels: Do Not Merge :warning:

#14682 Filter out non-useful events in Sentry (Fixes #14674)
  media/js/base/sentry-consent.es6.js
Labels: P3, Needs Review, Review: µ

#14683 Run JS tests in CI using ubuntu-latest
  .github/workflows/pull_request_tests.yml
Labels: P3, Needs Review, Review: µ

#14685 Remove Mozilla account CTA Promo
  bedrock/firefox/templates/firefox/browsers/mobile/index.html
  bedrock/firefox/templates/firefox/index.html
  bedrock/mozorg/templates/mozorg/includes/mozilla-account-cta-promo.html
  bedrock/mozorg/templates/mozorg/includes/mozilla-account-promo.html
  bedrock/products/templates/products/landing.html
  l10n/en/mozilla-account-promo.ftl
Labels: Needs Review, Review: XS

#14644 Update front-end linters and dependencies
  .pre-commit-config.yaml
  eslint.config.js
  media/css/firefox/installer-help.scss
  media/css/firefox/releasenotes.scss
  media/css/firefox/switch.scss
  media/css/mozorg/rise25/components/promote.scss
  media/css/pocket/includes/_platform-footer.scss
  media/css/products/vpn/components/pricing-plus-relay.scss
  media/css/products/vpn/landing.scss
  media/js/base/error-pages.js
  media/js/base/search-params.js
  media/js/base/stub-attribution/stub-attribution.js
  media/js/firefox/whatsnew/whatsnew-123-na.js
  package-lock.json
  package.json
  tests/unit/spec/base/fxa-form.js
  tests/unit/spec/base/fxa-link.js
  tests/unit/spec/base/stub-attribution/stub-attribution.js
Labels: P3, Needs Review, Review: XS

#14686 Bump Glean.js to v5.0.2
  package-lock.json
  package.json
  requirements/dev.txt
  requirements/prod.in
  requirements/prod.txt
Labels: P3, Needs Review, Review: µ

#14690 Remove superfluous Glean metrics
  bedrock/base/templates/404.html
  glean/metrics.yaml
  media/js/glean/page.es6.js
  media/js/glean/utils.es6.js
  tests/unit/spec/glean/page.js
  tests/unit/spec/glean/utils.js
Labels: P3, Needs Review, Review: XS

#14669 Point links away from `firefox.privacy.*` subpages
  bedrock/firefox/templates/firefox/more.html
  bedrock/firefox/templates/firefox/more/misinformation.html
  bedrock/products/templates/products/vpn/more/when-to-use.html
  l10n/en/firefox/more.ftl
  l10n/en/firefox/more/misinformation.ftl
  l10n/en/products/vpn/more/when-to-use-a-vpn.ftl
  media/img/firefox/more/little-book-of-privacy.jpg
  media/img/firefox/more/passwords.png
Labels: Needs Review

#14698 add alt text for images on leadership page
  bedrock/mozorg/templates/mozorg/about/leadership/includes/boards.html
  bedrock/mozorg/templates/mozorg/about/leadership/includes/executive.html
  bedrock/mozorg/templates/mozorg/about/leadership/includes/mofo.html
  bedrock/mozorg/templates/mozorg/about/leadership/includes/senior.html
Labels: P3, Needs Review, Review: µ

#14709 Fix untranslated fallback strings
  lib/l10n_utils/fluent.py
Labels: Needs Review

#14646 Add NPM script for debugging Jasmine tests (Fixes #14645)
  media/js/base/mozilla-utils.js
  package.json
  tests/unit/spec/base/datalayer-begincheckout.js
  tests/unit/spec/base/mozilla-utils.js
  tests/unit/spec/newsletter/management.js
Labels: P3, Needs Review, Review: XS

#14697 Firefox download to install smoke test (Fixes #14696)
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/views.py
  media/js/firefox/new/desktop/thanks-smoke-test.es6.js
  media/static-bundles.json
Labels: P2, Needs Review, Review: XS

#14710 Bump node Docker image to 20.14.0-slim (Fixes #14705)
  Dockerfile
Labels: P3, Needs Review, Review: XS

#14730 Dep bump, driven by urllib3 security patch - also picks up other subdeps
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.txt
Labels: Backend

#14722 Set all VPN pages to use subnav-refresh.html (Fixes #14712)
  bedrock/products/templates/products/vpn/base.html
  bedrock/products/templates/products/vpn/features.html
  bedrock/products/templates/products/vpn/includes/subnav.html
  bedrock/products/templates/products/vpn/landing-refresh.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templates/products/vpn/pricing-refresh.html
  bedrock/products/templates/products/vpn/pricing.html
  bedrock/products/templates/products/vpn/resource-center/landing.html
Labels: P3, Needs Review, Review: µ, Frontend

#14743 Add configurability for DB connection params;
  bedrock/settings/base.py
Labels: Backend
