Repository mozilla/bedrock, pull requests merged in 2024-03, with the labels that each got.

#14237 Replace Adjust QRCodes (Fixes #14172)
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/browsers/mobile/get-app.html
  bedrock/firefox/templates/firefox/browsers/mobile/includes/s2d-android.html
  bedrock/firefox/templates/firefox/browsers/mobile/includes/s2d-focus.html
  bedrock/firefox/templates/firefox/browsers/mobile/includes/s2d-ios.html
  bedrock/firefox/templates/firefox/welcome/page17/page17-b.html
  bedrock/firefox/templates/firefox/welcome/page4.html
  bedrock/firefox/templates/firefox/welcome/page6.html
  bedrock/firefox/templates/firefox/whatsnew/includes/fx115-eu-vpn/laptop.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx115-eu-vpn/mobile.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx115-eu-vpn/vpn-header.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx115-eu/qr-de.html
  bedrock/firefox/templates/firefox/whatsnew/includes/fx115-eu/qr-fr.html
  bedrock/firefox/templates/firefox/whatsnew/includes/fx115-eu/qr-uk.html
  bedrock/firefox/templates/firefox/whatsnew/includes/fx115/addons.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx118/arrow-blue.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx118/arrow-white.svg
  bedrock/firefox/templates/firefox/whatsnew/includes/fx118/translate-icon.svg
  bedrock/firefox/templates/firefox/whatsnew/index-account.html
  bedrock/firefox/templates/firefox/whatsnew/index.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx120-na.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx121.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx122-eu.html
  docs/redirects.rst
  media/img/firefox/browsers/mobile/qr-firefox.png
  media/img/firefox/browsers/mobile/qr-focus.png
  media/img/firefox/browsers/mobile/qr-klar.png
  media/img/firefox/browsers/mobile/qr-variation.svg
  media/img/firefox/browsers/mobile/qrcode-firefox-browsers-mobile-android.png
  media/img/firefox/browsers/mobile/qrcode-firefox-browsers-mobile-focus.png
  media/img/firefox/browsers/mobile/qrcode-firefox-browsers-mobile-get-app.png
  media/img/firefox/browsers/mobile/qrcode-firefox-browsers-mobile-ios.png
  media/img/firefox/browsers/mobile/qrcode-firefox-browsers-mobile-klar.png
  media/img/firefox/welcome/qrcode-firefox-welcome-4.png
  media/img/firefox/welcome/qrcode-firefox-welcome-6.png
  media/img/firefox/welcome/welcome-qr-firefox.png
  media/img/firefox/welcome/welcome-qr-lockwise.png
  media/img/firefox/whatsnew/qrcode-firefox-whatsnew.png
  media/img/firefox/whatsnew/qrcode-fxa.png
  media/img/firefox/whatsnew/qrcode.png
  media/img/firefox/whatsnew/whatsnew120-na/qr-code.svg
  media/img/firefox/whatsnew/whatsnew120-na/qr-novideo.png
  media/img/firefox/whatsnew/whatsnew120-na/qr-video.png
  media/img/firefox/whatsnew/whatsnew122/qrcode-firefox-whatsnew-122.png
  media/img/l10n/de/firefox/welcome/page17/qr-code.png
  media/img/l10n/de/firefox/wnp-121/presents-and-qr.svg
  media/img/l10n/de/firefox/wnp-121/qrcode-firefox-whatsnew-121.svg
  media/img/l10n/en-GB/firefox/wnp-121/presents-and-qr.svg
  media/img/l10n/en-GB/firefox/wnp-121/qrcode-firefox-whatsnew-121.svg
  media/img/l10n/en-US/firefox/welcome/page17/qr-code.png
  media/img/l10n/en-US/firefox/wnp-121/presents-and-qr.svg
  media/img/l10n/en-US/firefox/wnp-121/qrcode-firefox-whatsnew-121.svg
  media/img/l10n/fr/firefox/welcome/page17/qr-code.png
  media/img/l10n/fr/firefox/wnp-121/presents-and-qr.svg
  media/img/l10n/fr/firefox/wnp-121/qrcode-firefox-whatsnew-121.svg
  media/js/firefox/whatsnew/whatsnew-120-experiment-na.es6.js
  media/static-bundles.json
Labels: P2, Needs Review, Review: S

#14293 Leadership: remove McKinley, Murillo, and Samiee [fix #14292]
  bedrock/mozorg/templates/mozorg/about/leadership/includes/senior.html
  media/img/mozorg/about/leadership/dan-mckinley-high-res.jpg
  media/img/mozorg/about/leadership/dan-mckinley.jpg
  media/img/mozorg/about/leadership/leyla-samiee-high-res.jpg
  media/img/mozorg/about/leadership/leyla-samiee.jpg
  media/img/mozorg/about/leadership/oscar-murillo-high-res.jpg
  media/img/mozorg/about/leadership/oscar-murillo.jpg
Labels: Review: µ

#14265 Move `/firefox/accounts` URL to `/account`
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/browsers/compare/brave.html
  bedrock/firefox/templates/firefox/browsers/compare/edge.html
  bedrock/firefox/templates/firefox/browsers/compare/safari.html
  bedrock/firefox/templates/firefox/features/password-manager.html
  bedrock/firefox/templates/firefox/features/sync.html
  bedrock/firefox/templates/firefox/features/tips/tips.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/privacy/products.html
  bedrock/firefox/templates/firefox/set-as-default/thanks.html
  bedrock/firefox/templates/firefox/welcome/base.html
  bedrock/firefox/templates/firefox/whatsnew/index-account.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx122-eu.html
  bedrock/firefox/urls.py
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/account.html
  bedrock/mozorg/templates/mozorg/includes/mozilla-account-cta-promo.html
  bedrock/mozorg/templates/mozorg/includes/mozilla-account-form-promo.html
  bedrock/mozorg/urls.py
  bedrock/newsletter/templates/newsletter/management.html
  bedrock/privacy/templates/privacy/faq.html
  l10n/en/firefox/accounts.ftl
  l10n/en/firefox/set-as-default/thanks.ftl
  l10n/en/navigation.ftl
  media/css/firefox/set-as-default/thanks.scss
  media/css/mozorg/account.scss
  media/img/firefox/set-as-default/thanks/firefox-logomark-black.svg
  media/img/firefox/set-as-default/thanks/mozilla-logo.svg
  media/js/mozorg/account.es6.js
  media/static-bundles.json
  tests/functional/test_account.py
  tests/pages/account.py
  tests/redirects/map_globalconf.py
Labels: Needs Review, Review: S

#14300 Update Firefox speed content [fix #14298]
  bedrock/firefox/templates/firefox/browsers/compare/index.html
  bedrock/firefox/templates/firefox/features/fast-2024.html
  bedrock/firefox/templates/firefox/features/index.html
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  l10n/en/brands.ftl
  l10n/en/firefox/browsers/compare/index.ftl
  l10n/en/firefox/browsers/compare/shared.ftl
  l10n/en/firefox/features/fast-2024.ftl
  l10n/en/firefox/features/index-2023.ftl
  media/css/firefox/compare/compare.scss
Labels: Needs Review, Review: XS

#14301 Add WNP 124 (Fixes #14296)
  bedrock/firefox/templates/firefox/whatsnew/includes/release-notes.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-de-voices-share.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-de-voices-video.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-eu-compare.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-na-static.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-na-video.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  l10n/en/firefox/whatsnew/whatsnew.ftl
  media/css/firefox/whatsnew/whatsnew-124-eu-compare.scss
  media/css/firefox/whatsnew/whatsnew-124-eu-voices.scss
  media/css/firefox/whatsnew/whatsnew-124-na.scss
  media/img/firefox/whatsnew/whatsnew124-eu/ctd-voices-thumbnail-1200.jpg
  media/img/firefox/whatsnew/whatsnew124-eu/ctd-voices-thumbnail-600.jpg
  media/img/firefox/whatsnew/whatsnew124-eu/ctd-voices-thumbnail-800.jpg
  media/img/firefox/whatsnew/whatsnew124-na/monitor-plus-static-1200.jpg
  media/img/firefox/whatsnew/whatsnew124-na/monitor-plus-static-600.jpg
  media/img/firefox/whatsnew/whatsnew124-na/monitor-plus-thumbnail-1200.png
  media/img/firefox/whatsnew/whatsnew124-na/monitor-plus-thumbnail-600.png
  media/img/icons/video-play-dark.svg
  media/js/firefox/whatsnew/whatsnew-124-eu-compare.js
  media/js/firefox/whatsnew/whatsnew-124-eu-voices.es6.js
  media/js/firefox/whatsnew/whatsnew-124-experiment-de.es6.js
  media/js/firefox/whatsnew/whatsnew-124-experiment-na.es6.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_124.py
  tests/pages/firefox/whatsnew/whatsnew_124.py
Labels: P1, Needs Review, Review: XS

#14306 Add CTD pages in ES, IT, and PL [fix #14264]
  bedrock/firefox/templates/firefox/challenge-the-default/includes/hero.html
  bedrock/firefox/templates/firefox/challenge-the-default/landing-base.html
  bedrock/firefox/templates/firefox/challenge-the-default/landing-switch.html
  bedrock/firefox/templates/firefox/challenge-the-default/langs/landing.es-ES.html
  bedrock/firefox/templates/firefox/challenge-the-default/langs/landing.it.html
  bedrock/firefox/templates/firefox/challenge-the-default/langs/landing.pl.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  media/css/firefox/challenge-the-default/_compare-table.scss
  media/css/firefox/challenge-the-default/_hero.scss
  media/css/firefox/challenge-the-default/index.scss
  media/img/firefox/challenge-the-default/ctd-share-es.png
  media/img/firefox/challenge-the-default/ctd-share-it.png
  media/img/firefox/challenge-the-default/ctd-share-pl.png
  media/img/firefox/challenge-the-default/logo-ctd-es.svg
  media/img/firefox/challenge-the-default/logo-ctd-fr.svg
  media/img/firefox/challenge-the-default/logo-ctd-it.svg
  media/img/firefox/challenge-the-default/logo-ctd-pl.svg
Labels: Needs Review, Review: XS

#14289 Remove accounts popup from download flow (Fix #14246)
  bedrock/firefox/templates/firefox/new/desktop/download.html
  l10n/en/firefox/browsers.ftl
  l10n/en/firefox/browsers/mobile/index.ftl
  l10n/en/firefox/home.ftl
  l10n/en/firefox/new/desktop.ftl
  l10n/en/firefox/products.ftl
  media/css/firefox/new/desktop/download.scss
  media/js/firefox/new/desktop/join-modal.js
  media/static-bundles.json
  tests/functional/firefox/new/test_download.py
  tests/pages/firefox/new/download.py
Labels: Needs Review, Review: XS

#14315 Update WNP24 monitor link utms (Issue #14296)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-na-static.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-na-video.html
  tests/functional/firefox/whatsnew/test_whatsnew_124.py
Labels: P1, Needs Review, Review: µ

#14297 Add mobile install data links to docs
  docs/attribution/0003-firefox-mobile.rst
Labels: P3, Needs Review, Review: µ

#14313 String fix for speed feature page [#14298]
  l10n/en/firefox/features/fast-2024.ftl
Labels: Review: µ

#14320 WNP 124 NA updates for Monitor Plus (Issue #14296)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-na-static.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-na-video.html
  media/css/firefox/whatsnew/whatsnew-124-na.scss
Labels: P1, Needs Review, Review: µ

#14121 Remove sticky promo component from pages (Fixes #14120, #14247)
  bedrock/base/templates/base-protocol.html
  bedrock/base/templates/includes/sticky-promo.html
  bedrock/firefox/templates/firefox/browsers/best-browser.html
  bedrock/firefox/templates/firefox/browsers/browser-history.html
  bedrock/firefox/templates/firefox/browsers/compare/brave.html
  bedrock/firefox/templates/firefox/browsers/compare/chrome.html
  bedrock/firefox/templates/firefox/browsers/compare/edge.html
  bedrock/firefox/templates/firefox/browsers/compare/index.html
  bedrock/firefox/templates/firefox/browsers/compare/opera.html
  bedrock/firefox/templates/firefox/browsers/compare/safari.html
  bedrock/firefox/templates/firefox/browsers/incognito-browser.html
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/index.html
  bedrock/firefox/templates/firefox/browsers/quantum.html
  bedrock/firefox/templates/firefox/browsers/what-is-a-browser.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/releases/notes.html
  bedrock/settings/base.py
  docs/attribution/0001-analytics.rst
  l10n/en/firefox/sticky-promo.ftl
  media/css/firefox/browsers-products.scss
  media/css/firefox/home/master.scss
  media/css/firefox/new/desktop/download.scss
  media/css/firefox/sticky-promo.scss
  media/js/firefox/sticky-promo.es6.js
  media/static-bundles.json
  tests/functional/firefox/new/test_sticky_promo.py
  tests/functional/firefox/test_home.py
  tests/pages/firefox/home.py
  tests/pages/firefox/new/sticky_promo.py
  tests/pages/regions/sticky_promo.py
Labels: P2, Needs Review, Review: XS

#14321 Fix intermittent JS test failure (Fixes #14319)
  tests/unit/spec/base/datalayer-begincheckout.js
  tests/unit/spec/base/datalayer-productdownload.js
  tests/unit/spec/products/vpn/invite.js
Labels: P3, Needs Review, Review: µ

#14307 Retire light-theme footer in Firefox pages
  bedrock/base/templates/base-protocol.html
  bedrock/firefox/templates/firefox/whatsnew/base.html
Labels: Needs Review, Review: S

#14323 Replace Monitor WNP with PDF Editor (Issue #14296)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-na-pdf.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-na-static.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-na-video.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-124-na-pdf.scss
  media/css/firefox/whatsnew/whatsnew-124-na.scss
  media/img/firefox/whatsnew/whatsnew124-na/edit-pdfs-dark.svg
  media/img/firefox/whatsnew/whatsnew124-na/edit-pdfs-light.svg
  media/img/firefox/whatsnew/whatsnew124-na/monitor-plus-static-1200.jpg
  media/img/firefox/whatsnew/whatsnew124-na/monitor-plus-static-600.jpg
  media/img/firefox/whatsnew/whatsnew124-na/monitor-plus-thumbnail-1200.png
  media/img/firefox/whatsnew/whatsnew124-na/monitor-plus-thumbnail-600.png
  media/js/firefox/whatsnew/whatsnew-124-experiment-na.es6.js
  media/js/firefox/whatsnew/whatsnew-124-na-pdf.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_124.py
Labels: P1, Needs Review, Fire :fire:

#14330 Add extra GA events for WNP 124 EU (Issue #14181)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-de-voices-share.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx124-de-voices-video.html
  media/js/firefox/whatsnew/whatsnew-124-eu-compare.js
  media/js/firefox/whatsnew/whatsnew-124-eu-events.js
  media/static-bundles.json
Labels: Needs Review

#14198 Move VPN Resource Center images from Contentful CDN to Bedrock media
  bedrock/contentful/migrations/0007_data_switch_to_local_images.py
  bin/run-db-update.sh
  media/img/products/vpn/resource-center/AppExclusions1_w1376.png
  media/img/products/vpn/resource-center/AppExclusions1_w688.png
  media/img/products/vpn/resource-center/AppExclusions2_w1376.png
  media/img/products/vpn/resource-center/AppExclusions2_w688.png
  media/img/products/vpn/resource-center/AppExclusionsExample_w1376.png
  media/img/products/vpn/resource-center/AppExclusionsExample_w688.png
  media/img/products/vpn/resource-center/data-privacy-day-tips.jpg
  media/img/products/vpn/resource-center/eyes.jpg
  media/img/products/vpn/resource-center/faces.jpg
  media/img/products/vpn/resource-center/fast-vpn-from-mozilla.png
  media/img/products/vpn/resource-center/gaming-with-a-vpn-from-mozilla.png
  media/img/products/vpn/resource-center/get-a-private-vpn-with-mozilla-vpn.png
  media/img/products/vpn/resource-center/get-an-open-source-vpn-with-mozilla-vpn.png
  media/img/products/vpn/resource-center/hiding-your-ip-address-with-mozilla-vpn.png
  media/img/products/vpn/resource-center/how-to-browse-anonymously-with-a-vpn.png
  media/img/products/vpn/resource-center/image1_w1376.gif
  media/img/products/vpn/resource-center/image1_w688.gif
  media/img/products/vpn/resource-center/io.png
  media/img/products/vpn/resource-center/ip.png
  media/img/products/vpn/resource-center/ipaddress-devices-high-res.23bbc64d74fa_w1376.jpg
  media/img/products/vpn/resource-center/ipaddress-devices-high-res.23bbc64d74fa_w688.jpg
  media/img/products/vpn/resource-center/ipaddress-example-high-res.3f7c8132de1f_w1376.jpg
  media/img/products/vpn/resource-center/ipaddress-example-high-res.3f7c8132de1f_w688.jpg
  media/img/products/vpn/resource-center/lightpattern.jpg
  media/img/products/vpn/resource-center/lines.jpg
  media/img/products/vpn/resource-center/moz_location_history_blog_header_1920x1080.jpg
  media/img/products/vpn/resource-center/moz_vpn_blog_header_seo_explainer_home.jpg
  media/img/products/vpn/resource-center/no-Logging-vpn-from-mozilla.png
  media/img/products/vpn/resource-center/reasons-why-mozilla-vpn-is-a-secure-vpn.png
  media/img/products/vpn/resource-center/relax-at-home-with-a-vpn-from-mozilla.png
  media/img/products/vpn/resource-center/risks-of-using-a-free-vpn.png
  media/img/products/vpn/resource-center/vpn-16x9-devices.png
  media/img/products/vpn/resource-center/vpn-16x9-phoneglobe.png
  media/img/products/vpn/resource-center/vpn-16x9-toggle.png
  media/img/products/vpn/resource-center/vpn-16x9-world.png
  media/img/products/vpn/resource-center/vpn-proxy-high-res_w1376.png
  media/img/products/vpn/resource-center/vpn-proxy-high-res_w688.png
  media/img/products/vpn/resource-center/vpn-servers-around-the-world.png
  media/img/products/vpn/resource-center/vpn_location_w1376.png
  media/img/products/vpn/resource-center/vpn_location_w688.png
  media/img/products/vpn/resource-center/what-does-a-vpn-do.png
  media/img/products/vpn/resource-center/work-with-a-vpn-from-mozilla.png
Labels: Review: S

#14314 Simplify dev edition product, firstrun, and whatsnew pages (Fix #14243 Fix #14244 )
  bedrock/firefox/templates/firefox/developer/firstrun.html
  bedrock/firefox/templates/firefox/developer/includes/alt-newsletter.html
  bedrock/firefox/templates/firefox/developer/includes/arrow-right.svg
  bedrock/firefox/templates/firefox/developer/includes/features.html
  bedrock/firefox/templates/firefox/developer/includes/for-developers.html
  bedrock/firefox/templates/firefox/developer/includes/highlights.html
  bedrock/firefox/templates/firefox/developer/includes/intro-features.html
  bedrock/firefox/templates/firefox/developer/includes/mdn-features.html
  bedrock/firefox/templates/firefox/developer/includes/nightly.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/developer/whatsnew.html
  l10n/en/firefox/developer.ftl
  l10n/en/firefox/installer-help.ftl
  l10n/en/firefox/whatsnew/whatsnew-developer-mdnplus.ftl
  media/css/firefox/developer/developer.scss
  media/css/firefox/developer/includes/engage.scss
  media/css/firefox/developer/includes/features.scss
  media/css/firefox/developer/includes/gallery-grid.scss
  media/css/firefox/developer/includes/highlights.scss
  media/css/firefox/developer/includes/intro.scss
  media/css/firefox/developer/includes/newsletter.scss
  media/css/firefox/developer/includes/performance.scss
  media/img/firefox/developer/feature-console.svg
  media/img/firefox/developer/feature-debugger.svg
  media/img/firefox/developer/feature-inspector.svg
  media/img/firefox/developer/feature-memory.svg
  media/img/firefox/developer/feature-network.svg
  media/img/firefox/developer/feature-performance.svg
  media/img/firefox/developer/feature-responsive-mode.svg
  media/img/firefox/developer/feature-storage.svg
  media/img/firefox/developer/feature-style-editor.svg
  media/img/firefox/developer/feature-visual-editing.svg
  media/img/firefox/developer/mail.svg
  media/img/logos/mdn/mdn-wordmark-white.svg
Labels: Needs Review, Review: S

#14328 Schedule task to remove obsolete l10n strings Fix #14259
  .github/workflows/routine_l10n_obsolete.yml
  docs/l10n.rst
Labels: L10N, Needs Review, Review: XS

#14350 Remove pageHasVideo GA event property (Fixes #14331)
  media/js/base/core-datalayer-init.js
  media/js/base/core-datalayer.js
  tests/unit/spec/base/core-datalayer.js
Labels: P3, Needs Review, Review: µ

#14352 Update /research redirect [fix #14351]
  bedrock/mozorg/redirects.py
  tests/redirects/map_globalconf.py
Labels: Review: µ

#14356 Careers: update applicant privacy notice [fix #14348]
  bedrock/careers/templates/careers/position.html
Labels: Needs Review, Review: µ

#14347 String fixes for Developer Edition pages [#14243, #14244]
  bedrock/firefox/templates/firefox/developer/firstrun.html
  bedrock/firefox/templates/firefox/developer/includes/for-developers.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/developer/whatsnew-mdnplus.html
  bedrock/firefox/templates/firefox/installer-help.html
  l10n/en/firefox/developer.ftl
  l10n/en/firefox/installer-help.ftl
  l10n/en/firefox/whatsnew/whatsnew-developer-mdnplus.ftl
Labels: Review: XS

#14349 Move /firefox/browsers to /firefox (Fixes #14222)
  bedrock/base/templates/includes/protocol/navigation/menus/firefox.html
  bedrock/contentful/templates/includes/contentful/cta.html
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/browsers/browser-history.html
  bedrock/firefox/templates/firefox/browsers/what-is-a-browser.html
  bedrock/firefox/templates/firefox/challenge-the-default/landing-switch.html
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/faq.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/index.html
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  bedrock/mozorg/templates/mozorg/account.html
  bedrock/newsletter/templates/newsletter/knowledge-is-power.html
  bedrock/products/templates/products/landing.html
  l10n/en/firefox/browsers.ftl
  l10n/en/firefox/home.ftl
  media/css/firefox/browsers-products.scss
  media/css/firefox/home/ie9.scss
  media/css/firefox/home/master.scss
  media/img/firefox/home/master/browsers-mr1-high-res.jpg
  media/img/firefox/home/master/browsers-mr1.jpg
  media/img/firefox/home/master/firefox-relay.jpg
  media/img/firefox/home/master/hero-high-res.jpg
  media/img/firefox/home/master/hero.jpg
  media/img/firefox/home/master/monitor-mr1.svg
  media/img/firefox/home/master/pocket-mr1.svg
  media/img/firefox/home/master/respect-high-res.jpg
  media/img/firefox/home/master/respect-rtl-high-res.jpg
  media/img/firefox/home/master/respect-rtl.jpg
  media/img/firefox/home/master/respect.jpg
  media/img/firefox/home/master/spacer.gif
  media/img/firefox/home/master/vpn.svg
  media/img/firefox/home/master/zap-privacy.svg
  media/img/firefox/home/master/zap-respect.svg
  media/js/firefox/browsers-products.js
  media/js/firefox/home/master.js
  media/static-bundles.json
  tests/functional/firefox/test_browsers.py
  tests/functional/firefox/test_home.py
  tests/pages/firefox/browsers/landing.py
  tests/pages/firefox/home.py
  tests/redirects/map_globalconf.py
Labels: P2, Needs Review, Review: S

#14357 Update to Glean 5.0.0
  media/js/glean/init.es6.js
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#14359 Share page: add event tracking to copy button [#14199]
  media/js/firefox/share-page.es6.js
Labels: Needs Review, Review: µ

#14338 Migrate ESLint to use flat config (Fixes #13770)
  .eslintignore
  .eslintrc.js
  .pre-commit-config.yaml
  Dockerfile
  docs/coding.rst
  eslint.config.js
  media/js/firefox/welcome/welcome14.js
  media/js/firefox/welcome/welcome16.js
  package-lock.json
  package.json
  tests/unit/spec/base/core-datalayer.js
  tests/unit/spec/base/datalayer-productdownload.js
  tests/unit/spec/base/fxa-attribution.js
  tests/unit/spec/base/fxa-form.js
  tests/unit/spec/base/mozilla-client.js
  tests/unit/spec/base/mozilla-run.js
Labels: P3, Review: XS

#14372 Update research redirect [#14351]
  bedrock/mozorg/redirects.py
  tests/redirects/map_globalconf.py
Labels: Needs Review, Review: µ

#14369 Extend Rise25 nomination deadline [#14200]
  bedrock/mozorg/templates/mozorg/rise25/landing.html
Labels: Needs Review, Review: µ
