Repository mozilla/bedrock, pull requests merged in 2024-01, with the labels that each got.

#14016 Front end dependency bumps
  package-lock.json
  package.json
Labels: P3

#14009 Update Monitor links to monitor.mozilla.org (Fixes #14008)
  bedrock/base/templates/includes/protocol/navigation/menus/products.html
  bedrock/base/templates/includes/sticky-promo.html
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/browsers/best-browser.html
  bedrock/firefox/templates/firefox/browsers/compare/brave.html
  bedrock/firefox/templates/firefox/browsers/compare/chrome.html
  bedrock/firefox/templates/firefox/browsers/compare/safari.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/privacy/passwords.html
  bedrock/firefox/templates/firefox/privacy/products.html
  bedrock/firefox/templates/firefox/products/index.html
  bedrock/firefox/templates/firefox/welcome/page7.html
  bedrock/firefox/templates/firefox/welcome/page8.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx119-eu-trio-v1.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx119-na-trio.html
  bedrock/foundation/templates/foundation/annualreport/2017/index.html
  bedrock/foundation/templates/foundation/annualreport/2018/index.html
  bedrock/mozorg/templates/mozorg/antiharassment-tool.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/newsletter/templates/newsletter/updated.html
  bedrock/products/templates/products/vpn/includes/download-faq.html
  bedrock/settings/base.py
  docs/attribution/0001-analytics.rst
  docs/mozilla-accounts.rst
  l10n/en/firefox/browsers/best-browser.ftl
  l10n/en/firefox/browsers/compare/brave.ftl
  l10n/en/firefox/browsers/compare/chrome.ftl
  l10n/en/firefox/browsers/compare/safari.ftl
  l10n/en/firefox/privacy/passwords.ftl
  l10n/en/products/vpn/platform-post-download.ftl
  media/js/base/fxa-attribution.es6.js
  media/js/base/fxa-product-button.es6.js
  tests/unit/spec/base/fxa-attribution.js
  tests/unit/spec/base/fxa-link.js
Labels: P3, Review: µ

#14017 Update front end linting and test dependencies
  .pre-commit-config.yaml
  .stylelintrc
  package-lock.json
  package.json
Labels: P3

#14037 Create new Fluent string for monitor name change (Issue #14008)
  bedrock/products/templates/products/vpn/includes/download-faq.html
  l10n/en/products/vpn/platform-post-download.ftl
Labels: P2, Needs Review, Review: µ

#14036 Remove home page fundraising banner (Issue #14015)
  bedrock/base/templates/includes/banners/fundraiser.html
  bedrock/mozorg/templates/mozorg/home/home-new.html
  bedrock/mozorg/templates/mozorg/home/home-old.html
  bedrock/settings/base.py
  docs/banners.rst
  l10n/en/banners/fundraising.ftl
  media/css/base/banners/fundraiser.scss
  media/img/banners/fundraising/hand-heart-1000.png
  media/img/banners/fundraising/hand-heart-1200.png
  media/img/banners/fundraising/hand-heart-1400.png
  media/img/banners/fundraising/hand-heart-600.png
  media/img/banners/fundraising/hand-heart-800.png
  media/img/banners/fundraising/thermometer-1000.png
  media/img/banners/fundraising/thermometer-1200.png
  media/img/banners/fundraising/thermometer-1400.png
  media/img/banners/fundraising/thermometer-600.png
  media/img/banners/fundraising/thermometer-800.png
  media/js/mozorg/home/banner-experiment.es6.js
  media/js/mozorg/home/banner-init.js
  media/static-bundles.json
Labels: P3, Needs Review, Review: XS

#14010 Update twitter to X on firefox /new product images (Fixes #13987)
  bedrock/firefox/templates/firefox/new/desktop/download.html
  media/css/firefox/new/desktop/download.scss
  media/img/firefox/new/desktop/firefox-browser-light-1200.png
  media/img/firefox/new/desktop/firefox-browser-light-600.png
  media/img/firefox/new/desktop/firefox-new-tab-1000.png
  media/img/firefox/new/desktop/firefox-new-tab-1200.png
  media/img/firefox/new/desktop/firefox-new-tab-1400.png
  media/img/firefox/new/desktop/firefox-new-tab-1600.png
  media/img/firefox/new/desktop/firefox-new-tab-1800.png
  media/img/firefox/new/desktop/firefox-new-tab-2000.png
  media/img/firefox/new/desktop/firefox-new-tab-800.png
  media/img/firefox/new/desktop/hero-mr1-high-res.png
  media/img/firefox/new/desktop/hero-mr1.png
  media/img/firefox/new/desktop/screen-mr1-high-res.png
  media/img/firefox/new/desktop/screen-mr1.png
Labels: P2, Review: µ

#13988 Remove old Glean page hit event (Issue #13431)
  glean/metrics.yaml
  media/js/glean/init.es6.js
  media/js/glean/page.es6.js
  media/js/glean/utils.es6.js
  package-lock.json
  package.json
  tests/unit/spec/glean/page.js
  tests/unit/spec/glean/utils.js
Labels: P3, Needs Review, Review: XS

#14044 Remove Convert integration (Fix #14039)
  bedrock/base/templates/base-protocol.html
  bedrock/mozorg/redirects.py
  bedrock/privacy/templates/privacy/convert-opt-out.html
  bedrock/privacy/urls.py
  bedrock/settings/__init__.py
  bedrock/settings/base.py
  docs/abtest.rst
  media/js/base/convert-snippet.js
  media/static-bundles.json
  tests/redirects/map_globalconf.py
Labels: Needs Review, Review: S

#14045 Add pocket pencil banner to homepage
  bedrock/base/templates/includes/banners/pocket-pencil-banner.html
  bedrock/mozorg/templates/mozorg/home/home-new.html
  media/css/mozorg/home/includes/pocket-best-of.scss
  media/img/home/2023/pocket-best-of-pencil.png
  media/img/home/2023/pocket-logo-transparent.svg
  media/js/mozorg/home/banner-init.js
  media/static-bundles.json
Labels: Needs Review

#14049 Remove `performance.html` references
  bedrock/firefox/templates/firefox/developer/firstrun.html
  bedrock/firefox/templates/firefox/developer/includes/performance.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/developer/whatsnew.html
  l10n/en/firefox/developer.ftl
Labels: Needs Review, Review: XS, Frontend

#14050 Update and add translations for Moments 17
  bedrock/firefox/templates/firefox/welcome/page17/page17-a.html
  bedrock/firefox/templates/firefox/welcome/page17/page17-b.html
  bedrock/firefox/templates/firefox/welcome/page17/page17-c.html
  media/css/firefox/welcome17.scss
Labels: Review: XS

#13950 [Jan 8] Include attribution data with macOS Nightly links (Fixes #12761)
  docs/attribution/0002-firefox-desktop.rst
  media/js/base/stub-attribution.js
  media/js/firefox/all/all-downloads-unified.js
  tests/unit/spec/base/stub-attribution.js
Labels: Do Not Merge :warning:, P2, Review: XS

#14071 Add missing data-cta-text values
  bedrock/careers/templates/careers/benefits.html
  bedrock/careers/templates/careers/home.html
  bedrock/careers/templates/careers/locations.html
  bedrock/careers/templates/careers/teams.html
  bedrock/firefox/templates/firefox/browsers/compare/brave.html
  bedrock/firefox/templates/firefox/browsers/compare/chrome.html
  bedrock/firefox/templates/firefox/browsers/compare/edge.html
  bedrock/firefox/templates/firefox/browsers/compare/ie.html
  bedrock/firefox/templates/firefox/browsers/compare/opera.html
  bedrock/firefox/templates/firefox/browsers/compare/safari.html
  bedrock/firefox/templates/firefox/privacy/products.html
  bedrock/products/templates/products/vpn/pricing-refresh.html
  lib/l10n_utils/templatetags/fluent.py
Labels: Needs Review, Review: XS, analytics 📈

#14057 Record link_click event in GA4 #14053
  bedrock/base/templates/includes/protocol/footer/footer.html
  bedrock/base/templates/includes/protocol/navigation/menus/firefox.html
  bedrock/base/templates/includes/protocol/navigation/menus/innovation.html
  bedrock/base/templates/includes/protocol/navigation/menus/products.html
  bedrock/base/templates/includes/protocol/navigation/menus/whoweare.html
  bedrock/base/templates/includes/protocol/navigation/navigation.html
  bedrock/base/templates/includes/sticky-promo.html
  bedrock/base/templates/macros-protocol.html
  bedrock/base/templates/macros.html
  bedrock/base/tests/test_macros.py
  bedrock/careers/templates/careers/includes/footer.html
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/browsers/browser-history.html
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/browsers/what-is-a-browser.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/faq.html
  bedrock/firefox/templates/firefox/features/includes/subnav.html
  bedrock/firefox/templates/firefox/features/index.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/new/desktop/includes/sub_nav.html
  bedrock/firefox/templates/firefox/privacy/book.html
  bedrock/firefox/templates/firefox/switch.html
  bedrock/mozorg/templates/mozorg/about/index.html
  bedrock/mozorg/templates/mozorg/about/manifesto.html
  bedrock/newsletter/templates/newsletter/opt-out-confirmation.html
  bedrock/products/templates/products/vpn/includes/subnav-refresh.html
  bedrock/products/templates/products/vpn/includes/subnav.html
  bedrock/stories/templates/stories/stories-base-article.html
  docs/attribution/0001-analytics.rst
  tests/pages/base.py
Labels: Do Not Merge :warning:, Needs Review, Review: XS, analytics 📈

#14065 Add `title` attributes to embedded `iframe` videos
  bedrock/careers/templates/careers/home.html
  bedrock/firefox/templates/firefox/facebookcontainer/includes/video.html
  bedrock/firefox/templates/firefox/features/tips/includes/eyedropper-bram.html
  bedrock/firefox/templates/firefox/features/tips/includes/forget-damiano.html
  bedrock/firefox/templates/firefox/features/tips/includes/password-nneka.html
  bedrock/firefox/templates/firefox/features/tips/includes/pip-tina.html
  bedrock/foundation/templates/foundation/annualreport/2019/index.html
  bedrock/foundation/templates/foundation/annualreport/2020/index.html
  bedrock/mozorg/templates/mozorg/diversity/2021/index.html
Labels: Needs Review, Review: XS

#14091 Remove firefox/welcome/8 experiment (Fixes #14090)
  bedrock/firefox/templates/firefox/welcome/page8.html
  bedrock/firefox/urls.py
  media/css/firefox/welcome.scss
  media/img/firefox/welcome/arrows-down.svg
  media/img/firefox/welcome/arrows-right.svg
  media/img/firefox/welcome/trackers-magnify.svg
  media/img/firefox/welcome/trackers-money.svg
  media/img/firefox/welcome/trackers-shield.svg
  media/js/firefox/welcome/welcome8-traffic-cop.js
  media/static-bundles.json
Labels: P3, Needs Review, Review: XS

#14101 Update Firefox iOS app store link on /firefox/new/ (Fixes #14099)
  bedrock/firefox/templates/firefox/new/desktop/download.html
Labels: Needs Review, Review: µ

#14104 Add attribution params to Firefox pre-release download links on macOS (Issue #12761)
  media/js/base/stub-attribution.js
  media/js/firefox/all/all-downloads-unified.js
  tests/unit/spec/base/stub-attribution.js
  tests/unit/spec/firefox/all/all-downloads-unified.js
Labels: P1, Needs Review, Review: XS

#14089 Remove VPN holiday 2023 banner and experiment (Fixes #14043)
  bedrock/base/templates/includes/banners/vpn-events-banner.html
  bedrock/products/templates/products/vpn/landing-refresh.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/views.py
  bedrock/settings/base.py
  l10n/en/banners/vpn-holidays.ftl
  media/css/base/banners/vpn-events-banner.scss
  media/img/banners/vpn/vpn-banner-bg.png
  media/js/base/banners/vpn-events-banner-na-experiment.es6.js
  media/js/base/banners/vpn-events-banner.es6.js
  media/static-bundles.json
Labels: P3, Needs Review, Review: XS

#14103 Add WNP for Firefox 122 [fix #14058]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx122-eu.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx122-na.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/includes/_sign-off.scss
  media/css/firefox/whatsnew/whatsnew-122-eu.scss
  media/css/firefox/whatsnew/whatsnew-122-na.scss
  media/img/firefox/whatsnew/whatsnew122/check-dark.svg
  media/img/firefox/whatsnew/whatsnew122/check-light.svg
  media/img/firefox/whatsnew/whatsnew122/dash-dark.svg
  media/img/firefox/whatsnew/whatsnew122/dash-light.svg
  media/img/firefox/whatsnew/whatsnew122/products-dark-2x.png
  media/img/firefox/whatsnew/whatsnew122/products-dark.png
  media/img/firefox/whatsnew/whatsnew122/products-light-2x.png
  media/img/firefox/whatsnew/whatsnew122/products-light.png
  media/img/firefox/whatsnew/whatsnew122/tilde-dark.svg
  media/img/firefox/whatsnew/whatsnew122/tilde-light.svg
  media/img/logos/ddg/logo-duckduckgo-high-res.png
  media/img/logos/ddg/logo-duckduckgo.png
  media/js/firefox/whatsnew/whatsnew-122-eu.js
  media/js/firefox/whatsnew/whatsnew-122-na.js
  media/static-bundles.json
Labels: P1, Needs Review, Review: XS

#14105 Create GTM review issue template
  .github/ISSUE_TEMPLATE/z_gtm_review.md
Labels: Needs Review, Review: µ

#14110 Update Homepage CTA to reflect Mozilla Foundation (Fixes #14100)
  bedrock/mozorg/templates/mozorg/home/home-new.html
  media/css/mozorg/home/home-new.scss
  media/img/home/2023/external-link-black.png
  media/img/home/2023/external-link-white.png
Labels: Needs Review, Review: µ

#14116 Updates to NA WNP for Firefox 122 [#14058]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx122-na.html
  media/css/firefox/whatsnew/whatsnew-122-na.scss
Labels: P1, Needs Review, Review: µ

#14123 Add disclaimer to NA WNP 122 [#14058]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx122-na.html
  media/css/firefox/whatsnew/whatsnew-122-na.scss
Labels: Needs Review, Review: µ

#14124 Update Pocket’s OneTrust script [fix #14122]
  bedrock/settings/__init__.py
Labels: Needs Review, Review: µ

#14128 Add VPN 30-day guarantee note to pricing [fix #14127]
  bedrock/products/templates/products/vpn/includes/pricing-refresh.html
  media/css/products/vpn/common-refresh.scss
  media/css/products/vpn/pricing-refresh.scss
  media/img/products/vpn/common/check-green.svg
Labels: Needs Review, Review: XS

#14126 Update to Glean 4.0.0
  docs/attribution/0001-analytics.rst
  package-lock.json
  package.json
Labels: P3, Needs Review, Review: µ

#14083 Split GA4 event product_download into product specific events Fix #14072
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  docs/attribution/0001-analytics.rst
  media/js/base/datalayer-productdownload.es6.js
  tests/unit/spec/base/datalayer-productdownload.js
Labels: Needs Review, Review: S, analytics 📈
