Repository mozilla/bedrock, pull requests merged in 2024-09, with the labels that each got.

#15045 Update WNP 130 variant params [#15034]
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
Labels: Needs Review, Review: µ

#15038 Fix smaller text a11y color contrast
  bedrock/mozorg/templates/mozorg/home/includes/mofo-donate-promo.html
  media/css/mozorg/home/includes/mofo-donate-promo.scss
  media/css/products/vpn/common-refresh.scss
  media/img/products/vpn/common/check-green.svg
Labels: Needs Review, Frontend

#14834 Migrate /about/leadership/ page to Wagtail (Fixes #14801)
  bedrock/cms/models/pages.py
  bedrock/cms/templates/cms/simple_rich_text_page.html
  bedrock/mozorg/blocks/__init__.py
  bedrock/mozorg/blocks/leadership.py
  bedrock/mozorg/migrations/0003_leadershippage.py
  bedrock/mozorg/models.py
  bedrock/mozorg/templates/mozorg/about/leadership/blocks/leadership_block.html
  bedrock/mozorg/templates/mozorg/cms/about/leadership.html
  bedrock/mozorg/tests/factories.py
  bedrock/mozorg/tests/test_models.py
  bedrock/mozorg/urls.py
  bedrock/settings/base.py
  media/css/cms/base.scss
  media/css/cms/rich-text.scss
  media/css/mozorg/leadership.scss
  tests/playwright/specs/leadership.spec.js
Labels: P2, Needs Review, Backend, Frontend

#15062 Bugfix: ensure correct list of available translations for a CMS-backed page
  bedrock/cms/models/base.py
  bedrock/cms/tests/conftest.py
  bedrock/cms/tests/test_models.py
Labels: Backend, Wagtail

#15033 L10n fixes
  bedrock/firefox/templates/firefox/all/lang.html
  bedrock/firefox/templates/firefox/all/platform.html
  bedrock/firefox/templates/firefox/all/product.html
  l10n/en/firefox/all.ftl
Labels: Needs Review, Review: µ, Frontend

#14913 Remove "page ID" and "core page" code
  bedrock/base/templates/404.html
  bedrock/base/templates/500.html
  bedrock/base/templates/base-protocol.html
  bedrock/base/templates/includes/google-analytics.html
  bedrock/firefox/templates/firefox/releases/aurora-notes.html
  bedrock/firefox/templates/firefox/releases/beta-notes.html
  bedrock/firefox/templates/firefox/releases/dev-browser-notes.html
  bedrock/firefox/templates/firefox/releases/esr-notes.html
  bedrock/firefox/templates/firefox/releases/nightly-notes.html
  bedrock/firefox/templates/firefox/releases/notes.html
  bedrock/firefox/templates/firefox/releases/release-notes.html
  bedrock/firefox/templates/firefox/releases/system_requirements.html
  bedrock/firefox/templates/firefox/whatsnew/base.html
  bedrock/mozorg/templates/mozorg/home/base.html
  bedrock/newsletter/templates/newsletter/confirm.html
  bedrock/newsletter/templates/newsletter/country.html
  bedrock/newsletter/templates/newsletter/management.html
  media/js/base/core-datalayer-init.js
  media/js/base/core-datalayer-page-id.js
  media/js/base/core-datalayer.js
  media/js/base/experiment-amo-init.es6.js
  media/js/base/experiment-amo.es6.js
  media/js/base/gtm/ie/gtm-snippet-ie-init.es6.js
  media/js/mozorg/home/fundraising-banner-experiment.es6.js
  media/static-bundles.json
  tests/unit/spec/base/core-datalayer-page-id.js
  tests/unit/spec/base/core-datalayer.js
  tests/unit/spec/base/experiment-amo.js
  webpack.test.config.js
Labels: P2, Review: XS, Analytics 📈, Frontend

#15081 Leadership page, remove Teixeira [fix #15080]
  bedrock/mozorg/templates/mozorg/about/leadership/includes/executive.html
  media/img/mozorg/about/leadership/steve-teixeira-high-res.jpg
  media/img/mozorg/about/leadership/steve-teixeira.jpg
Labels: Needs Review, Review: µ

#15077 Add Firefox campaign URLs to a11y checker
  tests/playwright/specs/a11y/includes/urls.js
Labels: P3, Needs Review, Review: µ

#15061 Fix node warning calling rmdirSync() when running Playwright setup (Fixes #15058)
  docs/cms.rst
  docs/testing.rst
  tests/playwright/global-setup.js
Labels: P3, Needs Review, Review: µ

#15029 Fix a11y nested interactive element in sub nav (Fixes #15005)
  bedrock/base/templates/macros.html
  bedrock/base/tests/test_macros.py
  bedrock/firefox/templates/firefox/browsers/browser-history.html
  bedrock/firefox/templates/firefox/browsers/what-is-a-browser.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/faq.html
  bedrock/firefox/templates/firefox/features/includes/subnav.html
  bedrock/firefox/templates/firefox/includes/sub-nav-firefox.html
  bedrock/products/templates/products/vpn/includes/subnav-refresh.html
  media/css/firefox/family/components/_subnav.scss
  media/css/firefox/family/styles.scss
  media/css/protocol/components/_sub-navigation.scss
  media/js/base/protocol/protocol-sub-navigation.js
  media/js/firefox/family/subnav.js
  media/static-bundles.json
  tests/playwright/specs/a11y/components.spec.js
Labels: P3, Needs Review, Review: XS, Frontend

#15071 Update a11y for `firefox/all/` page
  bedrock/firefox/templates/firefox/all/download.html
  bedrock/firefox/templates/firefox/all/lang.html
  bedrock/firefox/templates/firefox/all/platform.html
  media/css/firefox/all.scss
Labels: Needs Review, Review: XS, a11y

#15103 Add ./static to ESLint ignore paths
  eslint.config.js
Labels: P3, Needs Review, Review: µ, Frontend

#14984 Enable dependabot updates for front-end NPM packages
  .github/dependabot.yml
Labels: P3, Needs Review, Review: µ, Frontend

#14967 footer refresh
  bedrock/base/templates/base-protocol-mozilla.html
  bedrock/base/templates/base-protocol.html
  bedrock/base/templates/includes/protocol/footer/footer-newsletter.html
  bedrock/base/templates/includes/protocol/footer/footer-refresh.html
  bedrock/base/templates/includes/protocol/footer/footer.html
  bedrock/base/templates/includes/protocol/lang-switcher-refresh.html
  bedrock/settings/base.py
  l10n/en/footer-refresh.ftl
  media/css/m24/base-navigation-and-footer.scss
  media/css/m24/base.scss
  media/css/m24/components/footer-refresh.scss
  media/css/m24/vars/fonts.scss
  media/css/m24/vars/text.scss
  media/img/logos/mozilla/footer-refresh/icon-arrow-down.svg
  media/img/logos/mozilla/footer-refresh/icon-globe.svg
  media/img/logos/mozilla/footer-refresh/mozilla-in-white.svg
  media/img/logos/mozilla/footer-refresh/symbol.svg
  media/static-bundles.json
  tests/playwright/specs/a11y/components.spec.js
  tests/playwright/specs/footer.spec.js
Labels: Frontend, Refresh 🦖

#14955 Convert buttons with data-link-type="download" into CTAs
  bedrock/base/templates/includes/banners/mobile/firefox-app-store.html
  bedrock/base/templates/includes/banners/mobile/focus-app-store.html
  bedrock/base/templates/macros.html
  bedrock/firefox/templates/firefox/browsers/chromebook.html
  bedrock/firefox/templates/firefox/browsers/mobile/index.html
  bedrock/firefox/templates/firefox/enterprise/index.html
  bedrock/firefox/templates/firefox/includes/download-button-thanks.html
  bedrock/firefox/templates/firefox/includes/download-button.html
  bedrock/firefox/templates/firefox/includes/download-list.html
  bedrock/firefox/templates/firefox/includes/download-unsupported.html
  bedrock/firefox/templates/firefox/includes/macros.html
  bedrock/firefox/templates/firefox/index.html
  bedrock/firefox/tests/test_helpers.py
  bedrock/firefox/tests/test_views.py
  bedrock/mozorg/templates/mozorg/analytics-tests/ga-index.html
  media/css/firefox/browsers-products.scss
  media/js/base/base-page-init.js
  media/js/base/mozilla-utils.js
  tests/pages/firefox/family/landing.py
  tests/unit/spec/base/mozilla-utils.js
  tests/unit/spec/firefox/new/common/thanks.js
Labels: P1, Review: S, Analytics 📈, Frontend

#15119 Decommission Knowledge-is-Power newsletter (Fixes #15075)
  bedrock/mozorg/templates/mozorg/home/home-new.html
  bedrock/newsletter/redirects.py
  bedrock/newsletter/templates/newsletter/includes/form.html
  bedrock/newsletter/templates/newsletter/knowledge-is-power-confirm.html
  bedrock/newsletter/templates/newsletter/knowledge-is-power.html
  bedrock/newsletter/tests/test_views.py
  bedrock/newsletter/urls.py
  bedrock/newsletter/views.py
  bedrock/settings/base.py
  l10n/en/mozorg/home-new.ftl
  l10n/en/mozorg/newsletters.ftl
  l10n/en/newsletter_form.ftl
  media/css/newsletter/newsletter-knowledge-is-power-confirm.scss
  media/css/newsletter/newsletter-knowledge-is-power.scss
  media/css/protocol/protocol-firefox.scss
  media/css/protocol/protocol-mozilla.scss
  media/js/newsletter/confirm-init.es6.js
  media/js/newsletter/confirm.es6.js
  media/js/newsletter/management.es6.js
  media/static-bundles.json
  tests/pages/newsletter/knowledge_is_power.py
  tests/redirects/map_globalconf.py
  tests/unit/spec/newsletter/confirm.js
  tests/unit/spec/newsletter/data.js
  tests/unit/spec/newsletter/management.js
Labels: P1, Needs Review, Review: XS

#15130 Fix new vs. old logo sizing
  media/css/protocol/protocol-mozilla.scss
Labels: P1, Review: XS, Refresh 🦖

#15127 Fix JS error thrown by nav CTA experiment (Fixes #15126)
  media/js/mozorg/home/fundraising-nav-cta.es6.js
Labels: P2, Needs Review, Review: µ

#15121 Add product logos to MVP home page
  bedrock/mozorg/templates/mozorg/home/includes/m24/products.html
  media/css/m24/spring.scss
  media/img/logos/fakespot/logo-white.svg
Labels: P1, Review: µ, Frontend, Refresh 🦖

#15132 Refresh: #a11y improvements to footer newsletter #15129
  media/css/m24/components/footer-newsletter.scss
  media/css/m24/components/footer-refresh.scss
Labels: P2, Review: XS, Refresh 🦖

#15140 Fix missing footer styles on /firefox/new/ and /thanks/ (Fixes #15138)
  bedrock/base/templates/base-protocol-mozilla.html
  bedrock/cms/templates/cms/base-protocol.html
  bedrock/firefox/templates/firefox/new/basic/base.html
  bedrock/firefox/templates/firefox/new/desktop/base.html
  bedrock/products/templates/products/vpn/base.html
Labels: P2, Needs Review, Review: µ

#14966 Navigation refresh
  bedrock/base/templates/includes/protocol/navigation/menus-refresh/about-us.html
  bedrock/base/templates/includes/protocol/navigation/menus-refresh/firefox.html
  bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html
  bedrock/base/templates/includes/protocol/navigation/navigation-refresh.html
  bedrock/base/templates/includes/protocol/navigation/navigation.html
  bedrock/settings/base.py
  l10n/en/navigation_refresh.ftl
  media/css/m24/base-navigation-and-footer.scss
  media/css/m24/components/navigation-refresh.scss
  media/css/m24/vars/color.scss
  media/img/m24/arrow-dark-up.svg
Labels: Frontend, Refresh 🦖

#14995 Remove JUL24 home fundraising banner
  bedrock/base/templates/includes/banners/fundraiser.html
  bedrock/mozorg/templates/mozorg/home/home-new.html
  bedrock/mozorg/templates/mozorg/home/home-old.html
  media/css/base/banners/fundraiser.scss
  media/img/banners/fundraising/hand-heart-1000.png
  media/img/banners/fundraising/hand-heart-1200.png
  media/img/banners/fundraising/hand-heart-1400.png
  media/img/banners/fundraising/hand-heart-600.png
  media/img/banners/fundraising/hand-heart-800.png
  media/js/mozorg/home/fundraising-banner-experiment.es6.js
  media/js/mozorg/home/fundraising-banner.es6.js
  media/static-bundles.json
Labels: Frontend

#15118 Update dependabot.yml to ignore certain front-end deps
  .github/dependabot.yml
Labels: P3, Needs Review, Review: µ

#15136 Update a11y-checker to scan redesigned footer
  tests/playwright/specs/a11y/components.spec.js
  tests/playwright/specs/a11y/includes/locators.js
Labels: P3, Needs Review, Review: µ

#15153 Fix navigation functional tests
  tests/functional/firefox/family/test_family.py
  tests/functional/test_navigation.py
  tests/pages/base.py
  tests/pages/firefox/family/landing.py
  tests/playwright/specs/navigation.spec.js
  tests/playwright/specs/products/vpn/vpn-landing.spec.js
Labels: P2, Needs Review, Review: µ

#15160 Refresh: make grid tiles block links
  bedrock/base/templates/macros-m24.html
  bedrock/mozorg/templates/mozorg/about/includes/m24/amplify.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/ai-grid.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/resources-grid.html
  media/css/m24/grid.scss
Labels: Needs Review, Review: XS

#15106 Add new wordmarks and logos to Trademarks page
  bedrock/foundation/templates/foundation/trademarks/list.html
  media/img/trademarks/mozilla-dino-flag.svg
  media/img/trademarks/mozilla-logo-tm.svg
  media/img/trademarks/mozilla-rebranded.svg
  media/img/trademarks/pontoon-logo.svg
  media/img/trademarks/zilla-dino-roar.svg
  media/img/trademarks/zilla-dino.svg
  media/img/trademarks/zilla-flag.svg
Labels: Needs Review, Review: XS, Frontend

#15141 Pin ESR 115 for unsupported operating systems (Fixes #13753)
  bedrock/firefox/templates/firefox/includes/download-unsupported.html
  tests/playwright/specs/products/firefox/firefox-channel-desktop.spec.js
  tests/playwright/specs/products/firefox/firefox-developer.spec.js
  tests/playwright/specs/products/firefox/firefox-new.spec.js
  tests/unit/spec/base/datalayer-productdownload.js
Labels: P1, Review: XS

#15158 Set Dependabot to ignore specific dependency updates
  .github/dependabot.yml
Labels: P3, Needs Review, Review: µ

#15164 Use sentence case for navigation headings and titles
  l10n/en/navigation_refresh.ftl
Labels: P1, Needs Review, Review: µ

#15144 Refresh: update brand fonts globally [fix #15088]
  bedrock/base/templates/base-protocol-mozilla.html
  bedrock/base/templates/base-protocol.html
  bedrock/base/templates/includes/protocol/footer/footer-refresh.html
  bedrock/firefox/templates/firefox/new/basic/base.html
  bedrock/firefox/templates/firefox/new/desktop/base.html
  bedrock/mozorg/views.py
  bedrock/newsletter/templates/newsletter/security-privacy-news.html
  media/css/careers/components/diversity.scss
  media/css/careers/components/locations.scss
  media/css/careers/components/position.scss
  media/css/careers/components/testimonials.scss
  media/css/firefox/challenge-the-default/_compare-table.scss
  media/css/firefox/challenge-the-default/_hero.scss
  media/css/firefox/challenge-the-default/index.scss
  media/css/firefox/family/components/_hero.scss
  media/css/firefox/new/desktop/download.scss
  media/css/firefox/nothing-personal/_browser.scss
  media/css/firefox/nothing-personal/styles.scss
  media/css/firefox/releasenotes.scss
  media/css/firefox/switch.scss
  media/css/foundation/annual-report-2019-2020.scss
  media/css/foundation/annual-report-2021.scss
  media/css/foundation/annual-report.scss
  media/css/m24/base.scss
  media/css/m24/copy.scss
  media/css/m24/vars/fonts.scss
  media/css/mozorg/about-forums.scss
  media/css/mozorg/about-patents.scss
  media/css/mozorg/about.scss
  media/css/mozorg/account.scss
  media/css/mozorg/antiharassment-tool.scss
  media/css/mozorg/contribute.scss
  media/css/mozorg/diversity/diversity.scss
  media/css/mozorg/home/ctd-promo-de.scss
  media/css/mozorg/home/home-new.scss
  media/css/mozorg/home/includes/featured-vpn.scss
  media/css/mozorg/home/includes/mofo-donate-promo.scss
  media/css/mozorg/home/includes/monitor-banner.scss
  media/css/mozorg/impact.scss
  media/css/mozorg/manifesto.scss
  media/css/mozorg/mozilla-account-promo.scss
  media/css/mozorg/sustainability.scss
  media/css/newsletter/newsletter-monitor-waitlist.scss
  media/css/newsletter/newsletter-security-privacy-news.scss
  media/css/privacy/privacy-protocol.scss
  media/css/products/monitor/waitlist.scss
  media/css/products/vpn/common-refresh.scss
  media/css/products/vpn/download.scss
  media/css/products/vpn/invite.scss
  media/css/products/vpn/resource-center.scss
  media/css/protocol/basic-article.scss
  media/css/protocol/components/_menu.scss
  media/css/protocol/components/_sub-navigation.scss
  media/css/protocol/protocol-mozilla-2024.scss
  media/static-bundles.json
Labels: P1, Review: M, Refresh 🦖

#15174 Remove new brand assets from trademarks list [#15091]
  bedrock/foundation/templates/foundation/trademarks/list.html
Labels: Review: µ

#15176 Add WNP 131 (Fixes #15097)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx131-eu.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx131-na.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/includes/_mofo-donate-cta.scss
  media/css/firefox/whatsnew/whatsnew-131-eu.scss
  media/css/firefox/whatsnew/whatsnew-131-na.scss
  media/img/firefox/whatsnew/whatsnew131-eu/main-image-1100.png
  media/img/firefox/whatsnew/whatsnew131-eu/main-image-500.png
  media/img/firefox/whatsnew/whatsnew131-eu/main-image-700.png
  media/img/firefox/whatsnew/whatsnew131-eu/main-image-900.png
  media/img/firefox/whatsnew/whatsnew131-na/main-image.svg
  media/js/firefox/whatsnew/whatsnew-131-protections-dashboard.js
  media/js/firefox/whatsnew/whatsnew-131.js
  media/static-bundles.json
Labels: P1, Needs Review, Review: XS

#15189 Updates to adblocker feature page [fix #15104]
  bedrock/firefox/templates/firefox/features/adblocker.html
  l10n/en/firefox/features/adblocker.ftl
Labels: Needs Review, Review: XS

#15186 Misc a11y fixes
  bedrock/base/templates/includes/protocol/footer/footer-refresh.html
  bedrock/base/templates/includes/protocol/footer/footer.html
  bedrock/firefox/templates/firefox/built-for-you/landing.de.html
  bedrock/mozorg/templates/mozorg/about/index-m24.html
Labels: P3, Needs Review, Review: µ

#15199 String fix for adblocker page [#15104]
  l10n/en/firefox/features/adblocker.ftl
Labels: Needs Review, Review: µ

#15204 Add custom app store links to built-for-you page (Fixes #15203)
  bedrock/firefox/templates/firefox/built-for-you/landing.de.html
  bedrock/firefox/templates/firefox/built-for-you/landing.fr.html
Labels: P2, Needs Review, Review: µ

#14904 Migrate remaining VPN Selenium tests to Playwright
  bedrock/products/templates/products/vpn/includes/macros.html
  bedrock/products/templates/products/vpn/includes/pricing-basic.html
  bedrock/products/templates/products/vpn/includes/pricing-plus-relay.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templates/products/vpn/pricing-refresh.html
  bedrock/products/templates/products/vpn/pricing.html
  tests/functional/products/vpn/__init__.py
  tests/functional/products/vpn/test_features.py
  tests/functional/products/vpn/test_landing.py
  tests/functional/products/vpn/test_pricing.py
  tests/functional/products/vpn/test_resource_center.py
  tests/pages/products/vpn/__init__.py
  tests/pages/products/vpn/features.py
  tests/pages/products/vpn/landing.py
  tests/pages/products/vpn/pricing.py
  tests/pages/products/vpn/resource_center.py
  tests/playwright/specs/products/vpn/vpn-features.spec.js
  tests/playwright/specs/products/vpn/vpn-landing-old.spec.js
  tests/playwright/specs/products/vpn/vpn-pricing-old.spec.js
  tests/playwright/specs/products/vpn/vpn-pricing.spec.js
Labels: P3, Review: XS, Frontend
