Repository mozilla/bedrock, pull requests merged in 2024-11, with the labels that each got.

#15406 VPN download page CTA margin fix (Fixes #15405)
  media/css/products/vpn/download.scss
Labels: P2, Needs Review, Review: XS, Frontend

#15425 Update front-end linters
  .pre-commit-config.yaml
  media/js/firefox/welcome/welcome19-to-24.js
  package-lock.json
  package.json
Labels: P3, Review: µ

#15381 [Refresh] Progressively enhance navigation (Fixes #15360)
  media/css/m24/components/navigation-refresh.scss
Labels: P2, Needs Review, Review: XS, Frontend, Refresh 🦖

#15440 update wnp132 video thumbnails (fix #15419)
  media/img/firefox/whatsnew/whatsnew132/video-high-res.jpg
  media/img/firefox/whatsnew/whatsnew132/video.jpg
Labels: Needs Review, Review: µ, Frontend

#15435 Refresh: Standardize border widths at 2px (Fix #15428)
  media/css/m24/components/footer-newsletter.scss
  media/css/m24/components/footer-refresh.scss
  media/css/m24/components/navigation-refresh.scss
  media/css/m24/components/pencil-banner.scss
  media/css/m24/grid.scss
  media/css/m24/spring.scss
  media/css/m24/vars/_spacing.scss
Labels: Needs Review, Review: µ, Frontend, Refresh 🦖

#15372 Remove unused VPN article templates (Fixes #15371)
  bedrock/products/templates/products/vpn/more/do-i-need.html
  bedrock/products/templates/products/vpn/more/what-is-a-vpn-v2.html
  bedrock/products/templates/products/vpn/more/why-mozilla-vpn.html
  bedrock/products/urls.py
  media/css/products/vpn/vpn-info.scss
  media/static-bundles.json
Labels: P3, Needs Review, Review: µ

#15413 Add close button to pencil banner (Fixes #15331)
  bedrock/base/templates/includes/banners/pencil-banner.html
  bedrock/base/templates/includes/protocol/navigation/navigation.html
  media/css/m24/components/pencil-banner.scss
  media/img/m24/close.svg
  media/js/base/banners/m24-pencil-banner-check.js
  media/js/base/banners/m24-pencil-banner-init.es6.js
  media/js/base/banners/m24-pencil-banner.es6.js
  media/static-bundles.json
  tests/unit/spec/base/m24-pencil-banner.js
Labels: P2, Needs Review, Review: XS, Refresh 🦖

#15444 Fix 404 ESR115 download links for /sat/ and /skr/ languages (Fixes #15437)
  bedrock/firefox/templates/firefox/includes/download-unsupported.html
  bedrock/firefox/views.py
Labels: P2, Review: XS, Frontend

#15449 Rename components to match designs (#15429)
  bedrock/base/templates/macros-m24.html
  bedrock/mozorg/templates/mozorg/about/includes/m24/amplify.html
  bedrock/mozorg/templates/mozorg/about/includes/m24/careers.html
  bedrock/mozorg/templates/mozorg/about/includes/m24/hero.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/ai-grid.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/hero.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/products.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/resources-grid.html
  media/css/m24/base.scss
  media/css/m24/careers.scss
  media/css/m24/gallery.scss
  media/css/m24/hero.scss
  media/css/m24/intro.scss
  media/css/m24/launchpad.scss
Labels: Needs Review, Review: µ, Refresh 🦖

#15453 Refresh: update favicon (Fixes #15401)
  bedrock/base/templates/base-protocol.html
  media/img/favicons/mozilla/m24/apple-touch-icon.png
  media/img/favicons/mozilla/m24/favicon-196x196.png
  media/img/favicons/mozilla/m24/favicon.ico
Labels: P2, Needs Review, Review: µ

#15455 Refresh: update open graph image (Fixes #15248)
  bedrock/base/templates/base-protocol.html
  media/img/m24/og.png
Labels: P2, Review: µ, Refresh 🦖

#15451 M24 footer updates (fix #15427)
  bedrock/base/templates/includes/protocol/footer/footer-refresh.html
  media/css/m24/components/footer-newsletter.scss
  media/css/m24/components/footer-refresh.scss
  media/img/icons/m24-small/social-instagram-gray.svg
  media/img/icons/m24-small/social-linkedin-gray.svg
  media/img/icons/m24-small/social-spotify-gray.svg
  media/img/icons/m24-small/social-tiktok-gray.svg
  media/img/icons/m24-small/social-x-gray.svg
  media/img/icons/m24-small/social-youtube-gray.svg
Labels: Needs Review, Frontend, Refresh 🦖

#15433 Refresh: Nav - Don't lazy load images in top level of header navigation menu
  bedrock/base/templates/includes/protocol/navigation/menus-refresh/firefox.html
  bedrock/base/templates/includes/protocol/navigation/navigation-refresh.html
Labels: Needs Review, Review: µ, Frontend, Refresh 🦖

#15409 add Fx 20th NA+EU pages (fix #15383)
  bedrock/firefox/templates/firefox/firefox-20th/index.html
  bedrock/firefox/urls.py
  media/css/firefox/firefox-20th/firefox-20th.scss
  media/img/firefox/firefox-20th/fan-art-high-res.png
  media/img/firefox/firefox-20th/fan-art.png
  media/img/firefox/firefox-20th/firefox-20th-dark.png
  media/img/firefox/firefox-20th/firefox-20th-social-share.png
  media/js/firefox/firefox-20th/firefox-20th.js
  media/static-bundles.json
Labels: Needs Review, Frontend

#15465 fix SUMO link
  bedrock/firefox/templates/firefox/firefox-20th/index.html
Labels: P1, Needs Review, Review: µ, Frontend

#15471 Add new campaign params for experiment [fix #15470]
  bedrock/firefox/redirects.py
Labels: Needs Review, Review: µ

#15472 Refresh: add fly-apart animation to showcase [#15304]
  bedrock/mozorg/templates/mozorg/home/includes/m24/showcase.html
  media/css/m24/showcase.scss
  media/img/home/2024/rise25-one-high-res.jpg
  media/img/home/2024/rise25-one.jpg
  media/img/home/2024/rise25-static-high-res.png
  media/img/home/2024/rise25-static.png
  media/img/home/2024/rise25-three-high-res.jpg
  media/img/home/2024/rise25-three.jpg
  media/img/home/2024/rise25-two-high-res.jpg
  media/img/home/2024/rise25-two.jpg
Labels: Needs Review, Review: XS, Refresh 🦖

#15476 Add pricing information to VPN mobile subscription CTA (Fixes #15463)
  bedrock/products/templates/products/vpn/includes/mobile-subscribe.html
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  bedrock/settings/base.py
  l10n/en/products/vpn/pricing-2023.ftl
  media/css/products/vpn/pricing-refresh.scss
Labels: P1, Needs Review, Review: XS

#15452 Remove dontate nav CTA experiment code (Fixes #15446)
  bedrock/mozorg/templates/mozorg/home/home-new.html
  bedrock/mozorg/views.py
  media/js/mozorg/home/fundraising-nav-cta.es6.js
  media/static-bundles.json
Labels: Papercuts 💸, P3, Review: µ, Frontend

#15483 update M24 navigation about menu layout (fix #15431)
  bedrock/base/templates/includes/protocol/navigation/menus-refresh/about-us.html
  l10n/en/navigation_refresh.ftl
  media/css/m24/components/navigation-refresh.scss
Labels: Frontend, Refresh 🦖

#15490 Update pencil banner icon (Fixes #15479)
  media/css/m24/components/pencil-banner.scss
  media/img/icons/m24-small/close.svg
  media/img/m24/close.svg
Labels: P3, Needs Review, Review: µ, Refresh 🦖

#15493 M24 remove ctas (fix #15478)
  bedrock/mozorg/templates/mozorg/about/includes/m24/community.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/resources-grid.html
Labels: Needs Review, Review: µ, Frontend, Refresh 🦖

#15491 Increase navigation logo lockup size (Fixes #15477)
  bedrock/base/templates/includes/protocol/navigation/navigation-refresh.html
  media/css/m24/components/navigation-refresh.scss
Labels: P3, Needs Review, Review: µ, Refresh 🦖

#15497 Add spacer to VPN mobile pricing display (#15463)
  media/css/products/vpn/pricing-refresh.scss
Labels: P3, Needs Review, Review: µ

#15502 Update ESR link on /welcome/20/ page to link to /firefox/all/desktop-esr/ (Fixes #15501)
  bedrock/firefox/templates/firefox/welcome/page19.html
  bedrock/firefox/templates/firefox/welcome/page20.html
  bedrock/firefox/templates/firefox/welcome/page21.html
  bedrock/firefox/templates/firefox/welcome/page22.html
  bedrock/firefox/templates/firefox/welcome/page23.html
  bedrock/firefox/templates/firefox/welcome/page24.html
Labels: P2, Needs Review, Review: µ

#15462 Add a11y test for side menu component
  bedrock/base/templates/macros-protocol.html
  tests/playwright/specs/a11y/components.spec.js
  tests/playwright/specs/a11y/components/footer.spec.js
  tests/playwright/specs/a11y/components/navigation.spec.js
  tests/playwright/specs/a11y/components/side-menu.spec.js
  tests/playwright/specs/a11y/components/sub-navigation.spec.js
  tests/playwright/specs/a11y/includes/helpers.js
  tests/playwright/specs/a11y/includes/locators.js
Labels: P3, Needs Review, Review: XS

#15506 Remove impact report switch logic [no bug]
  bedrock/base/templates/includes/protocol/navigation/menus/whoweare.html
  bedrock/mozorg/templates/mozorg/impact-report/index.html
Labels: Papercuts 💸, P3, Needs Review, Review: µ

#15494 homepage donate section style update (fix #15480)
  bedrock/mozorg/templates/mozorg/home/includes/m24/donate.html
  media/css/m24/donate.scss
  media/img/m24/todo-21-9.svg
Labels: Needs Review, Frontend, Refresh 🦖

#15512 Add WNP 133 for VPN (Fixes #15488)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx133-vpn.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-133-vpn.scss
  media/img/firefox/whatsnew/whatsnew133-vpn/wnp-133-vpn-fast-dark.svg
  media/img/firefox/whatsnew/whatsnew133-vpn/wnp-133-vpn-fast-light.svg
  media/img/firefox/whatsnew/whatsnew133-vpn/wnp-133-vpn-header-dark.svg
  media/img/firefox/whatsnew/whatsnew133-vpn/wnp-133-vpn-header-light.svg
  media/img/firefox/whatsnew/whatsnew133-vpn/wnp-133-vpn-safe-dark.svg
  media/img/firefox/whatsnew/whatsnew133-vpn/wnp-133-vpn-safe-light.svg
  media/js/firefox/whatsnew/whatsnew-events.js
  media/static-bundles.json
Labels: P1, Needs Review, Review: XS

#15460 Leadership page a11y fixed (Fixes #15335)
  bedrock/base/templates/macros-protocol.html
  bedrock/mozorg/templates/mozorg/cms/about/blocks/leadership_block.html
  bedrock/mozorg/templates/mozorg/cms/about/leadership.html
  media/css/mozorg/leadership.scss
  media/js/mozorg/about-leadership.js
Labels: P3, Review: XS, Frontend

#14965 Fixup CTD landing & update promo link
  bedrock/firefox/templates/firefox/challenge-the-default/includes/toggles.html
  bedrock/firefox/templates/firefox/challenge-the-default/landing-base.html
  bedrock/firefox/templates/firefox/challenge-the-default/langs/landing.fr.html
  bedrock/mozorg/templates/mozorg/home/includes/ctd-promo-de.html
  media/css/firefox/challenge-the-default/_animations.scss
  media/css/firefox/challenge-the-default/_compare-table.scss
  media/css/firefox/challenge-the-default/_hero.scss
  media/css/firefox/challenge-the-default/_toggle.scss
  media/css/firefox/challenge-the-default/index.scss
  media/css/mozorg/home/ctd-promo-de.scss
  media/img/firefox/challenge-the-default/logo-firefox.svg
Labels: P3, Frontend

#15518 Order VPN articles by first published date descending (Fixes #15517)
  bedrock/products/models.py
Labels: P3, Needs Review, Review: XS

#15508 Refresh: homepage - hero, update to black with flag (Fix#15482)
  bedrock/mozorg/templates/mozorg/home/home-m24.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/hero.html
  media/css/m24/base.scss
  media/css/m24/flag.scss
  media/img/home/2024/hero-symbol-white-2-1.svg
  media/img/home/2024/hero-symbol-white-27-1.svg
  media/img/home/2024/hero-symbol-white.svg
Labels: Review: XS, Frontend, Refresh 🦖

#15448 Refresh: Add springboard component (Fix #15305)
  bedrock/base/templates/macros-m24.html
  bedrock/mozorg/templates/mozorg/home/home-m24.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/ai-grid.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/media-springboard.html
  media/css/m24/base.scss
  media/css/m24/launchpad.scss
  media/css/m24/springboard.scss
  media/css/m24/vars/_animation.scss
  media/css/m24/vars/_spacing.scss
  media/img/home/2024/media/bravo.jpg
  media/img/home/2024/media/chambers.jpg
  media/img/home/2024/media/irl-green.png
  media/img/home/2024/media/irl-orange.png
  media/img/home/2024/media/irl-pink.png
  media/img/home/2024/media/khalifah.jpg
  media/img/home/2024/media/smith.jpg
  media/img/icons/m24-small/download-white.svg
  media/img/icons/m24-small/download.svg
  media/img/icons/m24-small/glasses-white.svg
  media/img/icons/m24-small/glasses.svg
  media/img/icons/m24-small/headphones-white.svg
  media/img/icons/m24-small/headphones.svg
  media/img/icons/m24-small/plus-white.svg
  media/img/icons/m24-small/plus.svg
Labels: Needs Review, Review: S, Frontend, Refresh 🦖

#15537 Fix unmatched closing tag in m24-c-springboard
  bedrock/mozorg/templates/mozorg/home/includes/m24/media-springboard.html
Labels: P3, Needs Review, Review: µ, Refresh 🦖

#14897 Explore more CSP tightening (report-only)
  bedrock/settings/__init__.py
Labels: P3, Needs Review, Backend, Frontend

#15535 Fix navigation menu padding on older browsers (Fixes #15499)
  media/css/m24/components/navigation-refresh.scss
Labels: P3, Needs Review, Review: µ, Refresh 🦖

#15543 Refresh: Tweaks from design review session
  media/css/m24/base.scss
  media/css/m24/components/pencil-banner.scss
  media/css/m24/flag.scss
  media/css/m24/launchpad.scss
  media/css/m24/showcase.scss
Labels: Needs Review, Review: µ, Refresh 🦖

#15511 Add WNP for Firefox 134beta [fix #15489]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx134beta.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/includes/_dark-mode.scss
  media/css/firefox/whatsnew/whatsnew-134beta.scss
  media/img/firefox/whatsnew/whatsnew134beta/foxfood-high-res.png
  media/img/firefox/whatsnew/whatsnew134beta/foxfood.png
  media/static-bundles.json
Labels: Review: XS

#15509 add wnp133 EU, NA, and MOFO pages (fix #15485, #15486, #15487)
  bedrock/firefox/templates/firefox/whatsnew/includes/fx133/donation-common.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx133-donation-eu.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx133-donation-na.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx133-donation.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx133-eu-newsletter.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx133-na-fakespot.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx133-na-mobile.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-133-donation.scss
  media/css/firefox/whatsnew/whatsnew-133-fakespot.scss
  media/css/firefox/whatsnew/whatsnew-133-newsletter.scss
  media/img/firefox/whatsnew/whatsnew133/fox-mailbox.png
  media/img/firefox/whatsnew/whatsnew133/icon-shopping-light.svg
  media/img/firefox/whatsnew/whatsnew133/icon-shopping.svg
  media/img/firefox/whatsnew/whatsnew133/mofo-heart-high-res.png
  media/img/firefox/whatsnew/whatsnew133/mofo-heart.png
  media/img/firefox/whatsnew/whatsnew133/review-checker-high-res.png
  media/img/firefox/whatsnew/whatsnew133/review-checker.png
  media/js/firefox/whatsnew/whatsnew-133-experiment-donation.es6.js
  media/js/firefox/whatsnew/whatsnew-133-experiment-eu.es6.js
  media/js/firefox/whatsnew/whatsnew-133-experiment-na-mobile.es6.js
  media/js/firefox/whatsnew/whatsnew-133-experiment-na.es6.js
  media/static-bundles.json
Labels: Needs Review, Frontend

#15551 remove word per stakeholder request fix (#15485, #15486, #15487)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx133-donation.html
Labels: Needs Review, Review: µ, Frontend

#15528 Refresh: update the font stack and headline weight
  media/css/m24/base.scss
  media/css/m24/root.scss
  media/css/protocol/protocol-mozilla-2024.scss
Labels: Needs Review, Review: µ, Refresh 🦖

#15559 Copy fix for nothing personal page [fix #15558]
  bedrock/firefox/templates/firefox/nothing-personal/index.html
Labels: Needs Review, Review: µ

#15561 Punt 134beta WNP to 135beta [#15489]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx135beta.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-135beta.scss
  media/img/firefox/whatsnew/whatsnew135beta/foxfood-high-res.png
  media/img/firefox/whatsnew/whatsnew135beta/foxfood.png
  media/static-bundles.json
Labels: Needs Review, Review: XS

#15544 Refresh: make pixel transitions a standalone component [fix #15524]
  bedrock/base/templates/includes/protocol/footer/footer-refresh.html
  bedrock/mozorg/templates/mozorg/about/includes/m24/community.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/donate.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/hero.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/media-springboard.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/products.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/resources-gallery.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/showcase.html
  media/css/m24/theme.scss
  media/css/m24/transition.scss
  media/img/m24/pixel-transition.svg
Labels: Needs Review, Review: XS, Refresh 🦖

#15539 Fix invalid role on /leadership modal links (fixes #15538)
  bedrock/mozorg/templates/mozorg/cms/about/blocks/leadership_block.html
  bedrock/mozorg/templates/mozorg/cms/about/leadership.html
  media/js/mozorg/about-leadership.js
Labels: P3, Needs Review, Review: XS

#15573 Refresh: Update .ico file for clarity
  media/img/favicons/mozilla/m24/favicon.ico
Labels: Needs Review, Review: µ, Refresh 🦖

#15534 Add Giving Tuesday fundraising banner (Fixes #15527)
  bedrock/base/templates/includes/banners/fundraiser.html
  bedrock/mozorg/templates/mozorg/home/home-new.html
  bedrock/mozorg/views.py
  media/css/base/banners/fundraiser.scss
  media/img/banners/fundraiser/eoy-2024-photo-200.png
  media/img/banners/fundraiser/eoy-2024-photo-400.png
  media/js/base/banners/fundraiser-experiment.es6.js
  media/js/base/banners/fundraiser.es6.js
  media/static-bundles.json
Labels: P1, Needs Review, Review: XS, Frontend

#15567 Refresh: About page strings (Fix #15299)
  bedrock/mozorg/templates/mozorg/about/includes/m24/amplify.html
  bedrock/mozorg/templates/mozorg/about/includes/m24/careers.html
  bedrock/mozorg/templates/mozorg/about/includes/m24/community.html
  bedrock/mozorg/templates/mozorg/about/includes/m24/intro.html
  bedrock/mozorg/templates/mozorg/about/includes/m24/manifesto.html
  bedrock/mozorg/templates/mozorg/about/index-m24.html
  bedrock/mozorg/views.py
  l10n/en/mozorg/about-m24.ftl
  media/css/m24/feature.scss
Labels: Needs Review, Review: XS, Refresh 🦖

#15576 Add more languages for Giving Tuesday banner (Fixes #15527)
  bedrock/base/templates/includes/banners/fundraiser.html
  bedrock/mozorg/templates/mozorg/home/home-new.html
  bedrock/mozorg/templates/mozorg/home/home-old.html
Labels: P1, Needs Review, Review: µ

#15584 Refresh: About page l10n fixes
  l10n/configs/pontoon.toml
  l10n/en/mozorg/about-m24.ftl
  l10n/en/navigation_refresh.ftl
Labels: L10N, Needs Review, Review: µ, Refresh 🦖

#15582 Bump VPN minimum requirements for iOS 15.0 and up (Fixes #15581)
  bedrock/products/templates/products/vpn/download.html
Labels: P3, Needs Review, Review: µ

#15588 Fix string ID typo in homepage gallery
  bedrock/mozorg/templates/mozorg/home/includes/m24/ai-gallery.html
Labels: L10N, Needs Review

#15589 Refresh: Donation block tweak source order and spacing
  bedrock/mozorg/templates/mozorg/home/includes/m24/donate.html
  media/css/m24/donate.scss
Labels: Needs Review, Review: µ, Frontend, Refresh 🦖
