Repository mozilla/bedrock, pull requests merged in 2024-05, with the labels that each got.

#14407 Add products to product list page
  bedrock/privacy/templates/privacy/notices/mdn-plus.html
  bedrock/products/templates/products/landing.html
  l10n/en/brands.ftl
  l10n/en/firefox/products.ftl
  media/css/products/landing.scss
  media/img/logos/fakespot/logo.svg
  media/img/logos/mdn/mdn-plus-logo.svg
  media/img/logos/thunderbird/logo-thunderbird.svg
  media/img/privacy/icon-mdn-plus.svg
  media/img/products/landing/browsers-high-res.jpg
  media/img/products/landing/browsers.jpg
  media/img/products/landing/firefox-focus-high-res.jpg
  media/img/products/landing/firefox-focus.jpg
  media/img/products/landing/monitor.svg
  media/img/products/landing/pocket.svg
  media/img/products/landing/relay.svg
  media/img/products/landing/vpn.svg
Labels: Review: XS

#14513 Remove redundant product landing tests [#14220]
  tests/functional/products/test_landing.py
  tests/pages/products/landing.py
Labels: Needs Review, Review: µ

#14485 Omit non-essential fields from RTAMO flow (Fixes #14482)
  docs/attribution/0002-firefox-desktop.rst
  docs/download-buttons.rst
  media/js/base/stub-attribution.js
  media/js/firefox/new/common/thanks-direct.es6.js
  media/js/firefox/new/common/thanks-direct.js
  media/static-bundles.json
  tests/unit/spec/base/stub-attribution.js
Labels: P1, Needs Review, Review: XS

#14502 Enable FxA attribution to be optional (Fixes #14488)
  media/js/base/fxa-attribution.es6.js
  media/js/base/fxa-bundle-init.es6.js
  media/js/base/fxa-coupon.es6.js
  media/js/base/fxa-form.es6.js
  media/js/base/fxa-link.es6.js
  tests/unit/spec/base/fxa-attribution.js
  tests/unit/spec/base/fxa-coupon.js
  tests/unit/spec/base/fxa-form.js
Labels: P1, Needs Review, Review: XS

#14547 Change CTA buttons on /products to use secondary theme styling
  bedrock/products/templates/products/landing.html
Labels: P3, Needs Review, Review: µ

#14551 Add John Humphrey to leadership page [fix #14540]
  bedrock/mozorg/templates/mozorg/about/leadership/includes/senior.html
  media/img/mozorg/about/leadership/john-humphrey-high-res.jpg
  media/img/mozorg/about/leadership/john-humphrey.jpg
Labels: Needs Review, Review: µ

#14549 Update Firefox Translation supported languages [fix #14548]
  bedrock/firefox/templates/firefox/features/translate.html
  bedrock/firefox/views.py
  media/css/firefox/features/article.scss
Labels: Needs Review, Review: XS

#14539 H2 2023 Transparency Report
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/reports-nav.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2023.html
  bedrock/mozorg/urls.py
Labels: Needs Review, Review: S

#14557 Update link in `/sustainability/carbon-neutral` page
  bedrock/mozorg/templates/mozorg/sustainability/carbon-neutral.html
Labels: Needs Review, Review: µ

#14546 Add WNP 126 (Fixes #14512)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx126-eu.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx126-na.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-126-eu.scss
  media/css/firefox/whatsnew/whatsnew-126-na.scss
  media/img/firefox/whatsnew/whatsnew126-na/extensions.svg
  media/img/firefox/whatsnew/whatsnew126-na/jigsaw-piece.svg
  media/img/l10n/de/firefox/wnp-126/edit-pdfs-dark.svg
  media/img/l10n/de/firefox/wnp-126/edit-pdfs-light.svg
  media/img/l10n/en-US/firefox/wnp-126/edit-pdfs-dark.svg
  media/img/l10n/en-US/firefox/wnp-126/edit-pdfs-light.svg
  media/img/l10n/es-ES/firefox/wnp-126/edit-pdfs-dark.svg
  media/img/l10n/es-ES/firefox/wnp-126/edit-pdfs-light.svg
  media/img/l10n/fr/firefox/wnp-126/edit-pdfs-dark.svg
  media/img/l10n/fr/firefox/wnp-126/edit-pdfs-light.svg
  media/img/l10n/it/firefox/wnp-126/edit-pdfs-dark.svg
  media/img/l10n/it/firefox/wnp-126/edit-pdfs-light.svg
  media/img/l10n/pl/firefox/wnp-126/edit-pdfs-dark.svg
  media/img/l10n/pl/firefox/wnp-126/edit-pdfs-light.svg
  media/js/firefox/whatsnew/whatsnew-126.js
  media/static-bundles.json
Labels: P1, Review: XS

#14560 Extend 126beta WNP to 127beta [fix #14435]
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
Labels: Needs Review, Review: µ

#14567 Rename PDFs for EU WNP126 [#14512]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx126-eu.html
Labels: Needs Review, Review: µ

#14568 Fix typo in es-ES WNP 126
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx126-eu.html
Labels: Needs Review, Review: µ

#14561 Update donate links and footer [fix #14537]
  bedrock/base/templates/404.html
  bedrock/base/templates/includes/protocol/footer/footer.html
  bedrock/careers/templates/careers/404.html
  bedrock/foundation/templates/foundation/annualreport/2009/broadening-our-scope.html
  bedrock/foundation/templates/foundation/annualreport/2016/index.html
  bedrock/foundation/templates/foundation/annualreport/2017/index.html
  bedrock/foundation/templates/foundation/annualreport/2019/index.html
  bedrock/foundation/templates/foundation/annualreport/2020/index.html
  bedrock/foundation/templates/foundation/annualreport/2021/index.html
  bedrock/foundation/templates/foundation/openwebfund/more.html
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/contact/contact-landing.html
  bedrock/mozorg/templates/mozorg/contribute.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/redirects/redirects.py
  bedrock/settings/base.py
  l10n/en/footer.ftl
  media/css/protocol/components/_footer.scss
  tests/redirects/map_301.py
  tests/redirects/map_globalconf.py
Labels: Needs Review, Review: XS

#14250 Wagtail in Bedrock: main groundwork
  .env-dist
  .gitignore
  bedrock/careers/tests/test_views.py
  bedrock/cms/__init__.py
  bedrock/cms/apps.py
  bedrock/cms/migrations/0001_initial.py
  bedrock/cms/migrations/__init__.py
  bedrock/cms/models.py
  bedrock/cms/templates/cms/base-protocol.html
  bedrock/cms/templates/cms/simple_rich_text_page.html
  bedrock/cms/tests/__init__.py
  bedrock/cms/tests/conftest.py
  bedrock/cms/tests/factories.py
  bedrock/cms/tests/test_models.py
  bedrock/cms/tests/test_rendering.py
  bedrock/contentful/migrations/0007_data_switch_to_local_images.py
  bedrock/mozorg/tests/test_views.py
  bedrock/settings/__init__.py
  bedrock/settings/base.py
  bedrock/urls/mozorg_mode.py
  gcp/bedrock-demos/cloudrun/mozorg-demo.env.yaml
  gcp/bedrock-demos/cloudrun/pocket-demo.env.yaml
  lib/l10n_utils/__init__.py
  media/css/cms/base.scss
  media/static-bundles.json
  requirements/dev.in
  requirements/dev.txt
  requirements/docs.txt
  requirements/prod.in
  requirements/prod.txt
  tests/redirects/test_urls.py
Labels: Review: M

#14589 Update install docs with note to uncheck Rosetta emulation on macOS using Docker (Fixes #14588)
  docs/install.rst
Labels: P3, Needs Review, Review: µ

#14562 Add some docs for the privacy notice templates #14233
  docs/index.rst
  docs/legal-docs.rst
Labels: P3, Needs Review, Review: XS

#14577 Update fallback WNP [fix #14501]
  bedrock/firefox/templates/firefox/whatsnew/index-account.html
  bedrock/firefox/templates/firefox/whatsnew/index.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx122-eu.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  l10n/configs/pontoon.toml
  l10n/en/firefox/whatsnew/whatsnew-account.ftl
  l10n/en/firefox/whatsnew/whatsnew-s2d.ftl
  media/css/firefox/whatsnew/whatsnew-account.scss
  media/css/firefox/whatsnew/whatsnew.scss
  media/img/firefox/whatsnew/qr-wrapper-foxphone.svg
  media/img/firefox/whatsnew/qrcode-firefox-whatsnew.png
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew.py
  tests/functional/firefox/whatsnew/test_whatsnew_60.py
  tests/pages/firefox/whatsnew/whatsnew.py
  tests/pages/firefox/whatsnew/whatsnew_60.py
Labels: Needs Review, Review: XS

#14552 Homepage and global nav updates
  bedrock/base/templates/includes/protocol/navigation/menus/products.html
  bedrock/mozorg/templates/mozorg/home/home-new.html
  bedrock/mozorg/templates/mozorg/home/includes/mofo-donate-promo.html
  l10n/en/brands.ftl
  l10n/en/mozorg/home-new.ftl
  l10n/en/navigation_v2.ftl
  media/css/mozorg/home/home-new.scss
  media/css/mozorg/home/includes/mofo-donate-promo.scss
  media/img/home/2023/colorwaves-high-res.jpg
  media/img/home/2023/colorwaves.jpg
  media/img/home/2023/mofo-heart.svg
  media/img/logos/fakespot/logo-blue.svg
  media/static-bundles.json
  tests/functional/test_home.py
  tests/pages/home.py
Labels: Review: S

#14611 Remove Moz AI and Moz VC Fluent strings from navigation
  l10n/en/navigation_v2.ftl
Labels: Needs Review, Review: µ

#14607 Relaunch browser comparison pages [fix #14336]
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/browsers/compare/base-article.html
  bedrock/firefox/templates/firefox/browsers/compare/brave.html
  bedrock/firefox/templates/firefox/browsers/compare/chrome.html
  bedrock/firefox/templates/firefox/browsers/compare/edge.html
  bedrock/firefox/templates/firefox/browsers/compare/includes/subnav.html
  bedrock/firefox/templates/firefox/browsers/compare/index.html
  bedrock/firefox/templates/firefox/browsers/compare/opera.html
  bedrock/firefox/templates/firefox/browsers/compare/safari.html
  bedrock/firefox/templates/firefox/browsers/mobile/index.html
  bedrock/firefox/templates/firefox/faq.html
  bedrock/firefox/templates/firefox/more.html
  bedrock/firefox/urls.py
  l10n/en/firefox/browsers/compare/brave.ftl
  l10n/en/firefox/browsers/compare/chrome.ftl
  l10n/en/firefox/browsers/compare/edge.ftl
  l10n/en/firefox/browsers/compare/index.ftl
  l10n/en/firefox/browsers/compare/opera.ftl
  l10n/en/firefox/browsers/compare/safari.ftl
  l10n/en/firefox/browsers/compare/shared.ftl
  l10n/en/firefox/browsers/mobile/index.ftl
  media/css/firefox/compare/article.scss
  media/css/firefox/compare/index.scss
  media/img/firefox/compare/article-header.svg
  media/img/firefox/compare/footer-browser-high-res.png
  media/img/firefox/compare/footer-browser.png
  media/img/firefox/compare/header-left.svg
  media/img/firefox/compare/header-right.svg
  media/img/firefox/compare/meta-img-brave.jpg
  media/img/firefox/compare/meta-img-chrome.jpg
  media/img/firefox/compare/meta-img-edge.jpg
  media/img/firefox/compare/meta-img-opera.jpg
  media/img/firefox/compare/meta-img-safari.jpg
  media/js/firefox/browsers/compare-article.es6.js
  media/static-bundles.json
  tests/redirects/map_globalconf.py
Labels: Review: S

#14606 Update security bugs policy known issues URL
  bedrock/mozorg/templates/mozorg/about/governance/policies/security/bugs.html
Labels: Needs Review

#14603 Remove press_blog_url helper
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/settings/base.py
Labels: Needs Review
