Repository mozilla/bedrock, pull requests merged in 2024-08, with the labels that each got.

#14887 Remove MS Store experiment code (#11090)
  bedrock/firefox/templates/firefox/new/desktop/download-ms-store.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/views.py
  media/js/firefox/new/desktop/download-ms-store-exp.es6.js
  media/static-bundles.json
Labels: Papercuts 💸, P3, Review: µ, Frontend

#14976 Fix disappearing reader mode icon on WNP 129 (Fixes #14975)
  media/js/firefox/whatsnew/whatsnew-129-na.js
Labels: P2, Needs Review, Review: µ

#14956 Prefer supplied CTA content for WNP fundraiser buttons
  bedrock/firefox/templates/firefox/whatsnew/includes/mofo-donate-cta.html
Labels: P3, Needs Review, Frontend

#14988 Update list of supported languages on translate feature page [fix #14987]
  bedrock/firefox/templates/firefox/features/translate.html
  bedrock/firefox/views.py
Labels: Needs Review, Review: µ

#14862 Add a11y test job running against key pages (#14773)
  .github/workflows/a11y_tests.yml
  .github/workflows/integration_tests.yml
  .gitignore
  bedrock/base/templates/macros.html
  docs/testing.rst
  tests/playwright/global-setup.js
  tests/playwright/package-lock.json
  tests/playwright/package.json
  tests/playwright/playwright.config.js
  tests/playwright/specs/a11y/components.spec.js
  tests/playwright/specs/a11y/includes/helpers.js
  tests/playwright/specs/a11y/includes/locators.js
  tests/playwright/specs/a11y/includes/urls.js
  tests/playwright/specs/a11y/pages.spec.js
Labels: P3, Needs Review, Review: XS, Frontend

#15006 update leadership bio [fix #14994]
  bedrock/mozorg/templates/mozorg/about/leadership/includes/mofo.html
Labels: Needs Review, Review: µ, Frontend

#14990 Add WNP 130 (Fixes #14946)
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx130.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-130.scss
  media/img/l10n/de/firefox/wnp-130/duplicate-tabs-1000.gif
  media/img/l10n/de/firefox/wnp-130/duplicate-tabs-1000.png
  media/img/l10n/de/firefox/wnp-130/duplicate-tabs-500.gif
  media/img/l10n/de/firefox/wnp-130/duplicate-tabs-500.png
  media/img/l10n/en-US/firefox/wnp-130/duplicate-tabs-1000.gif
  media/img/l10n/en-US/firefox/wnp-130/duplicate-tabs-1000.png
  media/img/l10n/en-US/firefox/wnp-130/duplicate-tabs-500.gif
  media/img/l10n/en-US/firefox/wnp-130/duplicate-tabs-500.png
  media/img/l10n/es-ES/firefox/wnp-130/duplicate-tabs-1000.gif
  media/img/l10n/es-ES/firefox/wnp-130/duplicate-tabs-1000.png
  media/img/l10n/es-ES/firefox/wnp-130/duplicate-tabs-500.gif
  media/img/l10n/es-ES/firefox/wnp-130/duplicate-tabs-500.png
  media/img/l10n/fr/firefox/wnp-130/duplicate-tabs-1000.gif
  media/img/l10n/fr/firefox/wnp-130/duplicate-tabs-1000.png
  media/img/l10n/fr/firefox/wnp-130/duplicate-tabs-500.gif
  media/img/l10n/fr/firefox/wnp-130/duplicate-tabs-500.png
  media/img/l10n/it/firefox/wnp-130/duplicate-tabs-1000.gif
  media/img/l10n/it/firefox/wnp-130/duplicate-tabs-1000.png
  media/img/l10n/it/firefox/wnp-130/duplicate-tabs-500.gif
  media/img/l10n/it/firefox/wnp-130/duplicate-tabs-500.png
  media/img/l10n/pl/firefox/wnp-130/duplicate-tabs-1000.gif
  media/img/l10n/pl/firefox/wnp-130/duplicate-tabs-1000.png
  media/img/l10n/pl/firefox/wnp-130/duplicate-tabs-500.gif
  media/img/l10n/pl/firefox/wnp-130/duplicate-tabs-500.png
  media/js/firefox/whatsnew/whatsnew-130.js
  media/static-bundles.json
Labels: P1, Review: XS

#14885 Update URLs to use `uuid` path converter
  bedrock/newsletter/tests/test_views.py
  bedrock/newsletter/urls.py
  bedrock/newsletter/views.py
Labels: Backend

#15012 Leadership page, update Surman’s bio [#14994]
  bedrock/mozorg/templates/mozorg/about/leadership/includes/mofo.html
Labels: Needs Review, Review: µ

#15019 No longer exclude root page for zh-CN route
  bedrock/sitemaps/utils.py
Labels: Backend

#15018 Fix heading levels on /products/ page (Fixes #15002)
  bedrock/products/templates/products/landing.html
Labels: P3, Needs Review, Review: µ, Frontend

#15017 Fix landmark and heading levels on /about/ page (Fixes #15001)
  bedrock/mozorg/templates/mozorg/about/index.html
Labels: P3, Needs Review, Review: µ, Frontend

#14886 Selenium cleanup
  tests/functional/firefox/browsers/test_best_browser.py
  tests/functional/firefox/more/__init__.py
  tests/functional/firefox/more/test_misinformation.py
  tests/functional/firefox/test_pocket.py
  tests/functional/firefox/test_switch.py
  tests/functional/test_lean_data.py
  tests/pages/firefox/browsers/best_browser.py
  tests/pages/firefox/more/__init__.py
  tests/pages/firefox/more/misinformation.py
  tests/pages/firefox/pocket.py
  tests/pages/firefox/switch.py
  tests/pages/lean_data.py
Labels: P3, Needs Review, Backend, Review: µ, Frontend

#14933 Update contribute, MDN, wiki redirects
  bedrock/mozorg/redirects.py
  tests/redirects/map_globalconf.py
  tests/redirects/map_htaccess.py
Labels: P3, Needs Review, Backend, Review: XS

#14942 Stop showing mobile store banners for current users
  media/js/base/banners/firefox-app-store-banner.es6.js
Labels: P3, Needs Review, Frontend

#14324 Explore changing /firefox/all/ to be less process intensive.
  bedrock/base/templates/product-all-unified-macros.html
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/all-unified.html
  bedrock/firefox/templates/firefox/all/base.html
  bedrock/firefox/templates/firefox/all/download.html
  bedrock/firefox/templates/firefox/all/lang.html
  bedrock/firefox/templates/firefox/all/mobile.html
  bedrock/firefox/templates/firefox/all/platform.html
  bedrock/firefox/templates/firefox/all/product.html
  bedrock/firefox/templates/firefox/includes/download-unsupported.html
  bedrock/firefox/templatetags/helpers.py
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/tests/test_firefox_all.py
  bedrock/firefox/tests/test_helpers.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  l10n/en/firefox/all.ftl
  l10n/en/firefox/enterprise.ftl
  media/css/firefox/all.scss
  media/css/firefox/all/all-unified-old-ie.scss
  media/css/firefox/all/all-unified.scss
  media/img/firefox/all/icon-question-high-res.png
  media/img/firefox/all/icon-question.png
  media/img/firefox/all/icon-question.svg
  media/img/logos/testflight/testflight.svg
  media/js/base/stub-attribution/stub-attribution.js
  media/js/firefox/all/all-downloads-unified.js
  media/js/firefox/all/all-init.es6.js
  media/static-bundles.json
  tests/functional/firefox/test_all.py
  tests/pages/firefox/all.py
  tests/redirects/map_globalconf.py
  tests/unit/spec/firefox/all/all-downloads-unified.js
  webpack.test.config.js
Labels: Needs Review, Backend, Review: L, Frontend

#15016 Add aria-label to aside landmarks on home page (Fixes #15000)
  bedrock/base/templates/includes/banners/base.html
  bedrock/base/templates/includes/banners/basic.html
  bedrock/base/templates/includes/banners/mobile/firefox-app-store.html
  bedrock/base/templates/includes/banners/mobile/focus-app-store.html
  bedrock/mozorg/templates/mozorg/home/home-new.html
  l10n/en/banners/firefox-app-store.ftl
  l10n/en/newsletter_form.ftl
  l10n/en/ui.ftl
Labels: P3, Needs Review, Review: µ, Frontend

#15023 Add mobile app store badges to nothing-personal campaign page (Fixes #15020)
  bedrock/firefox/templates/firefox/nothing-personal/index.html
  media/css/firefox/nothing-personal/_primary-cta.scss
Labels: P2, Needs Review, Review: XS, Frontend

#14992 Bump glean.js to v5.0.3 and glean-parser to v14.5.0
  docs/attribution/0001-analytics.rst
  package-lock.json
  package.json
  requirements/dev.txt
  requirements/prod.in
  requirements/prod.txt
Labels: P3, Needs Review, Review: µ

#15028 Add email campaign IDs to app store redirector (Fixes #15027)
  bedrock/firefox/redirects.py
Labels: P2, Needs Review, Review: µ

#15031 Fix failing integration test on /all
  tests/functional/firefox/test_all.py
Labels: P1, Needs Review, Review: µ

#15035 Add default WNP fallback variant to WNP 130 URLs (Fixes #15034)
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
Labels: P1, Needs Review, Review: µ

#15032 Add Firefox built for you landing page [fix #14985]
  bedrock/firefox/templates/firefox/built-for-you/includes/v1-pinocchio-de.html
  bedrock/firefox/templates/firefox/built-for-you/includes/v1-pinocchio-fr.html
  bedrock/firefox/templates/firefox/built-for-you/includes/v2-superhero-de.html
  bedrock/firefox/templates/firefox/built-for-you/includes/v2-superhero-fr.html
  bedrock/firefox/templates/firefox/built-for-you/includes/v3-sloth.html
  bedrock/firefox/templates/firefox/built-for-you/includes/v4-alien.html
  bedrock/firefox/templates/firefox/built-for-you/includes/v5-human.html
  bedrock/firefox/templates/firefox/built-for-you/landing.de.html
  bedrock/firefox/templates/firefox/built-for-you/landing.fr.html
  bedrock/firefox/urls.py
  media/css/firefox/built-for-you/landing.scss
  media/img/firefox/built-for-you/alien-1000.jpg
  media/img/firefox/built-for-you/alien-1200.jpg
  media/img/firefox/built-for-you/alien-600.jpg
  media/img/firefox/built-for-you/alien-800.jpg
  media/img/firefox/built-for-you/choose.svg
  media/img/firefox/built-for-you/human-desktop-1000.jpg
  media/img/firefox/built-for-you/human-desktop-1200.jpg
  media/img/firefox/built-for-you/human-desktop-800.jpg
  media/img/firefox/built-for-you/human-mobile-1000.jpg
  media/img/firefox/built-for-you/human-mobile-600.jpg
  media/img/firefox/built-for-you/human-mobile-800.jpg
  media/img/firefox/built-for-you/icon-pdf-editor.svg
  media/img/firefox/built-for-you/icon-picture-in-picture.svg
  media/img/firefox/built-for-you/icon-sync.svg
  media/img/firefox/built-for-you/icon-translation.svg
  media/img/firefox/built-for-you/meta-de.jpg
  media/img/firefox/built-for-you/meta-fr.jpg
  media/img/firefox/built-for-you/pinocchio-1000.jpg
  media/img/firefox/built-for-you/pinocchio-1200.jpg
  media/img/firefox/built-for-you/pinocchio-600.jpg
  media/img/firefox/built-for-you/pinocchio-800.jpg
  media/img/firefox/built-for-you/privacy-high-res.png
  media/img/firefox/built-for-you/privacy.png
  media/img/firefox/built-for-you/sloth-1000.jpg
  media/img/firefox/built-for-you/sloth-1200.jpg
  media/img/firefox/built-for-you/sloth-600.jpg
  media/img/firefox/built-for-you/sloth-800.jpg
  media/img/firefox/built-for-you/speed-high-res.jpg
  media/img/firefox/built-for-you/speed.jpg
  media/img/firefox/built-for-you/superhero-1000.jpg
  media/img/firefox/built-for-you/superhero-1200.jpg
  media/img/firefox/built-for-you/superhero-600.jpg
  media/img/firefox/built-for-you/superhero-800.jpg
  media/img/firefox/built-for-you/trackers-high-res.png
  media/img/firefox/built-for-you/trackers.png
  media/js/base/consent/allow-list.es6.js
  media/static-bundles.json
Labels: Review: XS

#14935 Update Wagtail/ Smartling integration on the Bedrock side
  bedrock/cms/management/commands/run_smartling_sync.py
  bedrock/cms/models/base.py
  bedrock/settings/base.py
Labels: Do Not Merge :warning:
