Repository mozilla/bedrock, pull requests merged in 2024-02, with the labels that each got.

#14133 Update strings for Firefox Features Translate page [fix #14134]
  bedrock/firefox/templates/firefox/features/translate.html
Labels: Needs Review, Review: XS

#14138 Updated public license FAQ [fixes #14137]
  bedrock/mozorg/templates/mozorg/mpl/2.0/faq.html
  media/css/mozorg/license-faq.scss
  media/static-bundles.json
Labels: Review: XS

#14168 Remove `mobile/compare` page and references
  bedrock/base/templates/includes/banners/mobile/mobile-compare.html
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/browsers/compare/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/compare.html
  bedrock/firefox/templates/firefox/browsers/mobile/includes/sub-nav.html
  bedrock/firefox/templates/firefox/browsers/mobile/index.html
  bedrock/firefox/urls.py
  l10n/en/firefox/browsers/compare/index.ftl
  l10n/en/firefox/browsers/mobile/compare.ftl
  l10n/en/firefox/browsers/mobile/index.ftl
  media/css/base/banners/mobile-compare.scss
  media/css/firefox/browsers-products.scss
  media/img/firefox/browsers/mobile/compare-mobile-browsers.svg
  media/img/firefox/browsers/mobile/index/compare-mobile-browsers.svg
  media/js/base/banners/mobile-compare-banner-init.js
  media/static-bundles.json
  tests/redirects/map_globalconf.py
Labels: Review: XS

#14174 More string fixes for Linux download buttons
  bedrock/firefox/templates/firefox/includes/download-button.html
  bedrock/firefox/templates/firefox/includes/macros.html
  bedrock/firefox/templates/firefox/new/basic/thanks.html
  bedrock/firefox/templates/firefox/new/desktop/thanks.html
  l10n/en/download_button.ftl
Labels: Needs Review, Review: µ

#14130 Port Challenge the Default landing page to French
  bedrock/firefox/templates/firefox/challenge-the-default/includes/hero-v2.html
  bedrock/firefox/templates/firefox/challenge-the-default/includes/hero-v3.html
  bedrock/firefox/templates/firefox/challenge-the-default/includes/hero-v4.html
  bedrock/firefox/templates/firefox/challenge-the-default/includes/hero-v5.html
  bedrock/firefox/templates/firefox/challenge-the-default/includes/hero.html
  bedrock/firefox/templates/firefox/challenge-the-default/includes/heroes/hero-v1.html
  bedrock/firefox/templates/firefox/challenge-the-default/includes/heroes/hero-v2.html
  bedrock/firefox/templates/firefox/challenge-the-default/includes/heroes/hero-v3.html
  bedrock/firefox/templates/firefox/challenge-the-default/includes/heroes/hero-v4.html
  bedrock/firefox/templates/firefox/challenge-the-default/includes/heroes/hero-v5.html
  bedrock/firefox/templates/firefox/challenge-the-default/includes/heroes/hero-v6.html
  bedrock/firefox/templates/firefox/challenge-the-default/includes/toggles.html
  bedrock/firefox/templates/firefox/challenge-the-default/includes/wednesday.html
  bedrock/firefox/templates/firefox/challenge-the-default/landing-base.html
  bedrock/firefox/templates/firefox/challenge-the-default/landing-switch.html
  bedrock/firefox/templates/firefox/challenge-the-default/langs/landing.de.html
  bedrock/firefox/templates/firefox/challenge-the-default/langs/landing.fr.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  media/css/firefox/challenge-the-default/_hero.scss
  media/css/firefox/challenge-the-default/index.scss
  media/img/firefox/challenge-the-default/ctd-share-fr.png
  media/img/firefox/challenge-the-default/ctd-share.png
  media/img/firefox/challenge-the-default/logo-ctd-fr.svg
Labels: Needs Review, Review: S

#14178 Fix JS error in GA4 event tracking (Fixes #14177)
  media/js/base/datalayer-productdownload.es6.js
Labels: P2, Needs Review, Review: µ

#14143 Add Monitor plus Banner to homepage
  bedrock/base/templates/includes/banners/monitor-plus.html
  bedrock/mozorg/templates/mozorg/home/home-new.html
  bedrock/mozorg/templates/mozorg/home/includes/monitor-mid-banner.html
  media/css/mozorg/home/includes/monitor-banner.scss
  media/img/home/2023/mozilla-monitor-logo-hor.svg
  media/img/home/2023/mozilla-monitor-logo-ver.svg
  media/js/mozorg/home/monitor-banner-init.js
  media/static-bundles.json
Labels: Needs Review, Review: XS

#14114 Update Monitor copy [Feb 6th]
  bedrock/firefox/templates/firefox/accounts.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/privacy/products.html
  bedrock/firefox/templates/firefox/products/index.html
  bedrock/mozorg/templates/mozorg/home/home-new.html
  bedrock/newsletter/templates/newsletter/updated.html
  l10n/en/mozorg/home-new.ftl
  media/css/mozorg/home/home-new.scss
Labels: Needs Review, Review: XS

#14180 Remove hard-coded English strings from VPN nav CTA (Fixes #14179)
  bedrock/products/templates/products/vpn/includes/macros.html
Labels: P2, Needs Review, Review: µ

#14187 Redirect Firefox Monitor privacy notice to subscription-services notice (Fixes #14186)
  bedrock/privacy/redirects.py
  bedrock/privacy/templates/privacy/archive/firefox-monitor-2024-02.html
  bedrock/privacy/templates/privacy/archive/index.html
  bedrock/privacy/templates/privacy/notices/firefox-monitor.html
  bedrock/privacy/urls.py
  bedrock/privacy/views.py
  tests/redirects/map_globalconf.py
Labels: P2, Needs Review, Review: XS

#14190 Remove second Monitor CTA from Firefox products page [#14188]
  bedrock/firefox/templates/firefox/products/index.html
  tests/functional/firefox/test_products.py
  tests/pages/firefox/products.py
Labels: Bug :bug:, Review: µ

#14144 VPN landing page headline experiment [fix #14131]
  bedrock/products/templates/products/vpn/landing-refresh.html
  bedrock/products/templates/products/vpn/landing.html
  bedrock/products/templates/products/vpn/variants/landing-1.html
  bedrock/products/templates/products/vpn/variants/landing-2.html
  bedrock/products/templates/products/vpn/variants/landing-refresh-1.html
  bedrock/products/templates/products/vpn/variants/landing-refresh-2.html
  bedrock/products/tests/test_views.py
  bedrock/products/views.py
  media/css/products/vpn/common-refresh.scss
  media/js/products/vpn/landing-experiment-headlines.es6.js
  media/js/products/vpn/landing-experiment-pricing-position.es6.js
  media/static-bundles.json
Labels: Review: XS

#14196 Fix footer community link formatting on CTD page [fix #14192]
  bedrock/firefox/templates/firefox/challenge-the-default/landing-base.html
Labels: Bug :bug:, Review: µ

#14125 Remove adjust links (Fixes #11698)
  bedrock/base/templates/includes/banners/mobile/firefox-app-store.html
  bedrock/base/templates/includes/banners/mobile/focus-app-store.html
  bedrock/firefox/templates/firefox/browsers/chromebook.html
  bedrock/firefox/templates/firefox/browsers/compare/includes/download-menu-list.html
  bedrock/firefox/templates/firefox/browsers/compare/safari.html
  bedrock/firefox/templates/firefox/browsers/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/android.html
  bedrock/firefox/templates/firefox/browsers/mobile/focus.html
  bedrock/firefox/templates/firefox/browsers/mobile/get-app.html
  bedrock/firefox/templates/firefox/browsers/mobile/get-ios.html
  bedrock/firefox/templates/firefox/browsers/mobile/index.html
  bedrock/firefox/templates/firefox/browsers/mobile/ios.html
  bedrock/firefox/templates/firefox/contentful-all.html
  bedrock/firefox/templates/firefox/facebookcontainer/index.html
  bedrock/firefox/templates/firefox/home/index-master.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/products/index.html
  bedrock/firefox/templates/firefox/releases/release-notes.html
  bedrock/firefox/templates/firefox/welcome/page17/page17-b.html
  bedrock/firefox/templates/firefox/welcome/page4.html
  bedrock/firefox/templates/firefox/welcome/page6.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx114-en.html
  bedrock/landing/templates/landing/firefox/fx100.html
  bedrock/mozorg/templates/mozorg/contentful-all.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/settings/appstores.py
  bedrock/settings/base.py
  docs/attribution/0003-firefox-mobile.rst
  media/js/base/datalayer-productdownload.es6.js
  tests/unit/spec/base/datalayer-productdownload.js
  tests/unit/spec/firefox/all/all-downloads-unified.js
Labels: P2, Needs Review, Review: S

#14205 Copy update on French CTD page [fix #14169]
  bedrock/firefox/templates/firefox/challenge-the-default/langs/landing.fr.html
Labels: Needs Review, Review: µ

#14206 Replaced non-Mozilla product Fluent terms w/ regular string in `/browsers/compare/` update
  l10n/en/firefox/browsers/compare/index.ftl
  l10n/en/firefox/more.ftl
Labels: Needs Review, Review: µ

#14195 Add WNP 123 for EU + NA [fixes #14181]
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx123-eu.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx123-na.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-123-eu.scss
  media/css/firefox/whatsnew/whatsnew-123-na.scss
  media/img/firefox/whatsnew/whatsnew-123-na/search-high-res.png
  media/img/firefox/whatsnew/whatsnew-123-na/search-icon.svg
  media/img/firefox/whatsnew/whatsnew-123-na/search.png
  media/img/firefox/whatsnew/whatsnew123-eu/reader-icon.svg
  media/js/firefox/whatsnew/whatsnew-123-eu.js
  media/js/firefox/whatsnew/whatsnew-123-na.js
  media/static-bundles.json
  tests/functional/firefox/whatsnew/test_whatsnew_123.py
  tests/pages/firefox/whatsnew/whatsnew_123.py
Labels: Needs Review, Review: S

#14208 Add mobile app store redirector (Issue #14172)
  bedrock/firefox/redirects.py
  bedrock/redirects/util.py
  tests/redirects/map_globalconf.py
Labels: Needs Review, Review: XS

#14212 Fix /careers/diversity/ video error (Fixes #14211)
  bedrock/careers/templates/careers/diversity.html
Labels: P2, Needs Review, Review: µ

#14207 Enable attribution for all macOS Firefox download links (Fixes #12761)
  media/js/base/stub-attribution.js
  media/js/firefox/all/all-downloads-unified.js
  tests/unit/spec/base/stub-attribution.js
  tests/unit/spec/firefox/all/all-downloads-unified.js
Labels: Do Not Merge :warning:, Needs Review, Review: XS

#14218 Fix release notes header branding [fix #14214]
  bedrock/firefox/templates/firefox/releases/aurora-notes.html
  bedrock/firefox/templates/firefox/releases/beta-notes.html
  bedrock/firefox/templates/firefox/releases/dev-browser-notes.html
  bedrock/firefox/templates/firefox/releases/nightly-notes.html
  bedrock/firefox/templates/firefox/releases/notes.html
  media/css/firefox/releasenotes.scss
Labels: Bug :bug:, Needs Review, Review: XS

#14219 Update Mitchell Baker's title in homepage
  bedrock/mozorg/templates/mozorg/home/home-new.html
  l10n/en/mozorg/home-new.ftl
Labels: Needs Review, Review: µ

#14241 Add Impressum link to /de/ footer (Fixes #14240)
  bedrock/base/templates/includes/protocol/footer/footer.html
Labels: P2, Needs Review, Review: µ

#14242 Move /firefox/products/ to /products/ (Fixes #14221)
  bedrock/base/templates/includes/protocol/navigation/menus/products.html
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/faq.html
  bedrock/firefox/urls.py
  bedrock/mozorg/redirects.py
  bedrock/products/templates/products/landing.html
  bedrock/products/urls.py
  l10n/en/firefox/faq.ftl
  l10n/en/firefox/products.ftl
  media/css/firefox/browsers-products.scss
  media/css/products/landing.scss
  media/img/firefox/products/fxa.svg
  media/img/firefox/products/hero-high-res.jpg
  media/img/firefox/products/hero.jpg
  media/img/products/landing/browsers-high-res.jpg
  media/img/products/landing/browsers.jpg
  media/img/products/landing/firefox-focus-high-res.jpg
  media/img/products/landing/firefox-focus.jpg
  media/img/products/landing/monitor.svg
  media/img/products/landing/pocket.svg
  media/img/products/landing/relay.svg
  media/img/products/landing/vpn.svg
  media/js/mozorg/products.es6.js
  media/static-bundles.json
  tests/functional/firefox/test_products.py
  tests/functional/products/test_landing.py
  tests/pages/firefox/products.py
  tests/pages/products/landing.py
  tests/pages/regions/menu_list.py
  tests/redirects/map_301.py
  tests/redirects/map_globalconf.py
Labels: P2, Needs Review, Review: XS

#14254 Add Rise25 nomination page [fix #14200]
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/rise25/includes/hero-video.html
  bedrock/mozorg/templates/mozorg/rise25/includes/social-share.html
  bedrock/mozorg/templates/mozorg/rise25/landing.html
  bedrock/mozorg/templates/mozorg/rise25/thanks.html
  bedrock/mozorg/urls.py
  media/css/mozorg/rise25/_lib.scss
  media/css/mozorg/rise25/components/blog.scss
  media/css/mozorg/rise25/components/category.scss
  media/css/mozorg/rise25/components/faq.scss
  media/css/mozorg/rise25/components/hero.scss
  media/css/mozorg/rise25/components/promote.scss
  media/css/mozorg/rise25/components/social.scss
  media/css/mozorg/rise25/rise25.scss
  media/fonts/rise25/Inter-Black.woff
  media/fonts/rise25/Inter-Black.woff2
  media/fonts/rise25/Inter-ExtraBold.woff
  media/fonts/rise25/Inter-ExtraBold.woff2
  media/img/mozorg/rise25/blog-thumbnail-high-res.jpg
  media/img/mozorg/rise25/blog-thumbnail.jpg
  media/img/mozorg/rise25/hero-poster-high-res.jpg
  media/img/mozorg/rise25/hero-poster.jpg
  media/img/mozorg/rise25/hero-thumb-high-res.jpg
  media/img/mozorg/rise25/hero-thumb.jpg
  media/img/mozorg/rise25/page-image.jpg
  media/img/mozorg/rise25/play-button.svg
  media/img/mozorg/rise25/rise25-wordmark-white.svg
  media/img/mozorg/rise25/winners-poster-high-res.jpg
  media/img/mozorg/rise25/winners-poster.jpg
  media/js/mozorg/rise25/rise25.js
  media/static-bundles.json
  tests/redirects/map_globalconf.py
Labels: Needs Review, Review: S

#14255 Update Rise25 nomination page URL [#14200]
  bedrock/mozorg/redirects.py
  bedrock/mozorg/urls.py
  media/js/mozorg/rise25/rise25.js
  tests/redirects/map_globalconf.py
Labels: Bug :bug:, Fire :fire:, Review: µ

#14261 Convert translation feature page to Fluent [fix #14257]
  bedrock/firefox/templates/firefox/features/index.html
  bedrock/firefox/templates/firefox/features/translate.html
  bedrock/firefox/views.py
  l10n/en/firefox/features/index-2023.ftl
  l10n/en/firefox/features/translate.ftl
Labels: Needs Review, Review: XS

#14258 Rise25, add image to Twitter card metadata [#14200]
  bedrock/mozorg/templates/mozorg/rise25/landing.html
Labels: Bug :bug:, Needs Review, Review: µ

#14041 Updating Twitter references and icons to Xitter [fixes #13980]
  bedrock/base/templates/includes/protocol/footer/footer.html
  bedrock/careers/templates/careers/includes/footer.html
  bedrock/firefox/templates/firefox/nightly/whatsnew.html
  bedrock/firefox/templates/firefox/privacy/book.html
  bedrock/firefox/templates/firefox/releases/nightly-notes.html
  bedrock/mozorg/templates/mozorg/about/leadership/includes/boards.html
  bedrock/mozorg/templates/mozorg/about/leadership/includes/executive.html
  bedrock/mozorg/templates/mozorg/about/leadership/includes/mofo.html
  bedrock/mozorg/templates/mozorg/about/leadership/includes/senior.html
  bedrock/mozorg/templates/mozorg/about/manifesto.html
  bedrock/mozorg/templates/mozorg/contact/contact-landing.html
  bedrock/newsletter/templates/newsletter/opt-out-confirmation.html
  bedrock/pocket/templates/pocket/contact-info.html
  bedrock/pocket/templates/pocket/includes/footer-platform.html
  bedrock/stories/templates/stories/stories-base-article.html
  l10n/en/firefox/nightly/whatsnew.ftl
  l10n/en/firefox/privacy/book.ftl
  l10n/en/footer.ftl
  l10n/en/mozorg/about/manifesto.ftl
  l10n/en/newsletter/opt-out-confirmation.ftl
  media/css/careers/components/footer.scss
  media/css/firefox/switch.scss
  media/css/firefox/welcome11.scss
  media/css/firefox/welcome12.scss
  media/css/firefox/welcome13.scss
  media/css/firefox/welcome15.scss
  media/css/firefox/welcome16.scss
  media/css/firefox/welcome17.scss
  media/css/firefox/whatsnew/includes/_dark-mode.scss
  media/css/mozorg/leadership.scss
  media/css/newsletter/newsletter-opt-out-confirmation.scss
  media/css/pocket/includes/_footer.scss
  media/css/pocket/includes/_platform-footer.scss
  media/css/protocol/components/_footer.scss
  media/css/stories/stories-article.scss
  media/img/logos/social/social-icon-sprite-dark.svg
  media/img/logos/social/social-icon-sprite.svg
  media/img/logos/social/x-icon-black.svg
  media/img/logos/social/x-icon-white.svg
Labels: Review: S

#14234 Remove Hubs from navigation
  bedrock/base/templates/includes/protocol/navigation/menus/innovation.html
  l10n/en/navigation.ftl
  l10n/en/navigation_v2.ftl
  media/css/protocol/components/_menu-item.scss
  media/img/nav/icons/icon-mozilla-hubs.svg
Labels: Do Not Merge :warning:

#14236 Remove one-off campaign pages (Fixes #14231)
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/flashback/index.de.html
  bedrock/firefox/templates/firefox/flashback/index.fr.html
  bedrock/firefox/templates/firefox/flashback/index.html
  bedrock/firefox/urls.py
  bedrock/landing/__init__.py
  bedrock/landing/models.py
  bedrock/landing/templates/landing/base-landing.html
  bedrock/landing/templates/landing/firefox/fx100.html
  bedrock/landing/templates/landing/includes/footer.html
  bedrock/landing/urls.py
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/santa-locator.html
  bedrock/mozorg/urls.py
  bedrock/settings/base.py
  bedrock/urls/mozorg_mode.py
  media/css/firefox/flashback/flashback.scss
  media/css/landing/landing-shared.scss
  media/css/mozorg/santa-locator.scss
  media/img/firefox/flashback/og-de.jpg
  media/img/firefox/flashback/og-fr.jpg
  media/img/firefox/flashback/og.png
  media/img/firefox/flashback/panda-high-res.jpg
  media/img/firefox/flashback/panda.jpg
  media/img/mozorg/santa-locator/apple-touch-icon.png
  media/img/mozorg/santa-locator/favicon-196x196.png
  media/img/mozorg/santa-locator/favicon.png
  media/img/mozorg/santa-locator/page-image.png
  media/img/mozorg/santa-locator/panda-clause-sprite.png
  media/img/mozorg/santa-locator/panda-clause.png
  media/js/landing/landing-shared.js
  media/js/mozorg/santa-locator.js
  media/static-bundles.json
  tests/redirects/map_globalconf.py
Labels: P3, Needs Review, Review: XS

#14263 String fixes for Translation page
  bedrock/firefox/templates/firefox/features/translate.html
  bedrock/firefox/templates/firefox/nightly/whatsnew.html
  l10n/en/firefox/features/translate.ftl
  l10n/en/firefox/nightly/whatsnew.ftl
Labels: Review: µ
