Repository mozilla/bedrock, pull requests merged in 2025-05, with the labels that each got.

#15784 Enable Tajik localization in prod
  bedrock/settings/base.py
Labels: L10N

#16241 add new variants for whatsnew evergreen page (fix #16229)
  bedrock/firefox/templates/firefox/whatsnew/index.html
  media/css/firefox/whatsnew/whatsnew.scss
  media/img/firefox/whatsnew/qr-wrapper-foxphone-spring.svg
  media/img/firefox/whatsnew/qrcode-firefox-whatsnew-variant-a.png
  media/img/firefox/whatsnew/qrcode-firefox-whatsnew-variant-b.png
Labels: Needs Review, Frontend, WMO and FXC

#16240 Linearize ToS tables on product variant (Fix #16235)
  media/css/privacy/privacy-firefox-simple.scss
Labels: Review: µ, Frontend

#16234 Mozilla new products
  bedrock/base/templates/includes/protocol/navigation/menus-refresh/about-us.html
  l10n/en/navigation_refresh.ftl
Labels: Frontend

#16242 Monitor articles are ordered using wagtail "path" field
  bedrock/products/models.py
Labels: Needs Review, Review: XS

#16243 Add firefox gaming landing page (Fixes #15920)
  bedrock/firefox/templates/firefox/landing/gaming.html
  bedrock/firefox/urls.py
  media/img/firefox/landing/gaming/gamers-1000.png
  media/img/firefox/landing/gaming/gamers-1200.png
  media/img/firefox/landing/gaming/gamers-400.png
  media/img/firefox/landing/gaming/gamers-600.png
  media/img/firefox/landing/gaming/gamers-800.png
  media/img/firefox/landing/gaming/hero-1000.png
  media/img/firefox/landing/gaming/hero-400.png
  media/img/firefox/landing/gaming/hero-600.png
  media/img/firefox/landing/gaming/hero-800.png
  media/img/firefox/landing/gaming/icon-augmented-steam-128.png
  media/img/firefox/landing/gaming/icon-augmented-steam-64.png
  media/img/firefox/landing/gaming/icon-bitwarden-128.png
  media/img/firefox/landing/gaming/icon-bitwarden-64.png
  media/img/firefox/landing/gaming/icon-customize.svg
  media/img/firefox/landing/gaming/icon-enhancer-128.png
  media/img/firefox/landing/gaming/icon-enhancer-64.png
  media/img/firefox/landing/gaming/icon-privacy.svg
  media/img/firefox/landing/gaming/icon-stream.svg
  media/img/firefox/landing/gaming/og.png
  media/js/base/consent/allow-list.es6.js
Labels: Review: XS, Frontend

#16250 Increase visibility of help link on download thanks
  media/css/firefox/new/basic/thanks.scss
  media/css/firefox/new/desktop/thanks.scss
Labels: Needs Review, Review: µ, Frontend, WMO and FXC

#16258 Update firefox download button docs
  docs/docs/download-buttons.md
  docs/mkdocs.yml
Labels: Needs Review, Documentation :memo:, Review: XS, Frontend

#16262 Remove Firefox family logo (Fixes #16252)
  bedrock/firefox/templates/firefox/browsers/browser-history.html
  bedrock/firefox/templates/firefox/browsers/what-is-a-browser.html
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/faq.html
  bedrock/firefox/templates/firefox/includes/sub-nav-firefox.html
  bedrock/privacy/templates/privacy/archive/firefox-relay-2022-10.html
Labels: Needs Review, Review: µ, Frontend, WMO and FXC

#16269 Remove CJMS affiliate code (Fixes #16268)
  bedrock/products/templates/products/vpn/landing-refresh.html
  bedrock/products/templates/products/vpn/pricing-refresh.html
  bedrock/products/tests/test_views.py
  bedrock/products/views.py
  bedrock/settings/__init__.py
  bedrock/settings/base.py
  docs/docs/attribution/0005-affiliate-marketing.md
  docs/docs/attribution/0005-consent-management.md
  docs/docs/attribution/index.md
  docs/mkdocs.yml
  media/js/base/experiment-utils.es6.js
  media/js/products/shared/affiliate-attribution.es6.js
  media/js/products/shared/affiliate-consent.es6.js
  media/js/products/shared/affiliate-init.es6.js
  media/static-bundles.json
  tests/unit/spec/base/experiment-utils.js
  tests/unit/spec/products/shared/affiliate-attribution.js
  tests/unit/spec/products/shared/affiliate-consent.js
Labels: Review: XS, Frontend

#16280 Update cookie banner docs with debug info
  docs/docs/attribution/0005-consent-management.md
Labels: Needs Review, Documentation :memo:, Review: µ

#16276 Allow crawl of whatsnew and firstrun so they are deindexed (#16275)
  bedrock/mozorg/templates/mozorg/robots.txt
Labels: Needs Review, SEO, Review: µ, WMO and FXC

#16274 No-index, no-follow /all with different syntax (#16104)
  bedrock/firefox/templates/firefox/all/base.html
Labels: Needs Review, SEO, Review: µ, WMO and FXC

#16283 Fix newsletter & 404 bidi arrows direction
  media/css/base/page-not-found.scss
  media/css/newsletter/newsletter-updated.scss
Labels: Needs Review, Frontend, WMO and FXC

#16298 (fix) Ensure Japanese Mac downloads don't 404 on Bouncer
  bedrock/firefox/templates/firefox/includes/macros.html
  tests/playwright/specs/products/firefox/firefox-platforms.spec.js
Labels: Needs Review, WMO and FXC

#16301 Update platform download tests to handle mac or osx in url
  tests/playwright/specs/products/firefox/firefox-platforms.spec.js
Labels: Needs Review
