Repository mozilla/bedrock, pull requests merged in 2025-04, with the labels that each got.

#16084 Add Monitor article pages to CMS #15751
  bedrock/base/templatetags/helpers.py
  bedrock/base/tests/test_helpers.py
  bedrock/cms/cms_only_urls.py
  bedrock/cms/templates/wagtailcore/shared/richtext.html
  bedrock/products/migrations/0005_monitorcalltoactionsnippet_monitorarticlepage_and_more.py
  bedrock/products/migrations/0006_alter_monitorarticleindexpage_articles_heading_and_more.py
  bedrock/products/models.py
  bedrock/products/templates/products/monitor/base.html
  bedrock/products/templates/products/monitor/cms/article.html
  bedrock/products/templates/products/monitor/cms/includes/breadcrumbs.html
  bedrock/products/templates/products/monitor/cms/includes/macros.html
  bedrock/products/templates/products/monitor/cms/includes/subnav.html
  bedrock/products/templates/products/monitor/cms/index.html
  bedrock/products/tests/factories.py
  bedrock/products/tests/test_models.py
  bedrock/settings/base.py
  docs/cms.rst
  l10n/en/ui.ftl
  media/css/products/monitor/article.scss
  media/img/products/monitor/common/social-share.png
  media/js/base/article-toc.es6.js
  media/static-bundles.json
Labels: Wagtail, WMO and FXC

#15874 Simplify new nav for old IE basic styling
  bedrock/firefox/templates/firefox/new/basic/base.html
  bedrock/firefox/templates/firefox/new/desktop/base.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/new/desktop/thanks.html
  docs/docs/browser-support.md
  media/css/firefox/new/basic/ie.scss
  media/css/firefox/new/desktop/ie8.scss
  media/css/firefox/new/desktop/ie9.scss
  media/css/firefox/new/desktop/thanks-ie.scss
  media/css/protocol/common-old-ie.scss
  media/css/protocol/components/_fx-unsupported-ie.scss
  media/css/protocol/components/_navigation-ie.scss
  media/static-bundles.json
Labels: Needs Review, Frontend, WMO and FXC

#16130 Add nimbus experiment docs
  docs/docs/abtest.md
Labels: P3, Needs Review, Documentation :memo:, Review: µ

#16131 update transparency report 2024 H2 (fix #16091)
  bedrock/mozorg/templates/mozorg/about/policy/transparency/2024.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/includes/past-reports.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jan-jun-2024.html
  bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2024.html
  bedrock/mozorg/urls.py
Labels: Fixed Date, Frontend

#16143 Remove tou switch and associated fallbacks
  bedrock/firefox/templates/firefox/browsers/update-browser.html
  bedrock/firefox/templates/firefox/faq.html
  bedrock/firefox/templates/firefox/more.html
  bedrock/legal/templates/legal/terms/firefox-2025.html
  bedrock/legal/templates/legal/terms/firefox.html
  bedrock/legal/tests/test_views.py
  bedrock/legal/views.py
  bedrock/privacy/templates/privacy/notices/firefox-2025.html
  bedrock/privacy/templates/privacy/notices/firefox-simple-2025.html
  bedrock/privacy/templates/privacy/notices/firefox-simple.html
  bedrock/privacy/templates/privacy/notices/firefox.html
  bedrock/privacy/views.py
  l10n/en/firefox/faq.ftl
  media/css/legal/terms-firefox.scss
  media/css/privacy/privacy-firefox.scss
  media/static-bundles.json
Labels: Review: XS, Frontend

#16128 Fix FxA form link contrasts
  media/css/mozorg/mozilla-account-promo.scss
Labels: WMO and FXC

#16138 Remove refresh switch and associated fallbacks
  bedrock/base/templates/base-error.html
  bedrock/base/templates/base-protocol-mozilla.html
  bedrock/base/templates/base-protocol.html
  bedrock/base/templates/includes/protocol/footer/footer.html
  bedrock/base/templates/includes/protocol/navigation/navigation.html
  bedrock/firefox/templates/firefox/built-for-you/landing.de.html
  bedrock/firefox/templates/firefox/built-for-you/landing.fr.html
  bedrock/firefox/templates/firefox/challenge-the-default/landing-base.html
  bedrock/firefox/templates/firefox/developer/firstrun.html
  bedrock/firefox/templates/firefox/developer/whatsnew.html
  bedrock/firefox/templates/firefox/family/index.html
  bedrock/firefox/templates/firefox/nightly/firstrun.html
  bedrock/firefox/templates/firefox/nightly/whatsnew.html
  bedrock/firefox/templates/firefox/nothing-personal/index.html
  bedrock/firefox/templates/firefox/welcome/base.html
  bedrock/firefox/templates/firefox/whatsnew/base.html
  bedrock/mozorg/tests/test_views.py
  bedrock/mozorg/views.py
  media/css/protocol/components/_navigation.scss
  media/css/protocol/navigation-and-footer.scss
  media/static-bundles.json
Labels: Review: XS, Frontend

#16175 Add add nofollow to pages under /all (Fixes #16104)
  bedrock/firefox/templates/firefox/all/base.html
Labels: Needs Review, Review: µ, Frontend

#16182 Only build/deploy docs on commits to mozilla/bedrock repo
  .github/workflows/publish_docs.yml
Labels: Review: µ

#16149 Redirect /firefox/ to /firefox/new/ (Fixes #16089)
  bedrock/base/redirects.py
  bedrock/base/templates/base-error.html
  bedrock/base/templates/includes/protocol/navigation/menus-refresh/firefox.html
  bedrock/base/templates/includes/protocol/navigation/menus/firefox.html
  bedrock/contentcards/tests/test_data/content/home/card_1.en-US.json
  bedrock/contentcards/tests/test_models.py
  bedrock/contentful/templates/includes/contentful/cta.html
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/browsers/browser-history.html
  bedrock/firefox/templates/firefox/browsers/what-is-a-browser.html
  bedrock/firefox/templates/firefox/challenge-the-default/landing-switch.html
  bedrock/firefox/templates/firefox/channel/base.html
  bedrock/firefox/templates/firefox/developer/index.html
  bedrock/firefox/templates/firefox/faq.html
  bedrock/firefox/templates/firefox/includes/sub-nav-firefox.html
  bedrock/firefox/templates/firefox/index.html
  bedrock/firefox/tests/test_views.py
  bedrock/firefox/urls.py
  bedrock/firefox/views.py
  bedrock/foundation/templates/foundation/annualreport/2018/index.html
  bedrock/foundation/templates/foundation/annualreport/2019/index.html
  bedrock/foundation/templates/foundation/annualreport/2020/index.html
  bedrock/mozorg/redirects.py
  bedrock/mozorg/templates/mozorg/about/history.html
  bedrock/mozorg/templates/mozorg/about/manifesto-details.html
  bedrock/mozorg/templates/mozorg/account.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/products.html
  bedrock/products/templates/products/landing.html
  bedrock/releasenotes/views.py
  l10n/en/firefox/browsers.ftl
  media/img/firefox/browsers/desktop-high-res-v2.jpg
  media/img/firefox/browsers/desktop-v2.jpg
  media/img/firefox/browsers/enterprise-high-res.jpg
  media/img/firefox/browsers/enterprise.jpg
  media/img/firefox/browsers/mobile-high-res-v2.jpg
  media/img/firefox/browsers/mobile-v2.jpg
  tests/functional/firefox/test_home.py
  tests/functional/test_link_hreflang_tags.py
  tests/pages/firefox/home.py
  tests/playwright/specs/a11y/includes/urls.js
  tests/playwright/specs/products/firefox/firefox-home.spec.js
  tests/redirects/map_301.py
  tests/redirects/map_globalconf.py
  tests/redirects/test_urls.py
Labels: Review: XS

#16180 Reapply "Remove set-as-default experiment code (Fixes #16095) (#16096)" (#16112)
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/new/desktop/experiment-firefox-new-default.html
  bedrock/firefox/views.py
  media/css/firefox/new/desktop/default-experiment.scss
  media/js/firefox/new/desktop/default-experiment-criteria.es6.js
  media/js/firefox/new/desktop/default-experiment.es6.js
  media/js/firefox/new/desktop/default-opt-out-init.es6.js
  media/js/firefox/new/desktop/default-opt-out.es6.js
  media/static-bundles.json
  tests/unit/spec/firefox/new/desktop/default-experiment-criteria.js
  tests/unit/spec/firefox/new/desktop/default-opt-out.js
Labels: Needs Review, Review: µ, Frontend

#16188 Check TOML config file within Fluent linter workflow
  .github/l10n/check_toml_configs.py
  .github/l10n/requirements.txt
  .github/workflows/fluent_linter.yml
Labels: WMO and FXC

#16152 mobile navigation keyboard focus trap [fix #16090]
  media/js/base/protocol/m24-keyboard-focus-trap.es6.js
  media/js/base/protocol/m24-menu.es6.js
  media/js/base/protocol/m24-navigation.es6.js
Labels: Frontend, WMO and FXC

#15554 Set the `form-action` directive in the report-only CSP
  bedrock/settings/__init__.py
Labels: Backend

#16211 restore l10n string for Firefox sub navigation (fix #16209)
  l10n/en/sub_navigation.ftl
Labels: L10N, Needs Review, WMO and FXC

#16169 WNP 138 (fixes #16170)
  bedrock/firefox/templates/firefox/whatsnew/includes/fx138/video.html
  bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx138-tab-groups.html
  bedrock/firefox/tests/test_base.py
  bedrock/firefox/views.py
  media/css/firefox/whatsnew/whatsnew-138.scss
  media/img/firefox/whatsnew/whatsnew138/poster-de-high-res.png
  media/img/firefox/whatsnew/whatsnew138/poster-en-high-res.png
  media/img/firefox/whatsnew/whatsnew138/poster-fr-high-res.png
  media/js/firefox/whatsnew/whatsnew-138-video-events.es6.js
  media/static-bundles.json
Labels: P2, Review: XS

#16214 add VPN promo pencil banner (fix #16198)
  bedrock/base/templates/includes/banners/pencil-banner.html
  bedrock/products/templatetags/misc.py
  bedrock/products/tests/test_helper_misc.py
  media/css/m24/components/pencil-banner.scss
Labels: P1, Frontend

#16199 Add experiment for refreshed /new in en-US/CA (Fix #16160)
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/new/desktop/experiment-firefox-new-refresh-a.html
  bedrock/firefox/templates/firefox/new/desktop/experiment-firefox-new-refresh-b.html
  bedrock/firefox/views.py
  media/css/firefox/new/desktop/refresh-experiment.scss
  media/img/firefox/new/desktop/experiment-refresh/block.svg
  media/img/firefox/new/desktop/experiment-refresh/dark.svg
  media/img/firefox/new/desktop/experiment-refresh/free.svg
  media/img/firefox/new/desktop/experiment-refresh/hero-high-res.png
  media/img/firefox/new/desktop/experiment-refresh/hero.png
  media/img/firefox/new/desktop/experiment-refresh/multi.svg
  media/img/firefox/new/desktop/experiment-refresh/screens.svg
  media/img/firefox/new/desktop/experiment-refresh/tabs.svg
  media/img/firefox/new/desktop/experiment-refresh/think.svg
  media/img/firefox/new/desktop/experiment-refresh/toggle.svg
  media/js/firefox/new/desktop/download.js
  media/js/firefox/new/desktop/experiment-refresh-data.es6.js
  media/js/firefox/new/desktop/experiment-refresh-init.es6.js
  media/static-bundles.json
Labels: P1, Review: S

#16212 Update Monitor link in nav
  bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/products.html
  bedrock/products/templates/products/landing.html
Labels: Review: µ

#16221 Migrate remaining Selenium tests to Playwright
  .github/workflows/integration_tests.yml
  bedrock/firefox/templates/firefox/nightly/firstrun.html
  bedrock/firefox/templates/firefox/nightly/whatsnew.html
  bedrock/firefox/templates/firefox/welcome/page4.html
  bedrock/firefox/templates/firefox/welcome/page6.html
  bedrock/mozorg/templates/mozorg/analytics-tests/ga-index.html
  bedrock/privacy/templates/privacy/data-preferences.html
  docs/docs/testing.md
  tests/functional/analytics/test_google_analytics.py
  tests/functional/firefox/test_nightly.py
  tests/functional/firefox/welcome/test_welcome_page1.py
  tests/functional/firefox/welcome/test_welcome_page10.py
  tests/functional/firefox/welcome/test_welcome_page11.py
  tests/functional/firefox/welcome/test_welcome_page12.py
  tests/functional/firefox/welcome/test_welcome_page13.py
  tests/functional/firefox/welcome/test_welcome_page14.py
  tests/functional/firefox/welcome/test_welcome_page15.py
  tests/functional/firefox/welcome/test_welcome_page2.py
  tests/functional/firefox/welcome/test_welcome_page4.py
  tests/functional/firefox/welcome/test_welcome_page6.py
  tests/functional/firefox/welcome/test_welcome_page7.py
  tests/functional/firefox/welcome/test_welcome_page8.py
  tests/functional/firefox/welcome/test_welcome_page9.py
  tests/functional/firefox/whatsnew/test_whatsnew_nightly_70.py
  tests/functional/privacy/test_data_preferences.py
  tests/functional/test_locales.py
  tests/pages/analytics/index.py
  tests/pages/firefox/nightly.py
  tests/pages/firefox/welcome/page1.py
  tests/pages/firefox/welcome/page10.py
  tests/pages/firefox/welcome/page11.py
  tests/pages/firefox/welcome/page12.py
  tests/pages/firefox/welcome/page13.py
  tests/pages/firefox/welcome/page14.py
  tests/pages/firefox/welcome/page15.py
  tests/pages/firefox/welcome/page2.py
  tests/pages/firefox/welcome/page4.py
  tests/pages/firefox/welcome/page6.py
  tests/pages/firefox/welcome/page7.py
  tests/pages/firefox/welcome/page8.py
  tests/pages/firefox/welcome/page9.py
  tests/pages/firefox/whatsnew/whatsnew_nightly_70.py
  tests/pages/locales.py
  tests/pages/privacy/__init__.py
  tests/pages/privacy/data_preferences.py
  tests/playwright/specs/google-analytics.spec.js
  tests/playwright/specs/locales.spec.js
  tests/playwright/specs/privacy/data-preferences.spec.js
  tests/playwright/specs/products/firefox/firefox-nightly-firstrun.spec.js
  tests/playwright/specs/products/firefox/firefox-nightly-whatsnew.spec.js
  tests/playwright/specs/products/firefox/welcome/firefox-welcome-4.spec.js
  tests/playwright/specs/products/firefox/welcome/firefox-welcome-6.spec.js
Labels: Needs Review, Review: XS

#16233 Add firefox education landing page (Fixes #15953)
  bedrock/firefox/templates/firefox/landing/education.html
  bedrock/firefox/urls.py
  media/css/firefox/landing/index.scss
  media/css/protocol/components/_sub-navigation.scss
  media/img/firefox/landing/education/hero-1000.png
  media/img/firefox/landing/education/hero-400.png
  media/img/firefox/landing/education/hero-600.png
  media/img/firefox/landing/education/hero-800.png
  media/img/firefox/landing/education/icon-language-tool-128.png
  media/img/firefox/landing/education/icon-language-tool-64.png
  media/img/firefox/landing/education/icon-privacy.svg
  media/img/firefox/landing/education/icon-productivity.svg
  media/img/firefox/landing/education/icon-search.svg
  media/img/firefox/landing/education/icon-tomato-clock-128.png
  media/img/firefox/landing/education/icon-tomato-clock-64.png
  media/img/firefox/landing/education/icon-unhook-128.png
  media/img/firefox/landing/education/icon-unhook-64.png
  media/img/firefox/landing/education/og.png
  media/img/firefox/landing/education/students-1000.png
  media/img/firefox/landing/education/students-1200.png
  media/img/firefox/landing/education/students-400.png
  media/img/firefox/landing/education/students-600.png
  media/img/firefox/landing/education/students-800.png
  media/img/firefox/landing/logo-word-hor.svg
  media/js/base/consent/allow-list.es6.js
  media/js/firefox/landing/init.es6.js
  media/js/firefox/landing/partner-build-download.es6.js
  media/static-bundles.json
Labels: Review: XS, Frontend

#16232 Restrict z-index selector for animation button (fixes #16151)
  media/css/m24/flag.scss
Labels: Review: µ, Frontend
