Repository mozilla/bedrock, pull requests merged in 2025-06, with the labels that each got.

#16336 Add ten tabs newsletter
  bedrock/newsletter/templates/newsletter/includes/form.html
  bedrock/newsletter/templates/newsletter/ten-tabs.html
  bedrock/newsletter/urls.py
  media/css/newsletter/newsletter-ten-tabs.scss
  media/img/newsletter/ten-tabs/ten-tabs.svg
  media/static-bundles.json
  tests/playwright/specs/newsletter/newsletter-ten-tabs.spec.js
Labels: Review: XS

#16361 Remove Fakespot from home, global nav, and product page (#16359)
  bedrock/base/templates/includes/protocol/navigation/menus-refresh/products.html
  bedrock/base/templates/includes/protocol/navigation/menus/products.html
  bedrock/mozorg/templates/mozorg/about/includes/m24/manifesto.html
  bedrock/mozorg/templates/mozorg/home/home-new.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/products.html
  bedrock/products/templates/products/landing.html
  l10n/en-US/mozorg/home-m24.ftl
  l10n/en/firefox/products.ftl
  l10n/en/mozorg/about-m24.ftl
  l10n/en/mozorg/home-m24.ftl
  l10n/en/mozorg/home-new.ftl
  l10n/en/navigation_refresh.ftl
  l10n/en/navigation_v2.ftl
  media/css/m24/launchpad.scss
  media/img/logos/fakespot/logo-blue.svg
  media/img/logos/fakespot/logo-white.svg
  media/img/logos/fakespot/logo.svg
Labels: Needs Review, Frontend

#16286 Add anchors for all release notes headings
  bedrock/firefox/templates/firefox/releases/notes.html
Labels: WMO and FXC
