Repository mozilla/bedrock, pull requests merged in 2025-07, with the labels that each got.

#16364 remove Fakespot from advertising pages (fix #16358)
  .github/l10n/linter_config.yml
  bedrock/firefox/templates/firefox/welcome/page18.html
  bedrock/firefox/urls.py
  bedrock/mozorg/templates/mozorg/advertising/formats.html
  bedrock/mozorg/templates/mozorg/advertising/includes/product-fakespot-media.html
  bedrock/mozorg/templates/mozorg/advertising/landing.html
  media/css/firefox/welcome18.scss
  media/img/firefox/welcome/page18/fakespot-rc-high-res.png
  media/img/firefox/welcome/page18/fakespot-rc.png
  media/img/firefox/welcome/page18/icon-tag-white.svg
  media/img/firefox/welcome/page18/icon-tag.svg
  media/img/mozorg/advertising/product-fakespot-15x.png
  media/img/mozorg/advertising/product-fakespot.png
  media/static-bundles.json
Labels: Needs Review, Frontend, WMO and FXC

#16365 remove Pocket mentions (fix #16358)
  .github/l10n/linter_config.yml
  bedrock/careers/templates/careers/teams.html
  bedrock/contentful/templates/includes/contentful/cta.html
  bedrock/contentful/tests/test_contentful_api.py
  bedrock/firefox/redirects.py
  bedrock/firefox/templates/firefox/browsers/mobile/android.html
  bedrock/firefox/templates/firefox/browsers/mobile/ios.html
  bedrock/firefox/templates/firefox/features/tips/tips.html
  bedrock/firefox/templates/firefox/more/misinformation.html
  bedrock/firefox/templates/firefox/pocket.html
  bedrock/firefox/templates/firefox/welcome/page2.html
  bedrock/firefox/urls.py
  bedrock/mozorg/templates/mozorg/account.html
  bedrock/mozorg/templates/mozorg/advertising/formats.html
  bedrock/mozorg/templates/mozorg/advertising/includes/product-pocket-media.html
  bedrock/mozorg/templates/mozorg/advertising/landing.html
  bedrock/mozorg/templates/mozorg/contact/contact-landing.html
  bedrock/mozorg/templates/mozorg/home/home-new.html
  bedrock/mozorg/templates/mozorg/home/includes/m24/products.html
  bedrock/mozorg/templates/mozorg/includes/mozilla-account-promo.html
  bedrock/mozorg/templatetags/misc.py
  bedrock/mozorg/tests/test_helper_misc.py
  bedrock/products/templates/products/landing.html
  bedrock/settings/appstores.py
  bedrock/settings/base.py
  l10n/configs/pontoon.toml
  l10n/en/firefox/accounts.ftl
  l10n/en/firefox/browsers/mobile/android.ftl
  l10n/en/firefox/browsers/mobile/ios.ftl
  l10n/en/firefox/more/misinformation.ftl
  l10n/en/firefox/products.ftl
  l10n/en/firefox/welcome/page2.ftl
  l10n/en/mozilla-account-promo.ftl
  l10n/en/mozorg/home-m24.ftl
  l10n/en/mozorg/home-new.ftl
  media/css/firefox/pocket.scss
  media/css/m24/launchpad.scss
  media/img/firefox/features/tips/fx_video-thumb_secret-menu_pocket_amy.jpg
  media/img/firefox/more/misinformation/pocket.svg
  media/img/firefox/welcome/pocket-hero.svg
  media/img/icons/navigate-green.svg
  media/img/icons/pocket-outline-green.svg
  media/img/icons/pocket.svg
  media/img/mozorg/advertising/product-pocket-15x.png
  media/img/mozorg/advertising/product-pocket.png
  media/static-bundles.json
  tests/redirects/map_globalconf.py
  tests/unit/spec/base/fxa-product-button.js
Labels: WIP :construction:, WMO and FXC

#16404 add Ten Tabs to advertising pages (fix #16401)
  bedrock/mozorg/templates/mozorg/advertising/formats.html
  bedrock/mozorg/templates/mozorg/advertising/includes/product-ten-tabs-media.html
  bedrock/mozorg/templates/mozorg/advertising/landing.html
  media/img/mozorg/advertising/ads-hero-15x.png
  media/img/mozorg/advertising/ads-hero.png
  media/img/mozorg/advertising/product-ten-tabs-15x.png
  media/img/mozorg/advertising/product-ten-tabs.png
Labels: Frontend

#16418 clean up expired l10n strings (fix #16413)
  .github/l10n/linter_config.yml
  bedrock/base/templates/includes/protocol/footer/footer-refresh.html
  bedrock/firefox/templates/firefox/developer/includes/mdn-features.html
  bedrock/firefox/templates/firefox/new/desktop/download.html
  bedrock/firefox/templates/firefox/nightly/whatsnew.html
  bedrock/privacy/templates/privacy/includes/privacy-basics.html
  l10n/en/firefox/developer.ftl
  l10n/en/firefox/new/desktop.ftl
  l10n/en/firefox/nightly/whatsnew.ftl
  l10n/en/footer-refresh.ftl
  l10n/en/privacy/firefox.ftl
Labels: L10N, Needs Review

#16400 pocket removal clean up (fix #16358)
  docs/docs/attribution/0001-analytics.md
  docs/docs/mozilla-accounts.md
  l10n/en/firefox/more/misinformation.ftl
  l10n/en/mozorg/home-new.ftl
  media/css/mozorg/home/home-new.scss
  media/js/base/datalayer-productdownload.es6.js
  tests/unit/spec/base/datalayer-productdownload.js
  tests/unit/spec/base/fxa-attribution.js
Labels: Needs Review, Frontend

#16420 16150 Monitor Article Enhancements
  bedrock/products/migrations/0007_remove_monitorarticlepage_icon.py
  bedrock/products/models.py
  bedrock/products/templates/products/monitor/cms/index.html
  bedrock/products/tests/factories.py
  bedrock/products/tests/test_models.py
Labels: P1

#16426 Update docs for download pages
  docs/docs/attribution/0002-firefox-desktop.md
  docs/docs/firefox-downloads/desktop-download-as-default.md
  docs/docs/firefox-downloads/desktop-download-pages.md
  docs/docs/mozilla-accounts.md
Labels: Needs Review, Review: XS
